### ISSUE TITLE
How to update the Apptainer to a newer version?

### ISSUE THREAD

**Issue by praksharma** [apptainer/apptainer#1011]
### Version of Apptainer
```sh
╰─ apptainer --version 
apptainer version 1.0.2
```

### Expected behavior
I updated the apptainer using these instructions : https://apptainer.org/docs/admin/main/installation.html#install-debian-ubuntu-packages. The `apt` shows the updated version, but `apptainer --version` is still the older one.
```sh
╰─ apt list --installed | grep apptainer 
WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
apptainer/now 1.1.5 amd64 [installed,local]
```

### Steps to reproduce this behavior

I updated the apptainer using these instructions : https://apptainer.org/docs/admin/main/installation.html#install-debian-ubuntu-packages. 

### What OS/distro are you running

```sh
╰─ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Apptainer
I updated the apptainer using these instructions : https://apptainer.org/docs/admin/main/installation.html#install-debian-ubuntu-packages.

**Comment by DrDaveD** [comment]
I just tried reproducing it, by installing apptainer-1.0.2 using the same method first on a fresh ubuntu-20.04 docker container, and then apptainer-1.1.5.  It worked fine for me.  How was apptainer installed before?  Was it through a different method, such that the old version is earlier in your PATH?  My first guess would be that it is in /usr/local/bin and that's earlier in your PATH than /usr/bin.

**Comment by praksharma** [comment]
Yes you are right. The old one is installed in `the /usr/local/bin`.
![image](https://user-images.githubusercontent.com/70601302/213138402-5f3edd5f-8992-4ed1-93c2-647684160a69.png)
 What should I do? Is there an env variable which I need to change. Then I simply delete the older file?

**Comment by praksharma** [comment]
Thank you I fixed this. Both the paths were in`$PATH`. The path for older version was appearing first. So, I moved the folder version to the desktop and I can now use the newer version.
