### ISSUE TITLE
Failed to create mount namespace

### ISSUE THREAD

**Issue by cb4github** [apptainer/apptainer#1017]
### Version of Apptainer
```
$ apptainer --version
apptainer version 1.1.5-1.el7
```
### Expected behavior
No such error (see below.)

### Actual behavior
ERROR  : Failed to create mount namespace: mount namespace requires privileges, check Apptainer installation
### Steps to reproduce this behavior
```
module load apptainer/1.1.5
mkdir -p $HOME/.cache/registry
apptainer run --env REGISTRY_HTTP_ADDR=127.0.0.1:5001 \
                --env REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io \
                --bind $HOME/.cache/registry:/var/lib/registry \
                docker://registry:2.7
```
### What OS/distro are you running
```sh
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
$ kerver  #alias for kernel version
Linux 3.10.0-693.5.2.el7.x86_64 x86_64
$ centos #alias for centos version
CentOS Linux release 7.4.1708 (Core) 
```

### How did you install Apptainer
```
$ git clone https://github.com/apptainer/apptainer.git
$ cd apptainer
$ tools/install-unprivileged.sh $APPS7/apptainer/1.1.5
```
Dear All,

I obtained the above error on our campus cluster attempting to install apptainer first in my local module before I can install in a shared module.

Please advise, and please let me know if you need more information, thanks.

Best,
CB

**Comment by DrDaveD** [comment]
That means that unprivileged user namespaces are not enabled on that machine.  They are not enabled by default on el7.  You can try asking the system administrator to [enable them](https://apptainer.org/docs/admin/latest/user_namespace.html#rhel-centos-7), or try it on another machine.  They are enabled by default on most other currently supported Linux distribution versions.

**Comment by cb4github** [comment]
@DrDaveD Many thanks for your reply.
Well, the value user.max_user_namespaces is set in sysctl, though that setting appears to be originating from a different file - /etc/sysctl.d/90-max_net_namespaces.conf vice /etc/sysctl.d/90-max_user_namespaces.conf
Is that a problem?
```
$ ls /etc/sysctl.d/90-max_user_namespaces.conf
ls: cannot access /etc/sysctl.d/90-max_user_namespaces.conf: No such file or directory
$ sysctl --all 2>/dev/null | grep user.max_user_namespaces
user.max_user_namespaces = 15000
$ grep user.max_user_namespaces /etc/sysctl.d/*
/etc/sysctl.d/90-max_net_namespaces.conf:user.max_user_namespaces=15000
```
Also, I had to go back and reinstall v1.1.5 from source vice tools/install-unprivileged.sh in order to avoid a 'not found' message due to libseccomp.so.2 => /lib64/libseccomp.so.2 in my environment.
Nonetheless the original ERROR persists.
Again please advise, and please let me know if you need more information, thanks.

**Comment by DrDaveD** [comment]
I'm sorry, I think I must have glanced too quickly at the error message.  That is a different message than we normally see when user namespaces are disabled.  You do have them enabled (the file name in /etc/sysctl.d does not matter).  Network namespaces are on by default and we do recommend disabling them as documented if possible, but it wouldn't cause the error you are seeing.

The message is coming from [starter.c](https://github.com/apptainer/apptainer/blob/432177df51a6161770f8b078bca1def461cc43d5/cmd/starter/c/starter.c#L508).  It must be getting EPERM from an `unshare(CLONE_NEWNS)`.  Your command works fine on my el7 system.  Do you know if there is some unusual configuration that your shell is running under?  Can you successfully run the command `unshare -rm id`?

**Comment by cb4github** [comment]
My result follows - on a compute node running el7, whereas others are still running el6 (EOL notwithstanding):
```
$ unshare -rm id
unshare: unshare failed: Operation not permitted
$ 
```
Also, I have no admin privilege here. Is the above something our sysadmin should try?
Also, see below for what it's worth.
```
$ sysctl --all 2>/dev/null | grep mount
fs.may_detach_mounts = 0
fs.nfs.nfs_mountpoint_timeout = 500
```
I'm not sure what other tests to run, thanks.

**Comment by DrDaveD** [comment]
`unshare -rm` should be able to be run by any user when unprivileged user namespaces is available ...

Oh I think the problem is the kernel is too old.  The apptainer [system requirements](https://apptainer.org/docs/admin/latest/installation.html#system-requirements) lists a minimum kernel version of 3.10.0-1127 on RHEL7.  It's kind of surprising that someone set the unprivileged user namespace sysctl setting on such an old kernel.

**Comment by cb4github** [comment]
Thanks for pointing out the minimum kernel version 3.10.0-1127 specifically for RHEL7  in the 
the stated [system requirements](https://apptainer.org/docs/admin/latest/installation.html#system-requirements).

I'll check with our sysadmin to see if a kernel upgrade is feasible for our el7 image.

Also, for the benefit of others, let me suggest including explicit mention of CentOS7 alongside RHEL7 in those requirements.

At my typing, it mentions >=3.8 in general and then "...3.10.0-1127 on RHEL7" and understandably, though implicitly, applying to CentOS7 as well granted the similarities. Nonetheless, in light of possible differences admittedly unknown to me yet nonetheless indicated in [CentOS vs. RELH](https://www.redhat.com/en/topics/linux/what-is-centos#centos-vs-rhel) (for example, mention therein of differences in binary paths with no further details), it wasn't clear that CentOS7 was similarly affected by the same kernel dependency as RELH7.

I'm closing this for now with again many thanks for all your efforts.

Best,
CB

**Comment by DrDaveD** [comment]
It gets awkward to mention all the alternatives every time we refer to a RHEL-based distribution.  CentOS7 (and Rocky 8 & 9 and Alma 8 & 9) all say they are bug-for-bug compatible with the corresponding RHEL releases, so any time we mention RHEL we do mean to include all the derivatives.
