### ISSUE TITLE
Adding locally a global remote is allowed but causes "remote" commands not to work any more

### ISSUE THREAD

**Issue by mambelli** [apptainer/apptainer#1018]
### Version of Apptainer

This problem happened to a student during a tutorial, using an installation on CVMFS instead of the system installed apptainer. Not sure if I should report this here or the version is obsolete.
`singularity version 3.8.6`

### Expected behavior

A warning during the addition of the remote if it is already present and would cause name collisions

### Actual behavior

The addition was OK, the problem started when using remote commands after that:
```
» singularity remote add --no-login SylabsCloud cloud.sycloud.io
INFO:    Remote "SylabsCloud" added.
» singularity remote use SylabsCloud
FATAL:   name collision while syncing: SylabsCloud
» singularity remote list                                                                                                                                   
FATAL:   name collision while syncing: SylabsCloud
```

### Steps to reproduce this behavior

1. Add a global remote as root.
2. Add the same remote locally (as regular user)
3. Try to use `singularity remote` commands

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="http://cern.ch/linux/"
BUG_REPORT_URL="http://cern.ch/linux/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Apptainer

It is a CVMFS installation on `lxplus.cern.ch` :
```
$ which singularity
/cvmfs/lhcb.cern.ch/lib/var/lib/LbEnv/2683/stable/linux-64/bin/singularity
```

**Comment by DrDaveD** [comment]
This does still happen with apptainer-1.1.5.  I had added a SylabsCloud remote first as an unprivileged user, then ran
```
$ sudo apptainer remote add --global SylabsCloud cloud.sycloud.io
$ sudo apptainer remote use --global SylabsCloud
```
then running the use command as an unprivileged user I got:
```
$ singularity remote use SylabsCloud
FATAL:   name collision while syncing: SylabsCloud
```

**Comment by DrDaveD** [comment]
Oh, but there is a difference because if I manually delete my own entry in ~/.apptainer/remote.yaml and try to add it back that is rejected:
```
$ singularity remote add --no-login SylabsCloud cloud.sycloud.io
FATAL:   SylabsCloud is already a remote
```

**Comment by DrDaveD** [comment]
> Oh, but there is a difference because if I manually delete my own entry in ~/.apptainer/remote.yaml and try to add it back that is rejected:
> 
> ```
> $ singularity remote add --no-login SylabsCloud cloud.sycloud.io
> FATAL:   SylabsCloud is already a remote
> ```

I can't reproduce this behavior so I think I must have done it incorrectly.  I only get that error if I try to run the add command twice.  So your reported behavior is still happening in 1.1.5.
