### ISSUE TITLE
FATAL:   container creation failed: mount hook function failure: mount /proc/self/fd/3->/var/lib/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3hfuse_ll exited with status 255: Something went wrong trying to read the squashfs image.

### ISSUE THREAD

**Issue by 0820LL** [apptainer/apptainer#1021]
### Version of Apptainer

apptainer version 1.1.4

### What OS/distro are you running

 cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

### How did you install Apptainer

curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | \
    bash -s - install-dir

### the command is bellow 
`
nextflow run /data_5t/lilin/biotools/nf-core_pipeline/nf-core-sarek-3.1.2/workflow/main.nf 
  --input /data_5t/lilin/biotools/nf-core_pipeline_test/fastq_pair.csv 
  --wes 
  --igenomes_base /data_5t/lilin/biotools/aws-igenomes/references 
  -offline 
  -profile singularity 
  -resume
`

**Comment by GodloveD** [comment]
Can you include the commands that you ran to obtain that error after performing the installation please?
