### ISSUE TITLE
tools fails to detect/load so file from container "Transport endpoint is not connected"

### ISSUE THREAD

**Issue by stdweird** [apptainer/apptainer#1025]
### Version of Apptainer

1.1.3

### Expected behavior

All .so files from container are found/usable. 

### Actual behavior

.so file is not found/usable (and even ld.so.cache isn't; and ld.so.cache was usable in previous parts of the strace)

it seems something stops working (eg the open ld.so.cache worked 74 times since the strace was attached, before the error occured)

```
421271 open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = -1 ENOTCONN (Transport endpoint is not connected)
421271 open("/lib64/tls/x86_64/libfontconfig.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
421271 stat("/lib64/tls/x86_64", 0x7ffcbe267990) = -1 ENOENT (No such file or directory)
421271 open("/lib64/tls/libfontconfig.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOTCONN (Transport endpoint is not connected)
421271 stat("/lib64/tls", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
421271 open("/lib64/x86_64/libfontconfig.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
421271 stat("/lib64/x86_64", 0x7ffcbe267990) = -1 ENOENT (No such file or directory)
421271 open("/lib64/libfontconfig.so.1", O_RDONLY|O_CLOEXEC) = -1 ENOTCONN (Transport endpoint is not connected)
421271 stat("/lib64", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
```

### Steps to reproduce this behavior

This is FLUENT 2020/R1, trying to start fluent in a centos 7.9 container

### What OS/distro are you running

OS is rhel 8.4, container is cenots 79

### How did you install Apptainer

RPM

**Comment by GodloveD** [comment]
Can you provide some more information on this.  A definition file or link to the container and the actual commands that were used to build/run the container would be welcome.  Thank you.

**Comment by stdweird** [comment]
@GodloveD  the container does "work", the files are also there and eg the ld.so.cache does its regular work, except after some time it doesn't. the `ENOTCONN` error seem to point to some fuse overlay or something similar that has an issue after a while.

from the container
```
singularity]$ singularity shell images/centos7_9_hpc 
Apptainer> md5sum /lib64/libfontconfig.so.1
d155c5185cf571a9c004a0f7dfcbe6e8  /lib64/libfontconfig.so.1
Apptainer> md5sum /etc/ld.so.cache 
5a81940d7a2c3d5de3757687979aebf1  /etc/ld.so.cache
```

this is the partial singularity file. there is nothing odd about it: start from centos7 image and add bunch of rpms to it.
it's generated from `spython recipe` and then build with `singularity build --fakeroot ...`

```
Bootstrap: docker
From: centos:7.9.2009
Stage: spython-base

%files
singularity.d /.singularity.d
%post
major=7
minor=9
subminor=2009
mofed=5.5-1.0.3.2
slurm_version=20.11




yum -y upgrade && \
yum -y install epel-release yum-plugin-priorities && \
echo -e "# Mellanox OFED\n[MOFED]\nname=MOFED\nbaseurl=https://linux.mellanox.com/public/repo/mlnx_ofed/$mofed/rhel$major.$minor/\$basearch/\ngpgcheck=0\nenabled=1\npri
ority=5" >/etc/yum.repos.d/mofed.repo && \
yum -y groupinstall "Compatibility Libraries" \
"Development Tools" \
"Scientific Support" && \
yum -y install \
binutils \
...
<long list of rpms>
```

**Comment by GodloveD** [comment]
Just trying to get enough info to try to replicate the issue.  Right now I don't really know how to proceed.  What is in your `singularity.d` file?

**Comment by stdweird** [comment]
@GodloveD what is a `singularity.d` file?

not sure you will be able to reproduce this locally. the culprit that triggers it in the end is fluent. during its start, this just happens after 10-20 seconds while it is still loading plugins etc etc.
i'm quite sure fluent just trashes some fuse parts, we also have https://github.com/containers/fuse-overlayfs/issues/385 that we only see with fluent (but is not related to this case).

if you know what trace data you need, just let me know and i'll generate it. i'm afraid it's not trivial to give you access to the system.

**Comment by GodloveD** [comment]
You have this as part of your def file:
```
%files
singularity.d /.singularity.d
```
This is copying a file from your system to the location `/.singularity.d` in the container.  This is worrisome because `/.singularity.d` is the location of all of the metadata for the container in Apptainer.  So that is why I'm wondering what is in that `singularity.d` file or directory.

**Comment by DrDaveD** [comment]
"Transport endpoint is not connected" usually indicates that a FUSE process has died for some reason.  There's really not much we will be able to say about that without being able to reproduce it ourselves.  At a minimum we would need the whole definition file.

I believe that '%files' comes not from the host system but from whatever is installed in the %post section.  So we need to see the whole thing.

**Comment by DrDaveD** [comment]
> I believe that '%files' comes not from the host system but from whatever is installed in the %post section. So we need to see the whole thing.

No, sorry, I'm wrong about that.  That does copy files from the host.  So yes we need to see the contents of those files too in order to reproduce.

**Comment by stdweird** [comment]
i forgot about those (what i did was based on  https://github.com/opensciencegrid/osgvo-el7/blob/master/Dockerfile

if you think it matters, i can rebuild and retry without those files

```
[singularity]$ ls -l singularity.d/
total 8
-rw-rw-r-- 1 abc abc  125 May 14  2022 90-vsc.sh
drwxrwxr-x 2 abc abc 4096 May 14  2022 env
[singularity]$ ls -l singularity.d/env/
total 0
[singularity]$ cat singularity.d/90-vsc.sh 
# Custom environment shell code should follow

# ensure we have PS1 set
PS1="Singularity $SINGULARITY_NAME:\\w> "
export PS1
```


@DrDaveD what fuse libraries/tools are being used by apptainer? i can have a look for updates wrt what RHEL84 provides

**Comment by DrDaveD** [comment]
That singularity.d file won't cause any harm.

apptainer uses different fuse tools depending on what the command is.  You should be able to see with apptainer -d the tools that it is running.  The most common one is squashfuse_ll, and that is included in the apptainer rpm.

**Comment by stdweird** [comment]
i recently revisited this issue, even upgraded the squashfuse_ll to latest 0.1.105 release (it has a fix for "No such file or directory", but after investigation apptainer does not suffer from it (or at least not in this case).

and then ofcourse i spotted the issue: when you start fluent, you are prompted with a GUI to select a few things, but after pressing "start" button, the real fluent GUI is launched but in backgrounded way, so 'singularity run' stops leaving the gui process behind without access to the files in the container. 

i was a bit surprised that singularity doesn't wait for all processes (or even tries to clean them up), but i guess it's normal/expected/feature. anyway, wrapped the whole thing in a script that checks if stuff is still running and now things work smoothly.
