### ISSUE TITLE
APPTAINER_BIND strange value inside container 

### ISSUE THREAD

**Issue by Nortamo** [apptainer/apptainer#1030]
### Version of Apptainer

Broken in:
 
- 1.1.5-1.el8
- 1.1.3-1.el8

Works for 
- 1.0.2-1

### Expected behavior

`APPTAINER_BIND` retains value set outside the container upon launch. 

### Actual behavior

`APPTAINER_BIND` drops all content before an entry using `:`
or jumbles the ordering. 

**Does not affect any other observable behavior** so impact is very minor.  

### Steps to reproduce this behavior

As expected
```bash 
$ apptainer pull docker://opensuse/leap:15.3
$ export APPTAINER_BIND=/opt/,/var/spool,/home
$ apptainer exec leap_15.3.sif bash -c "echo \$APPTAINER_BIND"
/opt/,/var/spool,/home
```
Drops preceding entries
```bash 
$ export APPTAINER_BIND=/opt,/var/spool,/home,/etc/os-release:/etc/os-release
$ apptainer exec leap_15.3.sif bash -c "echo \$APPTAINER_BIND"
/etc/os-release
``` 
Jumbled ordering 
```bash
$  export APPTAINER_BIND=/etc/os-release:/etc/os-release,/home,/opt,/etc/DIR_COLORS:/etc/DIR_COLORS
$ apptainer exec leap_15.3.sif bash -c "echo \$APPTAINER_BIND"
/etc/os-release,/home,/opt,/etc/DIR_COLORS:/etc/os-release,/home,/opt,/etc/DIR_COLORS:/etc/DIR_COLORS
```

### What OS/distro are you running
```
NAME="Red Hat Enterprise Linux"
VERSION="8.6 (Ootpa)"
```

### How did you install Apptainer
RPM

**Comment by DrDaveD** [comment]
Thanks for the report.  I can reproduce also on centos7 with centos7.sif.  I suspect the changes to nested binds in #526 are to blame.  Running some tests.
