### ISSUE TITLE
squashfuse_ll failed to mount /var/apptainer/mnt/session/rootfs error

### ISSUE THREAD

**Issue by Nilad** [apptainer/apptainer#1033]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer version 1.1.4-2.el7`

### Expected behavior

Running my singularity images throught NFS bridge a web-server to cluster grid (each nodes contains apptainer at the version indicate previously - jobs works with SLURM) 

### Actual behavior

Since the 1.1.4 version of apptainer, somes jobs (not all...) didn't run and display this error.

```sh
FATAL: container creation failed: mount hook function failure: mount /proc/self/fd/10->/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/10: squashfuse_ll failed to mount /var/apptainer/mnt/session/rootfs in 2s: 
```

Everything was working between january 2022 and mid-december 2022, since the apptainer update to 1.1.4. I have this problem.

### Steps to reproduce this behavior

I launch my job submission with this kind of command.

```ssh
ssh MYUSER@CLUSTER_GRID -t "srun --partition=fast --qos=fast --ntasks=1 --cpus-per-task=5 --mem=10000M --exclude=SOMES_EXCLUDE_NODES --chdir=CHDIR singularity exec --no-home --cleanenv -B MOUNT_POINT MY_IMAGE COMMAND"
```

### What OS/distro are you running

Cluster_conf

```sh
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

**Comment by GodloveD** [comment]
It seems like squashfuse_ll is timing out trying to mount the container to the mount point.  Although I'm not sure if that error message is the actual problem or is just an effect of another error happening earlier.  I reread the release notes for 1.1.4 and I'm not seeing any changes having to do with squashfuse specifically.  If you have the user namespace enabled, you may try installing 1.1.5 in your personal space and see if that suffers from the same issue.  Maybe @DrDaveD has more ideas.

**Comment by DrDaveD** [comment]
The timeout is actually in apptainer itself.  It allows up to 2 seconds for squashfuse_ll to finish mounting so it knows that it's ok to proceed.  I wonder if in your conditions it sometimes actually takes more than 2 seconds for the mount to occur.  We could increase that maximum value a little in another release, if that in fact solves the problem.  Could you possibly compile from source to test that?  The timeout value is set on [this line of code](https://github.com/apptainer/apptainer/blob/release-1.1/internal/pkg/image/driver/imagedriver.go#L299).

With debugging enabled (using apptainer -d or setting APPTAINER_DEBUG=1) it shows how long the mount takes, in 10 millisecond intervals.  If you run that multiple times and often see it close to 2 seconds when it succeeds but the time is variable, that makes this solution more likely.  I have never seen it get close to 2 seconds in my tests.

**Comment by Nilad** [comment]
Thanks @GodloveD and @DrDaveD for the reply.

I am just a user of the cluster grid and unfortunately, i don't have any right to compile or update apptainer. I am looking for a solution to propose to the system admin of this cluster grid.

with `--debug` label in singularity, i got this output on a fail job.

(just display last lines)
```bash
.
.
.
.
VERBOSE [U=5426,P=7358]    init()                        Spawn RPC server
DEBUG   [U=5426,P=7198]    startup()                     apptainer runtime engine selected
VERBOSE [U=5426,P=7198]    startup()                     Execute master process
DEBUG   [U=5426,P=7358]    startup()                     apptainer runtime engine selected
VERBOSE [U=5426,P=7358]    startup()                     Serve RPC requests
DEBUG   [U=5426,P=7198]    findOnPath()                  Found "squashfuse_ll" at "/usr/libexec/apptainer/bin/squashfuse_ll"
DEBUG   [U=5426,P=7198]    findOnPath()                  Found "fuse2fs" at "/usr/sbin/fuse2fs"
DEBUG   [U=5426,P=7198]    findOnPath()                  Found "fuse-overlayfs" at "/usr/bin/fuse-overlayfs"
DEBUG   [U=5426,P=7198]    InitImageDrivers()            squashfuse_ll supports -o uid
DEBUG   [U=5426,P=7198]    InitImageDrivers()            Setting ImageDriver to fuseapps
DEBUG   [U=5426,P=7198]    setupSessionLayout()          Using Layer system: underlay
DEBUG   [U=5426,P=7198]    setupUnderlayLayout()         Creating underlay SESSIONDIR layout
DEBUG   [U=5426,P=7198]    addRootfsMount()              Mount rootfs in read-only mode
DEBUG   [U=5426,P=7198]    addRootfsMount()              Image type is 4096
DEBUG   [U=5426,P=7198]    addRootfsMount()              Mounting block [squashfs] image: MY_IMAGE
DEBUG   [U=5426,P=7198]    addKernelMount()              Checking configuration file for 'mount proc'
DEBUG   [U=5426,P=7198]    addKernelMount()              Adding proc to mount list
VERBOSE [U=5426,P=7198]    addKernelMount()              Default mount: /proc:/proc
DEBUG   [U=5426,P=7198]    addKernelMount()              Checking configuration file for 'mount sys'
DEBUG   [U=5426,P=7198]    addKernelMount()              Adding sysfs to mount list
VERBOSE [U=5426,P=7198]    addKernelMount()              Default mount: /sys:/sys
DEBUG   [U=5426,P=7198]    addDevMount()                 Checking configuration file for 'mount dev'
DEBUG   [U=5426,P=7198]    addDevMount()                 Adding dev to mount list
VERBOSE [U=5426,P=7198]    addDevMount()                 Default mount: /dev:/dev
DEBUG   [U=5426,P=7198]    addHostMount()                Not mounting host file systems per configuration
VERBOSE [U=5426,P=7198]    addBindsMount()               Found 'bind path' = /etc/localtime, /etc/localtime
VERBOSE [U=5426,P=7198]    addBindsMount()               Found 'bind path' = /etc/hosts, /etc/hosts
DEBUG   [U=5426,P=7198]    addHomeMount()                Skipping home directory mount by user request.
DEBUG   [U=5426,P=7198]    addUserbindsMount()           Adding MY_MOUNT to mount list
DEBUG   [U=5426,P=7198]    addTmpMount()                 Checking for 'mount tmp' in configuration file
VERBOSE [U=5426,P=7198]    addTmpMount()                 Default mount: /tmp:/tmp
VERBOSE [U=5426,P=7198]    addTmpMount()                 Default mount: /var/tmp:/var/tmp
DEBUG   [U=5426,P=7198]    addScratchMount()             Not mounting scratch directory: Not requested
DEBUG   [U=5426,P=7198]    addLibsMount()                Checking for 'user bind control' in configuration file
DEBUG   [U=5426,P=7198]    addFilesMount()               Checking for 'user bind control' in configuration file
DEBUG   [U=5426,P=7198]    addResolvConfMount()          Adding /etc/resolv.conf to mount list
VERBOSE [U=5426,P=7198]    addResolvConfMount()          Default mount: /etc/resolv.conf:/etc/resolv.conf
DEBUG   [U=5426,P=7198]    addHostnameMount()            Skipping hostname mount, not virtualizing UTS namespace on user request
DEBUG   [U=5426,P=7198]    create()                      Mount all
DEBUG   [U=5426,P=7198]    mountGeneric()                Mounting tmpfs to /var/apptainer/mnt/session
DEBUG   [U=5426,P=7198]    func2()                       Starting image driver fuseapps
DEBUG   [U=5426,P=7198]    Mount()                       Executing /usr/libexec/apptainer/bin/squashfuse_ll -f -o uid=5426,gid=5054,offset=45056 /proc/self/fd/3 /var/apptainer/mnt/session/rootfs
DEBUG   [U=5426,P=7198]    stop()                        Waiting for squashfuse_ll pid 7375 to exit
DEBUG   [U=5426,P=7198]    stop()                        Killing pid 7375
DEBUG   [U=5426,P=7198]    stop()                        squashfuse_ll pid 7375 exited with status -1 within 10ms
DEBUG   [U=5426,P=7198]    umount()                      Umount /var/apptainer/mnt/session/final
DEBUG   [U=5426,P=7198]    umount()                      Umount /var/apptainer/mnt/session/rootfs
DEBUG   [U=5426,P=7198]    stop()                        Waiting for squashfuse_ll pid 7375 to exit
DEBUG   [U=5426,P=7198]    stop()                        Waiting for squashfuse_ll pid 7375 failed: no child processes
FATAL   [U=5426,P=7198]    Master()                      container creation failed: mount hook function failure: mount /proc/self/fd/10->/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/10: squashfuse_ll failed to mount /var/apptainer/mnt/session/rootfs in 2s: 
srun: error: hpcnode39: task 0: Exited with exit code 255
```

I am at your dispose if you need more informations that i can give to you.

**Comment by DrDaveD** [comment]
That's helpful.  Can you do the same also for some of them that succeed, and look for DEBUG messages of the form
```
/var/apptainer/mnt/session/rootfs mounted in 50ms
```
I'd like to know if it is often getting close to 2000ms.

**Comment by Nilad** [comment]
From Debug log of a success job

```
.
.
.
DEBUG   [U=5426,P=1084]    create()                      Mount all
DEBUG   [U=5426,P=1084]    mountGeneric()                Mounting tmpfs to /var/apptainer/mnt/session
DEBUG   [U=5426,P=1084]    func2()                       Starting image driver fuseapps
DEBUG   [U=5426,P=1084]    Mount()                       Executing /usr/libexec/apptainer/bin/squashfuse_ll -f -o uid=5426,gid=5054,offset=40960 /proc/self/fd/3 /var/apptainer/mnt/session/rootfs
DEBUG   [U=5426,P=1084]    func1()                       fuse: failed to clone device fd: Inappropriate ioctl for device
DEBUG   [U=5426,P=1084]    func1()                       fuse: trying to continue without -o clone_fd.
DEBUG   [U=5426,P=1084]    Mount()                       /var/apptainer/mnt/session/rootfs mounted in 25ms
INFO    [U=5426,P=1084]    duplicateDir()                underlay of /usr/share/zoneinfo/Etc/UTC required more than 50 (56) bind mounts
DEBUG   [U=5426,P=1084]    mountGeneric()                Mounting /var/apptainer/mnt/session/rootfs/usr/bin to /var/apptainer/mnt/session/underlay/usr/bin
DEBUG   [U=5426,P=1084]    mountGeneric()                Mounting /var/apptainer/mnt/session/rootfs/usr/games to /var/apptainer/mnt/session/underlay/usr/games
DEBUG   [U=5426,P=1084]    mountGeneric()                Mounting /var/apptainer/mnt/session/rootfs/usr/include to /var/apptainer/mnt/session/underlay/usr/include
DEBUG   [U=5426,P=1084]    mountGeneric()                Mounting /var/apptainer/mnt/session/rootfs/usr/lib to /var/apptainer/mnt/session/underlay/usr/lib
DEBUG   [U=5426,P=1084]    mountGeneric()                Mounting /var/apptainer/mnt/session/rootfs/usr/local to /var/apptainer/mnt/session/underlay/usr/local
.
.
.
.
DEBUG   [U=5426,P=1084]    umount()                      Umount /var/apptainer/mnt/session/underlay/usr/sbin
DEBUG   [U=5426,P=1084]    umount()                      Umount /var/apptainer/mnt/session/underlay/usr/local
DEBUG   [U=5426,P=1084]    umount()                      Umount /var/apptainer/mnt/session/underlay/usr/lib
DEBUG   [U=5426,P=1084]    umount()                      Umount /var/apptainer/mnt/session/underlay/usr/include
DEBUG   [U=5426,P=1084]    umount()                      Umount /var/apptainer/mnt/session/underlay/usr/games
DEBUG   [U=5426,P=1084]    umount()                      Umount /var/apptainer/mnt/session/underlay/usr/bin
DEBUG   [U=5426,P=1084]    umount()                      Umount /var/apptainer/mnt/session/final
DEBUG   [U=5426,P=1084]    umount()                      Umount /var/apptainer/mnt/session/rootfs
DEBUG   [U=5426,P=1084]    stop()                        Waiting for squashfuse_ll pid 1115 to exit
DEBUG   [U=5426,P=1084]    stop()                        squashfuse_ll pid 1115 exited with status 0 within 10ms
DEBUG   [U=5426,P=1084]    Master()                      Child exited with exit status 0
```

**Comment by DrDaveD** [comment]
So that completed very quickly, 10ms.  So it does not seem likely that increasing the timeout will help.  There appears to be something on your system that is really causing it to hang. If I could reproduce it I would probably put a wrapper around squashfuse_ll to run strace on it, but I don't know if that's something you can do.

**Comment by GeertvanGeest** [comment]
If it's of any help, we're facing similar issues on CentOS-7 with `apptainer version 1.1.5-1.el7`. It typically happens with jobs submitted to slurm by nextflow, but other than that I can't find a pattern.

**Comment by DrDaveD** [comment]
If somebody could catch an strace of squashfuse_ll on one of those failing conditions, that could be a big help.

**Comment by Nilad** [comment]
@DrDaveD, my admin system change the `maxTime` variable of 2 to 30. 

Since 24h of jobs submission after the edited `apptainer` compilation, i did not encounter the previous problem.

So... maybe to ensure to not encounter this problem in the next version of `apptainer`, it should be interresting to increase by default this time limit, add the possibility to modify this setting and add explicit error message if this case of timeout is reach.

Thanks for your support.

**Comment by DrDaveD** [comment]
Thanks, that's a good data point.  It would additionally be very helpful if he could have it print an INFO message to say how long it took and for you to collect those numbers and report the ranges.  Then I could know how much to increase the limit.

We are planning a 1.1.6 release early next week but I don't know if there's enough time to get it in for that release.

What do you mean by "explicit error message if this case of timeout is reached"?  What would you like to see changed from the current error message?

**Comment by Nilad** [comment]
For the first part, i dont know how collect this information... if you have an idea...

Maybe just have more indication of the "squahfuse_ll" faillure...if its a timeout problem or another problem... maybe a message to indicate to try to increase the `maxTime` variable ? In the current error message, its difficult to understand the cause of the problem. Without your help or code investigation, i think it will be nearly impossible to resolve this error.

**Comment by DrDaveD** [comment]
> For the first part, i dont know how collect this information... if you have an idea...

If it is added to the output of apptainer on your system, can't you get that output?

> Maybe just have more indication of the "squahfuse_ll" faillure...if its a timeout problem or another problem... maybe a message to indicate to try to increase the `maxTime` variable ? In the current error message, its difficult to understand the cause of the problem. Without your help or code investigation, i think it will be nearly impossible to resolve this error.

In this case it is always a timeout problem.  Yes if I make the timeout configurable, including in the message a pointer to how to change it in the error message would be helpful.

**Comment by DrDaveD** [comment]
I think I'd really rather avoid adding an option to set the maxTime.  It's an unnecessary complication. There's not a lot of downside to making it long, but 30 seconds is too long.  It would be good to know how long it really takes in your environment, but I'm thinking of setting it at 5 or 10 for 1.1.6.
