### ISSUE TITLE
Unable to build sif using RH UBI 8 base image

### ISSUE THREAD

**Issue by singular55** [apptainer/apptainer#1034]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

`$ singularity --version
apptainer version 1.1.4-2.el8`

### Expected behavior

What did you expect to see when you do...?

Building from a def to sif file, expected to complete sif container.

### Actual behavior

What actually happened? Why was it incorrect?

sif creation fails for what looks like OCI related errors.  Would like to see complete sif or a more detailed error about the failure for debugging purposes.

$ singularity build rhubi.sif rhubi.def 
WARNING: DEPRECATED USAGE: Environment variable SINGULARITY_TMPDIR will not be supported in the future, use APPTAINER_TMPDIR instead
WARNING: DEPRECATED USAGE: Environment variable SINGULARITY_TMPDIR will not be supported in the future, use APPTAINER_TMPDIR instead
WARNING: 'nodev' mount option set on /ssd, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Checking if image destination supports signatures
FATAL:   While performing build: conveyor failed to get: initializing source oci:/home/kbrosius/.apptainer/cache/blob:323bb3abab06523d595d133fe82c40c13aea0242445c30c9842d34c81c221dea: copying system image from manifest list: Can not copy signatures to oci:/home/kbrosius/.apptainer/cache/blob:323bb3abab06523d595d133fe82c40c13aea0242445c30c9842d34c81c221dea: Pushing signatures for OCI images is not supported

However, a similar build with bionic is successful.

$ singularity build bionic.sif bionic.def 
WARNING: DEPRECATED USAGE: Environment variable SINGULARITY_TMPDIR will not be supported in the future, use APPTAINER_TMPDIR instead
WARNING: DEPRECATED USAGE: Environment variable SINGULARITY_TMPDIR will not be supported in the future, use APPTAINER_TMPDIR instead
WARNING: 'nodev' mount option set on /ssd, it could be a source of failure during build process
INFO:    Starting build...
...
completes sif successfully

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```sh
$ cat /etc/os-release

NAME="Red Hat Enterprise Linux"
VERSION="8.5 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.5 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.5"
VARIANT="Server"


```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.

Unsure, installed by admins.  If some detail is needed, I can request more information.
[rhubi.def.txt](https://github.com/apptainer/apptainer/files/10501675/rhubi.def.txt)
[bionic.def.txt](https://github.com/apptainer/apptainer/files/10501686/bionic.def.txt)

**Comment by singular55** [comment]
Oh, I should have stated that is a working def file on other platforms/singularity installs.  Note that Redhat says "Red Hat UBI images are available from both authenticated (registry.redhat.io) and unauthenticated (registry.access.redhat.com) registries."  The developer that setup our original ubi8 usage wanted to avoid authentication, I think.
So my real question is more along the lines of the oci dependencies and the errors that apptainer is throwing (if you know.)  This is a RHEL 8.5 which should work fine, I would think.  The other systems I have built with this type of def file on are not 8.5 though, I suspect.  And most are singularity versions, not apptainer.
I did pull an unprivileged install using the new script and tried it with:
`$ ./apptainer-unpriv/bin/singularity --version
apptainer version 1.1.5-1.el8`
On this system the rhubi def built successfully:
`$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
`
But the build still fails on the original system.  So it seems this is either newer RedHat related or maybe system setup?  Are there any external dependencies for the OCI layer that might be causing a problem?

I am a little suspicious of a thread and bug I found, but don't fully understand the implications: 
`https://access.redhat.com/discussions/6447391
https://bugzilla.redhat.com/show_bug.cgi?id=1633482`

**Comment by DrDaveD** [comment]
I have been able to reproduce this on rocky 8.7 and apptainer-1.1.5 installed from epel.  It does not fail on centos7.

**Comment by DrDaveD** [comment]
In debug mode, the rocky8 failure looks like this:
```
INFO    [U=0,P=1]          Full()                        Starting build...
DEBUG   [U=0,P=1]          Get()                         Reference: registry.access.redhat.com/ubi8/ubi:latest
DEBUG   [U=0,P=1]          getRefDigest()                Falling back to GetManifest digest: invalid checksum digest format
DEBUG   [U=0,P=1]          getRefDigest()                GetManifest digest for docker://registry.access.redhat.com/ubi8/ubi:latest is 323bb3abab06523d595d133fe82c40c13aea0242445c30c9842d34c81c221dea
Getting image source signatures
Checking if image destination supports signatures
DEBUG   [U=0,P=1]          cleanUp()                     Cleaning up "/scratch/tmp/build-temp-37875512/rootfs" and "/scratch/tmp/bundle-temp-3209264126"
FATAL   [U=0,P=1]          runBuildLocal()               While performing build: conveyor failed to get: initializing source oci:/home/dwd/.apptainer/cache/blob:323bb3abab06523d595d133fe82c40c13aea0242445c30c9842d34c81c221dea: copying system image from manifest list: Can not copy signatures to oci:/home/dwd/.apptainer/cache/blob:323bb3abab06523d595d133fe82c40c13aea0242445c30c9842d34c81c221dea: Pushing signatures for OCI images is not supported
DEBUG   [U=0,P=2756]       func1()                       Wait for process 2764 complete with status 65280, error <nil>
DEBUG   [U=0,P=2756]       Master()                      Child exited with exit status 255
```
The corresponding success on el7 never says `Checking if image destination supports signatures`:
```
INFO    [U=0,P=991407]     Full()                        Starting build...
DEBUG   [U=0,P=991407]     Get()                         Reference: registry.access.redhat.com/ubi8/ubi:latest
DEBUG   [U=0,P=991407]     getRefDigest()                Falling back to GetManifest digest: invalid checksum digest format
DEBUG   [U=0,P=991407]     getRefDigest()                GetManifest digest for docker://registry.access.redhat.com/ubi8/ubi:latest is 323bb3abab06523d595d133fe82c40c13aea0242445c30c9842d34c81c221dea
Getting image source signatures
Copying blob 649e5534d134 [====================>-------------] 46.1MiB / 75.5MiB
```

**Comment by DrDaveD** [comment]
It's because of a setting in `/etc/containers/policy.json`.  See sylabs/singularity#697.

**Comment by singular55** [comment]
Nice, I should have searched the syslabs bugs.  My google searches did not show that.
It matches my experience directly.  I have several RHEL < 8 and some SuSE Enterprise systems that have built with this def.  It's only this latest system that now has RHEL 8 with a RH UBI target.  So first time to come across the issue.
@GodloveD , is that why you suggested usage of a RedHat account?  I think that would bypass the issue as well as your suggestion of the Docker Hub source.  I will consider those.  I don't have access to the RedHat account used by the admins in this case, so that won't be the first choice.

**Comment by GodloveD** [comment]
I've not tested myself, but I bet the DockerHub image is identical to the one hosted on RH's main site.  Might even just be an alias to it.  It is maintained by RH, so I would just use it tbh.

**Comment by singular55** [comment]
I can confirm that using:
`Bootstrap: docker
From: redhat/ubi8:latest
`
Behaves properly and does not exhibit the signatures issue.

**Comment by DrDaveD** [comment]
Very good.  I'll close the ticket.  Reopen if you think there's something else that's still needed.
