### ISSUE TITLE
container creation failed: mount hook function failure: mount /proc/self/fd/3->/var/lib/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3: squashfuse_ll exited with status 255: Something went wrong trying to read the squashfs image

### ISSUE THREAD

**Issue by 0820LL** [apptainer/apptainer#1037]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

apptainer version 1.1.4

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Apptainer

curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh |
bash -s - install-dir

**Comment by GodloveD** [comment]
We need more info to reproduce this.

**Comment by DrDaveD** [comment]
Yes, we need more information about how you got to that error, what commands you ran.,

When I run the install command on ubuntu 18.04 I get the message
```
ubuntu18 not supported, sorry
```
and nothing got installed, so it's very curious how you got to the error in the title.
