### ISSUE TITLE
Privileged installation thinks that it is unprivileged

### ISSUE THREAD

**Issue by simonleary-umass-edu** [apptainer/apptainer#1038]
### Version of Apptainer
```
1.0.2
```

### What OS/distro are you running
```sh
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
```

### How did you install Apptainer
I installed apptainer from Spack v0.19.
```
spack install apptainer+suid
```

### The problem
When I try to use `--fakeroot`, apptainer complains that I don't have a `newuidmap` binary:
```
$ apptainer shell --fakeroot ./container.sif 
INFO:    Converting SIF file to temporary sandbox...
FATAL:   newuidmap was not found in PATH (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin), required with fakeroot and unprivileged installation
```
I want to find out why my apptainer thinks that it is unprivileged. The spack install came with some extra instructions:
```
chown root libexec/apptainer/bin/starter-suid
chown root etc/apptainer/apptainer.conf
chown root etc/apptainer/capability.json
chown root etc/apptainer/ecl.toml
chmod 4555 libexec/apptainer/bin/starter-suid
```
I thought this would be enough. **What exactly are the conditions that need to be met for a privileged installation?**

**Comment by DrDaveD** [comment]
I would think that it should have been enough as well for the starter-suid to manage that.  Perhaps running it with `apptainer -d` will give some more helpful information.

For `--fakeroot` and apptainer-1.0.x you will also need mappings in /etc/subuid and /etc/subgid. although I think that check comes later.

**Comment by simonleary-umass-edu** [comment]
`-no-init --writable -B /scratch/login/rootfs-2177617321:/image -B /usr/bin/unsquashfs:/usr/bin/unsquashfs:ro -B /lib/x86_64-linux-gnu/libpthread.so.0:/lib/x86_64-linux-gnu/libpthread.so.0:ro -B /lib/x86_64-linux-gnu/libm.so.6:/lib/x86_64-linux-gnu/libm.so.6:ro -B /lib/x86_64-linux-gnu/libz.so.1:/lib/x86_64-linux-gnu/libz.so.1:ro -B /lib/x86_64-linux-gnu/liblzma.so.5:/lib/x86_64-linux-gnu/liblzma.so.5:ro -B /lib/x86_64-linux-gnu/liblzo2.so.2:/lib/x86_64-linux-gnu/liblzo2.so.2:ro -B /usr/lib/x86_64-linux-gnu/liblz4.so.1:/usr/lib/x86_64-linux-gnu/liblz4.so.1:ro -B /usr/lib/x86_64-linux-gnu/libzstd.so.1:/usr/lib/x86_64-linux-gnu/libzstd.so.1:ro -B /lib/x86_64-linux-gnu/libc.so.6:/lib/x86_64-linux-gnu/libc.so.6:ro -B /lib64/ld-linux-x86-64.so.2:/lib64/ld-linux-x86-64.so.2:ro /scratch/login/rootfs-2177617321/tmp-rootfs-3670524818 /usr/bin/unsquashfs -no-xattrs -r -d /image/root /image/archive-2009417687 ^(.{0}[^d]|.{1}[^e]|.{2}[^v]|.{3}[^\x2f]).*$]
FATAL   [U=1630,P=163458]  execStarter()                 while extracting ./rf_container.sif: root filesystem extraction failed: extract command failed: FATAL:   container creation failed: mount ->/modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/apptainer-1.0.2-aeh2jazlxiqsyq57l7ikjjn4kfjzulow/var/apptainer/mnt/session/rootfs error: while mounting : could not remount /modules/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/apptainer-1.0.2-aeh2jazlxiqsyq57l7ikjjn4kfjzulow/var/apptainer/mnt/session/rootfs: permission denied
: exit status 255`

Do I read that apptainer is trying to mount into the global apptainer installation? My users do not have privileges to that `var/apptainer/mnt/session/` directory.

**Comment by simonleary-umass-edu** [comment]
disregard my last comment, apptainer doesn't work on the login nodes on my cluster and I'm not sure why.
This is what's relevant to this issue:
```
DEBUG   [U=1241,P=2658630] init()                        Use starter binary /modules/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/apptainer-1.0.2-uawrr5bip7roevgbe6jluopb2bpvhew7/libexec/apptainer/bin/starter
VERBOSE [U=1241,P=2658630]  print()                       Set messagelevel to: 5
VERBOSE [U=1241,P=2658630]  init()                        Starter initialization
VERBOSE [U=1241,P=2658630]  is_suid()                     Check if we are running as setuid
DEBUG   [U=1241,P=2658630]  read_engine_config()          Read engine configuration
DEBUG   [U=1241,P=2658630]  init()                        Wait completion of stage1
DEBUG   [U=1241,P=2658637]  set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1241,P=2658637]  init()                        Spawn stage 1
DEBUG   [U=1241,P=2658637] startup()                     apptainer runtime engine selected
VERBOSE [U=1241,P=2658637] startup()                     Execute stage 1
DEBUG   [U=1241,P=2658637] StageOne()                    Entering stage 1
VERBOSE [U=1241,P=2658637] prepareContainerConfig()      Fakeroot requested with unprivileged workflow, fallback to newuidmap/newgidmap
DEBUG   [U=1241,P=2658637] prepareContainerConfig()      Search for newuidmap binary
DEBUG   [U=1241,P=2658637] findOnPath()                  Found "newuidmap" at ""
FATAL   [U=1241,P=2658637] StageOne()                    newuidmap was not found in PATH (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin), required with fakeroot and unprivileged installation
VERBOSE [U=1241,P=2658630]  wait_child()                  stage 1 exited with status 255
```

I would guess that `is_suid()` returned false?

**Comment by simonleary-umass-edu** [comment]
```
static bool is_suid(void) {
    unsigned long auxval;

    verbosef("Check if we are running as setuid\n");

    errno = 0;
    auxval = getauxval(AT_SECURE);

    if( errno != 0 ) {
        fatalf("Cannot obtain AT_SECURE auxval: %s\n", strerror(errno));
    }

    return auxval != 0;
}
```

Is `AT_SECURE` a file?

**Comment by DrDaveD** [comment]
Is starter-suid perhaps stored on a filesystem that has the "nosuid" mount flag set?

**Comment by simonleary-umass-edu** [comment]
It's not:
```
simonleary_umass_edu@login2:~$ mount | grep modules
vast:/modules on /modules type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.100.1.15,mountvers=3,mountport=20048,mountproto=udp,local_lock=none,addr=10.100.1.15)
simonleary_umass_edu@login2:~$ mount | grep modules | grep suid
simonleary_umass_edu@login2:~$ 
```

**Comment by simonleary-umass-edu** [comment]
My system does not have user namespaces enabled. I'm a little confused by the docs, I think I read that if you use setuid then you don't need user namespaces. Is that true?

**Comment by DrDaveD** [comment]
Oh, right.  User namespaces was needed for fakeroot prior to apptainer-1.1, even with suid.  Do you have /etc/subuid mappings set up?

There may still be parts of the docs that are confusing on that point, but I'm pretty sure that the message for that case was improved with apptainer-1.1 ... well, it was slightly improved.  If there is an /etc/subuid mapping and user namespaces are not enabled with apptainer-suid installed, using `--fakeroot` now says this regardless of the presence or absence of newuidmap:
```
INFO   : Unprivileged user namespaces may not be enabled
ERROR  : Failed to create container process: Invalid argument
```
On the other hand if there is no /etc/subuid map, trying to run with a sif file says
```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    No user namespaces available
INFO:    The fakeroot command by itself is only useful with sandbox images
INFO:     which can be built with 'apptainer build --sandbox'
FATAL:   --fakeroot used without sandbox image or user namespaces
```
It does however work without /etc/subuid maps with sandboxes even without user namespaces, with the fakeroot command:
```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    No user namespaces available, using only the fakeroot command
Apptainer>
```
That's because fakeroot mode (either with /etc/subuid or without) essentially has to be unprivileged, but mounting a sif file unprivileged requires user namespaces.

You are trying to use what the docs call the "rootless" fakeroot mode (the mode that uses /etc/subuid mapping), and the [requirements](https://apptainer.org/docs/admin/latest/user_namespace.html#requirements) section for that does clearly say that user namespaces are needed.  If there's another part of the docs that misled you, please point them out.  It's true that newuidmap is not needed when apptainer-suid is installed, but that mode still requires user namespaces.

**Comment by simonleary-umass-edu** [comment]
So it turns out that user namespaces was in fact enabled. But I installed apptainer 1.1.5 and my issue has gone away.

**Comment by DrDaveD** [comment]
Ok, cool.  Did you install apptainer-suid too or are you just using the no-suid mode?

**Comment by simonleary-umass-edu** [comment]
I installed `--with-suid`, but I did my install via the Spack package manager.

**Comment by simonleary-umass-edu** [comment]
it's using "root mapped namespaces' iirc

**Comment by DrDaveD** [comment]
If you have user namespaces enabled I recommend trying it without suid.  There are [very few reasons to risk it](https://apptainer.org/docs/user/latest/security.html#setuid-user-namespaces) with apptainer-1.1.

**Comment by simonleary-umass-edu** [comment]
It works without suid. Thanks
