### ISSUE TITLE
fixes to key server response parser for v1.0

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#104]
...

_Originally posted by @PaulCharlton in https://github.com/apptainer/apptainer/pull/99#pullrequestreview-840666657_

**Comment by PaulCharlton** [comment]
@DrDaveD @ikaneshiro ^^^

**Comment by PaulCharlton** [comment]
<img width="933" alt="Screen Shot 2021-12-29 at 7 25 44 AM" src="https://user-images.githubusercontent.com/1747363/147723783-aa21fd63-f353-44a0-b06c-a3f374913b3d.png">
<img width="957" alt="Screen Shot 2021-12-29 at 7 25 35 AM" src="https://user-images.githubusercontent.com/1747363/147723797-c54e179b-98a0-4085-a969-024c640988ec.png">

**Comment by DrDaveD** [comment]
Fixed by #113
