### ISSUE TITLE
CAP_DAC_READ_SEARCH is not in the permitted capability set on google colab, but fakeroot works

### ISSUE THREAD

**Issue by stebo85** [apptainer/apptainer#1041]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? 

```
1.1.5
```

### Expected behavior

What did you expect to see when you do...?

I would like to run apptainer on google colab with a sandbox image directory. When I execute apptainer with

```
apptainer exec /cvmfs/neurodesk.ardc.edu.au/containers/fsl_6.0.4_20210105/fsl_6.0.4_20210105.simg bet
```

I get this error:

```
FATAL:   container creation failed: mount hook function failure: mount overlay->/var/lib/apptainer/mnt/session/final error: while mounting overlay: can't mount overlay filesystem to /var/lib/apptainer/mnt/session/final: while setting effective capabilities: CAP_DAC_READ_SEARCH is not in the permitted capability set

```

### Actual behavior

What actually happened? Why was it incorrect?

When I run with fakeroot it works however:

```
apptainer exec --fakeroot /cvmfs/neurodesk.ardc.edu.au/containers/fsl_6.0.4_20210105/fsl_6.0.4_20210105.simg bet
```

I am wondering if there is a way to run without --fakeroot because it seems unnessary or is this the correct way on google colab?

### Steps to reproduce this behavior
How can others reproduce this issue/problem?

Here is the google colab notebook with the issue: https://colab.research.google.com/drive/1g5cnZxj1llRaHmOs4xSglqsXnFkQYuol?usp=sharing

### What OS/distro are you running
20.04.5 LTS on Google Colab

### How did you install Apptainer

```
sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:apptainer/ppa
sudo apt update
sudo apt install -y apptainer
sudo apt install -y apptainer-suid
sudo apptainer config fakeroot --add root
```

**Comment by DrDaveD** [comment]
I tried reproducing the configuration on my ubuntu 20.04 vagrant setup and did not get it to fail.  Is the apptainer exec command running as root?  I tried running it with sudo and it still didn't fail, but maybe the default root on Google collab has limited capabilities; you can print the list of capabilities with `capsh --print`.  I suggest trying it under an unprivileged user id, or perhaps under `unshare -r` which should create a new root-mapped user namespace with all capabilities.  The `--fakeroot` option creates a new user namespace too but it also maps all the unprivileged user ids.

**Comment by stebo85** [comment]
Dear Dave,

Thank you for your very helpful response :)

I think the behaviour comes from google colab's limited capabilities and running apptainer as root by default:

```
WARNING: libcap needs an update (cap=40 should have a name).
Current: = cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_ptrace,cap_sys_admin,cap_mknod,cap_audit_write,cap_setfcap+eip
Bounding set =cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_raw,cap_sys_chroot,cap_sys_ptrace,cap_sys_admin,cap_mknod,cap_audit_write,cap_setfcap
Ambient set =
Securebits: 00/0x0/1'b0
 secure-noroot: no (unlocked)
 secure-no-suid-fixup: no (unlocked)
 secure-keep-caps: no (unlocked)
 secure-no-ambient-raise: no (unlocked)
uid=0(root) euid=0(root)
gid=0(root)
groups=
Guessed mode: UNCERTAIN (0)
```

`unshare -r apptainer` did the trick and it's all working nicely now :)

Thank you
Steffen
