### ISSUE TITLE
Issue running a program that utilizes graphics (`--nv`)

### ISSUE THREAD

**Issue by sudomaze** [apptainer/apptainer#1080]
### Version of Apptainer

_What version of Apptainer (or Singularity) are you using?_

- **[machine_build]** The machine that built the image: `apptainer version 1.1.5`
- **[machine_works]** The successful machine that runs the image: `apptainer version 1.1.5`
- **[machine_failed]** The failed machine that runs the image: `apptainer version 1.1.5`

### Expected behavior

_What did you expect to see when you do...?_

machine_build built the container that was shared with machine_works and machine_failed to be utilized to run some programs within it. Being able to run the container with NVIDIA GPU access.

### Actual behavior

_What actually happened? Why was it incorrect?_

**Our hypothesis:** `--nv` seems to expose a conflicting library into play that prevents our container’s version of that dependency to be found.  The improperly found dependency then depends on something that’s missing from the container.

machine_works managed to run the program without any issues, however, machine_failed managed to run the image but couldn’t run the program within the image.

We used the same command to run the image with nvidia-driver apptainer run `--nv IMAGE_NAME.sif` and `nvidia-smi` works on both containers’ shells.

The given error from running the program on the machine_failed is:

```
Traceback (most recent call last):
  File "PATH/SCRIPT.py", line 2, in <module>
   <UNRELATED TRACEBACK>
    import cv2
  File "/miniconda3/lib/python3.9/site-packages/cv2/init.py", line 181, in <module>
    bootstrap()
  File "/miniconda3/lib/python3.9/site-packages/cv2/init.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/miniconda3/lib/python3.9/importlib/init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLdispatch.so.0)
```

<details>
<summary>machine_build</summary>

```
libEGL.so.1
libEGL_nvidia.so.0
libGL.so.1
libGLESv1_CM_nvidia.so.1
libGLESv2.so.2
libGLESv2_nvidia.so.2
libGLX.so.0
libGLX_nvidia.so.0
libGLdispatch.so.0
libOpenGL.so.0
libcuda.so
libcuda.so.1
libnvcuvid.so
libnvcuvid.so.1
libnvidia-cfg.so
libnvidia-cfg.so.1
libnvidia-compiler.so.510.47.03
libnvidia-eglcore.so.510.47.03
libnvidia-encode.so
libnvidia-encode.so.1
libnvidia-fbc.so
libnvidia-fbc.so.1
libnvidia-glcore.so.510.47.03
libnvidia-glsi.so.510.47.03
libnvidia-glvkspirv.so.510.47.03
libnvidia-gtk2.so.470.57.01
libnvidia-gtk3.so.470.57.01
libnvidia-ml.so
libnvidia-ml.so.1
libnvidia-opencl.so.1
libnvidia-opticalflow.so
libnvidia-opticalflow.so.1
libnvidia-ptxjitcompiler.so
libnvidia-ptxjitcompiler.so.1
libnvidia-rtcore.so.510.47.03
libnvidia-tls.so.510.47.03
libnvoptix.so.1

```
</details>

<details>
<summary>machine_works has this version of libs in /.singularity.d/libs </summary>

```
libEGL.so.1
libEGL_nvidia.so.0
libGL.so.1
libGLESv1_CM_nvidia.so.1
libGLESv2.so.2
libGLESv2_nvidia.so.2
libGLX.so.0
libGLX_nvidia.so.0
libGLdispatch.so.0
libOpenGL.so.0
libcuda.so
libcuda.so.1
libnvcuvid.so
libnvcuvid.so.1
libnvidia-cfg.so
libnvidia-cfg.so.1
libnvidia-compiler.so.510.47.03
libnvidia-eglcore.so.510.47.03
libnvidia-encode.so
libnvidia-encode.so.1
libnvidia-fbc.so
libnvidia-fbc.so.1
libnvidia-glcore.so.510.47.03
libnvidia-glsi.so.510.47.03
libnvidia-glvkspirv.so.510.47.03
libnvidia-gtk2.so.470.57.01
libnvidia-gtk3.so.470.57.01
libnvidia-ml.so
libnvidia-ml.so.1
libnvidia-opencl.so.1
libnvidia-opticalflow.so
libnvidia-opticalflow.so.1
libnvidia-ptxjitcompiler.so
libnvidia-ptxjitcompiler.so.1
libnvidia-rtcore.so.510.47.03
libnvidia-tls.so.510.47.03
libnvoptix.so.1


```
</details>

<details>
<summary>machine_failed has this version of libs in /.singularity.d/libs, which is not identical</summary>

```
libEGL.so
libEGL.so.1
libEGL_nvidia.so.0
libGL.so
libGL.so.1
libGLESv1_CM.so
libGLESv1_CM.so.1
libGLESv1_CM_nvidia.so.1
libGLESv2.so
libGLESv2.so.2
libGLESv2_nvidia.so.2
libGLX.so
libGLX.so.0
libGLX_nvidia.so.0
libGLdispatch.so
libGLdispatch.so.0
libOpenCL.so
libOpenCL.so.1
libOpenGL.so
libOpenGL.so.0
libcuda.so
libcuda.so.1
libnvidia-cfg.so
libnvidia-cfg.so.1
libnvidia-compiler.so.510.108.03
libnvidia-egl-wayland.so.1
libnvidia-eglcore.so.515.86.01
libnvidia-fbc.so
libnvidia-fbc.so.1
libnvidia-glcore.so.515.86.01
libnvidia-glsi.so.515.86.01
libnvidia-glvkspirv.so.515.86.01
libnvidia-ml.so
libnvidia-ml.so.1
libnvidia-opencl.so.1
libnvidia-ptxjitcompiler.so
libnvidia-ptxjitcompiler.so.1
libnvidia-rtcore.so.515.86.01
libnvidia-tls.so.515.86.01
libnvoptix.so.1
```
</details>

### Steps to reproduce this behavior

_How can others reproduce this issue/problem?_
`--nv` seems to expose a conflicting library into play that prevents our container’s version of that dependency to be found.  The improperly found dependency then depends on something that’s missing from the container.

### What OS/distro are you running

<details>
<summary>machine_build</summary>

```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
</details>

<details>
<summary>machine_works</summary>

```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
</details>

<details>
<summary>machine_failed</summary>

```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
</details>

### How did you install Apptainer

_Write here how you installed Apptainer (or Singularity). Eg. RPM, source._

```bash
sudo apt update
sudo apt install -y software-properties-common
sudo add-apt-repository -y ppa:apptainer/ppa
sudo apt update  
sudo apt install -y apptainer
```

cc: @jedirv

**Comment by GodloveD** [comment]
Sorry for the delay and thanks for raising the issue.  Can you also provide the def file that you used to build the container please?  I'd like to try to reproduce.  

I think that the library `libGLdispatch.so` that is being imported from the newer host (Ubuntu 22) is built against a newer glibc (GLIBC_2.34) than what is found in the container.  If you have admin rights, you could try commenting out `libGLdispatch.so` and `libGLdispatch.so.0` from `etc/apptainer/nvliblist.conf`.  If your container has that library as part of the installation that should work (or at least give you a different error).

**Comment by sudomaze** [comment]
@GodloveD Thanks for the reply!

We thought of doing an experiment where we downgrade the `machine_failed` system from `Ubuntu 22.04` to `Ubuntu 20.04` to test our hypothesis that when `apptainer` is being installed, it allocates `etc/apptainer/nvliblist.conf` with "suggested" libs to be imported whenever `--nv` is triggered. Because we have a newer version of `Ubuntu`, we have different libs to be imported from the host to the container.

I think following your suggestion might save us some time and effort to not downgrade the system. I will check this today and keep you updated. Thanks for your suggestion!

**Comment by jedirv** [comment]
@GodloveD re the request for our def file - if pulls code from a private repo so you wouldn't be able to build it on your end.

**Comment by sudomaze** [comment]
@GodloveD Sorry for the late update.

We have done the following:
1. Downgrading OS from `Ubuntu 22.04` to `Ubuntu 20.04` and the built image managed to work without any issues!
2. We still use `Ubuntu 22.04` and we have commented out the suggested files from `etc/apptainer/nvliblist.conf`, but we still had other crashes for similar reasons. We commented out those also. After doing this, we managed to the built image managed to work! Please see the below `nvliblist.conf` file.

<details>
<summary><code>nvliblist.conf</code></summary>

```conf
# NVLIBLIST.CONF
# This configuration file determines which NVIDIA libraries to search for on 
# the host system when the --nv option is invoked.  You can edit it if you have
# different libraries on your host system.  You can also add binaries and they
# will be mounted into the container when the --nv option is passed.

# put binaries here
# In shared environments you should ensure that permissions on these files 
# exclude writing by non-privileged users.  
nvidia-smi
nvidia-debugdump
nvidia-persistenced
nvidia-cuda-mps-control
nvidia-cuda-mps-server

# put libs here (must end in .so) 
libcuda.so
libEGL_installertest.so
libEGL_nvidia.so
libEGL.so
#libGLdispatch.so
libGLESv1_CM_nvidia.so
libGLESv1_CM.so
libGLESv2_nvidia.so
libGLESv2.so
libGL.so
libGLX_installertest.so
#libGLX_nvidia.so
libglx.so
#libGLX.so
libnvcuvid.so
libnvidia-cbl.so
libnvidia-cfg.so
libnvidia-compiler.so
libnvidia-eglcore.so
libnvidia-egl-wayland.so
libnvidia-encode.so
libnvidia-fatbinaryloader.so
libnvidia-fbc.so
libnvidia-glcore.so
libnvidia-glsi.so
libnvidia-glvkspirv.so
libnvidia-gtk2.so
libnvidia-gtk3.so
libnvidia-ifr.so
libnvidia-ml.so
libnvidia-opencl.so
libnvidia-opticalflow.so
libnvidia-ptxjitcompiler.so
libnvidia-rtcore.so
libnvidia-tls.so
libnvidia-wfb.so
libnvoptix.so.1
libOpenCL.so
libOpenGL.so
libvdpau_nvidia.so
nvidia_drv.so
tls_test_.so
```
</details>

---

For the second solution, we looked into the libs in the system and we have realized that in the system `libGLX.so` exists in `nvliblist.conf` but in the system exists as `libGLX.so.0`. I think this might be a bug from `apptainer` side if it imports the wrong libs and append them to the config file.

cc: @jedirv @ridhap

**Comment by GodloveD** [comment]
I think that Apptainer uses the `nvliblist.conf` entries for a template matching strategy.  So for instance, the presence of `libGLX.so` in the conf file causes `libGLX.so.*` (from the ldconfig cache) to be bind mounted into the container.  But yes, that library list may be incorrect under certain circumstances.  

I have not used it extensively, but you might try installing the [nvidia container cli](https://github.com/NVIDIA/libnvidia-container) and using the `--nvccli` option instead of `--nv`.  That is supposed to generate a more "intelligent" list of libraries to bind mount in at runtime.

**Comment by sudomaze** [comment]
Thanks for giving more context, it makes sense. We might explore the `--nvccli` once we have some issues with the current setup. Thanks for your help!

I will close the issue as the issue has been resolved in https://github.com/apptainer/apptainer/issues/1080?notification_referrer_id=NT_kwDOAQV5_bM1NTYzODM4Nzc0OjE3MTM2MTI1#issuecomment-1434649979

**Comment by DrDaveD** [comment]
@sudomaze Can there be one configuration file that will work with in both cases?  If so we would want to update the default file we release.  I believe that apptainer silently ignores missing files.

**Comment by sudomaze** [comment]
@DrDaveD I just saw your updated message. I will revisit this by using the `built_machine`'s `nvconfig` file and share it with the other machines and see if this one works.

However, from what I recall from looking up into libs in each machine, they have different lib naming in each system which is due to OS, nvidia-driver, and other relevant libs that were installed either by using a different gcc or other components.

It is possible that there is a generic `nvconfig` file that could work with the majority of configurations, but I think it is a good idea to add some warning in the docs when using `--nv` to state something like this:

The use of `--nv` might cause an unexpected behavior due to opening the gate to other libs to be part of the container run. Possible solutions to overcome this unexpected behavior are 1. Ensuring that the OS where the built machine matches with the machines that will run the container. 2. Updating `nvconfig` with proper information.

**Comment by DrDaveD** [comment]
Let's first see if it is possible.  I don't know what you mean by `nvconfig` unless it is a shorthand for `nvliblist.conf`.
