### ISSUE TITLE
 Incorrect error message and documentation when mounting paths from `/tmp`

### ISSUE THREAD

**Issue by charmoniumQ** [apptainer/apptainer#1097]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.1.5
```

### Expected behavior

```
$ # edit apptainer.conf with "mount tmp = yes"
$ grep 'mount temp' /path/to/etc/apptainer/apptainer.conf
mount temp = yes
$ mkdir /tmp/test
$ apptainer exec -B /tmp/test https://depot.galaxyproject.org/singularity/python:3.8.3 pwd
FATAL:    Error related to "mount tmp = yes".
```

Also the [documentation](https://apptainer.org/docs/user/latest/build_a_container.html#bind) should be revised, as binding to mount points which do not exist seems to work fine. Perhaps there are conditions under which it works and under which it doesn't. Those should be documented. 

### Actual behavior

```
$ apptainer exec -B /tmp/test https://depot.galaxyproject.org/singularity/python:3.8.3 pwd
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
WARNING: Skipping mount /home/azureuser/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.3.0/apptainer-1.1.5-tkaiqwrpiog2vzr5okpp77nqpvdtwmv6/var/apptainer/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
FATAL:   container creation failed: mount hook function failure: mount /tmp/test->/tmp/test error: while mounting /tmp/test: destination /tmp/test doesn't exist in container   
```

The error message seems says, "destination /tmp/test doesn't exist in container". This seems to reference a part of the [documentation](https://apptainer.org/docs/user/latest/build_a_container.html#bind) which says

> Beware that the mount points must exist in the built image

This line of documentation is not true, as the following will work:

```
$ sudo mkdir -p /a/b/c
$ sudo chown $USER:$GROUP /a/b/c                                                                                                                     
$ apptainer exec -B /a/b/c https://depot.galaxyproject.org/singularity/python:3.8.3 pwd
WARNING: Skipping mount /home/azureuser/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.3.0/singularityce-3.10.3-z5qu45ho72nvsy4rpcyd4eqrop35tnbe/var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
/
```

and the true solution to this error is to set `mount temp = no` in /path/to/etc/singularity/singularity.conf.

```
$ # edit apptainer.conf with "mount tmp = no"
$ grep 'mount temp' /path/to/etc/apptainer/apptainer.conf
mount temp = no
$ mkdir /tmp/test
$ apptainer exec -B /tmp/test https://depot.galaxyproject.org/singularity/python:3.8.3 pwd
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
/
```

Note that `/tmp` _does_ in fact exist in the container, so the message about the bind mount point not existing must be wrong.

While incorrect error messages may seem unimportant, they can cost days of user time. See [this](https://github.com/nf-core/eager/issues/894#issuecomment-1428611633).

Note that this bug also happens in SingularityCE ([bug rep](https://github.com/sylabs/singularity/issues/1331)).

### What OS/distro are you running

```sh
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer

Spack

**Comment by DrDaveD** [comment]
I'm sorry that nobody ever responded to this issue, I'm not sure how that happened.

SingularityCE now has a fix for this in sylabs/singularity#2213.  We should see if it is also applicable to Apptainer.

**Comment by DrDaveD** [comment]
The fix from SingularityCE is quite extensive so I changed the milestone to 1.3.0.

**Comment by cclerget** [comment]
@DrDaveD @charmoniumQ PR #1843 for 1.3.0
