### ISSUE TITLE
DefaultRemote: FATAL error - remote has no library client

### ISSUE THREAD

**Issue by nrcfieldsa** [apptainer/apptainer#1103]
### Version of Apptainer

```sh
$ apptainer --version
apptainer version 1.1.5
```

### Expected behavior

apptainer command should work with the default library and allow to pull images as documented.
Otherwise, perhaps there should be documentation in Quick Start showing users how to point to a default library.

```sh
$ apptainer pull library://lolcow
INFO:    Downloading library image
90.4MiB / 90.4MiB [==========================================================================================] 100 % 12.1 MiB/s 0s
```

### Actual behavior

apptainer recently changed to use the new DefaultRemote ```cloud.apptainer.org```. It seems for some reason this is causing issues when pulling containers in regular use cases that singularity documentation list. It's non-obvious how to proceed unless users/admin are experienced with different library's available for singularity.

```sh
$ singularity pull library://alpine:latest
FATAL:   Unable to get library client configuration: remote has no library client

$ singularity remote list
Cloud Services Endpoints
========================

NAME             URI                  ACTIVE  GLOBAL  EXCLUSIVE  INSECURE
DefaultRemote    cloud.apptainer.org  YES     YES     NO         NO

Keyservers
==========

URI                       GLOBAL  INSECURE  ORDER
https://keys.openpgp.org  YES     NO        1*

* Active cloud services keyserver
```

### Steps to reproduce this behavior

Start with a default install of apptainer 1.1.5 - the DefaultRemote should point to a new server instead of to previously configured cloud.sylabs.io.  This default should work OK, but does not for the user after upgrade to apptainer.  For certain HPC centers this is not working, due to lack of specifying an explicit library configuration post-install.

  - Possible workaround: https://docs.mpcdf.mpg.de/bnb/211.html#notes-on-the-sylabs-cloud-endpoint 

If there is a difference in how the remote is setup for cloud.apptainer.org, then perhaps the same steps should be made to work or documented in quick start guide - so that user examples work when demonstrated to clients.  The documentation is not necessarily clear on this requirement for a site-local library configuration, though it does mention this difference.  Further, there is no example able to be located in docs of how to make this the default site-wide following install.

- https://apptainer.org/docs/user/latest/endpoint.html#managing-remote-endpoints :

> A fresh installation of Apptainer is configured with the DefaultRemote, which does not support the Library API as it is only configured with a functioning key server, https://keys.openpgp.org. Users or administrators should configure one of the Library API implementations listed [here](https://singularityhub.github.io/library-api/#/?id=library-api) if they would like to use a Library API registry.

 - https://apptainer.org/docs/user/1.0/quick_start.html#downloading-images

(not mentioned)

#### Is it in the release notes / upgrade guide?

 - https://github.com/apptainer/apptainer/releases/tag/v1.1.5

> ...
> * Add more helpful error message when no library endpoint found.
> ...

Even with this error message explaining: remote has no library client:

Users might get the impression that apptainer library client is simply missing in the install or their version of apptainer (singularity) does not work.

With-out being too verbose, perhaps when there is no library configured, the error could be changed to reflect the fact the site admin / user needs to setup at least one remote library for ```library://``` to work, and to refer to the documentation for details.

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Apptainer

Apptainer was installed from source into /usr/local by local HPC team. There does not appear to be any OS package (deb/apt) for apptainer/singularity used on this cluster at this time.  (It is understood but not confirmed that the install of apptainer-1.1.5 is using the defaults.)

**Comment by nrcfieldsa** [comment]
One potential work-around where the global `etc/apptainer/remote.yaml` config file is not able to be update site-wide, is to have a user .profile check at login, such as the following:

```bash
    #
    ### Check that apptainer has a DefaultRemote library configured:
    #
    { test -x /usr/local/bin/apptainer && test -f ~/.apptainer/remote.yaml && grep -q SylabsCloud ~/.apptainer/remote.yaml; } 2>&- ||{ cp -p ~/.apptainer/remote.yaml{,.bak}; apptainer remote add --no-login SylabsCloud cloud.sylabs.io; apptainer remote use SylabsCloud; } 2>&-
```

**Comment by DrDaveD** [comment]
I think the main problem is that we missed catching all the places errors can happen when we tried to make the error message more helpful.  The 1.1.5 release note was regarding #966 and that added a message "see https://apptainer.org/docs/user/latest/endpoint.html#no-default-remote" in one place but not here.  If this error message included that would it have been sufficient for you to easily find out what needed to be done?

**Comment by nrcfieldsa** [comment]
> If this error message included that would it have been sufficient for you to easily find out what needed to be done?

Yes.  That documentation section is clear and lists the commands needed.
