### ISSUE TITLE
Error creating rocky based singularity image

### ISSUE THREAD

**Issue by imerelli** [apptainer/apptainer#1119]
Hi, I'm trying build a rocky based singularity image using a fresh installation of apptainer

singularity --version
apptainer version 1.1.5-2.el8

Here the .def file:

BootStrap: yum
OSVersion: 8
MirrorURL: http://dl.rockylinux.org/pub/rocky/%{OSVERSION}/BaseOS/x86_64/os/
Include: dnf

%post
    dnf -y install epel-release
    dnf config-manager --set-enabled powertools

Every time I get this error:

...
 Complete!
 \+ dnf config-manager --set-enabled powertools
 \+ /root
 /.post.script: line 39: /root: Is a directory
 FATAL:   While performing build: while running engine: exit status 126

Am I doing something wrong?

**Comment by imerelli** [comment]
P.s. I have the same error with centos8-stream

**Comment by DrDaveD** [comment]
I didn't get the same symptom as you, but when I tried it unprivileged with no /etc/sub[ug]id mapping set up on my rocky8 VM, my attempt died much earlier with
```
FATAL:   While performing build: conveyor failed to get: while copying pseudo devices: while creating /scratch/tmp/build-temp-2179211480/rootfs/dev/null: operation not permitted
```

Do you need to use the yum bootstrap method?  I don't know why but I have had a lot of trouble with the yum bootstrap method using fakeroot, in addition to it being terribly slow on my little rocky8 VM.  Can you replace the first 4 lines with
```
Bootstrap: docker
From: rockylinux:8
```

**Comment by panda1100** [comment]
How about this def file?

```
Bootstrap: yum
OSVersion: 8
MirrorURL: https://download.rockylinux.org/pub/rocky/%{OSVersion}/BaseOS/x86_64/os/
Include: dnf

%post
dnf -y install epel-release
dnf config-manager --set-enabled powertools
```

**Comment by imerelli** [comment]
Hi, using your .def file it works. Thanks

**Comment by imerelli** [comment]
Can you suggest me a MirrorURL also for almalinux? I'm trying both of them

**Comment by panda1100** [comment]
I have never tried before but this may works,, https://repo.almalinux.org/almalinux/8/BaseOS/x86_64/os/

**Comment by DrDaveD** [comment]
Great, thanks for that better MirrorURL, @panda1100
