### ISSUE TITLE
Still need `squashfuse` when specified `squashfuse_version`?

### ISSUE THREAD

**Issue by Yikun** [apptainer/apptainer#1133]
Just a question about apptainer.spec, If we specified the `squashfuse_version`:
https://github.com/apptainer/apptainer/blob/ec8a99bf6a29684840f921d5f5415c1f93352124/dist/rpm/apptainer.spec.in#L98

Do we still need add squashfuse as `Require`?https://github.com/apptainer/apptainer/blob/ec8a99bf6a29684840f921d5f5415c1f93352124/dist/rpm/apptainer.spec.in#L106

Especially, when distro provided `squashfuse` might be conflicted with apptainer provided squashfuse_ll.

**Comment by Yikun** [comment]
maybe cc @DrDaveD

**Comment by DrDaveD** [comment]
Thanks for asking.  It's there in order to get squashfuse's dependencies, not really squashfuse itself.  It does not conflict, because at run time apptainer puts /usr/libexec/apptainer/bin first in the PATH.  Does that make sense?

**Comment by Yikun** [comment]
Thanks! Make sense!
