### ISSUE TITLE
fakeroot does not allow username instead of uid in /etc/subuid ?

### ISSUE THREAD

**Issue by dirkpetersen** [apptainer/apptainer#1148]
### Version of Apptainer

```
apptainer --version
apptainer version 1.1.3-1
```

### Expected behavior

```
80025037@red1 ~]$ apptainer shell --fakeroot ubuntu_22.04.sif
Apptainer> whoami
root
```

### Actual behavior
```
80025037@red1 ~]$ apptainer shell --fakeroot ubuntu_22.04.sif
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    Using fakeroot command combined with root-mapped namespace
Apptainer> whoami
```

What actually happened? Why was it incorrect?

username spaces can function either with username or uid as the first entry (the one to be mapped), however apptainer only seems to support uid and not username. Podman had a bug in an earlier version and only supported username but not uid as a result so we switched to username. Is Apptainer planning to support both ? 

```
80025037@red1 ~]$ id -u
87117

80025037@red1 ~]$ whoami
80025037

80025037@red1 ~]$ grep 80025037 /etc/subuid
80025037:871170000:65536

80025037@red1 ~]$ grep 87117 /etc/subuid
80025037:871170000:65536
```

### What OS/distro are you running

```sh
80025037@red1 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
```

**Comment by GodloveD** [comment]
Sorry for the delay.  What does `/etc/passwd` look like in the container?  I would imagine that is where the username is set.  Is there an entry for root?

**Comment by GodloveD** [comment]
Actually looks like I can exactly reproduce the behavior you are seeing like so:
```
$ cat no-root.def 
Bootstrap: docker
From: ubuntu:22.04

%post
    sed -i 's/root/ /g' /etc/passwd

$ apptainer build no-root.sif no-root.def
[...snip]

$ apptainer shell --fakeroot no-root.sif 
Apptainer> whoami
```
And this also works.
```
$ cat root-is-Dave.def 
Bootstrap: docker
From: ubuntu:22.04

%post
    sed -i 's/root/Dave/g' /etc/passwd

$ apptainer build root-is-Dave.sif root-is-Dave.def
[...snip]

$ apptainer shell --fakeroot root-is-Dave.sif 
Apptainer> whoami
Dave

Apptainer> id
uid=0(Dave) gid=0(root) groups=0(root),65534(nogroup)
```

**Comment by dirkpetersen** [comment]
My understanding of user name-spaces is that it is independent of any config inside the container and just depends on the host config, see 

https://man7.org/linux/man-pages/man5/subuid.5.html

It says `login name or UID` and login name does not seem to be working 

```
       Each line in /etc/subuid contains a user name and a range of
       subordinate user ids that user is allowed to use. This is
       specified with three fields delimited by colons (“:”). These
       fields are:

       •   login name or UID

       •   numerical subordinate user ID

       •   numerical subordinate user ID count

```

**Comment by GodloveD** [comment]
```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
```
I wonder if that is because your username on the host is completely numeric.  Maybe Apptainer interprets numeric data as a UID in this context.  

Can you please share your `/etc/passwd` from your Ubuntu container?  Or at least the line with UID 0?  Thanks.

**Comment by dirkpetersen** [comment]
You are right, in a brand new ubuntu image I created two users 80025037 and u80025037 and the error message only showed up with 80025037. 

Unfortunately per organizational policy, user names need to be numeric in this case. Other than debating the wisdom of this policy, is there a workaround?  I think there may be more environments out there with such a policy. 



The content of /etc/passwd is just the one from the latest ubuntu docker container :

```
Apptainer> cat /etc/passwd
root:x:0:0:root:/root:/bin/bash
daemon:x:1:1:daemon:/usr/sbin:/usr/sbin/nologin
bin:x:2:2:bin:/bin:/usr/sbin/nologin
sys:x:3:3:sys:/dev:/usr/sbin/nologin
sync:x:4:65534:sync:/bin:/bin/sync
games:x:5:60:games:/usr/games:/usr/sbin/nologin
man:x:6:12:man:/var/cache/man:/usr/sbin/nologin
lp:x:7:7:lp:/var/spool/lpd:/usr/sbin/nologin
mail:x:8:8:mail:/var/mail:/usr/sbin/nologin
news:x:9:9:news:/var/spool/news:/usr/sbin/nologin
uucp:x:10:10:uucp:/var/spool/uucp:/usr/sbin/nologin
proxy:x:13:13:proxy:/bin:/usr/sbin/nologin
www-data:x:33:33:www-data:/var/www:/usr/sbin/nologin
backup:x:34:34:backup:/var/backups:/usr/sbin/nologin
list:x:38:38:Mailing List Manager:/var/list:/usr/sbin/nologin
irc:x:39:39:ircd:/run/ircd:/usr/sbin/nologin
gnats:x:41:41:Gnats Bug-Reporting System (admin):/var/lib/gnats:/usr/sbin/nologin
nobody:x:65534:65534:nobody:/nonexistent:/usr/sbin/nologin
_apt:x:100:65534::/nonexistent:/usr/sbin/nologin
```

**Comment by DrDaveD** [comment]
Yes I think it's probably correct that apptainer interprets a numeric value in the first column of /etc/subuid as a user id instead of a name.

I believe the workaround would be for your /etc/subuid entry to start with the uid, 87117.

**Comment by dirkpetersen** [comment]
OK
