### ISSUE TITLE
Apparent permissions error when loading SIF file in server

### ISSUE THREAD

**Issue by nabw** [apptainer/apptainer#1171]
Hi everyone, I tried to squeeze as much info as possible in your template. If you need more, let me know, and thanks in advance. 

### Version of Apptainer

apptainer version 1.0.3+380-gea49318, installed on an HPC server, accessed with 'module load apptainer'. 

### Expected behavior

I want to pull a docker image, create s SIF file and use it to run my scripts. Pull works fine:

```
apptainer pull fd-test.sif docker://firedrakeproject/firedrake
```
Then, running a simple test script I have, I expect no output:
```
apptainer run --bind $PWD:/home/firedrake/work --home $PWD fd-test.sif /home/firedrake/firedrake/bin/python /home/firedrake/work/test.py
```

### Actual behavior

Instead, I get the following error:
```
ERROR  : Failed to retrieve root group information: Success
```

### What OS/distro are you running

```sh
CentOS 7 (Core)

```

### How did you install Apptainer

Preinstalled on system, loaded with modules interfaces.

**Comment by DrDaveD** [comment]
Those instructions do not help me reproduce the issue, however I can reproduce it by commenting out the `root` line in `/etc/group` on the host operating system.  The `getgrgid()` system call in [starter.c](https://github.com/apptainer/apptainer/blob/main/cmd/starter/c/starter.c#L1403) is documented in the man page to return NULL without an errno when a group is not found.  So the error message should be improved to not print "Success" in this case.

**Comment by nabw** [comment]
I'm sorry, but I don't have access to `/etc/group`, so I can't verify if the group exists. 

Is there a way to avoid this if apptainer is already installed in the system? If not, I will have to do a local installation. Thanks!

**Comment by DrDaveD** [comment]
I don't think it makes any difference how apptainer is installed; I think it can only happen by a system configuration issue.  If you don't have read access to /etc/group, that may be the whole problem.  Yes if I change the mode of /etc/group to 600 I get the same message.  Report the problem to your system administrator.

**Comment by nabw** [comment]
I think this is not going to change, and in the end I am helping the sysadmin compile the library by hand... which really defeats the purpose of containerization. Preaching to the choir here I guess. 

In any case, closing the issue. Thanks for looking into it.

**Comment by DrDaveD** [comment]
I am reopening this so we at least will fix the misleading "Success" message in release 1.2.0.

We could at the same time also channge apptainer to ignore the error reading `/etc/group` and just assume the group name in this case is `root`.  However, that might reveal a later error when trying to read the user's group id and possibly others, I'm not sure.

**Comment by DrDaveD** [comment]
This similar-looking "Success" error has also been reported:
```
ERROR  : 'newgidmap' execution failed. Check that 'newgidmap' is setuid root or has setcap cap_setgid+eip.
ERROR  : Error while waiting event for user namespace mappings: Success
```

**Comment by DrDaveD** [comment]
@JasonYangShadow if you can get to this sooner than I can that would be good.
