### ISSUE TITLE
`--no-mount bind-paths` raises warning message Ignoring unknown mount type 'bind-paths'

### ISSUE THREAD

**Issue by panda1100** [apptainer/apptainer#1173]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

1.1.6-1.el8

### Expected behavior

Disabled all bind path entries set in apptainer.conf
https://apptainer.org/docs/user/main/bind_paths_and_mounts.html#disabling-system-binds

### Actual behavior

```
$ apptainer exec --no-home --no-mount bind-paths  alpine.sif /bin/sh
WARNING: Ignoring unknown mount type 'bind-paths'
Apptainer> 
```

### Steps to reproduce this behavior

+ Install apptainer non-suid v1.1.6 from EPEL on Rocky Linux 8.7
+ `apptainer build alpine.sif docker://alpine`
+ `apptainer exec --no-home --no-mount bind-paths  alpine.sif /bin/sh`

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.7 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.7"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.7 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.7"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.7"
```

### How did you install Apptainer

from EPEL

**Comment by DrDaveD** [comment]
That is only implemented in the main branch, not on release-1.1.  See "latest" instead of "main" docs.
