### ISSUE TITLE
cp -a on file with ACLs fail with "Invalid argument" when running non-suid apptainer

### ISSUE THREAD

**Issue by akesandgren** [apptainer/apptainer#1239]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

```
apptainer --version
apptainer version 1.1.6
```

### Expected behavior

What did you expect to see when you do...?

User Id on both cases is "easybuild"
```
$ getfacl w
# file: w
# owner: easybuild
# group: easybuild
user::rw-
group::r-x                      #effective:r--
group:sysop:rwx                 #effective:rw-
group:easybuild:rwx             #effective:rw-
mask::rw-
other::r--

$ cp -a w t
```

### Actual behavior

What actually happened? Why was it incorrect?
```
Apptainer> getfacl w
# file: w
# owner: easybuild
# group: easybuild
user::rw-
group::r-x                      #effective:r--
group:easybuild:rwx             #effective:rw-
group:4294967295:rwx            #effective:rw-
mask::rw-
other::r--

Apptainer> cp -a w t
cp: preserving permissions for ‘t’: Invalid argument
```
This works with singularity in suid mode.

Removing the extra group from the acl eliminates the problem
```
$ setfacl -x group:sysop w
# starting apptainer
Apptainer> getfacl w
# file: w
# owner: easybuild
# group: easybuild
user::rw-
group::r-x
group:easybuild:rwx
mask::rwx
other::r--

Apptainer> cp -a w t
```

### Steps to reproduce this behavior

Should be reproducable with any ACL enabled file and non-suid apptainer

### What OS/distro are you running

```sh
On host:
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

In container:
Apptainer> cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


```

### How did you install Apptainer

From source making .deb as per instructions.

**Comment by DrDaveD** [comment]
Oh I see you do have an example command to setfacl, but how are you starting apptainer and what is the filesystem type.

**Comment by DrDaveD** [comment]
I'm guessing the problem has to do with the fact that unprivileged user namespaces have only one group available, and that there's nothing we can do about it.  Try using the "id" command both outside and inside the container to see what I mean.

**Comment by DrDaveD** [comment]
What groups do you see outside and inside of the container?  My guess is that inside the container you can't see all the groups and that's why cp complains.

**Comment by DrDaveD** [comment]
No it's not.  The only groups inside an unprivileged user namespace are the user's id (unless using `--fakeroot`, then it is 0) and the `nobody` group id 65534.

**Comment by akesandgren** [comment]
Some more data on this:
```
# Outside container
$ getfacl w
# file: w
# owner: easybuild
# group: easybuild
user::rw-
group::r-x                      #effective:r--
group:sysop:rwx                 #effective:rw-
group:easybuild:rwx             #effective:rw-
mask::rw-
other::r--
$ getent group easybuild | cut -d: -f1-3
easybuild:*:2069
$ getent group sysop | cut -d: -f1-3
sysop:*:2010

# Inside container:
Apptainer> getent group easybuild | cut -d: -f1-3
easybuild:x:2069
Apptainer> getent group sysop | cut -d: -f1-3
sysop:*:2010
Apptainer> getfacl w
# file: w
# owner: easybuild
# group: easybuild
user::rw-
group::r-x                      #effective:r--
group:easybuild:rwx             #effective:rw-
group:4294967295:rwx            #effective:rw-
mask::rw-
other::r--

Apptainer> cp -a w q
cp: preserving permissions for ‘q’: Invalid argument
```

So despite the group actually being in the containers /etc/group this fails.

**Comment by GodloveD** [comment]
I've found pretty much the same by using the `nobody` group.  Which should exist on the host and in the container. 
```
$ touch w

$ setfacl -m g:nobody:r w

$ apptainer shell --bind $PWD acl.sif 

Apptainer> cp -a w t
cp: preserving permissions for 't': Invalid argument
```

**Comment by DrDaveD** [comment]
Is the nobody group gid 65534?  On el7 at least that is called nfsnobody.

**Comment by GodloveD** [comment]
On my system `nobody` is gid 65534 on both the host and in the container.

**Comment by akesandgren** [comment]
Ah, I forgot to add that:
```
$ grep ACL_UNDEFINED_ID include/acl.h
#define ACL_UNDEFINED_ID	((id_t)-1)
```
and id_t is _u32

**Comment by DrDaveD** [comment]
Ok, so since I think it's clear that there's nothing that Apptainer can do about this, I am closing this ticket.
