### ISSUE TITLE
FATAL: container creation failed: mount ERROR: while mounting image: no loop devices available 

### ISSUE THREAD

**Issue by nevesLiliane** [apptainer/apptainer#1258]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`singularity version 3.7.3` (or `singularity --version`).

### Expected behavior

```
$ singularity run shub://GodloveD/lolcow
INFO:    Use cached image
 _________________________________________
/ A gift of a flower will soon be made to \
\ you.                                    /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

```

### Actual behavior

What actually happened? Why was it incorrect?
```
singularity run shub://GodloveD/lolcow
INFO:    Use cached image
FATAL:   container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: no loop devices available
```

I'm running multiple images, the first image is a RDBMS, if I run it I cannot execute other containers, it gives the error above, for any other image I try to execute after executing the RDBMS. 

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

I don't know, I have been using singularity for more than 2 years and this is the first time it happens, using this same RDBMS, I haven't changed anything recently, this worked yesterday, and still works on other machines. 
I have tested and found out that I can execute every image I have, but if I execute the RDBMS, the "no loop devices" message comes to the containers that I try to execute next. I have no idea how to solve that. Please help

### What OS/distro are you running

```sh
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.
I used apt-get to install singularity

**Comment by GodloveD** [comment]
This error message has come up a few times in the past and there are [several issues associated with it](https://github.com/apptainer/singularity/issues?q=is%3Aissue+%22no+loop+devices+available%22+).  But I don't see a consistent fix.  As a first step I would recommend updating to the latest version of Apptainer and maybe just rebooting the node you are running on (if that is possible).

**Comment by nevesLiliane** [comment]
Ok, thanks!

**Comment by nevesLiliane** [comment]
Ok thanks!

**Comment by nevesLiliane** [comment]
Hi, I'm quite sure that it has something to do with singularity not freeing up the loop device it is using. I'm using an RDBMS and distinctively from other applications, it executes while I do not stop it. All my other containers execute a task and exit when the task is done. Looking at my loop devices the one with the RDBMS keeps being assigned to the RDBMS even after I stop the container, just like [this](https://stackoverflow.com/questions/67385727/singularity-how-to-free-loop-devices). 
I will update singularity soon as suggested, but to "solve" it now I just edited singularity.conf and allowed the sharing of loop devices.

I'm sharing this in hope it helps someone

**Comment by nevesLiliane** [comment]
Hi again, my workaround just worked for a few days, apparently, it has something to do with my kernel version
In [apptainer/apptainer#1499](https://github.com/apptainer/apptainer/issues/1499) there is a better solution in the comment of [dtrudg](https://github.com/sylabs/singularity/issues/1499#issuecomment-1493908443):

> 
> **Solution**
> 
> On this kernel, you will need to configure `max_loop` for the `loop` driver to a higher value. Suggest setting it to the same as `max loop devices` in `singularity.conf`, which is 256 by default.
> 
> You must do this with a kernel CMDLINE entry, because `loop` is compiled into the kernel on Ubuntu. It is not a module.
> 
>     1. Add `max_loop=256` to the `GRUB_CMDLINE_LINUX` value in `/etc/default/grub`
> 
>     2. Run `update-grub2` as root.
> 
>     3. Reboot the system.
> 
>     4. `cat /proc/cmdline` and verify `max_loop=256` is present.
> 
> 
> After this, Singularity should work as normal.
