### ISSUE TITLE
Unwanted colors to STDERR

### ISSUE THREAD

**Issue by rhattersley** [apptainer/apptainer#1259]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.1.5
```

### Expected behavior

Using the `--nocolor` option would disable all use of color in output to STDERR as well as STDOUT.
Redirecting STDERR to a file would disable all use of color in output.

### Actual behavior

The message following message appears with the `INFO` prefix shown in blue even when `--nocolor` is included and/or STDERR is redirected to a file.
```
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
```

### Steps to reproduce this behavior

For both of these examples, the `INFO` label will be shown in blue, but the `FATAL` label is correctly using the default color instead of red.

```sh
$ SINGULARITY_TMPDIR=foo apptainer --nocolor build foo bar
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
FATAL:   Unable to build from bar: unable to open file bar: open bar: no such file or directory
```

```sh
$ SINGULARITY_TMPDIR=foo apptainer build foo bar 2> /tmp/errors
$ cat /tmp/errors
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
FATAL:   Unable to build from bar: unable to open file bar: open bar: no such file or directory
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer

```sh
$ wget https://github.com/apptainer/apptainer/releases/download/v1.1.5/apptainer_1.1.5_amd64.deb
$ sudo apt-get install -y ./apptainer_1.1.5_amd64.deb
```

**Comment by GodloveD** [comment]
I wonder if this is related to #982? <-- @JasonYangShadow

**Comment by JasonYangShadow** [comment]
@GodloveD It's unrelated with issue #982. But caused by that the log is printed too early before the color configuration is set. so `--nocolor` does not have any effect. I've created a PR for this
https://github.com/apptainer/apptainer/pull/1268

**Comment by rhattersley** [comment]
Thanks for the quick turnaround! 👏
