### ISSUE TITLE
`tar` breaks in overlay when used in memory-constrained environment

### ISSUE THREAD

**Issue by GPlaczek** [apptainer/apptainer#1267]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.1.7
```

### Expected behavior

Directory inode numbers should remain constant in apptainer overlays after dropping virtual memory cache.

### Actual behavior

Directory inodes change after dropping virtual memory cache. This leads to such errors when extracting tar archives in apptainer overlay when relatively low ammount of memory is available in the environment:
```
tar: ./deps/0/bin: Directory renamed before its status could be extracted
```
I think that this exact error was already reported (and pretty well described) in ubuntu [here](https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1728489). However, the fix that keeps the inode numbers constant mentioned there only applies when `lowerdir`, `upperdir` and `workdir` are all on the same mount point (as hinted [here](https://lwn.net/Articles/720794/)). I suspect that the problem is caused by this as running apptainer with `-d` flag indicates that `lowerdir` is on a different mount point than `workdir` and `upperdir`.

```
DEBUG   [U=0,P=2642035]    mountImage()                  Mounting loop device /dev/loop0 to /usr/local/var/apptainer/mnt/session/rootfs of type squashfs
DEBUG   [U=0,P=2642035]    mountGeneric()                Mounting /home/gplaczek/git/apptainer/sin to /usr/local/var/apptainer/mnt/session/overlay-images/0
```

The overlay is mounted like this:
```
$ mount | grep overlay
overlay on / type overlay (rw,nodev,relatime,lowerdir=/usr/local/var/apptainer/mnt/session/overlay-lowerdir:/usr/local/var/apptainer/mnt/session/rootfs,upperdir=/usr/local/var/apptainer/mnt/session/overlay-images/0/upper,workdir=/usr/local/var/apptainer/mnt/session/overlay-images/0/work)
```

### Steps to reproduce this behavior

If the output from both `stat` commands below is different, the issue was properly reproduced

```
$ mkdir overlay
$ sudo apptainer shell --overlay overlay docker://debian:bullseye
Apptainer> cd /
Apptainer> mkdir dir
Apptainer> stat -c%i dir
Apptainer> echo 2 > /proc/sys/vm/drop_caches
Apptainer> stat -c%i dir
```

To reproduce the issue with `tar` command:

```
$ mkdir overlay
$ sudo apptainer shell --overlay overlay docker://debian:bullseye
Apptainer> cd /
Apptainer> apt update && apt install wget
Apptainer> wget https://github.com/torvalds/linux/archive/refs/tags/v6.3-rc5.tar.gz # this or any relatively big tar
Apptainer> tar -xf v6.3-rc5.tar.gz & for i in {0..5}; do echo 2 > /proc/sys/vm/drop_caches; sleep 1; done
```

Running the commands above is expected to produce errors similar to these:

```
tar: linux-6.3-rc5/scripts/dtc/include-prefixes: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/scripts/dtc: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/scripts: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/include/dt-bindings/input: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/include/dt-bindings: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/include: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/arch/arm64/boot/dts/arm: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/arch/arm64/boot/dts: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/arch/arm64/boot: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/arch/arm64: Directory renamed before its status could be extracted
tar: linux-6.3-rc5/arch: Directory renamed before its status could be extracted
tar: linux-6.3-rc5: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
```

These errors will occasionally happen when user has relarively low ammount of available memory and cache drops will happen naturally.

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### How did you install Apptainer

I compiled and installed Apptainer manually following instructions from [INSTALL.md](https://github.com/apptainer/apptainer/blob/main/INSTALL.md)

If you're interested in fixing this issue, I would be eager to contribute and implement it myself if you provide me with some hints on how to approach the problem of keeping all overlays on the same mount point in your app.

**Comment by GodloveD** [comment]
@cclerget are you able to provide some advice on how to properly implement a fix here?

**Comment by DrDaveD** [comment]
What kind of filesystem is the "overlay" sandbox directory in?  Does it happen in any type of filesystem?  Overlayfs (and to a lesser extent fuse-overlayfs) don't fully support many networked filesystems, for example [lustre and gpfs](https://apptainer.org/docs/admin/latest/installation.html#lustre-gpfs).

Did you do a default installation, so it is not suid?  If so, then running with sudo could behave quite differently than running non-sudo, because with sudo it uses overlayfs from the kernel and without sudo it uses fuse-overlayfs.

**Comment by GPlaczek** [comment]
For what I have tested, it happens on tmpfs and ext4 so these are definitely not some exotic and rare ones.

I did the default installation, the problem only occurs on kernel overlayfs (after running with sudo), fuse-overlayfs works fine (after running without sudo).

**Comment by cclerget** [comment]
Hey @GPlaczek @GodloveD , having lower layers and upper layers on the same filesystem isn't going to be possible, we have usually three layers when using `--overlay` or `--writable-tmpfs`:

- First readonly layer is the container image (squashfs)
- Second readonly layer is a temporary layer to add container mount points required (tmpfs)
- Third writable layer is either directory (or a ext3 filesystem) specified by overlay or a tmpfs

So we always have potentially three (or two in best cases) different filesystems.

Actually the best option here seems to force `xino=on` in overlay mount option, some distro have `xino=auto` by default, but when apptainer is  using a squashfs filesystem for container image, the kernel overlay code disable `xino` as squashfs filesystems don't have a filesystem UUID, shown in `dmesg` output:
```
overlayfs: null uuid detected in lower fs '/', falling back to xino=off,index=off,nfs_export=off
```

If you run the command above on a ext3 image or a sandbox directory as container image on distro with `xino_auto` enabled, there is no issue:

```
$ mkdir overlay
$ sudo apptainer build -s /tmp/debian docker://debian:bullseye
$ sudo apptainer shell --overlay overlay /tmp/debian
Apptainer> cd /
Apptainer> mkdir dir
Apptainer> stat -c%i dir
7995517
Apptainer> echo 2 > /proc/sys/vm/drop_caches
Apptainer> stat -c%i dir
7995517
```

**Comment by GPlaczek** [comment]
Thanks for your help, I managed to get this to work by forcing `xino=on` in apptainer like that: https://github.com/GPlaczek/apptainer/commit/f1f7d5d685b315d1a228370453a8dca07aee59ae and it actually fixed my problem. The `dmesg` doesn't show anything that would hint that something is wrong:
```
overlayfs: "xino" feature enabled using 3 upper inode bits.
```
I'm not sure if this is safe to include by default. If you are interested in including something like that in your repository either by default or as an option, I can refactor it and submit a PR for you

**Comment by cclerget** [comment]
@GPlaczek Thanks for your proposal, I submitted a PR https://github.com/apptainer/apptainer/pull/1278 and added fallback in case `xino` is not supported (I expect it to be rare)

**Comment by GPlaczek** [comment]
That's great, thank you!
