### ISSUE TITLE
Allow both APPTAINER and SINGULARITY env variables to be set without warning

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#128]
On the current main branch, after #108, a warning is printed whenever a SINGULARITY prefix variable is set, even if the corresponding APPTAINER prefix variable is also set to the same value.  This behavior would prohibit people from writing scripts that work with both apptainer and singularity without having to ignore or suppress warnings.  Change the behavior to only print a warning if the value of the two variables are different, and to print only a debug message if they are the same.

**Comment by gmkurtzer** [comment]
Very elegant solution, ya got my vote!
