### ISSUE TITLE
[Feature request] Top-level directory independent image building and running

### ISSUE THREAD

**Issue by ShamrockLee** [apptainer/apptainer#1283]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
apptainer version 1.1.7
```

### Expected behavior

Apptainer instances built without the SUID support, should allow users to build and run images without relying on the top-level directories.

This is the remaining step toward the fully-unprivileged image building and running workflow. The motivation is to allow users to build Apptainer image with unprivileged-by-default Package managers / Project managers such as Nix and Gentoo ebuild.

Initial discussion:
https://github.com/apptainer/apptainer/issues/215#issuecomment-1165304302

In Nixpkgs, we have `singularity-tools.buildImage` to build Apptainer image, but it currently spowns a QEMU VM just to build an image, which is a great regression. When this issue is resolved, singularity-tools can build images without VM.

### Actual behavior

1.  When building an image, Apptainer currently needs to access `/etc/resolv.conf` and `/etc/hosts` on the host system, even when networking is not needed.
2.  When running an image, Apptainer currently needs to access `<localstatedir>/apptainer/mnt/session`

### Steps to reproduce this behavior

The build-image part:
1.  Set up an environment without `/etc/resolv.conf` or `/etc/hosts`
2.  Build Apptainer with the `--without-suid` configure flag passed to `mconfig`.
3.  Build an image from a definition file with the `scratch` directive with no privileged commands involved.

The run-image part:
1.  Set up an enviornment without `<localstatedir>/apptainer/mnt/session`. The `<localstatedir>` here refers to the path specified by the `--localstatedir` configure flag to pass to `mconfig` when building Apptainer.
2.  Build Apptainer with the `--without-suid` configure flag passed to `mconfig`.
3.  Execute commands that doesn't require superuser privilege.

### What OS/distro are you running

```sh
$ cat /etc/os-release
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="22.11.20230318.08ef7dc"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 22.11 (Raccoon)"
SUPPORT_END="2023-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="22.11 (Raccoon)"
VERSION_CODENAME=raccoon
VERSION_ID="22.11"
```

### How did you install Apptainer

Build and install from [`Nixpkgs`](https://github.com/NixOS/nixpkgs), which essentially builds it from source. The above version mentioned is built from the PR https://github.com/NixOS/nixpkgs/pull/224683, but this issue is still  relevant to stable versions of Apptainer.

**Comment by DrDaveD** [comment]
@ShamrockLee regarding your second point, is there a problem with including /var/apptainer/mnt/session in the Nix package?  That should be allowed based on Linux filesystem layout standards.  Mounts require a mount point, and they're only used inside of a mount namespace.  It would not be easy to change that mountpoint.

**Comment by ShamrockLee** [comment]
I'll try to configure `localstatedir` to a path inside the package directory or something.

1.  Does it need to be writable?
2.  Why is it hard to be dynamically specify the directory at run time?

**Comment by DrDaveD** [comment]
It does not need to be writable, because when the mounts happen in a mount namespace the user is running as a fake root.

Most important is that the directory has to pre-exist.  It might not be that hard to make it relocatable, but the question then is where would you relocate it to.
