### ISSUE TITLE
When using persistent overlays, $HOME, /tmp, and /var/tmp still use tmpfs.

### ISSUE THREAD

**Issue by wutz** [apptainer/apptainer#1286]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
apptainer version 1.1.7-1.el7
```

### Expected behavior

When using persistent overlay, $HOME, /tmp and /var/tmp are also stored using persistent overlay.

### Actual behavior

What actually happened? Why was it incorrect?

* When using persistent overlays, $HOME, /tmp, and /var/tmp still use tmpfs.
* This can cause users to consume a large amount of memory.
* In addition, the next time the container is started with overlay , the data stored in $HOME, /tmp, and /var/tmp will be lost

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

```sh
$ apptainer overlay create --size 10240 --sparse  my_overlay.img
$ apptainer shell -C --fakeroot --overlay my_overlay.img docker://ubuntu:22.04
Apptainer> dd if=/dev/zero of=./test bs=1M count=50000
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.

Use curl to install on rootless.

**Comment by DrDaveD** [comment]
That's a feature that's part of the `-C` option.  Remove that option if you don't want that behavior.

**Comment by wutz** [comment]
If the -C option is not included, the container again uses storage on the host. I want $HOME, /tmp, and /var/tmp to use the storage provided by overlay

**Comment by DrDaveD** [comment]
The `--no-home` option should prevent mounting of /home from the host.  It's very unusual to require saving /tmp and /var/tmp, but they can probably be prevented with `--no-mount` options.

**Comment by wutz** [comment]
Thanks for your help and using these options to solve my problem.
