### ISSUE TITLE
ERROR  : Failed to create mount namespace: mount namespace requires privileges, check Apptainer installation

### ISSUE THREAD

**Issue by xdgene** [apptainer/apptainer#1294]
no root user，can use build ，but not exec/run/shell with ERROR  : Failed to create mount namespace: mount namespace requires privileges, check Apptainer installation

### Version of Apptainer

What version of Apptainer (or Singularity) are you using?

**apptainer version 1.1.7**

### Actual behavior

**apptainer   run   lolcow_latest.sif
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
ERROR  : Failed to create mount namespace: mount namespace requires privileges, check Apptainer installation**

### What OS/distro are you running

**uname -sr
Linux 3.10.0-693.5.2.el7.x86_64**

**cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"**

### How did you install Apptainer

**conda create -n apptainer  -c conda-forge apptainer**

**Comment by DrDaveD** [comment]
This appears to be a problem with the conda distribution, and I don't know who does that.  Is there a way for you to contact the conda owner of apptainer?

**Comment by xdgene** [comment]
> 

I think its not the problem of conda  distribution，conda  distribution works well for Linux kernel 4.10.0，and i also install with compile way in Linux kernel 3.10.0：
`tar -zxvf singularity-3.8.7.tar.gz && cd singularity-3.8.7
./mconfig --without-suid --prefix=$HOME/singularity && \
    make -C ./builddir && \
    make -C ./builddir install`
But also the same error：
`ERROR : Failed to create mount namespace: mount namespace requires privileges, check Apptainer installation`

**Comment by xdgene** [comment]
> This appears to be a problem with the conda distribution, and I don't know who does that. Is there a way for you to contact the conda owner of apptainer?

I think its not the problem of conda distribution，conda distribution works well for Linux kernel 4.10.0，and i also install with compile way in Linux kernel 3.10.0：
`tar-zxvf singularity-3.8.7.tar.gz && cd singularity-3.8.7 ./mconfig --without-suid --prefix=$HOME/singularity && \ make -C ./builddir && \ make -C ./builddir install` 
But also the same error：
` ERROR : Failed to create mount namespace: mount namespace requires privileges, check Apptainer installation`

**Comment by DrDaveD** [comment]
I don't think I have seen this before, although googling for it found one other issue apptainer/singularity#5873.  There was no resolution to that, just a suspicion that it had something to do with an old kernel.   I though RHEL7.7 was new enough, but the [apptainer documentation](https://apptainer.org/docs/admin/latest/installation.html#system-requirements) recommends kernel 3.10.0-1127 or later.  

It looks like this is also subject to a sysctl setting.  What do you see with `sysctl user.max_mnt_namespaces`?

**Comment by xdgene** [comment]
> I don't think I have seen this before, although googling for it found one other issue [apptainer/singularity#5873](https://github.com/apptainer/singularity/issues/5873). There was no resolution to that, just a suspicion that it had something to do with an old kernel. I though RHEL7.7 was new enough, but the [apptainer documentation](https://apptainer.org/docs/admin/latest/installation.html#system-requirements) recommends kernel 3.10.0-1127 or later.
> 
> It looks like this is also subject to a sysctl setting. What do you see with `sysctl user.max_mnt_namespaces`?

sysctl user.max_mnt_namespaces
**user.max_mnt_namespaces = 124916**

**Comment by DrDaveD** [comment]
That looks OK.  So the only thing I can guess is that the kernel is too old.

**Comment by xdgene** [comment]
> That looks OK. So the only thing I can guess is that the kernel is too old.

maybe，thank you ！

**Comment by yannbouteiller** [comment]
I get the same issue when trying to build without sudo on Ubuntu 24:

```terminal
./bin/apptainer build lolcow.sif lolcow.def
ERROR  : Failed to create mount namespace: mount namespace requires privileges, check Apptainer installation
```

**Comment by DrDaveD** [comment]
I think that's a different issue with the same symptom, please create a new issue

**Comment by lumaqnhkaim** [comment]
Did you check the `/proc/sys/kernel/apparmor_restrict_unprivileged_userns` ?

**Comment by mppf** [comment]
A breadcrumb for anyone else finding this issue: as the previous comment suggests, apparmor can interfere with apptainer. I found this command to resolve the problem for me (temporarily, until reboot)

```
sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
```

**Comment by DrDaveD** [comment]
That apparmor requirement at this point is only in Ubuntu 23.10 and newer, and if you install an apptainer-1.3.4 or newer .deb package it should be set to unrestricted for apptainer.

**Comment by BenDo85** [comment]
For those on recent ubuntu, this might be of help : https://github.com/apptainer/apptainer/blob/main/INSTALL.md#apparmor-profile-ubuntu-2310
