### ISSUE TITLE
Add unit tests to fully test precedence of environment variables 

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#132]
...

4. There should probably be some automated tests added for this functionality.

_Originally posted by @DrDaveD in https://github.com/apptainer/apptainer/pull/131#pullrequestreview-850846612_

**Comment by PaulCharlton** [comment]
test:
APPTAINERENV_  => SINGULARITYENV_ => command line options, env file options =>  "clean env flag" => host env var

APPTAINER_  => SINGULARITY_ => host env var

test that output messages are correct debug level (warn, verbose, fatal, etc)
test overrides with different and identical values (output should be different)

**Comment by DrDaveD** [comment]
I marked this as 1.0.0 but it doesn't need to be in RC1

**Comment by PaulCharlton** [comment]
WIP
