### ISSUE TITLE
Error during the installation on raspberry pi 4 and 2.

### ISSUE THREAD

**Issue by FilGor** [apptainer/apptainer#1324]
### Version of Apptainer

from the main branch.
tried with the following go versions:
go1.20.4 linux/arm
 go1.19.5 linux/arm
### Expected behavior

Install apptainer on raspberry pi

### Actual behavior

Following error during the installation:
<img width="983" alt="image" src="https://user-images.githubusercontent.com/80070678/236762278-87568f63-fd87-49f0-aeed-c19a5f85cdc2.png">

### Steps to reproduce this behavior

apt-get update

apt-get install -y \
    build-essential \
    git \
    libseccomp-dev \
    pkg-config \
    uidmap \
    squashfs-tools \
    squashfuse \
    fuse2fs \
    fuse-overlayfs \
    fakeroot \
    cryptsetup \
    curl wget git \
    gocryptfs

 git clone https://github.com/apptainer/apptainer.git  && \
cd apptainer && \
./mconfig --without-suid && \
cd ./builddir && \
make && \
make install

error occurs during the ' make ' command
### What OS/distro are you running

"Raspbian GNU/Linux 10 (buster)"

### How did you install Apptainer
have written in 'Steps to reproduce this behavior' section.

**Comment by FilGor** [comment]
here is how to I fixed this error:
![image](https://github.com/apptainer/apptainer/assets/80070678/20711e06-b7c3-47a2-a064-fa0e6a34b237)

**Comment by DrDaveD** [comment]
That looks safe enough.  How about submitting it as a pull request?

**Comment by FilGor** [comment]
I think i am unable to do that
<img width="336" alt="image" src="https://github.com/apptainer/apptainer/assets/80070678/0851323d-4186-4d98-92e2-13a36dadd28c">

**Comment by DrDaveD** [comment]
Pull requests are made by making a branch in your own fork of the repository.  For example follow [this procedure](https://opensource.com/article/19/7/create-pull-request-github).  As an optimization I would clone from the "SSH" link instead of "HTTPS", although that requires having registered your ssh public key with github and for best convenience it requires using ssh-agent.

**Comment by DrDaveD** [comment]
Fixed by #1347
