### ISSUE TITLE
fakeroot fails with glibc error on minimal EL9 with no subuid entry

### ISSUE THREAD

**Issue by GodloveD** [apptainer/apptainer#1338]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.1.8-1.el9
```

### Expected behavior

I expect to be able to build a container from a base with an older glibc using fakeroot implicitly without error.  

### Actual behavior

I and others have observed this behavior in a few different environments now.   The basic symptom is this:

```
$ cat suse.def 
Bootstrap: docker
From: registry.suse.com/bci/bci-base:latest

%post
    ls -lh /.singularity.d/libs
    zypper install -y which hostname

$ apptainer build --force suse.sif suse.def 
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Starting build...
Getting image source signatures
Copying blob a044828fb7b8 skipped: already exists  
Copying config 446545e9f8 done  
Writing manifest to image destination
Storing signatures
2023/05/12 10:14:36  info unpack layer: sha256:a044828fb7b83c49cc759dbfac3542c94fc2c2a65ca8b222bb8d0bb8a9f2ce63
INFO:    Running post scriptlet
/.singularity.d/libs/faked: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /.singularity.d/libs/faked)
/.singularity.d/libs/faked: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/faked)
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
FATAL:   While performing build: while running engine: exit status 1
```

As near as I can figure, Apptainer is trying to bind mount `<base>/x86_64/utils/lib/libfakeroot` into the container at `/.singularity.d/libs` during the build, but the libraries don't work because the were compiled using a later version of glibc than the one that is available in the container.  

```
$ ldd --version
ldd (GNU libc) 2.34
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

$ apptainer shell docker://registry.suse.com/bci/bci-base:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob a044828fb7b8 skipped: already exists  
Copying config 446545e9f8 done  
Writing manifest to image destination
Storing signatures
2023/05/12 10:20:19  info unpack layer: sha256:a044828fb7b83c49cc759dbfac3542c94fc2c2a65ca8b222bb8d0bb8a9f2ce63
INFO:    Creating SIF file...
Apptainer> ldd --version
ldd (GNU libc) 2.31
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```

### Steps to reproduce this behavior

As I said, I and others have observed this behavior in a few different environments.  For various reasons I don't currently have access to these environments, so I can't say for certain if these are the same factors that have contributed to these errors in other cases.  But here is a method that triggers the error in my hands. 

1. First, install a _minimal_ version of EL9 like the one you can download [here](https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.1-x86_64-minimal.iso).  
2. Create an unprivileged user.
3. Install apptainer via the `install-unprivileged.sh` helper script in the unprivileged user's home directory. 
4. Remove the unprivileged user from the `/etc/subuid` file.
5. Try to build a container with an older base OS.  

### What OS/distro are you running

Note that this is the [_minimal_ version](https://download.rockylinux.org/pub/rocky/9/isos/x86_64/Rocky-9.1-x86_64-minimal.iso). 

```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.1 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.1"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.1 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.1"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.1"
```

### How did you install Apptainer

Via the [`install-unprivileged.sh`](https://github.com/apptainer/apptainer/blob/main/tools/install-unprivileged.sh) script.

**Comment by DrDaveD** [comment]
This is the "if the host libc library is of a very different vintage than the corresponding container the fakeroot command can fail" in fakeroot mode 3 in the [documentation](https://apptainer.org/docs/user/latest/fakeroot.html).  Apptainer has the same problem whenever binding in libraries from the host for example with the `--nv` option.  I haven't been able to think of a reasonable way to solve the problem automatically.  The easiest way is probably to first start a container of the OS vintage you want, do install-unprivileged.sh there, and then do your build.

**Comment by DrDaveD** [comment]
I probably ought to maintain container images in docker and/or ghcr with apptainer already installed on each major operating system type.  That would make it a lot easier for people to do this.

**Comment by DrDaveD** [comment]
@GodloveD Does this still happen for you with RockyLinux 9.2?  I just tried to reproduce it on an AlmaLinux 9.2 installation (admittedly not a minimal installation) and it does not fail for me.

**Comment by GodloveD** [comment]
I'm having a hard time trying to install with the convenience script.  
![image](https://github.com/apptainer/apptainer/assets/7672924/eaf75576-2e56-47a2-a452-0ac0f23659e0)

**Comment by DrDaveD** [comment]
The `-o` option is expected to only be used for suse-based distributions, so leave that out.  It does look like the script could be improved to have it at least not interfere with non-suse distributions.

**Comment by GodloveD** [comment]
Oh thanks.  That was a dumb mistake.  I got confused thinking that `-o` was the output directory for the build location. 

Looks like I'm still getting the error.  I think it has to be a minimal install though I don't know what it is that should be missing.  
```
09:06 AM
demouser@rocky9-minimal:~
$ apptainer --version
apptainer version 1.2.2-1.el9

09:06 AM
demouser@rocky9-minimal:~
$ cat containers/suse.def 
Bootstrap: docker
From: registry.suse.com/bci/bci-base:latest

%post
    cd /tmp
    wget https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh
    mkdir /tmp/apptainer/v1.1.8
    sh ./install-unprivileged.sh -v 1.1.8 /tmp/apptainer/v1.1.8


09:06 AM
demouser@rocky9-minimal:~
$ apptainer build --force containers/suse.sif containers/suse.def 
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Starting build...
Getting image source signatures
Copying blob ff71354b2d89 skipped: already exists  
Copying config e08891c355 done  
Writing manifest to image destination
Storing signatures
2023/09/18 09:07:06  info unpack layer: sha256:ff71354b2d890dbe98a63a7bfb498df56a8cdbadd1649bca29e732939aeba57e
INFO:    Running post scriptlet
/.singularity.d/libs/faked: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /.singularity.d/libs/faked)
/.singularity.d/libs/faked: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/faked)
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
FATAL:   While performing build: while running engine: exit status 1
```

**Comment by DrDaveD** [comment]
I installed a new VirtualBox image using the rockylinux9-minmal iso you linked.  It actually got stuck partway through installing python3, but I told it to do a hard reset and it booted up OK. I installed wget, created an unprivileged user for myself, switched to it, ran install-unprivileged.sh -v 1.2.2 there, then used that to build the .def file you gave (adding a `zypper install -y wget` before calling wget and a `-p` to the mkdir). It worked without error, so I had no luck reproducing the problem.

**Comment by GodloveD** [comment]
What does `cat /etc/subuid` turn up?  Did you remove all entries?  This error is triggered by the fallback method.

**Comment by DrDaveD** [comment]
Right, I thought I had mentioned that I had removed `/etc/subuid` but I see now I left that out of the description of the steps.

**Comment by DrDaveD** [comment]
I take it back!  I booted the system again and indeed that was the issue. I must have remembered a different attempt (right, it was when I ran rockylinux:9-mnimal under docker).  Now I really removed `/etc/subuid` and indeed did reproduce the issue.

**Comment by DrDaveD** [comment]
In fact, I can reproduce it on a non-minimal almalinux9 too.  The reason why I didn't reproduce it there before was that I had took a shortcut and ran apptainer from /cvmfs, but the installation there is done with the el7 distribution so it's not quite the same.  In fact a workaround for this issue is to add the `-d el7` option when you run install-unprivileged.sh because that installs fakeroot from el7 which has an older glibc.  It works fine on el9 as far as I've been able to tell.

Beyond that, however, I'm not sure there's much that can be done.  The `--fakeroot` documentation warns that a major mismatch between the glibc version on the host and the container doesn't work, and this is the type of symptom that shows up when that happens.  This does make me wonder, however, if the problem only happens when you try to run a container with an older glibc than the host and not newer.  If that's the case then maybe the install-unprivileged.sh script should just always install from the oldest supported operating system instead of trying to match the rpm packages to the host version.

**Comment by DrDaveD** [comment]
Yes, I found the same issue on ubuntu 22.04, and installing with `-d el7` fixes it there too, but only if fakeroot is not installed locally.  That's because although install-unprivileged.sh installs the binaries for all the helper commands (including fakeroot), it puts them after $PATH instead of before it.  So if I update install-unprivileged.sh to choose the oldest available destination, I should also change it to prefer the tools it downloads.
