### ISSUE TITLE
add tag `v1.0.0-rc1` -- make a branch for that, separate from main

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#135]
add tag `v1.0.0-rc1`

make a branch for that, separate from main -- new branch will only receive cherry pick from main and will be integrated back to main upon release of `v1.0.0`

**Comment by PaulCharlton** [comment]
@ikaneshiro @cclerget @DrDaveD

**Comment by PaulCharlton** [comment]
@DrDaveD we added a tag, but not a branch?

**Comment by DrDaveD** [comment]
The branch name is release-1.0
