### ISSUE TITLE
Commands like chgrp fail when using Apptainer installed without suid

### ISSUE THREAD

**Issue by preney** [apptainer/apptainer#1379]
### Version of Apptainer

```
apptainer version 1.1.8
```

### Expected behavior

It was expected to see Apptainer access/query/set groups that a given user belongs to without requiring `root`/`sudo` or using Apptainer installed with suid.

### Actual behavior

When I run Apptainer installed without suid, this is seen:
```
$ apptainer build ubuntu-basic.sif docker://ubuntu:latest
[snip]
$ apptainer shell ubuntu-basic.sif
Apptainer> groups
preney nogroup
Apptainer> exit
```
(NOTE: groups on our clusters are handled using LDAP --not via files in /etc. The use of Ubuntu in the `.sif` file can be replaced with other Linux distributions.)

But when I run `groups` (in the host OS shell) from the command line I correctly see all groups, e.g.,
```
$ groups
preney def-preney def-preney2 def-preney3
```

If I run Apptainer installed with suid, I do see all groups correctly, e.g.,
```
apptainer shell ubuntu-basic.sif
Apptainer> groups
preney def-preney def-preney2 def-preney3
Apptainer> exit
```

The issue is that the invoking user's group permissions is only correct when Apptainer installed with suid is run --and such should also be correct when Apptainer is installed without suid. This issue prevents querying, using chgrp, etc. from working correctly for the invoking user (which the user already has permissions to do when in the host OS shell) when Apptainer installed without suid is used. This can cause issues --that work without issues when the host OS shell is used. (For example, the chgrp command to change the group owner (e.g., using chgrp) of a directory/file will fail when using Apptainer installed without suid.)

While using Apptainer with suid is a work-around, this requires that Apptainer is also additionally always installed on local disk mounts as our other cluster file system mounts do not permit suid executables for security reasons --and this issue appears to be something that should be able to be done by Apptainer installed without suid (at least only) for the invoking user.

### Steps to reproduce this behavior

See previous question.

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Apptainer

Effectively from source with and without suid (in two different filesystem locations so the module command can be used to load either).

**Comment by DrDaveD** [comment]
Unfortunately this is a fundamental limitation of the Linux kernel unprivileged user namespaces feature.  The workflow will need to be modified to do any chgrp commands outside of the container, and do a newgrp to the desired group before starting apptainer.

**Comment by DrDaveD** [comment]
So setuid mode is required for supplemental groups, there's no way around that.  Would it help you if setuid mode supported fuse mounts, so that there wouldn't be the risk of kernel filesystem mounts discussed in the recent [apptainer security advisory](https://github.com/apptainer/apptainer/security/advisories/GHSA-j4rf-7357-f4cg)?  This is being considered for 1.3 in #1411.

**Comment by DrDaveD** [comment]
Also, I just learned to my surprise that even though the files appear to be the wrong group inside the unprivileged user namespace and chgrp cannot work, you can actually still access files accessible only to one of the supplemental groups available outside the namespace.  That could be very useful.  So you may not actually need to do a newgrp to change the one desired group outside of apptainer, just do the chgrps there.
