### ISSUE TITLE
"No more space on device" when pulling/building large image

### ISSUE THREAD

**Issue by matekelemen** [apptainer/apptainer#1380]
### Version of Apptainer

```
apptainer --version
apptainer version 1.1.7
```

### Expected behavior

Successful pull/build of a valid image of any size, provided that there's enough **disk** space available to the user.

### Actual behavior

When pulling a large image, apptainer tries to assemble an image from downloaded blobs but fails with the following message:
```
...
Copying config <a_hash> done  
Writing manifest to image destination
Storing signatures
FATAL:   While performing build: conveyor failed to get: writing blob: write /tmp/bundle-temp-<some-hash>/oci-put-blob<some-other-hash> no space left on device
```

After a lengthy digging, I found that [apptainer tries building the image in-memory](https://docs.sylabs.io/guides/3.6/user-guide/build_env.html):
```
Many modern Linux distributions use an in-memory tmpfs filesystem for /tmp when installed on a computer with a sufficient amount of RAM. This may limit the size of container you can build, as temporary directories under /tmp share RAM with runniing programs etc. A tmpfs also uses default mount options that can interfere with some container builds.

Set SINGULARITY_TMPDIR to a disk location, or disable the tmpfs /tmp mount on your system if you experience problems.
```

I still had the downloaded blobs, so I tried building them after setting `SINGULARITY_TMPDIR` such that apptainer wouldn't use `tmpfs`:
```
apptainer build output_image.sif oci://$HOME/.apptainer/cache/blob:<digest-hash>
```

That worked, but I'd expect apptainer to know both the size of the memory available to `tmpfs` **and** the image it's trying to build, so it should be able to make a correct decision.

### Steps to reproduce this behavior

Try pulling/building a BIG image. For example, the following image is ~16G:

`apptainer pull docker://l1naforever/stable-diffusion-rocm:latest`

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Manjaro Linux"
PRETTY_NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://forum.manjaro.org/"
BUG_REPORT_URL="https://docs.manjaro.org/reporting-bugs/"
PRIVACY_POLICY_URL="https://manjaro.org/privacy-policy/"
LOGO=manjarolinux
```

### How did you install Apptainer

`pacman -S apptainer`

**Comment by DrDaveD** [comment]
Apptainer has no way of calculating ahead of time how much space a container build will take, nor does it have any way to guess at another location to use in place of a too-small /tmp.  This is a common Linux issue; that's the reason why there is the TMPDIR convention.  I don't see how the situation can be improved.

**Comment by DrDaveD** [comment]
I think that people would forget to pass the argument too often.  It's better to set the environment variable once and forget it.

It would be good to add some mention of it in `apptainer build -h` though.  Let's use this issue for that.
