### ISSUE TITLE
error-out vs. warning about unused build args?

### ISSUE THREAD

**Issue by preminger** [apptainer/apptainer#1386]
I have been looking at picking PR #1356 into https://github.com/sylabs/singularity, and I noticed that the current behavior is to error out when there are arguments passed via `--build-arg` (or `--build-arg-file`) that are not consumed by the definition file:

```
$ cat vars.def
Bootstrap: docker
From: ubuntu:22.04

%runscript
    echo {{ var1 }} {{ var2 }}

$ sudo singularity build -F --build-arg var1=abcd --build-arg var2=efgh --build-arg var3=ijkl --build-arg var4=mnop vars.sif vars.def
FATAL:   While processing the definition file: while matching all variables, there are unmatched var4,var3 variables
```

While the `--build-arg` and `--build-arg-file` functionality is inspired by Docker, it's worth noting that erroring out in this case doesn't match the behavior of Docker under similar circumstances. Docker just ignores the unused build argument(s):
```
$ cat Dockerfile 
FROM ubuntu

$ docker build --build-arg PYTHON=3.11 .
[+] Building 0.0s (5/5) FINISHED                                                                                        
 => [internal] load .dockerignore                                                                                  0.0s
 => => transferring context: 2B                                                                                    0.0s
 => [internal] load build definition from Dockerfile                                                               0.0s
 => => transferring dockerfile: 109B                                                                               0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                   0.0s
 => CACHED [1/1] FROM docker.io/library/ubuntu                                                                     0.0s
 => exporting to image                                                                                             0.0s
 => => exporting layers                                                                                            0.0s
 => => writing image sha256:70f30450af0629512807117b9e0c16a4921939206b1468a3837bde0405a735f8                       0.0s
```

I'm wondering whether matching the behavior of Docker here might be preferable, perhaps issuing a `sylog` warning about the unused build argument but not erroring out?

**Comment by GodloveD** [comment]
Heya @preminger.  Are you able to give some justification for or against?  I don't really know which behavior would be more helpful to users in this case.

**Comment by preminger** [comment]
This is a good question, @GodloveD, and - in a vacuum - one about which some informal conversation between my colleagues & me has already revealed some differing opinions. _However_, I do feel, and my colleagues agree, that the decision to use the same option name (`--build-arg`) as Docker does (a decision which I wholeheartedly support, btw) will bring with it the expectation, on the part of users, that the behavior will be the same as Docker's behavior in this case.

In terms of which behavior would be more helpful to users, it'll obviously depend on how different users make use of the software. But to sketch out one use case where I think the warning-rather-than-error choice is preferable: suppose you're running `build` on a variety of `.def` files, and you're supplying them all via `--build-arg` with some specific information about your run environment (say, which version of Python to use). The warning-rather-than-error mode allows you to just do something like...

```
BUILD_ARGS = --build-arg pythonver=3.10 --build-arg datastash=/var/tmp
```

... and then just do `singularity build $BUILD_ARGS $siffile $deffile` (or `apptainer build $BUILD_ARGS $siffile $deffile`) for a variety of `.def` files, kind of like how `$CFLAGS` and `$LDFLAGS` are used, without worrying about whether each particular `.def` file does or does not happen to consume `{{ pythonver }}` and/or `{{ datastash }}`.

**Comment by DrDaveD** [comment]
I agree a warning would be better than an error.  @JasonYangShadow is that OK with you?

**Comment by JasonYangShadow** [comment]
@DrDaveD @GodloveD @preminger 
After talking with @cclerget , can we introduce a strict mode? where any mismatches will return error, and also a loose mode, where warnings will be printed out without returning errors?

**Comment by DrDaveD** [comment]
I wouldn't want to do that for only this set of warnings, but if it's a general option for both actions and build that would cause any warning to be fatal, I think that could be useful.
