### ISSUE TITLE
Image Building related issues from old repo 

### ISSUE THREAD

**Issue by kmuriki** [apptainer/apptainer#1392]
Download images before checking for fakeroot support https://github.com/apptainer/singularity/issues/4033

Inspect metadata no longer contains container size https://github.com/apptainer/singularity/issues/3932

Better error when there is not enough space on /tmp to build https://github.com/apptainer/singularity/issues/1680

**Comment by DrDaveD** [comment]
I don't think we have the problem from apptainer/singularity#4033 anymore, nor the problem referred in apptainer/singularity#1680.  Following through the links for apptainer/singularity#3932, it appears that much related work was attempted and some merged.  I don't think more will be done with it either.  Closing.
