### ISSUE TITLE
RFE: able to block Apptainer sub-command

### ISSUE THREAD

**Issue by JasonYangShadow** [apptainer/apptainer#1395]
Checking if there is a way to block the users from running the apptainer exec, shell to a running container.

The user should be able to start the instance and use apptainer run but not exec to the container or shell to it.

**Comment by DrDaveD** [comment]
How about if an instance start script instead removes or moves the information under ~/.apptainer/instances so the user can't see the instance?

**Comment by DrDaveD** [comment]
I'll close this, assuming that will work.  Reopen if not.

**Comment by JasonYangShadow** [comment]
@DrDaveD Sure, still confirming with the customer on details, guess that your suggestion is the expected solution.
