### ISSUE TITLE
run apptainer images inside docker without --privileged

### ISSUE THREAD

**Issue by fcasson** [apptainer/apptainer#1439]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using?   

`1.1.8-1.el8` inside my custom docker image `cassonf/rocky-apptainer:8.6`

### Expected behavior

I want to run `apptainer run` within docker without error without using the docker `--privileged` flag

### Actual behavior

` ... ERROR : Failed to create user namespace: not allowed to create user namespace`

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Fails:
```sh
docker run cassonf/rocky-apptainer:8.6 apptainer run docker://alpine
```

Fails:
```sh
docker run --runtime=sysbox-runc cassonf/rocky-apptainer:8.6 apptainer run docker://alpine
```

Works:
```sh
docker run --privileged cassonf/rocky-apptainer:8.6 apptainer run docker://alpine
```

### What OS/distro are you running

```sh
rockylinux:8.6
```

Have tested the docker commands above in different envs (both native ubuntu and WSL2 / ubuntu - I know the latter may be more difficult still...)  On some systems, docker version needs to be >= 23.0 to avoid a different issue:  https://github.com/singularityhub/singularity-docker/issues/18

### How did you install Apptainer

```dockerfile

FROM rockylinux:8.6

RUN yum update -y && \
    yum install -y epel-release && \
    yum update -y && \
    yum install -y apptainer-suid  # also tried apptainer without -suid
    
```   

### Use case 

My use case is to use apptainer in a docker image for testing of apptainer images in gitlab CI with the [docker executor](https://docs.gitlab.com/runner/executors/docker.html).

Our gitlab sysadmins don't want to start the gitlab runners in privileged model for security reasons, so ideally there would be a way to run the docker image without --privileged.  My apptainer runs don't need to start any special services or open network ports, they just need to mount one directory which is in the same userspace as the user executing singularity run.

The workaround is to move some of the gitlab docker executor runners to dedicated VM sandboxes where they can be started in privileged mode.  This means less resources will be available for my CI pipelines.

### Other notes

* I also tried sysbox because [this article]( https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) indicated it might be the better solution these days for this kind of workflow.  Maybe I didn't persue it enough but it didn't work out of the box (sic).  
* https://github.com/apptainer/singularity/issues/5458 indicates this is considered a niche use case, which I guess means it is unsupported?  I'm not clear what the fundamental limitation is, since I can run apptainer without root outside docker.  Maybe there isn't one but namespaces / rootless still seem to be tricky to get to work.

**Comment by fcasson** [comment]
Thanks, I can confirm this works on WSL2!  Now I need to see if there is way to put these options into the gitlab runners.

**Comment by DrDaveD** [comment]
Ok I'll close this.  If you need more help you can reopen.

**Comment by fcasson** [comment]
In some cases I have found 

`docker run --security-opt seccomp=unconfined --device /dev/fuse `

is sufficent, i.e. no need for for `systempaths=unconfined`

**Comment by DrDaveD** [comment]
> In some cases I have found
> 
> `docker run --security-opt seccomp=unconfined --device /dev/fuse `
> 
> is sufficent, i.e. no need for for `systempaths=unconfined`

Yes, the systempaths setting is only needed when using `--pid`.

**Comment by fnikolai** [comment]
On a somewhat similar configuration (apptainer within apptainer), I've found the `--unsquash`` flag to do the trick.

**Comment by DrDaveD** [comment]
> On a somewhat similar configuration (apptainer within apptainer), I've found the `--unsquash` flag to do the trick.

Maybe you had an old version of apptainer in the mix?  Recent versions should allow nesting by default with or without `--unsquash`.

**Comment by jemajet** [comment]
I'm running into different issues when using the flags
```--security-opt seccomp=unconfined --security-opt systempaths=unconfined --security-opt no-new-privileges --device /dev/fuse```, where I'm getting the error ```Installation issue: starter-suid doesn't have setuid bit set```. I am using it inside a docker container but am not sure how to set that bit from the documentation, here's the last part of the debug output:

```
VERBOSE [U=1000,P=165]     SetContainerEnv()             Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=1000,P=165]     init()                        Use starter binary /usr/libexec/apptainer/bin/starter-suid
VERBOSE [U=1000,P=165]     print()                       Set messagelevel to: 5
VERBOSE [U=1000,P=165]     init()                        Starter initialization
VERBOSE [U=1000,P=165]     is_suid()                     Check if we are running as setuid
DEBUG   [U=1000,P=165]     read_engine_config()          Read engine configuration
DEBUG   [U=1000,P=165]     init()                        Wait completion of stage1
DEBUG   [U=1000,P=173]     set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1000,P=173]     init()                        Spawn stage 1
DEBUG   [U=1000,P=173]     func1()                       Install prefix is /usr
DEBUG   [U=1000,P=173]     startup()                     apptainer runtime engine selected
VERBOSE [U=1000,P=173]     startup()                     Execute stage 1
DEBUG   [U=1000,P=173]     StageOne()                    Entering stage 1
DEBUG   [U=1000,P=173]     findOnPath()                  Found "squashfuse_ll" at "/usr/libexec/apptainer/bin/squashfuse_ll"
DEBUG   [U=1000,P=173]     findOnPath()                  Found "fuse2fs" at "/usr/sbin/fuse2fs"
DEBUG   [U=1000,P=173]     findOnPath()                  Found "fuse-overlayfs" at "/usr/bin/fuse-overlayfs"
DEBUG   [U=1000,P=173]     InitImageDrivers()            squashfuse_ll supports -o uid
DEBUG   [U=1000,P=173]     InitImageDrivers()            Setting ImageDriver to fuseapps
DEBUG   [U=1000,P=173]     prepareAutofs()               No autofs mount point found
DEBUG   [U=1000,P=173]     Init()                        Image format detection
DEBUG   [U=1000,P=173]     Init()                        Check for sandbox image format
DEBUG   [U=1000,P=173]     Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=1000,P=173]     Init()                        Check for sif image format
DEBUG   [U=1000,P=173]     Init()                        sif image format detected
DEBUG   [U=1000,P=173]     setSessionLayer()             Overlay seems supported and allowed by kernel
DEBUG   [U=1000,P=173]     setSessionLayer()             Attempting to use overlayfs (enable overlay = try)
DEBUG   [U=1000,P=173]     PrepareConfig()               image driver is fuseapps
VERBOSE [U=1000,P=165]     wait_child()                  stage 1 exited with status 0
DEBUG   [U=1000,P=165]     cleanup_fd()                  Close file descriptor 5
DEBUG   [U=1000,P=165]     cleanup_fd()                  Close file descriptor 6
DEBUG   [U=1000,P=165]     cleanup_fd()                  Close file descriptor 7
DEBUG   [U=1000,P=165]     init()                        Set child signal mask
DEBUG   [U=1000,P=165]     init()                        Create socketpair for master communication channel
DEBUG   [U=1000,P=165]     init()                        Create RPC socketpair for communication between stage 2 and RPC server
ERROR   [U=1000,P=165]     init()                        Installation issue: starter-suid doesn't have setuid bit set
```

**Comment by DrDaveD** [comment]
@jemajet Don't try to use a suid installation inside unprivileged docker.  If apptainer thinks it should be able to run setuid but it fails, it does not silently fail to user namespace mode.  So either remove the starter-suid (e.g. by not installing the apptainer-suid package) or change the config file to have `allow setuid = no`
