### ISSUE TITLE
How to disable logs or at least change the log level

### ISSUE THREAD

**Issue by plispe** [apptainer/apptainer#1446]
Is there a way, how to change apptainer log level? I would like to get rid of (at least) the INFO: log messages. I didn't found anything related to this in the documentation.

**Comment by GodloveD** [comment]
```
$ apptainer --help

Linux container platform optimized for High Performance Computing (HPC) and
Enterprise Performance Computing (EPC)

Usage:
  apptainer [global options...]

Description:
  Apptainer containers provide an application virtualization layer enabling
  mobility of compute via both application and environment portability. With
  Apptainer one is capable of building a root file system that runs on any
  other Linux system where Apptainer is installed.

Options:
      --build-config    use configuration needed for building containers
  -c, --config string   specify a configuration file (for root or
                        unprivileged installation only) (default
                        "/opt/apptainer/development//etc/apptainer/apptainer.conf")
  -d, --debug           print debugging information (highest verbosity)
  -h, --help            help for apptainer
      --nocolor         print without color output (default False)
  -q, --quiet           suppress normal output
  -s, --silent          only print errors
  -v, --verbose         print additional information
      --version         version for apptainer
```
You probably want `--quiet` or `--silent`.

**Comment by DrDaveD** [comment]
I believe that `--quiet` will suppress INFO without removing WARNING, and that `--silent` will also suppress WARNING.

**Comment by plispe** [comment]
> ```
> $ apptainer --help
> 
> Linux container platform optimized for High Performance Computing (HPC) and
> Enterprise Performance Computing (EPC)
> 
> Usage:
>   apptainer [global options...]
> 
> Description:
>   Apptainer containers provide an application virtualization layer enabling
>   mobility of compute via both application and environment portability. With
>   Apptainer one is capable of building a root file system that runs on any
>   other Linux system where Apptainer is installed.
> 
> Options:
>       --build-config    use configuration needed for building containers
>   -c, --config string   specify a configuration file (for root or
>                         unprivileged installation only) (default
>                         "/opt/apptainer/development//etc/apptainer/apptainer.conf")
>   -d, --debug           print debugging information (highest verbosity)
>   -h, --help            help for apptainer
>       --nocolor         print without color output (default False)
>   -q, --quiet           suppress normal output
>   -s, --silent          only print errors
>   -v, --verbose         print additional information
>       --version         version for apptainer
> ```
> 
> You probably want `--quiet` or `--silent`.

Thank you, this seams be ok, but I need a way, how to set in configuration file. Because I am using Apptainer in combination with https://singularity-hpc.readthedocs.io/ and I don't have control over all apptainer commands.

**Comment by DrDaveD** [comment]
Yes and meanwhile it looks like all you could do is make a wrapper script for apptainer that adds the option and is put earlier in the PATH.
