### ISSUE TITLE
gmake 4.4 

### ISSUE THREAD

**Issue by GodloveD** [apptainer/apptainer#1447]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.1.8-1.el9
```
### Expected behavior

`make -j2` in a def file on a distribution that uses gmake >=v4.4 should work.

### Actual behavior

On distributions with gmake >=v4.4 a parallel make command fails with the following error.

```
make: *** cannot open jobserver /tmp/GMfifo157: No such file or directory.  Stop.
```

### Steps to reproduce this behavior

I created a throw-away repo to allow people to replicate this issue easily.  Just do the following:

```
$ git clone https://github.com/GodloveD/gmake-4.4-test.git

$ cd gmake-4.4-test/

$ apptainer build make.sif make.def 
```
The repo contains the following toy files:

- `hellomake.c`

```c
#include <hellomake.h>

int main() {
  // call a function in another file
  myPrintHelloMake();

  return(0);
}
```
- `hellofunc.c`

```c
#include <stdio.h>
#include <hellomake.h>

void myPrintHelloMake(void) {

  printf("Hello makefiles!\n");

  return;
}
```
- `hellomake.h`

```c
/*
example include file
*/

void myPrintHelloMake(void);
```

- `Makefile`

```make
CC=gcc
CFLAGS=-I.
DEPS = hellomake.h
OBJ = hellomake.o hellofunc.o 

%.o: %.c $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

hellomake: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)
```

And then there is the def file used to produce the error.

```
Bootstrap: docker
From: fedora:39

%files
    hellomake.c
    hellofunc.c
    hellomake.h
    Makefile

%post
    dnf -y install gcc
    echo "**********"
    gmake --version
    echo "**********"
    make -j2
```
**NOTE:** This does not fail if you build the container with `sudo`!  :confused: 

Is there a suid binary or something that make is trying to use to create a fifo in `/tmp`?  

### What OS/distro are you running
I've replicated on a few different systems but here are details for one. 

```
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### How did you install Apptainer

Unprivileged helper script.

**Comment by DrDaveD** [comment]
strace on the make command shows:
```
116   mknodat(AT_FDCWD, "/tmp/GMfifo116", S_IFIFO|0600) = 0
116   openat(AT_FDCWD, "/tmp/GMfifo116", O_RDONLY|O_NONBLOCK) = -1 ENOENT (No such file or directory)
```

So it's creating a named pipe and immediately trying to read it non-blocking and failing.

**Comment by DrDaveD** [comment]
Here's a simpler make.def reproducer:
```
Bootstrap: docker
From: centos:7

%post
    mknod /tmp/fifo-test p
    ls -l /tmp/fifo-test
```
Then this is the output:
```
$ apptainer build make.sif make.def
INFO:    Starting build...
Getting image source signatures
Copying blob 2d473b07cdd5 skipped: already exists
Copying config 6d42e44a9f done
Writing manifest to image destination
Storing signatures
2023/06/15 15:28:50  info unpack layer: sha256:2d473b07cdd5f0912cd6f1a703352c82b512407db6b05b43f2553732b55df3bc
INFO:    Running post scriptlet
+ mknod /tmp/fifo-test p
+ ls -l /tmp/fifo-test
ls: cannot access /tmp/fifo-test: No such file or directory
FATAL:   While performing build: while running engine: exit status 2
```
It only silently fails to do the mknod when I have /etc/subuid mapping set up, not when apptainer does fakeroot with the fakeroot command.  I haven't been able to reproduce it yet with just `apptainer run -f` either, only at build time.

**Comment by cclerget** [comment]
@GodloveD @DrDaveD Fix here https://github.com/apptainer/apptainer/pull/1451

**Comment by GodloveD** [comment]
Thanks for the quick fix @cclerget !
