### ISSUE TITLE
Regression in unshare -r environment (/root inaccessible) after #1368

### ISSUE THREAD

**Issue by dtrudg** [apptainer/apptainer#1450]
### Version of Apptainer

`main`

Specifically 4a0d2b81b and later.

### Actual behavior

Hello. While looking at cherry-picking the fix for winbind user lookup in PR #1368, I noticed a behavior change.

When invoking apptainer from within a root-mapped namespace created with `unshare -r`:

Before PR #1368 ...

```
$ apptainer --version
apptainer version 1.1.8+638-gaf71753c7

$ unshare -r

$ apptainer run ~/almalinux_8.sif
INFO:    gocryptfs not found, will not be able to use gocryptfs
Singularity> ls /root
   <successful directory listing>
Singularity> exit
```

After PR #1368 ...

```
$ apptainer --version
apptainer version 1.1.8+639-g4a0d2b81b

$ unshare -r

$ apptainer run ~/almalinux_8.sif 
INFO:    gocryptfs not found, will not be able to use gocryptfs
bash: /root/.bashrc: Permission denied
Singularity> ls /root
ls: cannot open directory '/root': Permission denied
Singularity> exit
```

I believe this is probably a bug, as it's now not possible to use this flow (rare though it may be)?

If it's an accepted change, would be good to note it in the CHANGELOG.md.

### What OS/distro are you running

Fedora 38

### How did you install Apptainer

Git Source.

**Comment by DrDaveD** [comment]
Thanks for the report, DT.  I will have to re-test, but in at least a couple of different ways apptainer mounts the original user's home directory at ~root when running in any kind of fake root mode.  Hopefully those places still work.  In this case I think it may have been an accident that unshare -r worked that way, I'm not sure.  I would expect it to work if you did this before starting apptainer
```
$ unshare -rm
# mount --bind ~ ~root
# apptainer run ...
```
That works for me with version 1.2.0-pre1.

**Comment by dtrudg** [comment]
> Thanks for the report, DT. I will have to re-test, but in at least a couple of different ways apptainer mounts the original user's home directory at ~root when running in any kind of fake root mode. Hopefully those ways still work. In this case I think it may have been an accident that unshare -r worked that way, I'm not sure. I would expect it to work if you did this before starting apptainer
> 
> ```
> $ unshare -rm
> # mount --bind ~ ~root
> # apptainer run ...
> ```
> 
> That works for me with version 1.2.0-pre1.

Yeah, it wasn't clear to me whether it was accidental... perhaps this is fine, as long as it is documented as a change in behaviour... just in case anyone is depending on using an unshare without the bind?
