### ISSUE TITLE
Nested Containers: Propagating APPTAINERENV_APPEND_PATH?

### ISSUE THREAD

**Issue by WeeBull** [apptainer/apptainer#1466]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.1.8-1.el9
```

### Actual behavior

I'm currently using `$APPTAINER_PREPEND_PATH` to add some paths to the `PATH` environment variable inside the container. This allows me to have access to some software installed on our network.

```
$ export APPTAINERENV_PREPEND_PATH=/mnt/software/somePackage/bin
$ ./apptainer_imageA.sif    # This uses the software on the network
```

This works fine, but I also have a second Apptainer image `apptainer_imageB.sif` which is called from image A. When that happens, the software inside image B is unable to see the network software on its path. It appears that using this environment variable to control the PATH doesn't work with nested containers, as it's cleared in the first container to be run.

```
$ export APPTAINERENV_PREPEND_PATH=/mnt/software/somePackage/bin
$ apptainer shell ./apptainer_imageA.sif    # This uses the software on the network
Apptainer> echo $PATH
/mnt/software/somePackage/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Apptainer> echo $APPTAINERENV_PREPEND_PATH 

Apptainer> exit
```

### Expected behavior

I was (naively?) expecting APPTAINER_PREPEND_PATH & APPTAINER_APPEND_PATH to propagate through to nested containers.

Is there a way I can make this happen?

### What OS/distro are you running

```sh
$ cat /etc/os-release 
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### How did you install Apptainer

EPEL

**Comment by WeeBull** [comment]
That presumably would get me one level of nesting. I suppose I'd need to do that step in each container to establish `APPTAINERENV_APPTAINERENV_PREPEND_PATH` at each level of nesting

**Comment by DrDaveD** [comment]
I think it's pretty unusual to have more than one level of nesting!  Nesting has only really been supported since apptainer-1.1.  To support one more level you could probably add one more `APPTAINERENV_` prefix at the outer layer as well.

Anyway I'll go ahead and close this.
