### ISSUE TITLE
multiple virtual environments?

### ISSUE THREAD

**Issue by Phylloxera** [apptainer/apptainer#1467]
### Version of Apptainer

Singularity 3.10

### Expected behavior

NA

### Actual behavior

NA

### Steps to reproduce this behavior

NA

### What OS/distro are you running

Ubuntu 22.0.4

### How did you install Apptainer

source

### Howdy,

Great product! long time user but still uncomfortable with a lot of the terms. I found https://github.com/apptainer/singularity/issues/2587 that describes the beginning of my question... 
Ultimately, I want to have multiple (incompatible) virtual environments in the same container and have a way to pick among them when I run my singularity exec command to access the container. Is this possible? Or is this a use case where multiple containers are needed to run a single pipeline? I'm sure this has been addressed before. Just maybe not in language I understand... or I have not yet found. Thanks!

**Comment by DrDaveD** [comment]
The last version of Singularity before the name changed to Apptainer was 3.8.5.  You must be using SingularityCE.  Please submit your issue to https://github.com/sylabs/singularity.

**Comment by GodloveD** [comment]
Not totally sure how different the virtual environments need to be.  If you need entirely different file systems you just need different containers and container orchestration.  Fuzzball is the solution for this if you are running jobs.  If you just need different env vars and whatnot, you might look into [scif app support](https://apptainer.org/docs/user/latest/definition_files.html#scif-apps).
