### ISSUE TITLE
apptainer won't exit on SIGINT, SIGQUIT, or SIGTERM

### ISSUE THREAD

**Issue by fhriley** [apptainer/apptainer#1477]
### Version of Apptainer

```sh
root@pve:~# apptainer --version
apptainer version 1.2.0-rc.1
```

### Expected behavior

apptainer exits on SIGINT, SIGQUIT, or SIGTERM.

### Actual behavior

It doesn't exit. The only way to get it to exit is to send it a SIGKILL.

### Steps to reproduce this behavior

```sh
root@pve:~# mkdir -p /root/nginx/data /root/nginx/letsencrypt
root@pve:~# apptainer run --compat -B /root/nginx/data:/data,/root/nginx/letsencrypt:/etc/letsencrypt docker://jc21/nginx-proxy-manager
```

Then do a `ctrl-c`, `ctrl-\` or `kill -s SIGTERM $PID`.

### What OS/distro are you running

```sh
root@pve:~# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### How did you install Apptainer

.deb file from github

**Comment by DrDaveD** [comment]
That's a function of the particular container you are running combined with the `--compat` option.  Apptainer itself should not respond to those signals, it only passes them on to the container.  The `--compat` option tells Apptainer to do various things similar to docker, and in particular the two implied options `--pid --no-init` tell it to run the container's own "shim" process as pid 1, which among other things processes the signals.  If you try to run without the `--no-init` option by using all the other implied `--nocompat` options, specifically `--containall --no-umask --no-eval --writable-tmpfs` then the container dies saying
```
s6-overlay-suexec: fatal: can only run as pid 1
```
So this particular container requires that it handle the signals in pid 1, and it is ignoring them all.

**Comment by fhriley** [comment]
> So this particular container requires that it handle the signals in pid 1, and it is ignoring them all.

I'm not sure I understand this part. When I run this container with docker:

`docker run --rm -v /root/nginx/data:/data -v /root/nginx/letsencrypt:/etc/letsencrypt jc21/nginx-proxy-manager`

The output shows that when I ctrl-c it, pid 1 is passing the signal on:

```
[6/26/2023] [9:52:41 PM] [Global   ] › ℹ  info      Backend PID 162 listening on port 3000 ...
[6/26/2023] [9:52:41 PM] [Nginx    ] › ℹ  info      Reloading Nginx
[6/26/2023] [9:52:41 PM] [SSL      ] › ℹ  info      Renew Complete
[6/26/2023] [9:52:44 PM] [Global   ] › ℹ  info      PID 162 received SIGTERM
[6/26/2023] [9:52:44 PM] [Global   ] › ℹ  info      Stopping.
```

When I run under apptainer, I know something is causing the signals to be ignored, I'm just not sure who and how to correct it.

**Comment by fhriley** [comment]
Further testing shows that this a problem when apptainer is running with a terminal. If we simulate running without a TTY like this:

```sh
(setsid apptainer run --compat -B /root/nginx/data:/data,/root/nginx/letsencrypt:/etc/letsencrypt docker://jc21/nginx-proxy-manager) </dev/null |& cat
```

And then send the apptainer process a SIGTERM, the container receives the SIGTERM and exits properly:

**Comment by DrDaveD** [comment]
Ah, I see, docker has the same behavior if you add the `-it` options.

It is counter-intuitive that setsid and stdin/out/err redirects for Apptainer would help, though.  In fact a control-C gives back the shell prompt without killing anything, as I would expect.  Sure you can send a SIGTERM from a command line, but in fact I also see it cleanly exiting without the setsid if I send the signal to the s6-svscan process; I don't need to send SIGKILL (I am testing on CentOS 7).

Apptainer does not have an option to skip allocating a new tty, because in fact it never allocates one; it just uses the tty of the parent shell.  When in `--contain` mode it changes the name to `/dev/console` but it is still actually the same tty.
