### ISSUE TITLE
Add --instance-file-path to explicitly set instance path to avoid info leaks

### ISSUE THREAD

**Issue by JasonYangShadow** [apptainer/apptainer#1484]
files under `$HOME/.apptainer/instance` directory is shared across different containers (By default the home directory is bound to containers), which can result in info leaks.

For better security, we can add one new option `--instance-file-path` to explicitly set the instance path (Note: users have to set this path to somewhere they have permission to write) to prevent any instance info from being leaked.

**Comment by JasonYangShadow** [comment]
@DrDaveD  @anderbubble @GodloveD 
As previously discussed in the community meeting, we can add a new option for better info security for `instance start` subcommand. 

I will take care of this issue.  If you have any other comments, totally feel free to leave here. Thanks!

**Comment by GodloveD** [comment]
Sounds awesome! Don't forget to create the corresponding environment variable when you add the flag! :smile_cat:

**Comment by JasonYangShadow** [comment]
@GodloveD 
I guess #1463 is enough for this feature? As the entire configuration directory is customized.

**Comment by DrDaveD** [comment]
Oh, and I had forgotten that it already had been cherry-picked to the 1.2 branch.  It will be in 1.2.0-rc.2.
