### ISSUE TITLE
signature warning when building unsigned container

### ISSUE THREAD

**Issue by Gerardwx** [apptainer/apptainer#1490]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

apptainer version 1.1.4

### Steps

Using the following *def files (renamed .txt because github did not like .def)

```

$apptainer build  ubuntu18.sif ubuntu18.def 
INFO:    Starting build...
Getting image source signatures
Copying blob 7c457f213c76 skipped: already exists  
Copying config f9a80a55f4 done  
Writing manifest to image destination
Storing signatures
2023/06/27 14:56:29  info unpack layer: sha256:7c457f213c7634afb95a0fb2410a74b7b5bc0ba527033362c240c7a11bef4331 
...
$ apptainer build  scce.sif scce.def
INFO:    Starting build...
INFO:    Verifying bootstrap image ubuntu18.sif
WARNING: integrity: signature not found for object group 1
WARNING: Bootstrap image could not be verified, but build will continue.
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete: scce.sif
```

[scce.txt](https://github.com/apptainer/apptainer/files/11886144/scce.txt)
[ubuntu18.txt](https://github.com/apptainer/apptainer/files/11886145/ubuntu18.txt)

### What OS/distro are you running

```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal


```

### How did you install Apptainer

deb file

**Comment by DrDaveD** [comment]
I don't see any reason why there should be a warning about a missing signature when building from a localimage.  I think this particular warning should be moved to be a debug message.  If a signature is present but does not match, that's different and should still be shown.
