### ISSUE TITLE
gocryptfs build failed on PPA for Ubuntu environment (v1.2.0-rc.1)

### ISSUE THREAD

**Issue by panda1100** [apptainer/apptainer#1496]
### Version of Apptainer

v1.2.0-rc1

### Expected behavior

1.2.0-rc.1, gocryptfs successfully built on PPA for Ubuntu environment

### Actual behavior

1.2.0-rc.1, gocryptfs build failed on PPA for Ubuntu environment

```
+ cd debian/gocryptfs-2.3.2
+ PATH=/tmp/appdebgo/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games GOCACHE=/tmp/appdebgo/cache ./build-without-openssl.bash
build.bash: warning: could not determine gocryptfs version
go: github.com/hanwen/go-fuse/v2@v2.3.0: Get "https://proxy.golang.org/github.com/hanwen/go-fuse/v2/@v/v2.3.0.info": dial tcp: lookup proxy.golang.org: no such host
go: github.com/aperturerobotics/jacobsa-crypto@v1.0.0: Get "https://proxy.golang.org/github.com/aperturerobotics/jacobsa-crypto/@v/v1.0.0.mod": dial tcp: lookup proxy.golang.org: no such host
go: github.com/aperturerobotics/jacobsa-crypto@v1.0.0: Get "https://proxy.golang.org/github.com/aperturerobotics/jacobsa-crypto/@v/v1.0.0.mod": dial tcp: lookup proxy.golang.org: no such host
go: could not create module cache: mkdir /sbuild-nonexistent: permission denied
make[1]: *** [debian/rules:69: override_dh_auto_configure] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:64: build] Error 2
```

### Steps to reproduce this behavior

upload apptainer source changes file to PPA for Ubuntu

### What OS/distro are you running

Rocky Linux 9

**Comment by panda1100** [comment]
The last time I saw this on PPA for Ubuntu environment, GOCACHE settings solved the problem. I need to review what directory `./build-without-openssl.bash` actually trying to create inside script.

```
go: could not create module cache: mkdir /sbuild-nonexistent: permission denied
```

This looks more like a DNS issue.

```
go: github.com/hanwen/go-fuse/v2@v2.3.0: Get "https://proxy.golang.org/github.com/hanwen/go-fuse/v2/@v/v2.3.0.info": dial tcp: lookup proxy.golang.org: no such host
go: github.com/aperturerobotics/jacobsa-crypto@v1.0.0: Get "https://proxy.golang.org/github.com/aperturerobotics/jacobsa-crypto/@v/v1.0.0.mod": dial tcp: lookup proxy.golang.org: no such host
go: github.com/aperturerobotics/jacobsa-crypto@v1.0.0: Get "https://proxy.golang.org/github.com/aperturerobotics/jacobsa-crypto/@v/v1.0.0.mod": dial tcp: lookup proxy.golang.org: no such host
```

**Comment by panda1100** [comment]
DNS issue: related discussion https://github.com/golang/go/issues/41425

and possible workaround https://pkg.go.dev/net#hdr-Name_Resolution
`GODEBUG=netdns=cgo`

**Comment by panda1100** [comment]
https://bugs.launchpad.net/launchpad-buildd/+bug/1874423
> .deb package builds are not permitted to talk to the internet - you need to package or vendor your build-dependencies.

**Comment by panda1100** [comment]
I'll try downloading pre-built gocryptfs v2.3.2 package from official repo, like we do for golang v1.19.6

**Comment by DrDaveD** [comment]
[INSTALL.md](https://github.com/apptainer/apptainer/blob/v1.2.0-rc.1/INSTALL.md?plain=1#L316) says:
```
(If the rpm needs to be built offline from the internet see
additional instructions for the gocryptfs source code in
dist/rpm/apptainer.spec.in).
```
and [dist/rpm/apptainer.spec.in](https://github.com/apptainer/apptainer/blob/v1.2.0-rc.1/dist/rpm/apptainer.spec.in#L57) says:
```
# In order to build offline, this source tarball needs to have the "vendor"
# directory added, which can be done by unpacking it, doing the command
#   go mod vendor
# and then recreating the tarball.
```

**Comment by panda1100** [comment]
Thank you @DrDaveD -san! I'll try this today. Now, I fully understand what @JasonYangShadow told me :sweat_smile:

**Comment by panda1100** [comment]
Successfully built on PPA for Ubuntu environment. I'll create PR for this. Thank you.
