### ISSUE TITLE
Apptainer build fails with Go version 1.20.5 on aarch64

### ISSUE THREAD

**Issue by j34ni** [apptainer/apptainer#1531]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

` apptainer v1.1.9`

### Expected behavior
```
cd /tmp
git clone https://github.com/apptainer/apptainer.git
cd apptainer/
git checkout v1.1.9
./mconfig --without-suid --prefix=$HOME/apptainer_arm64
make -C ./builddir
```

### Actual behavior

```
make: Entering directory '/tmp/apptainer/builddir'
 GEN GO DEP /tmp/apptainer/builddir/starter.deps
 GEN GO DEP /tmp/apptainer/builddir/apptainer.deps
 GEN /tmp/apptainer/scripts/go-generate
 GO apptainer
    [+] GO_TAGS "containers_image_openpgp sylog oci_engine apptainer_engine fakeroot_engine apparmor selinux"
# crypto/internal/nistec
/home/user/go/src/crypto/internal/nistec/p256_ordinv.go:14:6: p256OrdMul redeclared in this block
        /home/user/go/src/crypto/internal/nistec/p256_asm_ordinv.go:14:6: other declaration of p256OrdMul
/home/user/go/src/crypto/internal/nistec/p256_ordinv.go:19:6: p256OrdSqr redeclared in this block
        /home/user/go/src/crypto/internal/nistec/p256_asm_ordinv.go:19:6: other declaration of p256OrdSqr
/home/user/go/src/crypto/internal/nistec/p256_ordinv.go:21:6: P256OrdInverse redeclared in this block
        /home/user/go/src/crypto/internal/nistec/p256_asm_ordinv.go:21:6: other declaration of P256OrdInverse
make: *** [Makefile:173: apptainer] Error 1
make: Leaving directory '/tmp/apptainer/builddir'
```

### What OS/distro are you running

NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"

### LSCPU

Architecture=aarch64
Vendor ID=ARM
Model nam=Neoverse-N1

However that worked with Go version 1.19.3

**Comment by GodloveD** [comment]
I tried and failed to replicate this on Jammy.  (Meaning the `make` step worked without error.)  Don't immediately have a Focal VM laying around, but if I have time I'll attempt spin one up and try again.

**Comment by j34ni** [comment]
@GodloveD Remember that it is on a machine with ARM processor that it fails (it works OK with Intel/AMD)

**Comment by GodloveD** [comment]
Thank you for clarification @j34ni .  I missed that detail.

**Comment by DrDaveD** [comment]
I don't know if any of us have a way to reproduce this so it would be very helpful if you could find a workaround and submit a pull request, @j3ni.

**Comment by bobhenkel** [comment]
I'm on an MacBook m1(arm). I run Linux virtual machines via qemu(usually Rocky :)). I was able to build Apptainer on a Debian 12 vm on arm without issue.
go version go1.20.6 linux/arm64
apptainer version 1.2.0
Linux lima-debian12 6.1.0-9-cloud-arm64 #1 SMP Debian 6.1.27-1 (2023-05-08) aarch64 GNU/Linu
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/

**Comment by j34ni** [comment]
@bobhenkel 

Sorry to be a pest, but the issue I had was with Apptainer v1.1.9, Go version 1.20.5 on an aarch64 machine with Ubuntu 20.04

So you are in a different configuration, and it may be that it does not happen with Debian 12, and/or with Go version 1.20.6, and/or Apptainer v1.2.0, or that someone it was fixed in Go version 1.20.6, and/or Apptainer v1.2.0

Anyway, I managed to build Apptainer v1.1.9 with Go version 1.19.3, and that has worked for me ever since

It may not be needed to search further

**Comment by DrDaveD** [comment]
The error was in the go internal libraries so it doesn't seem likely to be related to the O.S. version (although possible).   @j34ni could you try 1.20.6?  Perhaps it was a bug in go 1.20.5.

**Comment by j34ni** [comment]
@DrDaveD I just tried with Apptainer v1.1.9 and Go version 1.20.6, on the same aarch64 machine, and there was no error, so whatever bug there was it has now been fixed
