### ISSUE TITLE
Using --net --network-args="portmap=8080:80/tcp" blocks other ports outside the container

### ISSUE THREAD

**Issue by narein257** [apptainer/apptainer#1573]
### Version of Apptainer
apptainer version 1.2.0-rc.2

### Expected behavior
When using portmap to start nginx, other ports should be available without using port map.
apptainer run --fakeroot --net --network-args="portmap=8080:80/tcp" --writable-tmpfs nginx.sif

### Actual behavior

Other ports used by custom applications within the container are not accessible from outside.

### Steps to reproduce this behavior

Created a custom nginx server that listens on both port 80 and 8081. See the attached files used for creating sif image.

1. Create a sif image using the app.def file.
2. apptainer run --fakeroot --net --network-args="portmap=8080:80/tcp" --writable-tmpfs nginx.sif
3. Access nginx from the browser on port 8080. nginx start page is availble on 8080.
4. Access nginx from the browser on port 8081. nginx start page is NOT availble on 8081.
5. Run apptainer run --fakeroot --net --network-args="portmap=8080:80/tcp" --net --network-args "portmap=8081:8081/tcp" --writable-tmpfs nginx.sif
6. Now nginx start page is availble on 8081.
7. udp ports are not accessible even after portmap.

### What OS/distro are you running

NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"

### How did you install Apptainer
Built from source --with-suid option.

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.
[newport.zip](https://github.com/apptainer/apptainer/files/12142301/newport.zip)

**Comment by cclerget** [comment]
@narein257 This is the expected behavior, when using container network namespace, the container is running as isolated in a separate network, even on your local machine if you want to access container services, you have two options:

1. determine the container IP and use it to access service directly without `portmap`
2. expose container ports via `portmap`, in this case, you must expose all service ports you want to, all ports requiring to be accessible outside of container must be explicitly specified:

```
--network-args="portmap=8080:80/tcp" --network-args="portmap=8081:8081/tcp"
```

And if you want to expose UDP ports, replace `/tcp` by `/udp` :

```
--network-args="portmap=8081:8081/udp"
```

**Comment by narein257** [comment]
@cclerget tried using --network-args="portmap=8081:8081/udp" for udp, but getting an connection refused error. I am running as fakerrot when portmapping. This uses fakeroot network, so is there something that blocks udp ports?

**Comment by DrDaveD** [comment]
udp doesn't make connections so it sounds like you're trying to use tcp.
