### ISSUE TITLE
RFE: Use same namespaces when running in MPI context

### ISSUE THREAD

**Issue by cclerget** [apptainer/apptainer#1583]
Actually with unprivileged setup, each processes spawned by MPI run under its own user namespace, performance impact has been observed as highlighted in the issue https://github.com/apptainer/apptainer/issues/769.

The basic idea is to run all processes in the same user namespace, similarly to what's done with apptainer SUID.
The first process will setup the container (similar to `instance start`) while the other processes will join this container (like `exec instance://...`).

As it could be hard to automatically detect this case when apptainer is launched by `mpirun`, the addition of a CLI flag would be necessary to instruct `apptainer` to coordinate and run in this special mode for unprivileged setup.

**Comment by JasonYangShadow** [comment]
I will take care of this issue and update here if there are any progresses.
