### ISSUE TITLE
Templating cannot handle empty values

### ISSUE THREAD

**Issue by olesenm** [apptainer/apptainer#1584]
Further to issue #963 (@panda1100), I was attempting to use empty placeholders, but failed.

Attempt1:
```
%arguments
    OS_VER=latest
    FOAM_VERSION=2306
    SUBPKG=
    PACKAGE=openfoam{{ FOAM_VERSION }}{{ SUBPKG }}
```
and then use `--build-arg SUBPKG=-dev`.  Fails however with the initial `SUBPKG=` entry. Also attempted:
```
    SUBPKG
    SUBPKG=""
    SUBPKG=''
```
The first two didn't seem to parse, the last one parsed but added a pair of single quotes in the replacement!

Attempt2:
```
%arguments
    OS_VER=latest
    FOAM_VERSION=2306
    SUBPKG=-dev
    PACKAGE=openfoam{{ FOAM_VERSION }}{{ SUBPKG }}
```
and then use `--build-arg SUBPKG=""` but fails too.

Is there another way? Or is this just the limit of simple templates?

**Comment by panda1100** [comment]
@olesenm Thank you Mark-san,

Currently I believe this is by design, to make sure every variables has values. The intention of this design is make sure users can build their image without specifying any values.

This is good counter example. I'll discuss with Xu about this. meanwhile, how about `SUBPKG=" "` (single space)? This is not clean workaround though. (I'll try this later myself.)

**Comment by olesenm** [comment]
> how about `SUBPKG=" "` (single space)? This is not clean workaround though. (I'll try this later myself.)

For my current purposes, it doesn't matter either way (ie, I don't need a workaround - can simply use a different file).
However, I can easily imagine also wanting to have something like this:
```
%arguments
    OS_VER=latest
    FOAM_VERSION=2306
    DEBUG_OPT=
    SUBPKG=-dev
    PACKAGE=openfoam{{ DEBUG_OPT }}{{ FOAM_VERSION }}{{ SUBPKG }}
```
And then resolving as `openfoam2306-dev` or (with --build-arg) as `openfoam_debug2306-dev`.  We admittedly don't actually have any such package, but for flexible templating I think there needs to be provision for pasting in empty replacements.  However, feel free to close if you disagree or if it violates the design principle.

**Comment by JasonYangShadow** [comment]
thanks! I will take a look at it and reply here if there are any further discussions needed.

**Comment by panda1100** [comment]
Thank you @JasonYangShadow !

**Comment by DrDaveD** [comment]
@olesenm When you say it fails, what error do you get?  Does the `--warn-unused-build-args` option prevent it from failing?

**Comment by JasonYangShadow** [comment]
@panda1100 @olesenm 
I just created a PR for this issue
If you have time,  please help do double verification and leave any comments.
