### ISSUE TITLE
Configurable runscript timeout

### ISSUE THREAD

**Issue by vinjana** [apptainer/apptainer#1595]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
apptainer version 1.1.2-1.el7
```

### Expected behavior

The container should start in 100% of the runs independent of the runtime of the runscript. It should be possible to increase the timeout of the runscript beyond 1 min.

### Actual behavior

Currently, there is a timeout for the runscript of 1 minute. This timeout is not enough in all cases.

1. Conda-based containers may have a very long start-up time. Whether that is [reasonable](https://github.com/apptainer/singularity/issues/5653#issuecomment-717268942) really depends on the context. Even a multi-minute start-up time often is no problem for a container that runs many hours just to work on a defined number-crunching task.
2. The start-up time may depend on external factors uncontrollable by the Apptainer user. We are running Apptainer in a multi-user cluster, with a huge shared filesystem (many PB) and lots of UNIX groups (which affects access times through permission checks). Start-up times depend on these factors, as well as moment-to-moment (I/O) load on the executing compute node.

Having a possibly short timeout for the runscript *is* an important feature, but sometimes having a long or even no timeout is also a feature that is necessary for some use-cases, such as the one described. Therefore, I proposes to make the timeout configurable to make it adaptable for each specific use case.

### Related issues

* https://github.com/apptainer/singularity/issues/6455
* https://github.com/apptainer/singularity/issues/5653
* https://github.com/apptainer/singularity/issues/5589

**Comment by DrDaveD** [comment]
That sounds like a reasonable feature to me.  Would you be interested in submitting a pull request?

**Comment by kpedro88** [comment]
I'm also still having issues with the 1-minute timeout (which are very difficult to reproduce, because it depends on system load, caches, etc.).

**Comment by vinjana** [comment]
Thanks! (and sorry @DrDaveD)
