### ISSUE TITLE
[Feature Request] Use of `--nv` and `--rocm` simultaneously

### ISSUE THREAD

**Issue by upsj** [apptainer/apptainer#1596]
I would like to be able to run both ROCm and CUDA binaries in the same container for testing and development. Is there anything fundamentally preventing this from working? I have been successful with the same requirements in a docker container, and there seems to be no overlap in the libraries involved, so I would also be happy to take a look at tackling the implementation with some guidance.

**Comment by GodloveD** [comment]
I don't actually think there is any actual technical reason that you could not pass both the `--nv` and the `--rocm` options with the same container call.  I guess Apptainer will prevent you from doing so though:
```
$ apptainer exec --nv --rocm docker://ubuntu true
INFO:    Using cached SIF image
WARNING: --nv and --rocm cannot be used together. Only --nv will be applied.
```
So probably if you grep for that warning in the code you can find the place where it selects only one of the options and you can simply remove the block.  That's what I would suggest.  And then if you create a PR you will get input about whether there is any real reason why we don't want to allow that.
