### ISSUE TITLE
Docker credentials not read from `~/.docker/config.json`

### ISSUE THREAD

**Issue by kshakir** [apptainer/apptainer#1616]
### Version of Apptainer

```sh
$ apptainer --version
apptainer version 1.2.2-1.el7
$ 
```

### Expected behavior

If one only has a `~/.docker/config.json` then the credentials should be read from this file path, as [stated in the apptainer documentation](https://apptainer.org/docs/user/1.2/docker_and_oci.html#docker-cli-authentication).

### Actual behavior

Only the file `~/.apptainer/docker-config.json` is searched for credentials.

#### Remove your apptainer docker-config.json
```sh
# for example: rm ~/.apptainer/docker-config.json
```

#### Remove your docker configuration directory
```sh
# for example: rm ~/.docker/config.json
```

#### Login to DockerHub
```sh
sh-4.2$ apptainer remote login -u [elided] docker://docker.io
Password / Token: 
INFO:    Token stored in /[elided]/.apptainer/remote.yaml
sh-4.2$ 
```

NOTE: As we'll see, the token is NOT stored in that file… but that message isn't really the issue.

#### Try to pull a private docker image (this works)
```sh
# Don't need to pull the whole image, so using `timeout` which logs in, but then produces an error while cleaning up
$ timeout 5s apptainer -s build temp.sif docker://somerepo/someimg:sometag
ERROR:   Could not remove bundle: could not remove "/tmp/build-temp-574505820": unlinkat /tmp/build-temp-574505820/rootfs/usr/share/man: directory not empty
$ 
```

#### Move the file containing the token to `~/.docker/config.json`

```sh
$ mkdir ~/.docker
$ mv ~/.apptainer/docker-config.json ~/.docker/config.json
$ 
```

#### (Optional) Verify your username and password are stored within the `~/.docker/config.json`
```sh
$ jq -r '.auths["https://index.docker.io/v1/"].auth' ~/.docker/config.json | base64 -d && echo
[elided]
$ 
```

#### Try to pull the same private image, but using ~/.docker/config.json (should work but doesn't)
```sh
$ timeout 5s apptainer -s build temp.sif docker://somerepo/someimg:sometag
FATAL:   While performing build: conveyor failed to get: while converting reference: reading manifest sometag in docker.io/someimg/sometag: requested access to the resource is denied
$ 
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.7 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.7"
PRETTY_NAME="Red Hat Enterprise Linux"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.7:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.7
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.7"
$ 
```

### How did you install Apptainer

Was probably installed via RPM by our I/T department.

**Comment by GodloveD** [comment]
Thanks for the report and for your patience.  I've been able to replicate this issue and I also note that it seems due to something that changed between the 1.1.9 and 1.2.0 versions.
