### ISSUE TITLE
yum bootstrap agent broken on Scientific Linux with v1.2.x

### ISSUE THREAD

**Issue by GodloveD** [apptainer/apptainer#1635]
### Version of Apptainer
greater than or equal to v1.2.0

### Expected behavior
Building a container with the `yum` bootstrap agent on a Scientific Linux host completes without error.

### Actual behavior
The build fails. 

### Steps to reproduce this behavior
Get a VM or something with Scientific Linux and execute the following:
```
$ cat >reproducer.def<<"EOF"
BootStrap: yum
OSVersion: 7.9
MirrorURL: http://ftp.scientificlinux.org/linux/scientific/%{OSVERSION}/$basearch/os/
Include: yum
 
%post
    mkdir -p /etc/yum.repos.d
EOF

$ sudo apptainer build reproducer.sif reproducer.def 
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: while checking rpm path: macro is not defined 
```

### What OS/distro are you running

```
$ cat /etc/os-release 
NAME="Scientific Linux"
VERSION="7.9 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.9"
PRETTY_NAME="Scientific Linux 7.9 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.9:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

### How did you install Apptainer
Installed from source with the `with-suid` option (because Scientific Linux doesn't have user namespace support).

**Comment by DrDaveD** [comment]
I confirm that it also fails using the similar centos7 definition file in the [apptainer user docs](https://apptainer.org/docs/user/latest/definition_files.html#header), and that that definition file works with at least /etc/subuid fakeroot in version 1.1.9.  Assigning to @JasonYangShadow.

**Comment by DrDaveD** [comment]
There should also be an e2e test for this.

**Comment by JasonYangShadow** [comment]
@DrDaveD @GodloveD cc @cclerget 
After spending some time investigation in the code base, it looks like this commit adds related code
https://github.com/apptainer/apptainer/commit/008ed9201697f16b0c8c3d0a66fac9ec7514936d

rough logic here is to retrieve some newly defined macros `_db_backend`, centos 7 does not have this macro defined
```
[vagrant@localhost ~]$ rpm --showrc | grep _db
-14: __dbi_other        mp_mmapsize=128Mb mp_size=1Mb
-14: _dbi_config        %{?__dbi_other}
-14: _dbi_config_Packages       %{?_dbi_config} lockdbfd
-14: _dbpath    %{_var}/lib/rpm
-14: _dbpath_rebuild    %{_dbpath}
-14: _keyringpath       %{_dbpath}/pubkeys/
-14: _rpmlock_path      %{_dbpath}/.rpm.lock
[vagrant@localhost ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```
So we can just print a warning here instead directly return an error here?
