### ISSUE TITLE
PID issues in establishing Spack shell environment

### ISSUE THREAD

**Issue by preney** [apptainer/apptainer#1641]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using?

```
apptainer version 1.2.2
```

### Expected behavior

When running `apptainer shell --app spack spack-recreate-issue.sif` it is expected that the SCIF app's shell environment would be properly loaded in the shell.

### Actual behavior

When running `apptainer shell --app spack spack-recreate-issue.sif` it is SCIF app's shell environment is unable to load the Spack environment.

### Steps to reproduce this behavior

To reproduce this behaviour, use this definition file (the important items are in the sections for the SCIF app called `spack`):

```
Bootstrap: debootstrap
OSVersion: bookworm
MirrorURL: http://deb.debian.org/debian

# Or if Docker is preferred use...
#Bootstrap: docker
#From: debian:12

%post
  export DEBIAN_FRONTEND=noninteractive
  export LC_ALL=C.UTF-8
  export LANG=C.UTF-8
  export LANGUAGE=C.UTF-8

  apt-get update
  apt-get upgrade -y

  apt-get install -y --reinstall locales-all
  dpkg-reconfigure -fnoninteractive locales-all

  apt-get install -y tzdata
  dpkg-reconfigure -fnoninteractive tzdata

  apt-get autoremove -y
  apt-get clean -y

%runscript
  exec "$@"


%appinstall spack
  echo "${SCIF_APPNAME}: Install Spack prerequisite packages..."
  # e.g., https://spack.readthedocs.io/en/latest/getting_started.html
  apt-get install -y build-essential ca-certificates coreutils curl \
    environment-modules gfortran git gpg lsb-release python3 \
    python3-distutils python3-venv unzip zip
  apt-get autoremove -y
  apt-get clean -y

  echo "${SCIF_APPNAME}: git clone spack repository..."
  git clone --depth 1 --shallow-submodules -c feature.manyFiles=true https://github.com/spack/spack.git

  # Tell Spack that HOME is $SCIF_APPROOT so its bootstrap store is stored there...
  export HOME=${SCIF_APPROOT}
  
  # Load spack...
  . ${SCIF_APPROOT}/spack/share/spack/setup-env.sh
  
  # Add the previously installed compilers...
  spack compiler find

  # Tell Spack to prefer Spack package preference over the reuse of available
  # binaries...
  spack config add concretizer:reuse:false

  # spackcmd invokes spack within a new bash shell after 
  # setup-env.sh has been invoked...
  cat <<"ZZEOF" > $HOME/bin/spackcmd
#!/bin/bash
if [ "${SPACK_ROOT+x}" != x ]; then
  . ${SCIF_APPROOT}/spack/share/spack/setup-env.sh
fi
bash -s <<EOF
spack "$@"
EOF
ZZEOF
  chmod a+rx $HOME/bin/spackcmd

%appenv spack
  echo "spack env: shell process id is $$"
  # When shell process id is 1, setup-env.sh will not execute properly...
  if [ "${SPACK_ROOT+x}" != x ]; then
    echo "Attempting to load spack..."
    . ${SCIF_APPROOT}/spack/share/spack/setup-env.sh
  fi

%apprun spack
  echo "spack run: shell process id is $$"
  if [ "${SPACK_ROOT+x}" != x ]; then
    echo "Attempting to load spack..."
    . ${SCIF_APPROOT}/spack/share/spack/setup-env.sh
  fi
  exec "$@"
```

Build the image:
```
$ sudo apptainer build spack-recreate-issue.sif spack-recreate-issue.def
[snip - output not quoted]
```

When `apptainer run --app spack` is used, the runscript properly loads spack, e.g., 
```
$ apptainer run -C --app spack spack-recreate-issue.sif spack --help
INFO:    gocryptfs not found, will not be able to use gocryptfs
spack env: shell process id is 1
Attempting to load spack...
source: /scif/apps/spack/spack/share/spack/setup-env.sh:258:24: parameter expansion requires a literal
spack run: shell process id is 13
Attempting to load spack...
[snip - output not quoted but is what is expected]
```

When `apptainer shell --app spack` is used, the appenv is not properly sourced, e.g.,
```
INFO:    gocryptfs not found, will not be able to use gocryptfs
spack env: shell process id is 1
Attempting to load spack...
source: /scif/apps/spack/spack/share/spack/setup-env.sh:258:24: parameter expansion requires a literal
Apptainer> 
exit
```

which is not expected at all. Spack's `setup-env.sh`, line 258 is the true clause for `zsh`, e.g.,
```
#
# Figure out where this file is.
#
if [ "$_sp_shell" = bash ]; then
    _sp_source_file="${BASH_SOURCE[0]:-}"
elif [ "$_sp_shell" = zsh ]; then
    _sp_source_file="${(%):-%N}"
else
    # Try to read the /proc filesystem (works on linux without lsof)
    # In dash, the sourced file is the last one opened (and it's kept open)
    _sp_source_file_fd="$(\ls /proc/$$/fd 2>/dev/null | sort -n | tail -1)"
    if ! _sp_source_file="$(readlink /proc/$$/fd/$_sp_source_file_fd)"; then
        # Last resort: try lsof. This works in dash on macos -- same reason.
        # macos has lsof installed by default; some linux containers don't.
        _sp_lsof_output="$(lsof -p $$ -Fn0 | tail -1)"
        _sp_source_file="${_sp_lsof_output#*n}"
    fi

    # If we can't find this script's path after all that, bail out with
    # plain old $0, which WILL NOT work if this is sourced indirectly.
    if [ ! -f "$_sp_source_file" ]; then
        _sp_source_file="$0"
    fi
fi
```

i.e., the error occurs because it is somehow executing `_sp_source_file="${(%):-%N}"`. This is true regardless of whether or not zsh is actually running on the host. (I tried dash, bash, zsh, etc. and the same result always occurs.) Looking above line 258 in Spack's `setup-env.sh` script one sees this:

```
# Determine which shell is being used
_spack_determine_shell() {
    if [ -f "/proc/$$/exe" ]; then
        # If procfs is present this seems a more reliable
        # way to detect the current shell
        _sp_exe=$(readlink /proc/$$/exe)
        # Shell may contain number, like zsh5 instead of zsh
        basename ${_sp_exe} | tr -d '0123456789'
    elif [ -n "${BASH:-}" ]; then
        echo bash
    elif [ -n "${ZSH_NAME:-}" ]; then
        echo zsh
    else
        PS_FORMAT= ps -p $$ | tail -n 1 | awk '{print $4}' | sed 's/^-//' | xargs basename
    fi
}
_sp_shell=$(_spack_determine_shell)
```

i.e., `/proc/$$/exe` is being used to determine the shell as other ways are quite unreliable --and it appears through my explorations that this is related to the issues seen.

Could this also be a bug in Spack's `setup-env.sh` script? Perhaps. (I am currently baffled as to how `zsh` is somehow being detected as the shell. Maybe I am missing something obvious --my apologies if that is the case.) This appears to only occur within Apptainer when the $$ PID is 1. The Spack `setup-env.sh` code looks good so I started with reporting this issue here.

Regardless this is the underlying issue with Apptainer...

When using `apptainer run --app spack` a new shell is running so everything works which is good. Similarly, if one runs `spackcmd` (which is installed in the app's bin directory), Apptainer will start a new shell and work properly. However, when one uses `apptainer shell --app spack` it fails to work so one must manually load the Spack environment. Especially for starting SCIF app's shell, one should be able to have the environment completely activated --one should not have to manually activate it, right?

### What OS/distro are you running

```
$ cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.14"
```

### How did you install Apptainer

Using Gentoo Linux' package for Apptainer, e.g.,
```
emerge -av app-containers/apptainer
```

(suid is disabled; examples, network, and systemd USE flags are enabled. That said, this shouldn't be an issue as this occurs on other systems where the host Linux OS is not Gentoo Linux.)

**Comment by GodloveD** [comment]
Can you please clarify this a little more.  I see that you said:
>This appears to only occur within Apptainer when the $$ PID is 1.

Does this mean you are running the above commands with the PID namespace enabled?  It is not clear to me that this is the case from reading the description.

**Comment by preney** [comment]
@GodloveD Does my reply make sense? If not, please elaborate as I do not understand where you are coming from. My description included a definition file which has `echo "spack run: shell process id is $$"` in it (i.e., it outputs the process ID which is PID 1). If you referring to something else in terms of namespaces and how things are run, please elaborate. I am using Apptainer as outlined above with nothing fancy. :-)

**Comment by preney** [comment]
To be clear, I am not using `-p`, `--pid`, etc. at all. Moreover, `apptainer build` cannot be used with such options. The above definition file and details are what was being used and such clearly illustrates the problem. Do notice the printing of `$$` in the definition files.

(If I rerun my commands for `apptainer shell` and/or `apptainer run` to use `-p`, etc. the same results are observed.)

**Comment by GodloveD** [comment]
OK, there is a bunch of stuff going on here.  In no particular order:

1. The shell that is actually being resolved here is `dash`.  Not sure how the script is handling that, but it seems to be doing so.  
2. I _think_ you are getting the error you are seeing because the script is being sourced and not executed.  So all the lines are evaluated. 
3. I think that the setup script is not doing everything it is supposed to when it is sourced from within the app environment section.  The script assumes it will be run in the same shell where you actually execute the `spack` command.  That is why it fails when you try to use it with `shell` even though it is being sourced in the environment section. 
4. It seems to work in the `run` example because you are adding the sourcing separately to the runscript that executes in the same shell as the command. 
5. Unless you have good reason to use the scif stuff I would just skip it to simplify the container.  You only seem to be installing a single app, so it doesn't really add anything except extra complication in this case. 
6. The `-C` option is the thing that is entering a new PID namespace (at runtime).  But that's a red herring.  It doesn't matter what the PID number is.  The error is the same. 
7. I suggest that you change the bottom of your def file to the following (if you want to keep using the scif stuff)
```
%appenv spack
  export SPACK_ROOT=${SCIF_APPROOT}/spack
  . ${SCIF_APPROOT}/spack/share/spack/setup-env.sh
  export PATH=${SPACK_ROOT}/bin:$PATH

%apprun spack
  exec "$@"
```
That seems to work afaik, though I have not actually tried doing any work with the container.  I would just stick the same in an `%environment` section and `%runscript` section instead. 

This boils down to the spack init scripts making assumptions that are not met within the container I think.  I know that there are a bunch of containers that have [spack pre-installed already on Docker Hub](https://hub.docker.com/u/spack) that are used by Spack itself.  I don't know where the Dockerfiles live, but they may give you a hint about the way in which the developers containerize Spack.  

Hope that helps.

**Comment by preney** [comment]
Many thanks for your response. I tried your suggestion, i.e., 
```
%appenv spack
  export SPACK_ROOT=${SCIF_APPROOT}/spack
  . ${SCIF_APPROOT}/spack/share/spack/setup-env.sh
  export PATH=${SPACK_ROOT}/bin:$PATH

%apprun spack
  exec "$@"
```
and have verified that it appears to do what it should do. Thanks, I missed doing something as simple as that. The issue with Spack using the current PID to determine the shell appears to go away. :-) 

Concerning using Spack as a SCIF... This does not necessarily need to be done but it can be useful in that it keeps Spack separate from the rest of what is installed inside the container + the container environment is not automatically enabled in any way with Spack stuff except within the Spack app. For Spack, I agree this isn't much on its own for single/simple use cases.
