### ISSUE TITLE
instance log location

### ISSUE THREAD

**Issue by denisbertini** [apptainer/apptainer#1653]
### Version of Apptainer

  apptainer version 1.1.8-1.el8

According to the apptainer documentation when  creating  instance via 
```
apptainer instance start  ...
```

instance logs are created on the user home directory 

```
/home/user/.apptainer/instances/
```
Is there a way to change this log files location to user defined directory ?

**Comment by GodloveD** [comment]
You would think based on the docs that `$APPTAINER_CONFIGDIR` would change this location, but it seems not to.  Maybe a bug.

**Comment by denisbertini** [comment]
maybe another environment variable ?

**Comment by DrDaveD** [comment]
The `APPTAINER_CONFIGDIR` option was added for 1.2.0 in #1463.

Does that work for you in 1.2?

**Comment by GodloveD** [comment]
Oh, good call @DrDaveD .  I didn't realize that was added in 1.2.  Works for me in 1.2.2.

**Comment by denisbertini** [comment]
this does not seems to solve my problem.
i have on my system
- apptainer v1.2.2

Indeed using the APPTAINER_CONFIGDIR variable the instance `logs` filed will redirected to
$APPTAINER_CONFIGDIR
But still  when creating instance something is written in the
$HOME/.apptainer i.e
```
dbertini@citpc019  ~  tree -d .apptainer
.apptainer
└── instances
    └── app
        └── citpc019
            └── dbertini
                └── ompi7

6 directories
```
how to redirect that `app` information as well to another user defined directory ?

**Comment by DrDaveD** [comment]
Yes I noticed that too and made an issue #1665.  That's a bug.  But it does move the logs for you so isn't that enough?  For now you can still do the instance list/stop/run commands without the APPTAINER_CONFIGDIR and only use it with the instance start command.

**Comment by denisbertini** [comment]
nope, because if i try to create an instance on one our compute node i got still this kind of error:
```
FATAL:   no instance found with name 8559967
FATAL:   failed to create instance log files: mkdir /u: permission denied
FATAL:   no instance found with name 8559967
FATAL:   failed to create instance log files: mkdir /u: permission denied
FATAL:   no instance found with name 8559967
FATAL:   failed to create instance log files: mkdir /u: permission denied
FATAL:   no instance found with name 8559967
FATAL:   failed to create instance log files: mkdir /u: permission denied
FATAL:   no instance found with name 8559967
FATAL:   failed to create instance log files: mkdir /u: permission denied
FATAL:   no instance found with name 8559967
```
because apptainer wants still to write on the $HOME/.apptainer/instance something .. and my $HOME is not mounted there ...

**Comment by DrDaveD** [comment]
I see.  Well that's a slightly different issue than the one in the description here, but it should be covered by #1665.  So I will close this issue and follow up there.
