### ISSUE TITLE
Inconsistent movement of instance info with APPTAINER_CONFIGDIR

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#1665]
In apptainer-1.2.2, setting APPTAINER_CONFIGDIR when running `apptainer instance start` moves the logs to be under the new directory, but the instance information still goes to `~/.apptainer/instances/app`.   As a result if APPTAINER_CONFIGDIR is set when doing `apptainer instance list` and `apptainer instance stop`, the instance is not seen.  The instance is only seen when APPTAINER_CONFIGDIR is not set.

**Comment by DrDaveD** [comment]
The problem is that for locating the instance information the code [explicitly looks up the user's home directory](https://github.com/apptainer/apptainer/blob/main/internal/pkg/instance/instance_linux.go#L104).  I'm not sure of the security reasons for that.  Hopefully @cclerget can explain.

**Comment by panda1100** [comment]
- for `instance start` there is `--home` option https://apptainer.org/docs/user/main/cli/apptainer_instance_start.html#options
- related to homeDir
  - https://github.com/apptainer/apptainer/issues/388#issuecomment-1108893405
  - https://github.com/apptainer/apptainer/issues/546#issuecomment-1189327799

On https://github.com/openucx/ucx/issues/8958, there is discussion about [instance workaround](https://ciq.com/blog/workaround-for-communication-issue-with-mpi-apps-apptainer-without-setuid/) for shared memory access with `apptainer`. When compute nodes doesn't have $HOME directory, this workaround fails.

Slurm job script

```
#!/bin/bash
#SBATCH --partition=hpc
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=40

srun --mpi=pmi2 flock.sh
srun --nodes=2 --ntasks=2 --ntasks-per-node=1 apptainer instance stop $SLURM_JOB_ID
```

Instance workaround example for environment where `ssh` is not allowed

```
#!/bin/sh
if [ `flock -x /tmp/${SLURM_JOB_ID}.lock apptainer instance list $SLURM_JOB_ID | grep $SLURM_JOB_ID | wc -l` -eq 1 ]
then
        apptainer run instance://$SLURM_JOB_ID alltoall
else
        flock -o -x /tmp/${SLURM_JOB_ID}.lock apptainer instance start hpcx-imb.sif $SLURM_JOB_ID
        apptainer run instance://$SLURM_JOB_ID alltoall
fi
```

**Comment by panda1100** [comment]
I tested with explicitly change homeDir from `/home/ysenda` to `/data/ysenda` with `export HOME=/data/ysenda` still `/home/ysenda/instances/app/xps15/ysenda/INSTANCE_NAME/INSTANCE_NAME.json` created.

**Comment by DrDaveD** [comment]
I believe that the `--home` option (at least for non-instance, action commands) only affects where the home directory is **inside**  the container, not where the configuration is stored on the host.

**Comment by DrDaveD** [comment]
It turns out that #1666 did not actually fix the problem, although I'm quite sure that it did when I was testing it during development.  I don't know what went wrong, but I reopen the issue.  There should also be an e2e test for this.
