### ISSUE TITLE
yum does not find package

### ISSUE THREAD

**Issue by gsal** [apptainer/apptainer#1673]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? 

``` bash
apptainer version 1.1.7+536-g9d77c63a2
``` 

### Expected behavior
When I do `yum search qtwebengine` from my command line, the package `qt5-qtwebengine` is found; so, I assume that I can install such package when building a container.

So, I expect `yum install` find some specific package.

### Actual behavior

When running `yum install` inside the container during build, it reports `No match for argument: qt5-qtwebengine`

### Steps to reproduce this behavior

Run `yum install -y qt5-qtwebengine` in the `%post` section during the build process of a container

### What OS/distro are you running

```bash
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### How did you install Apptainer

From  source.

**Comment by GodloveD** [comment]
What is the base OS of the container you are trying to build?  If it is Rocky 9 the `qt5-qtwebengine` appears to be in epel.  Run the following in your def file to add the correct repo. 
```
yum install -y epel-release
```

**Comment by gsal** [comment]
Aaahh, ok; yeah, that did the trick. 

Thanks.
