### ISSUE TITLE
apptainer el9 container on centos7 host and sym linked libraries not followed

### ISSUE THREAD

**Issue by desilva2185** [apptainer/apptainer#1698]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

1.2.2

### Expected behavior

What did you expect to see when you do...?

```
apptainer exec -e  -B /cvmfs:/cvmfs /cvmfs/atlas.cern.ch/repo/containers/fs/singularity/x86_64-almalinux9 /bin/bash
```
followed by
```
ldd /cvmfs/sft.cern.ch/lcg/releases/LCG_104_ATLAS_1/qt5/5.15.9/x86_64-el9-gcc13-opt/bin/uic
```

### Actual behavior

The behaviour depends on the host OS (kernel?).  
eg on centos7 host (lxplus.cern.ch)
```
[desilva@lxplus775 ~]$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core) 
[desilva@lxplus775 ~]$ apptainer --version
apptainer version 1.2.2-1.el7
[desilva@lxplus775 ~]$ apptainer exec -e  -B /cvmfs:/cvmfs /cvmfs/atlas.cern.ch/repo/containers/fs/singularity/x86_64-almalinux9 /bin/bash
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
Apptainer> ldd /cvmfs/sft.cern.ch/lcg/releases/LCG_104_ATLAS_1/qt5/5.15.9/x86_64-el9-gcc13-opt/bin/uic
	linux-vdso.so.1 (0x00007ffca7381000)
	libQt5Core.so.5 => not found
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fb2a2a23000)
	libm.so.6 => /lib64/libm.so.6 (0x00007fb2a2948000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb2a292d000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb2a2724000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb2a2c55000)
Apptainer> 
Apptainer> uname -a
Linux lxplus775.cern.ch 3.10.0-1160.95.1.el7.x86_64 #1 SMP Mon Jul 24 13:59:37 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Apptainer> 
```

but on a RHEL9 host (lxplus9.cern.ch), the same container and commands shows;

```
[desilva@lxplus905 ~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.2 (Plow)
[desilva@lxplus905 ~]$ apptainer --version
apptainer version 1.2.2-1.el9
[desilva@lxplus905 ~]$ apptainer exec -e  -B /cvmfs:/cvmfs /cvmfs/atlas.cern.ch/repo/containers/fs/singularity/x86_64-almalinux9 /bin/bash
INFO:    Environment variable SINGULARITY_TMPDIR is set, but APPTAINER_TMPDIR is preferred
Apptainer> ldd /cvmfs/sft.cern.ch/lcg/releases/LCG_104_ATLAS_1/qt5/5.15.9/x86_64-el9-gcc13-opt/bin/uic
	linux-vdso.so.1 (0x00007ffe86ba5000)
	libQt5Core.so.5 => /cvmfs/sft.cern.ch/lcg/releases/LCG_104_ATLAS_1/qt5/5.15.9/x86_64-el9-gcc13-opt/bin/../lib/libQt5Core.so.5 (0x00007f29ea600000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f29ea200000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f29ea525000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f29eabc5000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f29e9e00000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f29eaba9000)
	libicui18n.so.67 => /lib64/libicui18n.so.67 (0x00007f29e9a00000)
	libicuuc.so.67 => /lib64/libicuuc.so.67 (0x00007f29ea015000)
	libicudata.so.67 => /lib64/libicudata.so.67 (0x00007f29e7e00000)
	libpcre2-16.so.0 => /lib64/libpcre2-16.so.0 (0x00007f29ea496000)
	libzstd.so.1 => /lib64/libzstd.so.1 (0x00007f29e9d29000)
	libgthread-2.0.so.0 => /lib64/libgthread-2.0.so.0 (0x00007f29eaba2000)
	libglib-2.0.so.0 => /lib64/libglib-2.0.so.0 (0x00007f29e7cc6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f29eabeb000)
	libpcre.so.1 => /lib64/libpcre.so.1 (0x00007f29e9988000)
Apptainer> 
Apptainer> uname -a
Linux lxplus905.cern.ch 5.14.0-284.25.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jul 20 09:11:28 EDT 2023 x86_64 x86_64 x86_64 GNU/Linux
Apptainer> 
```

What actually happened? Why was it incorrect?

The are some shared libraries installed with sym links.  If the host is centos7, those sym linked libraries are not showing up in ldd.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Start the container and do ldd inside the container.  Compare the differences between running on a centos7 host vs a RHEL9 host.  The commands are:

```
apptainer exec -e  -B /cvmfs:/cvmfs /cvmfs/atlas.cern.ch/repo/containers/fs/singularity/x86_64-almalinux9 /bin/bash

ldd /cvmfs/sft.cern.ch/lcg/releases/LCG_104_ATLAS_1/qt5/5.15.9/x86_64-el9-gcc13-opt/bin/uic
```

### What OS/distro are you running

```sh
$ cat /etc/os-release

```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.

RPM - installed by CERN Central services.

**Comment by DrDaveD** [comment]
I have been communicating with @desilva2185 about this by email before and after creating this issue.  We're working to find a simpler reproducer that doesn't depend on a hard to reproduce binary on cvmfs.  In addition, he found and I confirmed that the same behavior is seen when running an el9 docker container on an el7 host.

I think that #777 may be helpful, where we found that in order to do this type of relative rpath we needed to have /proc mounted inside the container.  I am guessing the root cause might have to do with the `ld.so` of el9 assuming certain features of /proc that are not present on el7.

**Comment by DrDaveD** [comment]
I attach an attempt to reproduce, in case it's helpful to anybody else.  It was mostly written by @desilva2185, with a few modifications by me.

To try to reproduce this, on el9 download and unpack [simpleTest-src.tgz](https://github.com/apptainer/apptainer/files/12693864/simpleTest-src.tgz) and do:
```
cd simpleTest/src
./build.sh
```
Then copy all the files to el7 and run
```
apptainer exec docker://rockylinux:9 ldd $PWD/simpleTest/src/myTest
```
It seems to me to be a pretty complete emulation of the basic steps of having a relative rpath shared library, but it does not reproduce the problem; it is able to successfully find the shared library.

(I did verify that under that slightly simplified apptainer command, if cvmfs is available and bound in with `-B /cvmfs` then `ldd /cvmfs/sft.cern.ch/lcg/releases/LCG_104_ATLAS_1/qt5/5.15.9/x86_64-el9-gcc13-opt/bin/uic` still shows the problem on el7.)

**Comment by desilva2185** [comment]
Hi,

Apparently this issue was related to only 1 package (Qt5) and followed up here https://sft.its.cern.ch/jira/browse/SPI-2436.  It has been fixed in a new release (LCG_104b) with these options to build Qt5:

"Always apply -no-feature-renameat2 -no-feature-getentropy to Qt5 configuration..."

Thanks !

regards,
Asoka
