### ISSUE TITLE
Apply patch for older go in debian packaging

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#17]
Continuation of apptainer/singularity#6259.  This may be taken care of as part of #8.

**Comment by PaulCharlton** [comment]
@DrDaveD is this still relevant now than minimum golang >= 1.16 ?

**Comment by DrDaveD** [comment]
No, although I was thinking of holding it open because the debian packaging will still need to deal with the version upgrade the way rpm packaging does, if the native go isn't new enough.  I'll deal with that instead in the other issue #97.
