### ISSUE TITLE
Remote login with $oauthtoken fails in docker compatibility mode

### ISSUE THREAD

**Issue by snoato** [apptainer/apptainer#1710]
### Version of Apptainer

`apptainer version 1.2.1`

### Expected behavior

When running `apptainer remote login --username $oauthtoken docker://nvcr.io` I expect it to behave it identically to `docker login nvcr.io`, establishing a remote login s.t. a container can be downloaded. This works for both docker and podman.

### Actual behavior
```apptainer remote login --username $oauthtoken docker://nvcr.io
Generate an access token at https://cloud.apptainer.org/auth/tokens, and paste it here.
Token entered will be hidden for security.
Access Token: 
FATAL:   while verifying token: error making request to server: Get "https://cloud.apptainer.org/assets/config/config.prod.json": dial tcp: lookup cloud.apptainer.org on 137.226.36.198:53: no such host
```

### Steps to reproduce this behavior
Run the command as above

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
```

**Comment by DrDaveD** [comment]
I can't reproduce that.  What do I set `$oauthtoken` to?  If I put in gibberish it prompts for a `Password / Token` and then says
```
FATAL:   while login to docker://nvcr.io: Get "https://nvcr.io/v2/": unauthorized: authentication required
```
If I try to go to https://nvcr.io in my web browser to find info, it just says `401 Authorization Required`.

**Comment by snoato** [comment]
`$oauthtoken` is not set to anything, it is supposed to be entered like that.

**Comment by DrDaveD** [comment]
That doesn't make sense, because if it isn't set to anything the shell will just replace it with an empty string and it will be as if it isn't there.  If I try that it prompts for an access token, does it do that for you?  If so, how do I get an access token?

**Comment by DrDaveD** [comment]
Oh, I see, it gives the prompt that you show!  So I do reproduce it.  That prompt is misleading, but if you want it to give you the same results as `docker login nvcr.io` then you need to give it an actual username with the `--username` option.  I see that the first thing that `docker login nvcr.io` prompts for is `Username:`.

**Comment by snoato** [comment]
That is sadly correct, Nvidia designed the remote login to work with `$oauthtoken `as the username. Because podman and docker ask for the username in a prompt it works there with no problem. But since apptainer expects the username as a command line argument it causes the problem I assume.

**Comment by DrDaveD** [comment]
Oh, then all you need to do is escape it from the shell.  Either precede it by a backslash (`\`) or surround it by single quotes.

**Comment by snoato** [comment]
I'm... stupid. Sorry. I tried it as a string (double quotes) which didn't work so I assumed it was not escapable...

**Comment by DrDaveD** [comment]
So it was taking `docker://nvcr.io` as the username, and attempting to log in to the currently active remote endpoint, which actually is a pseudo-endpoint that doesn't really exist.  I'm afraid there's nothing that can be done to improve the message if this happens to anyone else.
