### ISSUE TITLE
Templating replaces commented out lines in definition file

### ISSUE THREAD

**Issue by dcat52** [apptainer/apptainer#1719]
### Version of Apptainer

`apptainer version 1.2.3`

### Expected behavior

Commented out code to not have templated variables replaced

### Actual behavior

Commented out lines (lines beginning with `#` are also templated. This produces erroneous-like behavior if a commented line contains template arguments that are not declared (this includes commented out args).

### Steps to reproduce this behavior

```
Bootstrap: docker
From: ubuntu:20.04

%arguments
  my_var="mydefault"
#   not_my_var="commentedoutdefault"

%post
  echo {{ my_var }}

  # echo {{ not_my_var }}
```

Build the container.

```
apptainer build test.sif undefined_arg.def 
FATAL:   While processing the definition file: while updating the definition file with build args, err: while replacing var marshaled definition struct, err: build var not_my_var is not defined through either --build-arg (--build-arg-file) or 'arguments' section
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer

Github source (tag v1.2.3)

**Comment by DrDaveD** [comment]
@JasonYangShadow is the expert on templating, but it doesn't surprise me that comments don't hide templates.  The same thing happens with other preprocessing systems, like for example the `%define` in rpm SPEC files.  There you need to put `%%` inside a comment when you really want a macro to have no effect.

**Comment by JasonYangShadow** [comment]
@dcat52 cc @DrDaveD 
Sincerely thanks for reporting such issue.
Right now, template feature won't distinguish whether the line is commented or not, it'll scan the entire file and replace `{{ var }}` with the value defined in `%argument`, but I think we can add such comment support, i.e., ignoring the commented line during scanning.

I will take care of this, and update here when there are any progresses. Thanks!

**Comment by dcat52** [comment]
Thank you @JasonYangShadow and thanks for all your work on this feature!

I can fully understand if that is expected behavior (now that I think of it, I am not sure on official jinja spec if that is the ideal to follow). At minimum we may want to document these or use as further justification for more verbose of an error. 

I wonder if detecting commented out args and providing a `warn` may be a useful feature.  From a generic-ness perspective, it seems the `arguments` section has the most stable runtime since it is used for populating variables and then cleared (at least my understanding).

This may also be a useful to consider:
```
abc=hi # post line comment
```

**Comment by JasonYangShadow** [comment]
@dcat52 
I have created a PR for this issue. Template supports skipping comment line started with `#␣`. It'll erase the comment lines during template processing.

**Comment by DrDaveD** [comment]
> @JasonYangShadow is the expert on templating, but it doesn't surprise me that comments don't hide templates. The same thing happens with other preprocessing systems, like for example the `%define` in rpm SPEC files. There you need to put `%%` inside a comment when you really want a macro to have no effect.

When I made that comment I was thinking in terms of expanding variables.  I agree that people would expect to be able to comment out a variable definition.

**Comment by DrDaveD** [comment]
> > @JasonYangShadow is the expert on templating, but it doesn't surprise me that comments don't hide templates. The same thing happens with other preprocessing systems, like for example the `%define` in rpm SPEC files. There you need to put `%%` inside a comment when you really want a macro to have no effect.
> 
> When I made that comment I was thinking in terms of expanding variables. I agree that people would expect to be able to comment out a variable definition.

Wait, I had it right in the first place.  The error message in the description indicated that the variable definition was indeed commented out, it was just the variable expansion that was still happening.  I think that could go either way.
