### ISSUE TITLE
plugin compile fails while copying with tar

### ISSUE THREAD

**Issue by bsteinb** [apptainer/apptainer#173]
### Version of Apptainer:

`1.0.0-rc.1`

### Expected behavior

Plugin compiles successfully.

### Actual behavior

The plugin compilation aborts with the following message:

```
FATAL:   Plugin compile failed with error: while copying with tar: invalid symlink "/tmp/plugin-540310522/src/apptainer_source" -> "../../.."
```

### Steps to reproduce this behavior

From inside the extracted `1.0.0-rc.1` tarball:

```
$ ./mconfig
$ make -C builddir old_config=
$ make -C builddir install man
$ apptainer plugin compile examples/plugins
FATAL:   Plugin compile failed with error: while copying with tar: invalid symlink "/tmp/plugin-211074422/src/cli-plugin/apptainer_source" -> "../../.."
```

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.5:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

What else? 😉 

### How did you install Apptainer

From source, see above.

**Comment by DrDaveD** [comment]
Thanks for the bug report.

Removing the `examples/plugins/*/apptainer_source` symlinks as is done in #183 fixes it for me if I do `apptainer plugin compile` on each individual example plugin (as opposed to their parent directory as in your example).  @bsteinb Does that work for you?

**Comment by bsteinb** [comment]
> (as opposed to their parent directory as in your example)

Oops, no idea what happened there.

> Does that work for you?

Yes, I confirm that this fixes the issue.

Thanks for also opening #184. We have had issues with compiling plugins in a few of the recent releases (of singularity).
