### ISSUE TITLE
"newgidmap: Target <pid> is owned by a different user" error when building image with fakeroot

### ISSUE THREAD

**Issue by vbeliveau** [apptainer/apptainer#1751]
### Version of Apptainer

`apptainer version 1.1.6-bp155.2.18`

### Expected behavior

When building a container with `--fakeroot`,  the target for `newgidmap` should be in the range `bound + 65536`, where bound is specified in `/etc/subgid`.

### Actual behavior

The target for `newgidmap` is less than the bound specified in `/etc/subgid` and creates an error
```
> cat /etc/subuid 
4290:4294836224:65536
> cat /etc/subgid
4290:4294836224:65536
> apptainer build --fakeroot <dest> <def file>
newgidmap: Target 8153 is owned by a different user: uid:4290 pw_uid:4290 st_uid:4290, gid:1107 pw_gid:100 st_gid:1107
ERROR  : 'newgidmap' execution failed. Check that 'newgidmap' is setuid root or has setcap cap_setgid+eip.
ERROR  : Error while waiting event for user namespace mappings: Success
```

### What OS/distro are you running

```
NAME="openSUSE Leap"
VERSION="15.5"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.5"
PRETTY_NAME="openSUSE Leap 15.5"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.5"
```

**Comment by GodloveD** [comment]
What does the following command turn up?
```
$ ls -lh $(which newgidmap)
```

**Comment by vbeliveau** [comment]
Yes permissions look fine.
When I tried again in debug mode I got the following
```
DEBUG   [U=4290,P=11124]   set_mappings_external()       Executing '/usr/bin/newgidmap 11145 0 1107 1 1 4294836224 65536 >/dev/null'newgidmap: Target 11145 is owned by a different user: uid:4290 pw_uid:4290 st_uid:4290, gid:1107 pw_gid:100 st_gid:1107
ERROR   [U=4290,P=11124]   set_mappings_external()       'newgidmap' execution failed. Check that 'newgidmap' is setuid root or has setcap cap_setgid+eip.
ERROR   [U=65534,P=1]      init()                        Error while waiting event for user namespace mappings: Success
```
and from the `newgidmap` documentation, we've got
```
newgidmap pid gid lowergid count [gid lowergid count [ ... ]]
```
So, contrary to what I thought, it seems that it's not the target `gid` provided by `newgidmap` that is out of range, but that the input `pid` to `newgidmap` (I'm assuming here that this corresponds to the newly started apptainer process) belongs to another user? There must be something obvious I'm missing here.

**Comment by DrDaveD** [comment]
Yes @GodloveD your should be able to see extra capabilities on your commands:
```
$ getcap /usr/bin/newuidmap
/usr/bin/newuidmap = cap_setuid+eip
$ getcap /usr/bin/newgidmap
/usr/bin/newgidmap = cap_setgid+eip
```
but setuid root should work on them as well.

Ah, I see the problem.  The /etc/gidmap entry has to start with 1107 instead of 4290. 

It would be nice if the error message were more descriptive but I'm not sure how difficult that will be.

**Comment by vbeliveau** [comment]
> The /etc/gidmap entry has to start with 1107 instead of 4290.

@DrDaveD, I'm not exactly sure why you'd think that the entry should start with 1107 instead of 4290. Can you explain why you think so?

According to the user namespace documentation ([https://apptainer.org/docs/admin/1.0/user_namespace.html#user-namespace-requirements](url) the entry in `/etc/subgid` should look like
```
foo:100000:65536
```

where `foo` is the username, `100000` is the start of the UID range that can be used by foo in a user namespace uid mapping, and `65536` number of UIDs available for mapping. Given that my `uid` is 4290, then the entry `4290:4294836224:65536` looks fine to me. I also doubled checked with our sysadmin and he used `apptainer config fakeroot --add <user>` to set up the fakeroot user. So either there is a bug in that or the problem is elsewhere.

Looking again at the debug output above, the issue seems to be that with the command `newgidmap 11145 0 1107 1 1 4294836224 65536`, apptainer is asking for a new `gid` for the process with `pid=11145` , but that process doesn't belong to my user, i.e., `4290`, which is what is causing the error `Target 11145 is owned by a different user: uid:4290`.

**Comment by DrDaveD** [comment]
You're right, I'm sorry, I looked at it too quickly.  I had exactly the same settings on my test machine for the second and third items, with my own user id in the first column in both cases.

I think your analysis is correct, that newgid's complaint is that the pid doesn't belong to you.  Can you find out anything about the process whose pid it is getting the error on?  Is it somehow related but not yours?  I don't have an opensuse leap system, but I tried the opensuse/leap container under docker (on centos7) and apptainer did not fail in this scenario.  It seems like the error message from newgidmap is printing out debug information indicating that it is indeed your uid.  Maybe I need to create an opensuse vagrant VM.

**Comment by vbeliveau** [comment]
Unfortunately, there is not exact information on what that erroneous process is. Below is a longer snippet of the verbose output of the build command, also outputing the pid of the apptainer process. In the example below, apptainer starts with `pid=53225` and the problematic process has `pid=53250 `. My guess would be that it is the `master process` which is spawned just before the error occurs
```
VERBOSE [U=4290,P=53225]   init()                        Spawn master process
```

(slightly) Truncated debug output:
```
> apptainer --debug build --fakeroot test.sif test.def & ps -a | grep apptainer
[1] 53225
53225 pts/17   00:00:00 apptainer
...
VERBOSE [U=4290,P=53225]   init()                        Starter initialization
VERBOSE [U=4290,P=53225]   is_suid()                     Check if we are running as setuid
DEBUG   [U=4290,P=53225]   read_engine_config()          Read engine configuration
DEBUG   [U=4290,P=53225]   init()                        Wait completion of stage1
DEBUG   [U=4290,P=53244]   set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=4290,P=53244]   init()                        Spawn stage 1
DEBUG   [U=4290,P=53244]   func1()                       Install prefix is /usr
DEBUG   [U=4290,P=53244]   startup()                     fakeroot runtime engine selected
VERBOSE [U=4290,P=53244]   startup()                     Execute stage 1
DEBUG   [U=4290,P=53244]   StageOne()                    Entering stage 1
DEBUG   [U=4290,P=53244]   SetBinaryPath()               Setting binary path to /usr/lib/apptainer/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=4290,P=53244]   SetBinaryPath()               Using that path for all binaries
VERBOSE [U=4290,P=53244]   PrepareConfig()               Fakeroot requested with unprivileged workflow, fallback to newuidmap/newgidmap
DEBUG   [U=4290,P=53244]   PrepareConfig()               Search for newuidmap binary
DEBUG   [U=4290,P=53244]   findOnPath()                  Found "newuidmap" at "/usr/bin/newuidmap"
DEBUG   [U=4290,P=53244]   PrepareConfig()               Search for newgidmap binary
DEBUG   [U=4290,P=53244]   findOnPath()                  Found "newgidmap" at "/usr/bin/newgidmap"
VERBOSE [U=4290,P=53225]   wait_child()                  stage 1 exited with status 0
DEBUG   [U=4290,P=53225]   cleanup_fd()                  Close file descriptor 4
DEBUG   [U=4290,P=53225]   cleanup_fd()                  Close file descriptor 5
DEBUG   [U=4290,P=53225]   cleanup_fd()                  Close file descriptor 6
DEBUG   [U=4290,P=53225]   cleanup_fd()                  Close file descriptor 7
DEBUG   [U=4290,P=53225]   init()                        Set child signal mask
DEBUG   [U=4290,P=53225]   init()                        Create socketpair for master communication channel
DEBUG   [U=4290,P=53225]   init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=4290,P=53225]   user_namespace_init()         Create user namespace
VERBOSE [U=4290,P=53225]   pid_namespace_init()          Create pid namespace
VERBOSE [U=4290,P=53225]   init()                        Spawn master process
DEBUG   [U=4290,P=53225]   set_mappings_external()       Executing '/usr/bin/newgidmap 53250 0 1107 1 1 4294836224 65536 >/dev/null'newgidmap: Target 53250 is owned by a different user: uid:4290 pw_uid:4290 st_uid:4290, gid:1107 pw_gid:100 st_gid:1107
ERROR   [U=4290,P=53225]   set_mappings_external()       'newgidmap' execution failed. Check that 'newgidmap' is setuid root or has setcap cap_setgid+eip.
ERROR   [U=65534,P=1]      init()                        Error while waiting event for user namespace mappings: Success
```

**Comment by DrDaveD** [comment]
On my system the process id that is passed to newgidmap is the top level apptainer process.  Try making a shell script that just does `echo $$` and then `exec apptainer ...` so you get to see the process id of the top level process.  Alternatively just running it in the background in bash should show you the process id.

I installed an opensuse Leap system with vagrant using this Vagrantfile
```
Vagrant.configure("2") do |config|
  config.vm.box = "opensuse/Leap-15.3.x86_64"
end
```
and then installed apptainer-1.2.3 by doing
```
sudo zypper addrepo https://mirrorcache-us.opensuse.org/repositories/network:/cluster/openSUSE_Leap_15.3/network:cluster.repo
sudo zypper refresh
sudo zypper install apptainer
```
and it did not reproduce the problem.  So it must be something more specific to your installation, and we'll need you to continue to dig further to find out more.

**Comment by DrDaveD** [comment]
Oh, wait, I see you already have run it in the background and it showed a different process id.  So try using `strace -f`.

**Comment by DrDaveD** [comment]
Here's what mine shows (on centos7):
```
8183  write(2, "VERBOSE [U=3382,P=8183]    user_namespace_init()         Create user namespace\n", 79) = 79
8183  geteuid()                         = 3382
8183  geteuid()                         = 3382
8183  write(2, "VERBOSE [U=3382,P=8183]    pid_namespace_init()          Create pid namespace\n", 78) = 78
8183  rt_sigprocmask(SIG_BLOCK, NULL, [CHLD], 8) = 0
8183  clone(child_stack=0x56179c44c710, flags=CLONE_NEWUSER|CLONE_NEWPID|SIGCHLD) = 8197
8197  getpid( <unfinished ...>
8183  geteuid( <unfinished ...>
8197  <... getpid resumed>)             = 1
8183  <... geteuid resumed>)            = 3382
8183  geteuid( <unfinished ...>
8197  rt_sigprocmask(SIG_SETMASK, [CHLD],  <unfinished ...>
8183  <... geteuid resumed>)            = 3382
8197  <... rt_sigprocmask resumed>NULL, 8) = 0
8197  close(3 <unfinished ...>
8183  write(2, "VERBOSE [U=3382,P=8183]    init()                        Spawn master process\n", 78 <unfinished ...>
8197  <... close resumed>)              = 0
8197  read(4,  <unfinished ...>
8183  <... write resumed>)              = 78
8183  close(4)                          = 0
8183  open(".", O_RDONLY|O_DIRECTORY)   = 4
8183  chdir("/proc/8197")               = 0
8183  getpgid(0)                        = 8180
8183  getpgid(8197)                     = 8180
8183  geteuid()                         = 3382
8183  geteuid()                         = 3382
8183  write(2, "DEBUG   [U=3382,P=8183]    set_mappings_external()       Executing '/usr/bin/newgidmap 8197 0 9767 1 1 4294836224 65536 >/dev/null'", 131) = 131
```
So it is the master process.  But somehow newgidmap thinks it is not owned by the same user id.  Maybe you can see some system call failing along the way.  If you can't spot it, attach the whole strace file here please.  The newgidmap should fail for a different reason, because you can't strace a privileged binary, but it will show what came before it.

**Comment by vbeliveau** [comment]
@DrDaveD, thanks a lot for the help. Here's the full strace: [apptainer-trace.txt](https://github.com/apptainer/apptainer/files/13161746/apptainer-trace.txt). I've looked through it, but I don't have much experience interpreting this kind of output. Hopefully you can make heads or tails of it.

**Comment by DrDaveD** [comment]
I found one interesting piece of information from your trace, that soon before the failure there's a successful read of from `/var/run/samba/winbindd/pipe` including information that has your account name `vbeliveau`.  I'm not sure if this is the same problem, but there was a fix in #1368 related to windbindd that was put into apptainer 1.2.0.  Please try a 1.2.x version of apptainer.

**Comment by vbeliveau** [comment]
@DrDaveD Unfortunately the latest apptainer binaries for openSuse Leap 15.5 is version 1.1.6 and our sysadmin is not keen on pushing this further. So, until a newer version is released, there is not much I can do. Thanks for the help looking into this., 'll update this issue if we ever get an update.

**Comment by DrDaveD** [comment]
You could try a private install with [install-unprivileged.sh](https://apptainer.org/docs/admin/main/installation.html#install-unprivileged-from-pre-built-binaries).

**Comment by vbeliveau** [comment]
Ooh, that is actually very nice :) I didn't know a unprivileged install in that way was possible at all.

When I use those binaries, I can get beyond the original issue! Unfortunately, I soon after run into the following:

```
> apptainer build --fakeroot test.sif test.def
INFO:    Starting build...
Getting image source signatures
Copying blob a378f10b3218 done  
Copying config a74eaad96a done  
Writing manifest to image destination
Storing signatures
FATAL:   While performing build: packer failed to pack: while unpacking tmpfs: error unpacking rootfs: mkdir rootfs: mkdir vbeliveau/apptainer-tmp/build-temp-2231290146/rootfs: no such file or directory
```

Looking a bit closer at the last section of the strace, I seem to run into permission issues with newgidmap:
```
[pid 57675] openat(3, "gid_map", O_WRONLY) = 7
[pid 57675] write(7, "0 100 1\n1 4294836224 65536\n", 27) = -1 EPERM (Operation not permitted)
[pid 57675] write(2, "newgidmap: write to gid_map fail"..., 60newgidmap: write to gid_map failed: Operation not permitted
) = 60
[pid 57675] close(5)                    = 0
[pid 57675] exit_group(1)               = ?
[pid 57675] +++ exited with 1 +++
[pid 57674] <... wait4 resumed>[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 57675
[pid 57674] rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fac7482bdc0}, {sa_handler=0x555acf4b8d10, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fac7482bdc0}, 8) = 0
[pid 57674] ioctl(2, TIOCGWINSZ, {ws_row=30, ws_col=151, ws_xpixel=1513, ws_ypixel=641}) = 0
[pid 57674] ioctl(1, TCGETS, 0x7ffd380481e0) = -1 ENOTTY (Inappropriate ioctl for device)
[pid 57674] getuid()                    = 4290
[pid 57674] geteuid()                   = 4290
[pid 57674] getgid()                    = 100
[pid 57674] getegid()                   = 100
[pid 57674] getuid()                    = 4290
[pid 57674] geteuid()                   = 4290
[pid 57674] getuid()                    = 4290
[pid 57674] geteuid()                   = 4290
[pid 57674] getgid()                    = 100
[pid 57674] getegid()                   = 100
[pid 57674] getuid()                    = 4290
[pid 57674] geteuid()                   = 4290
[pid 57674] stat("/etc/terminfo", {st_mode=S_IFDIR|0755, st_size=6, ...}) = 0
[pid 57674] stat("/usr/share/terminfo", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 57674] getuid()                    = 4290
[pid 57674] setfsuid(4290)              = 4290
[pid 57674] getgid()                    = 100
[pid 57674] setfsgid(100)               = 100
[pid 57674] access("/etc/terminfo/d/dumb", R_OK) = -1 ENOENT (No such file or directory)
[pid 57674] geteuid()                   = 4290
[pid 57674] setfsuid(4290)              = 4290
[pid 57674] getegid()                   = 100
[pid 57674] setfsgid(100)               = 100
[pid 57674] getuid()                    = 4290
[pid 57674] setfsuid(4290)              = 4290
[pid 57674] getgid()                    = 100
[pid 57674] setfsgid(100)               = 100
[pid 57674] access("/usr/share/terminfo/d/dumb", R_OK) = 0
[pid 57674] openat(AT_FDCWD, "/usr/share/terminfo/d/dumb", O_RDONLY) = 5
[pid 57674] fstat(5, {st_mode=S_IFREG|0644, st_size=308, ...}) = 0
[pid 57674] read(5, "\32\1\30\0\2\0\1\0\202\0\10\0dumb|80-column dumb "..., 32768) = 308
[pid 57674] read(5, "", 28672)          = 0
[pid 57674] close(5)                    = 0
[pid 57674] geteuid()                   = 4290
[pid 57674] setfsuid(4290)              = 4290
[pid 57674] getegid()                   = 100
[pid 57674] setfsgid(100)               = 100
[pid 57674] ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 57674] ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 57674] ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 57674] ioctl(2, TCGETS, {B38400 opost isig icanon echo ...}) = 0
[pid 57674] ioctl(2, TIOCGWINSZ, {ws_row=30, ws_col=151, ws_xpixel=1513, ws_ypixel=641}) = 0
[pid 57674] ioctl(0, TIOCGWINSZ, {ws_row=30, ws_col=151, ws_xpixel=1513, ws_ypixel=641}) = 0
[pid 57674] rt_sigprocmask(SIG_SETMASK, [CHLD], NULL, 8) = 0
[pid 57674] rt_sigprocmask(SIG_BLOCK, [CHLD], [CHLD], 8) = 0
[pid 57674] rt_sigprocmask(SIG_SETMASK, [CHLD], NULL, 8) = 0
[pid 57674] close(3)                    = 0
[pid 57674] exit_group(1)               = ?
[pid 57674] +++ exited with 1 +++
[pid 57655] <... wait4 resumed>[{WIFEXITED(s) && WEXITSTATUS(s) == 1}], 0, NULL) = 57674
[pid 57655] rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fdf8edbddc0}, NULL, 8) = 0
[pid 57655] rt_sigaction(SIGQUIT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7fdf8edbddc0}, NULL, 8) = 0
[pid 57655] rt_sigprocmask(SIG_SETMASK, [CHLD], NULL, 8) = 0
[pid 57655] geteuid()                   = 4290
[pid 57655] getpid()                    = 57655
[pid 57655] getpid()                    = 57655
[pid 57655] geteuid()                   = 4290
[pid 57655] write(2, "\33[91mERROR   [U=4290,P=57655]   "..., 164ERROR   [U=4290,P=57655]   set_mappings_external()       'newgidmap' execution failed. Check that 'newgidmap' is setuid root or has setcap cap_setgid+eip.
) = 164
[pid 57655] exit_group(1)               = ?
[pid 57655] +++ exited with 1 +++
<... read resumed>"", 1)                = 0
geteuid()                               = 65534
getpid()                                = 1
getpid()                                = 1
geteuid()                               = 65534
write(2, "\33[91mERROR   [U=65534,P=1]      "..., 139ERROR   [U=65534,P=1]      init()                        Error while waiting event for user namespace mappings: no event received
) = 139
exit_group(1)                           = ?
+++ exited with 1 +++
```
Not sure if this is related to the original error or not. @DrDaveD , should I open a new issue or reopen this one?

**Comment by DrDaveD** [comment]
The operation  not permitted error is probably because of the strace itself, because newgidmap is a privileged process and you're not allowed to strace that.

The mkdir problem may be due to the underlying filesystem.  Does it work if you try it in a local filesystem such as /tmp?  

You can also try with `--ignore-subuid` in which case apptainer will fall back to using the fakeroot command instead of newgidmap/newuidmap, although that doesn't really tell us if the original problem was fixed or not.

**Comment by vbeliveau** [comment]
> The mkdir problem may be due to the underlying filesystem. Does it work if you try it in a local filesystem such as /tmp?

Unfortunately, building in /tmp didn't work either.

> You can also try with `--ignore-subuid` in which case apptainer will fall back to using the fakeroot command instead of newgidmap/newuidmap, although that doesn't really tell us if the original problem was fixed or not.

Using `--ignore-subuid` worked like a charm in version `1.2.4-1.el7` that I got from [install-unprivileged.sh](https://apptainer.org/docs/admin/main/installation.html#install-unprivileged-from-pre-built-binaries). I've also tried the older version `1.1.6-bp155.2.18` that is installed on our system, but the build ran into some issues when trying to use a command requiring root privileges (i.e., apt-get) - somehow it couldn't find fakeroot?

```
INFO:    fakeroot command not found
...
+ apt-get update -q
E: setgroups 65534 failed - setgroups (1: Operation not permitted)
E: setegid 65534 failed - setegid (22: Invalid argument)
E: seteuid 42 failed - seteuid (22: Invalid argument)
E: setgroups 0 failed - setgroups (1: Operation not permitted)
Reading package lists...
W: chown to _apt:root of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (22: Invalid argument)
W: chown to _apt:root of directory /var/lib/apt/lists/auxfiles failed - SetupAPTPartialDirectory (22: Invalid argument)
E: setgroups 65534 failed - setgroups (1: Operation not permitted)
E: setegid 65534 failed - setegid (22: Invalid argument)
E: seteuid 42 failed - seteuid (22: Invalid argument)
E: setgroups 0 failed - setgroups (1: Operation not permitted)
E: Method gave invalid 400 URI Failure message: Failed to setgroups - setgroups (1: Operation not permitted)
E: Method http has died unexpectedly!
E: Sub-process http returned an error code (112)
```
At least now I have a viable work around! Thanks!

**Comment by DrDaveD** [comment]
I don't know how the OpenSUSE package is done so yes apparently it didn't include fakeroot.  The install-unprivileged.sh script installs its own copy of fakeroot from el7, which works everywhere.  

It's good you have a workaround but I'm still concerned about the mkdir problem, so please create a new github issue for that.
