### ISSUE TITLE
go-generate and go-test need to be recreated if any of their template inputs change

### ISSUE THREAD

**Issue by dcat52** [apptainer/apptainer#176]
### Version of Apptainer:
What version of Apptainer are you using? Run:
```
$ apptainer --version
apptainer version 0.1.1+125-g0b671cb16-dirty
```

### Expected behavior
Commands:
```
./mconfig
cd buiddir
make
```
Expected to run go as found in previous step.

### Actual behavior
First command finds go correctly. The make command expects go to be located in `/usr/bin/go`

### Steps to reproduce this behavior
Install go following instructions here: https://go.dev/doc/install
Install apptainer:
```
./mconfig
cd buiddir
make
```

### What OS/distro are you running
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

### How did you install Apptainer
source

**Comment by DrDaveD** [comment]
What is the output you get from mconfig?  What version of go did you install?  Did you follow the instructions in apptainer INSTALL.md?

**Comment by dcat52** [comment]
I re-cloned the repo. I believe what appeared to happen is that there were 2 versions of go on the system at the time I ran `./mconfig`. Later one was removed and one (the one mconfig found).  I re-built apptainer and mconfig found go successfully (the 2nd one) but it did not regenerate the file `scripts/go-generate` which still referenced the old go location and so running make which triggers that file, could not find go.

Perhaps the file should be regenerated?

**Comment by DrDaveD** [comment]
If go is moved you need to re-run mconfig.  Did you not do that?  If you did, can you give an exact series of steps to reproduce the problem?

**Comment by dcat52** [comment]
Yes I re-ran mconfig. Here are steps that should be reproducible. Assuming a fresh apptainer repository and no go installed.
```bash
wget https://go.dev/dl/go1.17.6.linux-amd64.tar.gz
sudo rm -rf /usr/local/go && sudo tar -C /usr/local -xzf go1.17.6.linux-amd64.tar.gz
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
source ~/.bashrc

cd path/to/apptainer
./mconfig
cd builddir
make
sudo make install

sudo mv /usr/local/go /usr/local/go2
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
source ~/.bashrc
cd path/to/apptainer
./mconfig
cd builddir
make
```

The last command errors and will output:
```
 GEN GO DEP /home/davis/Documents/Programs/apptainer/builddir/starter.d
 GEN GO DEP /home/davis/Documents/Programs/apptainer/builddir/singularity.d
/home/davis/Documents/Programs/apptainer/scripts/go-generate: 9: exec: /usr/local/go/bin/go: not found
make: *** [Makefile:160: /home/davis/Documents/Programs/apptainer/internal/pkg/buildcfg/config.go] Error 127
```

The install instructions are found here: https://go.dev/doc/install

**Comment by DrDaveD** [comment]
Ok, thanks for the details, now I understand.  This isn't specific to Ubuntu or to apptainer, but it is an issue that singularity has had for a long time in that `scripts/go-generate` and `scripts/go-test` are generated by created from `.in` templates only if they are missing.  A workaround is to remove those two files.  I think a decent solution is probably to generate them into the builddir directory instead of the scripts directory and assume that people will remove the builddir directory if they are starting from scratch (which you also didn't do).

**Comment by DrDaveD** [comment]
Instead, #180 recreates those two scripts before they are used if mconfig has been run since the last time they were created.
