### ISSUE TITLE
a little bit too excited about the coming release (1.2.5)

### ISSUE THREAD

**Issue by arnaudbore** [apptainer/apptainer#1778]
Hi @DrDaveD ,

Can we expect a new release of apptainer (1.2.5) in the coming days ?
The NVIDIA bug fix will greatly help us move forward with a lot of our projects.

Thank you in advance for all the awesome work you doing :tada:

**Comment by DrDaveD** [comment]
I wasn't expecting to do a release extremely soon since there doesn't seem to be extremely urgent fixes yet.  Meanwhile it should be easy enough to add that extra line to /etc/apptainer/nvliblist.conf, right?

**Comment by arnaudbore** [comment]
Locally I would agree but since we are using different servers HCP on compute canada and to say the least there are not really keen on modifying anything and it would really help if there were a proper release with this bug fixed.

**Comment by DrDaveD** [comment]
Do you have access to /cvmfs/oasis.opensciencegrid.org?  I have edited the configuration of the apptainer-1.2.4 release at /cvmfs/oasis.opensciencegrid.org/mis/apptainer/bin/apptainer to include this.

**Comment by bartoldeman** [comment]
Just to let you know as the person who installs Apptainer on the computecanada (now known as Digitial Research Alliance of Canada) cvmfs, this is such a trivial configuration file change, that I've modified the installations in place, and they'll be active in a few minutes.

**Comment by arnaudbore** [comment]
Thank you very much @DrDaveD
Thank you @bartoldeman to set up the quick fix.
