### ISSUE TITLE
Incompatibility between cgroups v2 and hidepid

### ISSUE THREAD

**Issue by kpedro88** [apptainer/apptainer#1779]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.2.4-1.el9
```

### Expected behavior

This command should be successful:
```
apptainer instance start docker://centos:7 tstins
```

### Actual behavior

The command fails and the following error message is displayed:
```
INFO:    Using cached SIF image
ERROR:   container cleanup failed: no instance found with name tstins
FATAL:   container creation failed: while applying cgroups config: while creating cgroup manager: failed to connect to dbus (hint: for rootless containers, maybe you need to install dbus-user-session package, see https://github.com/opencontainers/runc/blob/master/docs/cgroup-v2.md): could not execute `busctl --user --no-pager status` (output: "Failed to get credentials: Operation not permitted\nBusAddress=unix:path=/run/user/51171/bus\nBusScope=user\nBusID=9427da0aa93b547eb91b7c5ce1c2ca11\n"): exit status 1

FATAL:   while executing starter: failed to start instance: while running /usr/libexec/apptainer/bin/starter: exit status 255
```

### Steps to reproduce this behavior

Run the above command on RHEL9 with hidepid enabled (for example, by `sudo mount /proc -o remount,hidepid=1`).

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.2 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.2 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### How did you install Apptainer

```
$ rpm -qa | grep apptainer
apptainer-1.2.4-1.el9.x86_64
```

**Comment by kpedro88** [comment]
System administrators for these rhel9 machines found a related issue in opencontainers, which is where the call to `busctl` actually happens: https://github.com/opencontainers/runc/issues/3124. The issue is not resolved yet.

One potential workaround from Apptainer's side would be to detect that hidepid is enabled and fall back to cgroups v1.

**Comment by DrDaveD** [comment]
It wouldn't fall back to cgroups v1 because that requires root access.  It just wouldn't use cgroups for instances at all, as we do in a few other cases.  There is already [code](https://github.com/apptainer/apptainer/blob/release-1.2/internal/pkg/runtime/launch/launcher_linux.go#L1243) that checks for the `hidepid` mount option on /proc when starting instances, but for a different case.
