### ISSUE TITLE
Support for --nohttps/--no-https when used with oras:// 

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#18]
Continuation of apptainer/singularity#6302

**Comment by colorzzr** [comment]
Hi all!

I am also wandering if `-nohttps` will be added into `push` command.

Thanks!

**Comment by JasonYangShadow** [comment]
I will take care of this issue and will update here when any progress is made. 
Thanks for the comment!

**Comment by JasonYangShadow** [comment]
PR is created here:
https://github.com/apptainer/apptainer/pull/565

**Comment by cclerget** [comment]
Closed by #565
