### ISSUE TITLE
shared_mount_namespace_init() Failed to set mount propagation: Permission denied

### ISSUE THREAD

**Issue by stebo85** [apptainer/apptainer#1806]
Dear Apptainer team,

Do you have any hint on how we could debug this problem? We are running Apptainer in a Kubernetes pod. Could this be related to missing capabilities in this Pod and how could we find out what is needed?

### Version of Apptainer

`apptainer version 1.2.4`

### Expected behavior

Container shell starts up.

### Actual behavior

INFO    [U=1000,P=1730]    func1()                       Environment variable SINGULARITY_BINDPATH is set, but APPTAINER_BINDPATH is preferred
DEBUG   [U=1000,P=1730]    setValue()                    Updated flag 'bind' value to: ["/data,/neurodesktop-storage,/tmp,/cvmfs,/home/jovyan:/home/matlab/.matlab/R2022a_licenses,/home/jovyan:/opt/matlab/R2022a/licenses"]
DEBUG   [U=1000,P=1730]    persistentPreRun()            Apptainer version: 1.2.4
DEBUG   [U=1000,P=1730]    persistentPreRun()            Parsing configuration file /etc/apptainer/apptainer.conf
DEBUG   [U=1000,P=1730]    SetBinaryPath()               Setting binary path to /usr/libexec/apptainer/bin:/opt/conda/bin:/opt/conda/condabin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/jovyan/.local/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=1000,P=1730]    SetBinaryPath()               Using that path for all binaries
DEBUG   [U=1000,P=1730]    handleConfDir()               /home/jovyan/.apptainer already exists. Not creating.
DEBUG   [U=1000,P=1730]    setUmask()                    Saving umask 0022 for propagation into container
VERBOSE [U=1000,P=1730]    useSuid()                     Unprivileged installation: using user namespace
DEBUG   [U=1000,P=1730]    checkEncryptionKey()          Checking for encrypted system partition
DEBUG   [U=1000,P=1730]    Init()                        Image format detection
DEBUG   [U=1000,P=1730]    Init()                        Check for sandbox image format
DEBUG   [U=1000,P=1730]    Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=1000,P=1730]    Init()                        Check for sif image format
DEBUG   [U=1000,P=1730]    Init()                        sif format initializer returned: SIF magic not found
DEBUG   [U=1000,P=1730]    Init()                        Check for squashfs image format
DEBUG   [U=1000,P=1730]    Init()                        squashfs image format detected
DEBUG   [U=1000,P=1730]    setCgroups()                  Recording rootless XDG_RUNTIME_DIR / DBUS_SESSION_BUS_ADDRESS
INFO    [U=1000,P=1730]    warnDeprecatedEnvUsage()      Environment variable SINGULARITYENV_SUBJECTS_DIR is set, but APPTAINERENV_SUBJECTS_DIR is preferred
VERBOSE [U=1000,P=1730]    setKeyIfNotAlreadyOverridden()Forwarding SINGULARITYENV_SUBJECTS_DIR as SUBJECTS_DIR environment variable
DEBUG   [U=1000,P=1730]    SetContainerEnv()             Forwarding TERM environment variable
VERBOSE [U=1000,P=1730]    SetContainerEnv()             Not forwarding SINGULARITY_BINDPATH environment variable
VERBOSE [U=1000,P=1730]    SetContainerEnv()             Not forwarding APPTAINER_DEBUG environment variable
VERBOSE [U=1000,P=1730]    SetContainerEnv()             Setting HOME=/home/jovyan
VERBOSE [U=1000,P=1730]    SetContainerEnv()             Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DEBUG   [U=1000,P=1730]    findOnPath()                  Found "squashfuse_ll" at "/usr/libexec/apptainer/bin/squashfuse_ll"
DEBUG   [U=1000,P=1730]    findOnPath()                  Found "fuse2fs" at "/usr/bin/fuse2fs"
DEBUG   [U=1000,P=1730]    findOnPath()                  Found "fuse-overlayfs" at "/usr/bin/fuse-overlayfs"
DEBUG   [U=1000,P=1730]    findOnPath()                  Found "gocryptfs" at "/usr/libexec/apptainer/bin/gocryptfs"
DEBUG   [U=1000,P=1730]    InitImageDrivers()            squashfuse_ll supports -o uid
DEBUG   [U=1000,P=1730]    InitImageDrivers()            Setting ImageDriver to fuseapps
DEBUG   [U=1000,P=1730]    init()                        Use starter binary /usr/libexec/apptainer/bin/starter
VERBOSE [U=1000,P=1730]    print()                       Set messagelevel to: 5
VERBOSE [U=1000,P=1730]    init()                        Starter initialization
VERBOSE [U=1000,P=1730]    is_suid()                     Check if we are running as setuid: 0
DEBUG   [U=1000,P=1730]    read_engine_config()          Read engine configuration
DEBUG   [U=1000,P=1730]    init()                        Wait completion of stage1
DEBUG   [U=1000,P=1737]    set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1000,P=1737]    init()                        Spawn stage 1
DEBUG   [U=1000,P=1737]    func1()                       Install prefix is /usr
DEBUG   [U=1000,P=1737]    startup()                     apptainer runtime engine selected
VERBOSE [U=1000,P=1737]    startup()                     Execute stage 1
DEBUG   [U=1000,P=1737]    StageOne()                    Entering stage 1
DEBUG   [U=1000,P=1737]    findOnPath()                  Found "squashfuse_ll" at "/usr/libexec/apptainer/bin/squashfuse_ll"
DEBUG   [U=1000,P=1737]    findOnPath()                  Found "fuse2fs" at "/usr/bin/fuse2fs"
DEBUG   [U=1000,P=1737]    findOnPath()                  Found "fuse-overlayfs" at "/usr/bin/fuse-overlayfs"
DEBUG   [U=1000,P=1737]    findOnPath()                  Found "gocryptfs" at "/usr/libexec/apptainer/bin/gocryptfs"
DEBUG   [U=1000,P=1737]    InitImageDrivers()            squashfuse_ll supports -o uid
DEBUG   [U=1000,P=1737]    InitImageDrivers()            Setting ImageDriver to fuseapps
DEBUG   [U=1000,P=1737]    prepareAutofs()               Found "/cvmfs" as autofs mount point
DEBUG   [U=1000,P=1737]    prepareAutofs()               Could not keep file descriptor for user bind path /data: no mount point
DEBUG   [U=1000,P=1737]    prepareAutofs()               Could not keep file descriptor for user bind path /neurodesktop-storage: no mount point
DEBUG   [U=1000,P=1737]    prepareAutofs()               Could not keep file descriptor for user bind path /tmp: no mount point
DEBUG   [U=1000,P=1737]    keepAutofsMount()             Open file descriptor for /cvmfs
DEBUG   [U=1000,P=1737]    prepareAutofs()               Could not keep file descriptor for user bind path /home/jovyan: no mount point
DEBUG   [U=1000,P=1737]    prepareAutofs()               Could not keep file descriptor for user bind path /home/jovyan: no mount point
DEBUG   [U=1000,P=1737]    prepareAutofs()               Could not keep file descriptor for bind path /etc/localtime: no mount point
DEBUG   [U=1000,P=1737]    prepareAutofs()               Could not keep file descriptor for bind path /etc/hosts: no mount point
DEBUG   [U=1000,P=1737]    prepareAutofs()               Could not keep file descriptor for home directory /home/jovyan: no mount point
DEBUG   [U=1000,P=1737]    prepareAutofs()               Could not keep file descriptor for current working directory /home/jovyan: no mount point
DEBUG   [U=1000,P=1737]    Init()                        Image format detection
DEBUG   [U=1000,P=1737]    Init()                        Check for sandbox image format
DEBUG   [U=1000,P=1737]    Init()                        sandbox format initializer returned: not a directory image
DEBUG   [U=1000,P=1737]    Init()                        Check for sif image format
DEBUG   [U=1000,P=1737]    Init()                        sif format initializer returned: SIF magic not found
DEBUG   [U=1000,P=1737]    Init()                        Check for squashfs image format
DEBUG   [U=1000,P=1737]    Init()                        squashfs image format detected
DEBUG   [U=1000,P=1737]    findOnPath()                  Searching for "mount" in SuidBinaryPath
DEBUG   [U=1000,P=1737]    findOnPath()                  Found "mount" at "/usr/bin/mount"
DEBUG   [U=1000,P=1737]    CheckRootless()               Rootless overlay not supported on this system: fork/exec /usr/bin/mount: permission denied
DEBUG   [U=1000,P=1737]    setSessionLayer()             Using underlay layer: user namespace requested
DEBUG   [U=1000,P=1737]    PrepareConfig()               image driver is fuseapps
VERBOSE [U=1000,P=1730]    wait_child()                  stage 1 exited with status 0
DEBUG   [U=1000,P=1730]    cleanup_fd()                  Close file descriptor 5
DEBUG   [U=1000,P=1730]    cleanup_fd()                  Close file descriptor 6
DEBUG   [U=1000,P=1730]    cleanup_fd()                  Close file descriptor 7
DEBUG   [U=1000,P=1730]    init()                        Set child signal mask
DEBUG   [U=1000,P=1730]    init()                        Create socketpair for master communication channel
DEBUG   [U=1000,P=1730]    init()                        Create RPC socketpair for communication between stage 2 and RPC server
VERBOSE [U=1000,P=1730]    user_namespace_init()         Create user namespace
VERBOSE [U=1000,P=1730]    create_namespace()            Create user namespace
VERBOSE [U=65534,P=1730]   init()                        Spawn master process
DEBUG   [U=65534,P=1730]   setup_userns_mappings()       Write deny to setgroups file
DEBUG   [U=65534,P=1730]   setup_userns_mappings()       Write to GID map
DEBUG   [U=65534,P=1730]   setup_userns_mappings()       Write to UID map
DEBUG   [U=1000,P=1745]    set_parent_death_signal()     Set parent death signal to 9
VERBOSE [U=1000,P=1745]    create_namespace()            Create mount namespace
ERROR   [U=1000,P=1745]    shared_mount_namespace_init() Failed to set mount propagation: Permission denied
VERBOSE [U=1000,P=1730]    wait_child()                  stage 2 exited with status 1

### Steps to reproduce this behavior

install Apptainer in a container running on Jupyterlab for Kubernetes on GKE.

### What OS/distro are you running

```sh
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

```

### How did you install Apptainer

```
$ sudo apt update
$ sudo apt install -y wget
$ cd /tmp
$ wget https://github.com/apptainer/apptainer/releases/download/v1.2.4/apptainer_1.2.4_amd64.deb
$ sudo apt install -y ./apptainer_1.2.4_amd64.deb
```

**Comment by DrDaveD** [comment]
Can you tell us all the options you're passing to apptainer and details about how to get the container image?

So it's running under Kubernetes, starting an Ubuntu 22.04 container with docker (or at least the docker software stack), correct?  Perhaps there are required capabilities missing.  The only problem that I have seen with default settings in kubernetes is something that blocks mounting /proc, needed by the apptainer `--pid` option.

Can you connect to the kubernetes pod with a shell interactively?  Do you run apptainer then from that interactive shell?

**Comment by stebo85** [comment]
Dear @DrDaveD,

Ok, that helped a lot already!

It seems to be a capability issue. When running the container with a privileged context everything works and we have these capabilities set:

```
cap_chown,cap_dac_override,cap_dac_read_search,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_linux_immutable,cap_net_bind_service,cap_net_broadcast,cap_net_admin,cap_net_raw,cap_ipc_lock,cap_ipc_owner,cap_sys_module,cap_sys_rawio,cap_sys_chroot,cap_sys_ptrace,cap_sys_pacct,cap_sys_admin,cap_sys_boot,cap_sys_nice,cap_sys_resource,cap_sys_time,cap_sys_tty_config,cap_mknod,cap_lease,cap_audit_write,cap_audit_control,cap_setfcap,cap_mac_override,cap_mac_admin,cap_syslog,cap_wake_alarm,cap_block_suspend,cap_audit_read,cap_perfmon,cap_bpf,cap_checkpoint_restore
```

When starting a "default" container it comes up with the above error and these capabilities are set:

```
cap_chown,cap_dac_override,cap_fowner,cap_fsetid,cap_kill,cap_setgid,cap_setuid,cap_setpcap,cap_net_bind_service,cap_net_admin,cap_net_raw,cap_sys_chroot,cap_sys_admin,cap_sys_time,cap_mknod,cap_audit_write,cap_setfcap
```

What minimal set of capabilities do we need for Apptainer to work correctly?

**Comment by stebo85** [comment]
It seems google cloud Kubernetes by defaults blocks a few things with AppArmor:
<img width="980" alt="image" src="https://github.com/apptainer/apptainer/assets/4021595/d3741662-31d3-4ffe-961a-e66aee4c7c51">

https://cloud.google.com/kubernetes-engine/docs/concepts/security-overview#limiting_pod_container_process_privileges

would any of this explain the error we get?

**Comment by DrDaveD** [comment]
That could possibly explain that error, I'm not sure.  I'm also not sure which capabilities exactly that you would need.  I don't have much experience with configuring kubernetes.

I do know that this set of docker options enables apptainer to run unprivileged without the `--privileged` flag
```
--security-opt seccomp=unconfined --security-opt systempaths=unconfined --security-opt no-new-privileges --device /dev/fuse
```
but I don't know how that translates to Kubernetes.  (The `no-new-privileges` security-opt isn't required, it's only for further security).

**Comment by stebo85** [comment]
Dear @DrDaveD,

Thank you for the help and thoughts on this problem :) The problem was indeed caused by Google Clouds default AppArmor policies. We solved it by applying an AppArmor profile through a deamonset that doesn't break apptainer.

If anyone else runs into this problem, here is what we did:

Annotate the container 
```
container.apparmor.security.beta.kubernetes.io/notebook: localhost/singleuser
```

Create an AppArmor Policy and apply with Daemon Set (https://github.com/kubernetes/kubernetes/tree/master/test/images/apparmor-loader):
```
profile singleuser flags=(attach_disconnected,mediate_deleted) {
  network,
  capability,
  umount,
  mount,
  signal (receive),
  ptrace peer=singleuser,
  file,

  deny /proc/mem rwklx,
  deny /proc/kmem rwklx,
  deny /proc/kcore rwklx,
  deny /proc/sysrq-trigger rwklx,
  deny /proc/{*,**^[0-9*],sys/kernel/shm*} wkx,
  deny /sys/kernel/security/** rwklx,
  deny /sys/firmware/** rwklx,
  deny /sys/** wklx,
}
```

**Comment by DrDaveD** [comment]
Thank you for figuring out and posting the solution, very likely it will help someone else.
