### ISSUE TITLE
how to build a container interactively? 

### ISSUE THREAD

**Issue by gsal** [apptainer/apptainer#1807]
Is it possible to build a container interactively? without a *.def file? 
This way I could test my app and install whatever library may be missing without having to start from scratch.

### Version of Apptainer
`apptainer version 1.2.4-1.el9`

### Expected behavior

I thought "Creating writable --sandbox directories" was about creating containers interactivley...I guess not? 

I did
```
apptainer build --sandbox r9/ docker://rockylinux:9.1
apptainer shell --writable r9/
```
upon entering the container shell, I was expecting to be able to install packages via `dnf install` command. 

### Actual behavior
Instead, I get the following error message:
`
Apptainer> dnf install which
Failed to set locale, defaulting to C.UTF-8
Error: This command has to be run with superuser privileges (under the root user on most systems).
`
### Steps to reproduce this behavior

```
apptainer build --sandbox r9/ docker://rockylinux:9.1
apptainer shell --writable r9/
Apptainer> dnf install which
```
### What OS/distro are you running

```sh
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"
```

### How did you install Apptainer

Not sure, but not from source; IT did it, they typically just do yum/dnf

**Comment by DrDaveD** [comment]
I assume you ran that `apptainer shell` command separately from the build command, although it looks like they were all on one command line.

If I'm correct, then try using `apptainer shell --fakeroot r9`.  You need the fakeroot permissions in order to install anything, because by default apptainer run commands under your own user id.

**Comment by gsal** [comment]
Ah, thanks for the hint.   This is what worked for me: 
```
apptainer build --sandbox r9/  docker://rockylinux:9.1
cd r9
chmod -R u+rwX *
cd ..
apptainer shell --fakeroot --writable r9/
```
