### ISSUE TITLE
How to run parallel command inside apptainer

### ISSUE THREAD

**Issue by manighanipoor** [apptainer/apptainer#1811]
Hi,

I have installed repeatmodeler using Apptainer in ubuntu (apptainer pull dfam-tetools-latest.sif docker://dfam/tetools:latest). When running the program inside the Apptainer using "parallel" command, it fails by the error: "bash: parallel: command not found".

When I run "apt-get install parallel", I get this error:

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  libsensors-config libsensors5 sysstat
Suggested packages:
  lm-sensors csh fish ksh tcsh zsh isag
The following NEW packages will be installed:
  libsensors-config libsensors5 parallel sysstat
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 2517 kB of archives.
After this operation, 4914 kB of additional disk space will be used.
W: Not using locking for read only lock file /var/lib/dpkg/lock-frontend
W: Not using locking for read only lock file /var/lib/dpkg/lock
W: Not using locking for read only lock file /var/cache/apt/archives/lock
E: You don't have enough free space in /var/cache/apt/archives/.

Could you please help me resolve this?

**Comment by truatpasteurdotfr** [comment]
That is not a issue for apptainer, but more a user support question...

Either ask the docker image provider to add parallel in their image, or build a new container based on their docker image with a "recipe".

quick a dirty `Singularity` definition file
```
BootStrap: docker
From: docker://dfam/tetools:latest

%post
apt-get update
apt-get install -y parallel
```

`apptainer build my-container.sif Singularity`

I have no idea if that is enough for your use case, but you get the idea. Good luck.

**Comment by manighanipoor** [comment]
Thanks for your helpful comment!
