### ISSUE TITLE
Sylabs PRs to import for 1.3.0

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#1844]
I think it would be good to import the following Sylabs PRs for apptainer-1.3.0.
- sylabs/singularity#1957
- sylabs/singularity#1958
- sylabs/singularity#1971
- sylabs/singularity#2003
- sylabs/singularity#2033
- sylabs/singularity#2035
- sylabs/singularity#2287

**Comment by JasonYangShadow** [comment]
@DrDaveD 

There are two PRs that can not be easily cherry picked
1. https://github.com/sylabs/singularity/pull/2033 it requires dependent commits as early as https://github.com/dtrudg/singularity/commit/88a85f10626c9a17cf4dc2dea02612c2eee91ecd, many changes involved. (Might have other dependent commits from other files)
2. https://github.com/sylabs/singularity/pull/1971 it also has many files diversed differently, for example, the https://github.com/dtrudg/singularity/commits/57ed2af44c2fe1f08be2c14ddc6ae5dac797d0be/internal/pkg/runtime/launcher/options.go `options.go` file has very different commits with apptainer's .

**Comment by DrDaveD** [comment]
Ah, I have @vzokay working on the change to orags-go v2 so that's why I didn't list it.  That may be enough for number 1.  Let's check again after that's done.

For number 2, yes, ignore all the oci files because they're not relevant.  I think that should make it end up being very simple.

**Comment by DrDaveD** [comment]
It turns out that the dependent PR we were waiting in, sylabs/singularity#1922, is quite a complex port, a bit too much for my just-learning helper.  @JasonYangShadow can you please add that to your list and see if you can do it instead?

**Comment by JasonYangShadow** [comment]
> It turns out that the dependent PR we were waiting in, [sylabs/singularity#1922](https://github.com/sylabs/singularity/pull/1922), is quite a complex port, a bit too much for my just-learning helper. @JasonYangShadow can you please add that to your list and see if you can do it instead?

I've taken a look at the cherry pick. There are too many changes and differences between singualrity and apptainer. 
Changes can trace back to one year ago. 
One example is: 
https://github.com/dtrudg/singularity/commits/23fdfa85b097115da1e56c278738b9ddc858b5d1/internal/pkg/runtime/launcher/options.go

**Comment by DrDaveD** [comment]
As I said, it is a complex port.  It needs to be adapted to the current Apptainer code.  Leave out everything that's related to code that Apptainer does not have.  By far the largest chunk of code that Apptainer does not have is anything to do with the `--oci` option or OCI-SIF.  On the other hand there may be other parts of Apptainer code which SingularityCE does not have which also need to be modified for this change.  Please try again and ask for help from Cedric or I if you get stuck.

**Comment by JasonYangShadow** [comment]
> As I said, it is a complex port. It needs to be adapted to the current Apptainer code. Leave out everything that's related to code that Apptainer does not have. By far the largest chunk of code that Apptainer does not have is anything to do with the `--oci` option or OCI-SIF. On the other hand there may be other parts of Apptainer code which SingularityCE does not have which also need to be modified for this change. Please try again and ask for help from Cedric or I if you get stuck.

Had a discussion with cedric, regarding this OCI-SIF implementation, let's discuss it in the next community meeting and maybe target at 1.3.x for this feature, as it'll bring new changes to existing image layout.

**Comment by DrDaveD** [comment]
To be clear, I am saying to remove any parts in the cherry-pick having to do with OCI-SIF and `--oci`, anything that Apptainer does not have.  I think there was a misunderstanding about that.

**Comment by DrDaveD** [comment]
All of the referenced PRs are merged.
