### ISSUE TITLE
Change default of `allow setuid-mount squashfs` to `no`

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#1845]
Now that setting `allow setuid-mount squashfs = no` causes setuid mounts of squashfs filesystems including SIF files to switch to squashfuse, change that to be the default for the improved security.

Whether or not to do this for 1.3.0 was debated in today's community call and the feeling is to go ahead.  It should not have a big effect on multithreaded performance as shown in #665.  However, its effect on mpi jobs running multiple single-core squashfuses is not known.  @JasonYangShadow agreed to do some performance tests in that regard and report here.

This does require squashfuse built with libfuse3 which is not the case by default in all distributions, so people who compile from source using `mconfig --with-suid` will need to also compile squashfuse.  It is included in rpm & debian packaging.

**Comment by JasonYangShadow** [comment]
@panda1100 it looks like I do not have enough time for this performance test, are you able to help the benchmark?

**Comment by DrDaveD** [comment]
Superseded by #1874
