### ISSUE TITLE
build fails with getopt command not found and fakeroot help text

### ISSUE THREAD

**Issue by nlvw** [apptainer/apptainer#1863]
### Version of Apptainer

```console
$ apptainer --version
apptainer version 1.2.5-1.el8
```

### Expected behavior

Container to properly build or atleast run the post section.

### Actual behavior

Build failed without running post section.

### Steps to reproduce this behavior

Not sure as the container recipe in question builds fine on other computers but fails on our HPC nodes.  I'm able to build the example lolcat container, [from the docs](https://apptainer.org/docs/user/main/build_a_container.html#building-containers-from-apptainer-definition-files), so I'm not sure why this is failing.  Further I tried using a rocky9 linux image and it didn't throw the same error but any version of Fedora (including images from quay.io) all fail like below.

container.def
```txt
BootStrap: docker
From: docker.io/fedora:39

%files
./.scripts/apptainer/runscript.sh /usr/local/bin/runscript.sh
./.scripts/apptainer/post.sh /usr/local/sbin/post.sh
./.scripts/apptainer/prj_comps.sh /etc/profile.d/prj_comps.sh

%runscript
/usr/local/bin/runscript.sh "$@"

%environment
export TZ="America/Denver"
export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

%post
# Correct File Perms of %files
chmod 0755 /usr/local/bin/runscript.sh
chmod 0750 /usr/local/sbin/post.sh
chmod 0755 /etc/profile.d/prj_comps.sh

# Run post script to finish setup/installation
/usr/bin/bash /usr/local/sbin/post.sh
```

Output:

```console
$ apptainer -v build cache/container.sif .scripts/apptainer/container.def
VERBOSE: Implying --fakeroot because building from definition file unprivileged
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Starting build...
Getting image source signatures
Copying blob 8237fce9fd6b skipped: already exists
Copying config eaa0754403 done
Writing manifest to image destination
Storing signatures
2023/12/13 09:23:23  info unpack layer: sha256:8237fce9fd6b5acc12e7010d84e6245c6b00937de832c1987c4769866af1573a
INFO:    Copying ./.scripts/apptainer/runscript.sh to /usr/local/bin/runscript.sh
INFO:    Copying ./.scripts/apptainer/post.sh to /usr/local/sbin/post.sh
INFO:    Copying ./.scripts/apptainer/prj_comps.sh to /etc/profile.d/prj_comps.sh
INFO:    Running post scriptlet
VERBOSE: Forwarding APPTAINERENV_SINGULARITY_LABELS as SINGULARITY_LABELS environment variable
VERBOSE: Forwarding APPTAINERENV_APPTAINER_ENVIRONMENT as APPTAINER_ENVIRONMENT environment variable
VERBOSE: Forwarding APPTAINERENV_SINGULARITY_ENVIRONMENT as SINGULARITY_ENVIRONMENT environment variable
VERBOSE: Forwarding APPTAINERENV_APPTAINER_LABELS as APPTAINER_LABELS environment variable
VERBOSE: Not forwarding APPTAINER_VERBOSE environment variable
VERBOSE: Not forwarding APPTAINER_SILENT environment variable
VERBOSE: Setting HOME=/root
VERBOSE: Setting PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VERBOSE: Set messagelevel to: 4
VERBOSE: Starter initialization
VERBOSE: Check if we are running as setuid: 0
VERBOSE: Spawn stage 1
VERBOSE: Execute stage 1
VERBOSE: stage 1 exited with status 0
VERBOSE: Spawn master process
VERBOSE: Create mount namespace
VERBOSE: Entering in mount namespace
VERBOSE: Create mount namespace
VERBOSE: Spawn RPC server
VERBOSE: Execute master process
VERBOSE: Serve RPC requests
VERBOSE: Default mount: /proc:/proc
VERBOSE: Default mount: /sys:/sys
VERBOSE: Default mount: /dev:/dev
VERBOSE: Default mount: /tmp:/tmp
VERBOSE: Default mount: /var/tmp:/var/tmp
VERBOSE: Skipping bind of the host's /etc/resolv.conf
WARNING: No current working directory set: skipping mount
VERBOSE: Not updating passwd/group files, running as root!
VERBOSE: rpc server exited with status 0
VERBOSE: Execute stage 2
VERBOSE: Running command with fakeroot
/.singularity.d/libs/fakeroot: line 46: getopt: command not found
/.singularity.d/libs/fakeroot: line 50: getopt: command not found
fakeroot, create a fake root environment.
   usage: fakeroot [-l|--lib fakerootlib] [-f|--faked fakedbin]
                   [-i file] [-s file] [-u|--unknown-is-real]
                   [-b|--fd-base fd] [-h|--help] [-v|--version]
                   [--] [command]
FATAL:   While performing build: while running engine: exit status 1
```

Here is an identical run but with `-d` instead of `-v`.
[build-debug.log](https://github.com/apptainer/apptainer/files/13663167/build-debug.log)

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.9 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.9 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"
```

### How did you install Apptainer

RPM from EPEL

**Comment by DrDaveD** [comment]
The fakeroot command being included from the el8 host because you don't have /etc/subuid and /etc/subgid mapping includes the use of the getopt command.  That is apparently not available on fedora39.  Unless you can begin from a modified fedora39 image that adds the getopt command, I think the only other solution you have to do a build as an unprivileged user is to set up /etc/subuid and /etc/subgid mapping for your user id.

**Comment by DrDaveD** [comment]
Or maybe you could bind in the getopt command from the host with `-B /usr/bin/getopt`.

**Comment by gsal** [comment]
Well, I just hit this problem, too. Kind of sucks. 

So far, I had played around wih apptainer to put together container with the same OS as the host system, but with additional libraries and programs so that I don't have to beg IT to install stuff just for me, etc. 

Now, I would like to prolong the life of a SuSE program but the combination Apptainer/Rocky9 does not like image `registry.opensuse.org/opensuse/bci/bci-minimal:20240228.0`

Is there a way around this?  Using apptainer to containerize current app is all good; but, really useful to apptainer in a modern OS to containerize an app that only runs in an older OS and has yet to be migrated to the new OS, etc.

**Comment by gsal** [comment]
I have tried a few command/options combinations with no success...it seem to be due to incompatibilities between the host OS and the container OS .....with complains about getopt and/or fakeroot and, ultimately about glibc version.

**Comment by DrDaveD** [comment]
Can you get `/etc/subuid` mapping set up?  The fakeroot command mode was a fallback option for people who couldn't do `/etc/subuid` but it has its limitations.  

What is a .def file that fails for you on Rocky9?

**Comment by DrDaveD** [comment]
I was able to workaround the issue with a .def file like this:
```
BootStrap: docker
From: registry.opensuse.org/opensuse/bci/bci-minimal:20240228.0

%setup
        touch $APPTAINER_ROOTFS/usr/bin/getopt

%post
        id
```
and building with
```
apptainer build -B /usr/bin/getopt issue1863.sif issue1863.def
```

I also worked around it by setting up /etc/subuid mappings.

Now if we could only think of a way to work around it automatically ...
```

**Comment by gsal** [comment]
> Can you get `/etc/subuid` mapping set up? The fakeroot command mode was a fallback option for people who couldn't do `/etc/subuid` but it has its limitations.
> 
> What is a .def file that fails for you on Rocky9?

Last year, as I started to learn about containers, the starting point was of course Docker; it takes a few acrobatics to make it work (a daemon, adding user to /etc/subuid, /etc/subgid), learning a new syntax, registries, etc. 

Second, I learned about podman and buildah...like them better than Docker; but still not quite what I was looking for. 

Finally, while asking for standalone deployment of a container, somebody pointed me to apptainer, and I liked it veryy very much....I refer to it as "container for the masses", why? Because it does require any setup, nor a registry...nothing!

So, no, I don't want to have to modify /etc/subuid and/or /etc/subgid; this would mean that only certain user can use apptainer and only in certain machines AND requires asking IT to keep up with all these. 

I hope apptainer never requires having to add users to /etc/subuid files.

I guess I would be interested in knowing what the limitations of fakeroot are.

**Comment by gsal** [comment]
> I was able to workaround the issue with a .def file like this:
> 
> ```
> BootStrap: docker
> From: registry.opensuse.org/opensuse/bci/bci-minimal:20240228.0
> 
> %setup
>         touch $APPTAINER_ROOTFS/usr/bin/getopt
> 
> %post
>         id
> ```
> 
> and building with
> 
> ```
> apptainer build -B /usr/bin/getopt issue1863.sif issue1863.def
> ```
> 
> I also worked around it by setting up /etc/subuid mappings.
> 
> Now if we could only think of a way to work around it automatically ...

---

Ok, so using `bci-minimal:20240228.0` worked for me:
   - without having to change /etc/subuid
   - adding `%setup: touch $APPTAINER_ROOTFS/usr/bin/getopt` to the .def file
   - adding `-B /usr/bin/getopt` to the apptainer command. 
Thank you for that....a bit of progress.

But, I ended up a bit confused because this miniimal install does not come with dnf or yum or apt or apt-get or zypper or nothing...so, I don't know how to continue and what command to use in the `%post` section of the *.def file to install other stuff I need. 

So, that is when I decided to move up to 
```
BootStrap: docker
From: registry.suse.com/bci/bci-base:15.5
```
And it is when attempting this where I run into trouble; here is the output: 
```
./build.sh 
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Starting build...
Getting image source signatures
Copying blob fc4ecc75782c skipped: already exists  
Copying config bfeef5e54e done  
Writing manifest to image destination
Storing signatures
2024/02/29 21:37:03  info unpack layer: sha256:fc4ecc75782c6fd9454cf62accfdd1cddeb87f7a2db444ca99dfd6f15214defe
INFO:    Running setup scriptlet
+ touch /tmp/build-temp-1536031634/rootfs/usr/bin/getopt
INFO:    Running post scriptlet
getopt: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by getopt)
getopt: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by getopt)
fakeroot, create a fake root environment.
   usage: fakeroot [-l|--lib fakerootlib] [-f|--faked fakedbin]
                   [-i file] [-s file] [-u|--unknown-is-real]
		   [-b|--fd-base fd] [-h|--help] [-v|--version]
                   [--] [command]
FATAL:   While performing build: while running engine: exit status 1
```

**Comment by DrDaveD** [comment]
Yes that's not too surprising.  In fact you don't need the `getopt` bind with that starting base, but if you leave that out you then hit a similar message on the `faked` command.

I found another workaround.  If you install apptainer with `tools/install-unprivileged.sh` as [documented](https://apptainer.org/docs/admin/latest/installation.html#install-unprivileged-from-pre-built-binaries) and then edit `install-dir/x86_64/utils/bin/fakeroot-sysv` to delete the `/usr/lib64/libfakeroot:` from the beginning of the PATHS variable, it works without any need to bind in getopt.  (It also works without the edit if fakeroot is not installed on the host).  The `unprivileged.sh` script is already editing that file as it is installed, so I could add another edit to do that delete automatically.

**Comment by gsal** [comment]
I am going to have to find out how IT installed Apptainer and/or see if we can install it again in some development box and install as recommended above with `unprivileged.sh` .  I speculate that IT installed via their typical dnf or yum command; not sure what installation mode is the default.

**Comment by DrDaveD** [comment]
Meanwhile you can do a test install in your own unprivileged space, or /tmp.

**Comment by gsal** [comment]
Ah, ok; I will try that, then.

**Comment by gsal** [comment]
Host OS: Rocky 9.3
apptainer version 1.2.5-1.el7
Attempting to install: registry.suse.com/bci/bci-base:15.5

I installed apptainer with the unprivileged script; it seems PATHS already come without `/usr/lib64/fakeroot`:
```
PATHS=${FAKEROOT_PREFIX}/lib64/libfakeroot:${FAKEROOT_PREFIX}/lib/libfakeroot
```

In any case, I still can't build a container; it complains about not finding glibc 2.33 or 2.34:
```
> /home/gsal/try/app
./build.sh 
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Starting build...
Getting image source signatures
Copying blob 20367cacc8e5 done  
Copying config 7329f2263b done  
Writing manifest to image destination
Storing signatures
2024/03/06 07:54:54  info unpack layer: sha256:20367cacc8e5e8e9c14b8c6344f7d58f1f27ef45ccb72efe7fff1761594fde18
INFO:    Running setup scriptlet
+ touch /tmp/build-temp-1068440976/rootfs/usr/bin/getopt
INFO:    Running post scriptlet
/.singularity.d/libs/faked: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by /.singularity.d/libs/faked)
/.singularity.d/libs/faked: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/faked)
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
FATAL:   While performing build: while running engine: exit status 1

> /home/gsal/try/app
ldd --version 
ldd (GNU libc) 2.34
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

```

**Comment by DrDaveD** [comment]
@gsal I received email saying that using `unprivileged.sh` didn't work, but don't see the post here.  Did you delete the post because you got it to work?

**Comment by gsal** [comment]
Ha, ha,, yes, sorry about that. 

I did some testing, got the error message, made a post; returned to continue testing just to realized that I was using one terminal with my apptainer install to build the container, but another terminal to to run the container but pulling IT's apptainer install.

So, I am good.  Thanks for checking.

**Comment by wisabd** [comment]
I get an error after using the tecbniques above. It asks to enable CRB repository to install some EPEL packaages. I am working on a working node on university's HPC cluster.

Should I post a dnf command in post, or something else? 

![image](https://github.com/user-attachments/assets/4d79f4ad-78e3-4816-933c-ae19c10a30e9)

**Comment by DrDaveD** [comment]
@wisabd the right thing to do is to make a new issue, which I assume you already did in #2436.
