### ISSUE TITLE
Build container using 'Bootstrap: library' without SSL verification?

### ISSUE THREAD

**Issue by kerbspaul** [apptainer/apptainer#1907]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? 
`singularity-ce version 4.0.2-jammy`

### Expected behavior
Build container with `singularity build` command from a definition file using `Bootstrap: library`.

### Actual behavior
Build process doesn't start because of failed SSL verification
```
FATAL:   Unable to get library client configuration: unable to get library service URI: error making request to server: Get "https://cloud.sylabs.io/assets/config/config.prod.json": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer
`sudo dpkg -i singularity-ce_4.0.2-jammy_amd64.deb`

Hello,
the machine I am working on accesses the internet through a proxy (http). So SSL verification is not possible.
Is it possible to deactivate the SSL verification for the `singularity build` command?

I have already tried to add a new remote: `singularity remote add --insecure SylabsCloud_insecure cloud.sylabs.io` but it asks for a token and verification of that token also fails with the message:
```
FATAL:   while verifying token: error making request to server: Get "https://cloud.sylabs.io/assets/config/config.prod.json": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Thanks in advance.

**Comment by DrDaveD** [comment]
Since this is singularity-ce, please submit your issue instead to their github at https://github.com/sylabs/singularity.

**Comment by DrDaveD** [comment]
Or if you intended to be using apptainer, the Ubuntu installation instructions are at https://apptainer.org/docs/admin/latest/installation.html#install-ubuntu-packages.
