### ISSUE TITLE
Harbor registry login fails in 1.3.0rc1

### ISSUE THREAD

**Issue by adalator** [apptainer/apptainer#1910]
### Version of Apptainer

`apptainer version 1.3.0~rc.1-1.el7`

### Expected behavior

When I run `apptainer remote login --username myusername docker://myharbor.com` or `apptainer registry login --username myusername docker://myharbor.com` I am prompted for my password/token and succesfully logged in, the token being stored.

### Actual behavior

Either command produces an error after entering the password/token:

```
apptainer remote login --username myusername docker://myharbor.com
WARNING: 'remote login' is deprecated for registries or keyservers and will be removed in a future release; running 'registry login'
Password / Token:
FATAL:   while login to docker://myharbor.com: GET https://myharbor.com/service/token?service=harbor-registry: unexpected status code 401 Unauthorized
```
(`myharbor.com` is not the actual URL)

The log in does work with version 1.2.5:
```
apptainer remote login --username myusername docker://myharbor.com
Password / Token:
INFO:    Token stored in /user1/.apptainer/remote.yaml
```

The Harbor registry is v2.5.2

### Steps to reproduce this behavior

Try logging into a Harbor registry as above

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"


```

### How did you install Apptainer

I downloaded  apptainer-1.3.0.rc.1-1.el7.x86_64.rpm from the Github release and installed it with `dnf localinstall`

**Comment by DrDaveD** [comment]
@ikaneshiro will look at this.  RELEASE_NOTES should also say that the remote login command still works with a deprecation message.

**Comment by JasonYangShadow** [comment]
I can also reproduce this issue by trying demo.goharbor.io
![image](https://github.com/apptainer/apptainer/assets/2051711/9ab8f662-bcca-4477-8d0a-381d192eaefb)
