### ISSUE TITLE
Builds fail when $HOME isn't readable

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#1959]
### Version of Apptainer

1.2.5, at least

### Expected behavior

I expect builds to work even when the home directory isn't readable, as happens with action commands and when the home directory doesn't exist.  Warnings make sense.

### Actual behavior

Apptainer dies with these messsages:
```
WARNING: Unable to retrieve information for /root/.apptainer: stat /root/.apptainer: permission denied
WARNING: Cache disabled - cannot access parent directory of cache: stat /root/.apptainer: permission denied.
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: while converting reference: loading registries configuration: reading registries.conf.d: lstat /root/.config/containers/registries.conf.d: permission denied
```

### Steps to reproduce this behavior

Set $HOME to a non-readable directory for build as an ordinary user:
```
$ HOME=/root apptainer build /tmp/centos7.sif docker://centos:7
```

It behaves the same for both suid mode and user namespace mode.

### What OS/distro are you running

CentOS7

### How did you install Apptainer

EPEL

**Comment by JasonYangShadow** [comment]
@DrDaveD 
I investigated this issue and it looks like the third-party library throws this error
https://github.com/apptainer/apptainer/blob/8b6bdf5fc1cc0c46039e36172e012c5be8a0e60c/internal/pkg/build/oci/oci.go#L243
https://github.com/apptainer/apptainer/blob/8b6bdf5fc1cc0c46039e36172e012c5be8a0e60c/internal/pkg/build/oci/oci.go#L212
```
failed to create client: getting username and password: reading registries.conf.d: lstat /root/.config/containers/registries.conf.d: permission denied
```
And we can not ignore/skip this error to continue building the images as the following pack will need reference info

**Comment by DrDaveD** [comment]
As a workaround, could we check ahead of time for readability of the home directory and if so set HOME to a non-existent directory?

**Comment by JasonYangShadow** [comment]
> As a workaround, could we check ahead of time for readability of the home directory and if so set HOME to a non-existent directory for the duration of the library call?

I figured out that we can reset `$HOME` value in the early stage if it is a non-readable value.
