### ISSUE TITLE
Enable insecure mode with SSL (via /etc/containers/registries.conf not working)

### ISSUE THREAD

**Issue by hashkeks** [apptainer/apptainer#196]
## Version of Singularity: 

```
$ singularity version
3.9.4
```

### Expected behavior

When editing the config file `/etc/containers/registries.conf` and setting `prefix` to my registry's domain and `insecure` to true, I expected the singularity client to login, push and pull to/from the selected registry which only serves a self-signed, untrusted certificate.
This approach was done as suggested in this issue: https://github.com/apptainer/singularity/issues/4725

My settings in `/etc/containers/registries.conf` (domain.com is of course my real domain name in reality):
![registries](https://user-images.githubusercontent.com/34633191/152139120-9d2d47e0-1f75-4eda-b49a-60ce433e4c1d.jpg)

### Actual 'request'
An option like `--skip-verify` (similar to `curl -k` for example) would be good or that the setting `insecure = true` in `/etc/containers/registries.conf` (see https://github.com/apptainer/singularity/issues/4725) would be applied. Is there any way to skip the verification of SSL certificates with singularity?

### Actual behavior

The settings don't do any difference. I still get the 'unknown authority' error message from singularity, for example with the pull command:
```
$ singularity pull alpine.sif library://collection-name/alpine:latest
FATAL:   Unable to get library client configuration: unable to get library service URI: error making request to server: Get "https://my.domain.com/assets/config/config.prod.json": x509: certificate signed by unknown authority

$ singularity remote login myregistry
Token entered will be hidden for security.
Access Token: 
FATAL:   while verifying token: error making request to server: Get "https://my.domain.com/assets/config/config.prod.json": x509: certificate signed by unknown authority

```

### Steps to reproduce this behavior

Try to push/pull an image to/from a registry that uses a self-signed, untrusted certificate.
I'm aware that I can make this certificate trusted on a system level, but that's not possible in my use case. 

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.3 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.3 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Singularity

From source.

#### Thank you in advance

**Comment by cclerget** [comment]
@hashkeks `/etc/containers/registries.conf` is for docker/oras image only, it doesn't work for library.

As a workaround you can set `SSL_CERT_DIR` environment variable to point to various directory containing trusted root CA certificates, so you could grab the root CA for `domain.com` and store it at `~/.cacerts/domain.crt`, then set the variable to have :

`export SSL_CERT_DIR=$HOME/.cacerts:/etc/ssl/certs`

Note: on Fedora you need to add `/etc/pki/tls/certs` to the directory list

**Comment by kerbspaul** [comment]
Hello,
I have the problem that the machine I'm working on has only internet access through a proxy and SSL is disabled.
I have set proxy environment variables but I don't know how to disable SSL verification for `singularity build`, so I get the same error message when I try to build through `Bootstrap: library`
```
FATAL:   Unable to get library client configuration: unable to get library service URI: error making request to server: Get "https://cloud.sylabs.io/assets/config/config.prod.json": tls: failed to verify certificate: x509: certificate signed by unknown authority
```

Is it possible to deactivate SSL verification while building containers with `Bootstrap: library`?
Thanks in advance for your respone.

**Comment by DrDaveD** [comment]
@kerbspaul It would be better to create a new issue, so we can start from scratch knowing your version number and environment.  I'm going to close this issue as being stale.

Having said that, what you might want is to use the `--insecure` flag when you add the SylabsCloud remote.
