### ISSUE TITLE
Build from local Docker daemon fails due to Docker client API requirements

### ISSUE THREAD

**Issue by oschulz** [apptainer/apptainer#1965]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

```
$ apptainer --version
apptainer version 1.2.5

$ docker --version
Docker version 25.0.1, build 29cf629
```

### Expected behavior

Expected build to work.

### Actual behavior

Apptainer v1.2.5 seems incompatible with Docker daemon v25 client-API requirements (see below).

Problem disappears after downgrading to Docker v24.0.8.

### Steps to reproduce this behavior

```
$ docker pull ubuntu:22.04

$ apptainer build out.sif docker-daemon:ubuntu:22.04
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: while converting reference: loading image from docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

But

```
$ apptainer build out.sif docker:ubuntu:22.04
```

works fine.

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
```

### How did you install Apptainer

Installed Apptainer from apptainer-ubuntu-ppa-jammy .

**Comment by GodloveD** [comment]
I have not tried to replicate but the error message seems straightforward.  Apptainer should have a newer version of the API.  I wonder how difficult it would be to implement this.

**Comment by DrDaveD** [comment]
@oschulz Can you please try it with 1.3.0-rc.1?  We have kept up with upgrading all the github libraries including ones for docker in the 1.3 branch but have not been updating the 1.2 branch.

**Comment by oschulz** [comment]
@DrDaveD , sorry - 1.3.0-rc.1 (I used the RC .deb assets) doesn't seem to work either, unfortunately:

```
$ apptainer --version
apptainer version 1.3.0-rc.1

$ docker --version
Docker version 25.0.1, build 29cf629

$ apptainer build out.sif docker-daemon:ubuntu:22.04
INFO:    Starting build...
FATAL:   While performing build: conveyor failed to get: while converting reference: loading image from docker engine: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
```

**Comment by DrDaveD** [comment]
Podman has the same problem containers/podman#21419.  That refers to containers/skopeo#2202 which in turn refers to containers/image#2260.

It looks like the fix is to upgrade to containers/image 5.29.1 which happened here on the release-1.3 branch in #1927 so it should be in the next 1.3.0 release candidate.   The corresponding PR for release-1.2 #1924 had a lot of ci check errors so it's probably too much work to fix it there, unless we just backported a patch for this problem.

**Comment by oschulz** [comment]
No worries, I'll try again with the next RC then.

**Comment by DrDaveD** [comment]
Could you try the [workaround](https://github.com/containers/skopeo/issues/2202#issuecomment-1908830671) to see if that makes the problem go away?  That could be useful for people who need the new docker but have an old apptainer.

**Comment by DrDaveD** [comment]
Fixed in #1927

**Comment by link89** [comment]
> 
> After creating a file "/etc/systemd/system/docker.service.d/version.conf", containing
> 
> ```
> [Service]
> Environment=DOCKER_MIN_API_VERSION=1.22
> ```

It didn't work in my case, I find the following error when restarting docker service:
```
dockerd[34153]: invalid DOCKER_MIN_API_VERSION: minimum supported API version is 1.24: 1.22
```

**Comment by DrDaveD** [comment]
> It didn't work in my case

Your situation may be different.  Please open a new issue, referring back to this one, with the particulars of your situation.
