### ISSUE TITLE
Unable to build apptainer from source

### ISSUE THREAD

**Issue by sramakintel** [apptainer/apptainer#1972]
I am trying to build apptainer from source based on instructions [here](https://github.com/apptainer/apptainer/blob/main/INSTALL.md). I have previously followed the same instructions and was able to get the build successful. However, this time I tried to build from `main` and `v1.3.0-rc.1` and I get the following error

```
# crypto/internal/nistec
/usr/local/go/src/crypto/internal/nistec/p256_ordinv.go:14:6: p256OrdMul redeclared in this block
        /usr/local/go/src/crypto/internal/nistec/p256_asm_ordinv.go:14:6: other declaration of p256OrdMul
/usr/local/go/src/crypto/internal/nistec/p256_ordinv.go:19:6: p256OrdSqr redeclared in this block
        /usr/local/go/src/crypto/internal/nistec/p256_asm_ordinv.go:19:6: other declaration of p256OrdSqr
/usr/local/go/src/crypto/internal/nistec/p256_ordinv.go:21:6: P256OrdInverse redeclared in this block
        /usr/local/go/src/crypto/internal/nistec/p256_asm_ordinv.go:21:6: other declaration of P256OrdInverse
make: *** [Makefile:176: apptainer] Error 1
```

**Comment by DrDaveD** [comment]
In order for us to help you, you need to tell us more information.  Tell us about your host and give instructions for how to reproduce it.  What is the OS version and cpu architecture. That looks like an issue with the go compiler, so what is the go version and how was it installed.

**Comment by sramakintel** [comment]
I had to wipe out the go installation and re-install to get it working successfully. Thanks. This issue can be closed
