### ISSUE TITLE
--nvccli does not work correctly on Ubuntu 22.04

### ISSUE THREAD

**Issue by xqms** [apptainer/apptainer#2028]
Hi, it seems apptainer calls `nvidia-container-cli` with `--ldconfig=@/usr/sbin/ldconfig`. However, `nvidia-container-cli` fails to call this as evident from its log:

```sh
I0216 13:44:10.417957 2014445 nvc_ldcache.c:380] executing /usr/sbin/ldconfig from host at /var/lib/apptainer/mnt/session/final
E0216 13:44:10.419067 1 nvc_ldcache.c:411] could not start /usr/sbin/ldconfig: process execution failed: no such file or directory
```

In the end, this means that the nvidia libraries are not usable in the container:
```sh
$ nvidia-smi
NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.
```

I think this is because `/usr/sbin/ldconfig` is a wrapper script on Ubuntu, and `/usr/sbin/ldconfig.real` should be used. I recall that older apptainer/singularity versions had an `ldconfig path` option, which was set to `ldconfig.real` on Ubuntu systems.

Indeed, if I disable the wrapper script by
```sh
mv /usr/sbin/ldconfig /usr/sbin/ldconfig.wrapper
mv /usr/sbin/ldconfig.real /usr/sbin/ldconfig
```

everything works fine.

To obtain the `nvidia-container-cli` debug log above, I wrote a wrapper script for nvidia-container-cli. Move nvidia-container-cli to nvidia-container-cli.real and put the following in its place:
```sh
#!/bin/bash
exec nvidia-container-cli.real --debug=/tmp/nvidia.log "$@"
```

### Version of Apptainer

```
apptainer version 1.3.0-rc.1
```
(also tested on 1.3.0-rc2 and 1.2.5)

### Expected behavior

Library symlinks are created correctly and `nvidia-smi` works.

### Actual behavior

Library symlinks are missing:
```
$ ls -la /usr/lib/x86_64-linux-gnu/libnvidia-ml*
-rw-r--r-- 1 nobody nogroup 1992128 Jan  8 16:06 /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.545.29.06
```

### Steps to reproduce this behavior

Run `apptainer --nv --writable-tmpfs --nvccli ...` on Ubuntu 22.04.

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer

GitHub release page.

**Comment by DrDaveD** [comment]
Indeed the [code](https://github.com/apptainer/apptainer/blob/main/internal/pkg/util/gpu/nvidia.go#L123) does that.  Would you be willing to try out your suggested change, and submit a PR if it works?
