### ISSUE TITLE
Embedding Signature History for Multi-Stage Builds [Enhancement]

### ISSUE THREAD

**Issue by jrwds** [apptainer/apptainer#2043]
Hello,

Right now my organization builds containers with multiple stages, particularly including an initial build (with multiple builds made by various people being used as each bootstrap builds off of a previous image), a review period (where one or multiple people look over a new build to see if it functions as expected manually in addition to programmatic tests), and the final live push (from one person).

I am looking to incorporate signatures into the containers that verify the chain of individuals who were involved with the container at each stage. As far as I am aware, multiple individuals can sign a container, but there is no built in way to distinguish their contributions (that is from which stage of the build/review process). I've come up with a few hacks that I will share, **but I wanted to first confirm there is no way to show that the signature from Alice was from the initial build stage, Bob and Conrad's were signed at the review stage, and Dan signed to push it live, correct?** I would want to be able to see who did what when doing `apptainer verify`.

**Additionally, is there a way to embed the signatures from previous builds?** For instance, if we have a base Ubuntu layer that more or less all our containers use (that has a base Ubuntu + tweaks for our environment) and was signed off by Eric, and then an additional build that adds Python 3.12 to the base Ubuntu image that was built by Frank, with our final container being the Ubuntu+Python and our specialized software stack that was signed by Garrett. I would want to see in the final image that Garrett produces that both Eric and Frank had signed for the earlier images, and which ones they signed for.

**Hack 1**

Create otherwise useless files in the containers and have the individuals from that image/step sign the files unique to that process, perhaps using `--sif-id`. 

**Hack 2**

Give each individual in the organization unique keys for each step of the build process, so we can see for instance that the JRWDS REVIEW key signed off on the container, and so we know that JRWDS reviewed the container. This is a brute force method that achieves the goal but it gets messy really quickly: we would have to make sure everyone uses the right signing keys at the right stages, and when a new step gets added everyone would have to generate another key.

**Feature Request**

Ideally if we allowed individuals to create their own signature database templates, then I could for instance craft my own signature database that is unique to our container production environment. This would allow the signature history to be embedded in the .sif itself, rather than having to keep track of that separately. The default template behavior would be exactly as it is now, with signatures applying to the whole container. So ideally the apptainer verify output may look something like:

```
$ apptainer verify my_container.sif`
Verifying image: my_container.sif
[LOCAL] [INITIAL BUILD]   Signing entity: Ian Kaneshiro (example key) <ikaneshiro@apptainer.org>
[LOCAL] [INITIAL BUILD]   Fingerprint: 8232570480B868E1473AEEB03DBCBA1EE9D661E5
[LOCAL] [REVIEW]   Signing entity: Alice Aardvark (example key) <aaardvark@apptainer.org>
[LOCAL] [REVIEW]   Fingerprint: 8232570480B868E1473AEEB03DBCBA1EE9D661E6
[LOCAL] [FINAL CONFIRMATION]   Signing entity: Bob Bear (example key) <bbear@apptainer.org>
[LOCAL] [FINAL CONFIRMATION]   Fingerprint: 8232570480B868E1473AEEB03DBCBA1EE9D661E7
Objects verified:
ID  |GROUP   |LINK    |TYPE
------------------------------------------------
1   |1       |NONE    |Def.FILE
2   |1       |NONE    |JSON.Generic
3   |1       |NONE    |JSON.Generic
4   |1       |NONE    |FS
Container verified: my_container.sif
```

When signing the container, individuals would have to specify for which of our customized stages they are signing for, perhaps something along the lines of:

`apptainer sign --stage "REVIEW" my_container.sif`

Perhaps there is a simpler solution that I am not seeing here, open to any thoughts/suggestions.

**Comment by jrwds** [comment]
I've found https://www.sigstore.dev/ which works in this area. It has development geared towards Docker in particular, by modifying the Dockerfile. It has multiple modules, covering provenance, multiple signatures, etc. If integrating something like sigstore into Apptainer isn't feasible, then at the very least the Apptainer specific implementation will look very similar because:

- Signatures are signed at build time
- Storing the signatures inside the container is already standard and I can't see any reason why creating separate files to store signatures would be preferable
- The issues of provenance, how to store signatures etc are all related, but separate problems and organizations might not need all those tools (hence why sigstore has separated them out)

Full disclosure: I am employed by Purdue University which is one of the primary developers of sigstore, although I personally do not work on the development of sigstore.

**Comment by DrDaveD** [comment]
Apptainer already uses sigstore for its signing and verification.

**Comment by GodloveD** [comment]
Sorry it has taken me some time to get back to you on this.  I've been thinking about it and trying to understand how it would work.  

I think the part I'm struggling with is that signatures are not just arbitrary data added to the container the way jsons or plain text can be.  They are applied to the other data in the container at the time of signing and the `verify` command doesn't just check to make sure that a signature is present but also uses it to check if any bits in the signed artifacts have changed since the time of signing.  

So in the situation you propose what would signatures on the base container be applied to in the final SIF file?  It's not enough to just carry the public key material over to the newly created SIF file.  The signature has to be applied over some artifact in the SIF file or else it is not really worth much.  And it can't be applied without the private key material (and hopefully a password from the key holder).  

I guess one useful way to think about this is "how could a bad actor defeat this"?  It seems like a bad actor could just dump the public key from one container and add it to a second container to claim that the downstream container was built from a trusted source.  Am I missing something?

**Comment by jrwds** [comment]
> Apptainer already uses sigstore for its signing and verification.

Ah! Forgive my ignorance, did not know this.

> So in the situation you propose what would signatures on the base container be applied to in the final SIF file?

This is what I am struggling with. It seems there are really two interests here: container integrity and provenance, ideally encapsulating both in the container itself. Container integrity is already done by checking the signature of the image at build time.

But the provenance portion, bundling the history of who was involved in the production of the container and also identifying contributions, might be fairly difficult to do and it may not be possible to do them both at once in the container (without things getting incredibly complicated). _There would have to be an immutable and/or append only signature database object wrapped in the container object at build time (so the SIF is still one file), that can be custom designed (limited number of signing slots per stage, explicit rules regarding signing, etc) that also records the changes made with each new signature (combining DEF and sig DB modifications?)._

> It seems like a bad actor could just dump the public key from one container and add it to a second container to claim that the downstream container was built from a trusted source.

Yes, if the .pubs were added directly it wouldn't make any sense. I had hoped that signing contributions layer by layer would solve this; but as you pointed out a new SIF built on a signed image will change the original SIF and thus the signature won't verify any longer. One would have to rebuild the original image(s) even if you stored the whole chain of DEF's at verification time which, while possible, might get incredibly lengthy. 

I will close this request, having given it some thought; my attempt at laziness has proven fruitless. There is probably a clever way to merge the provenance and integrity issues but it may be incredibly complicated to do within just 1 SIF file.
