### ISSUE TITLE
Cannot log into SylabsCloud

### ISSUE THREAD

**Issue by BEFH** [apptainer/apptainer#2052]
### Version of Apptainer

Apologies, but this is from within a GitHub workflow, so I did not run the version command

`apptainer-suid_1.2.5-1`

### Expected behavior

I expect login to be successful like in SingularityCE:

```
$ singularity remote login --tokenfile /tmp/s.key SylabsCloud
INFO:    Access Token Verified!
INFO:    Token stored in /home/runner/.apptainer/remote.yaml
WARNING: Skipping container verification
INFO:    Uploaded 850499333 bytes in 2m41.11[15]...
```

### Actual behavior

Apptainer fails to log into SylabsCloud:

```
$ singularity remote login --tokenfile /tmp/s.key SylabsCloud
FATAL:   --tokenfile is only supported for login to a remote endpoint, not OCI (docker/oras) or keyservers
```

When trying `singularity remote login` alone , I get the following error:

```
FATAL:   while login to :  transport is not supported
```

### Steps to reproduce this behavior

Steps are shown above

### What OS/distro are you running

Apologies, but this is from within a GitHub workflow, so I did not cat `/etc/os-release`, but the version is:

```
ubuntu22.04.0
```

### How did you install Apptainer

I installed using apt-get. The same errors were also present on a CentOS system with singularity built from source.

**Comment by GodloveD** [comment]
If you have not done so you might want to follow the [directions to restore pre-Apptainer library behavior](https://apptainer.org/docs/user/latest/endpoint.html#restoring-pre-apptainer-library-behavior).  Let us know if you try that and you are still stuck.

**Comment by BEFH** [comment]
Perfect! I updated my code to this:

```sh
apptainer remote add --no-login SylabsCloud cloud.sycloud.io
apptainer remote login --tokenfile /tmp/s.key SylabsCloud
apptainer remote use SylabsCloud
apptainer push -U container.sif \
  library://${owner}/${reponame}/${containername}:${tag}
```

And then I ran it with the following output:

```
INFO:    Remote "SylabsCloud" added.
INFO:    Access Token Verified!
INFO:    Token stored in /home/runner/.apptainer/remote.yaml
INFO:    Remote "SylabsCloud" now in use.
WARNING: Skipping container verification
INFO:    Uploading 850503429 bytes
```

Thanks very much!
