### ISSUE TITLE
Refactor `pkg/sypgp` to remove environment variable parsing

### ISSUE THREAD

**Issue by ikaneshiro** [apptainer/apptainer#207]
Refactor the `sypgp` package to remove direct parsing of environment variables in object initialization code. Environment variables should be parsed by the CLI as a flag ( potentially a hidden flag ) and passed down to invocations of this package.

Follow up of #200

**Comment by DrDaveD** [comment]
#208 moved the environment variable parsing to a utility function and uses it a few other places as well, so that reduces the motivation for moving this to a CLI flag.  It might still be a good idea though.

**Comment by JasonYangShadow** [comment]
I will take care of this issue and update here on any progress.

**Comment by JasonYangShadow** [comment]
not sure but do we need to close this issue now? 
@DrDaveD @ikaneshiro

**Comment by DrDaveD** [comment]
Fixed by #573
