### ISSUE TITLE
Putting sandbox on Lustre file system makes apptainer "hang"

### ISSUE THREAD

**Issue by akesandgren** [apptainer/apptainer#2096]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
b-an02 [~/support-hpc2n/ake/hepscore/t]$ apptainer --version
apptainer version 1.2.5

```
### Expected behavior

What did you expect to see when you do...?

```
apptainer build --sandbox ubuntu/ docker://ubuntu
apptainer shell ubuntu/
Apptainer>
```
I.e. I get a prompt

### Actual behavior

What actually happened? Why was it incorrect?

When putting the sandbox on a Lustre file system, `apptainer shell` hangs and I do not get a prompt.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

See above

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Apptainer

Self built from source.

**Comment by GodloveD** [comment]
Are you able to try this with v1.3.0 and see if the same issue occurs?  Sorry that I can't try myself, but I don't have easy access to a lustre system atm.

**Comment by akesandgren** [comment]
Ok, a reason as good as any to finally upgrade :-)
Will take a while...

**Comment by akesandgren** [comment]
Yes, 1.3.0 solves the problem. Many thanks.
