### ISSUE TITLE
Cleanup error stopping fuse-overlayfs driver when background process is running

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#2104]
### Version of Apptainer

apptainer version 1.3.0-1.el7

### Expected behavior

I expect apptainer to exit cleanly.

### Actual behavior

If a background process is running when apptainer running on CentOS7 exits from a shell, there is an INFO message
```
INFO:    Cleanup error: while stopping driver for /var/lib/apptainer/mnt/session/final: fuse-overlayfs exited
```

### Steps to reproduce this behavior

```
$ apptainer shell docker://alpine
Apptainer> sleep 1800 &
Apptainer> exit
INFO:    Cleanup error: while stopping driver for /var/lib/apptainer/mnt/session/final: fuse-overlayfs exited
```

### What OS/distro are you running

CentOS7

### How did you install Apptainer

```
yum install --enablerepo=epel-testing apptainer
```

**Comment by DrDaveD** [comment]
I forgot to mention that this is non-suid mode.  Suid mode uses overlayfs instead.

**Comment by plopresti** [comment]
I believe we are encountering the same issue:

`INFO:    Cleanup error: while stopping driver for /var/lib/apptainer/mnt/session/rootfs: squashfuse_ll exited`

Our platform is Alma 9 using apptainer-1.3.0-1.el9.x86_64.rpm from EPEL.

Is a fix or work-around available?

**Comment by DrDaveD** [comment]
I plan on fixing this for 1.3.1.  Meanwhile you can ignore it because it doesn't indicate a real error, or use `apptainer -q` to hide INFO messages.

**Comment by DrDaveD** [comment]
Indeed, with apptainer-suid on el7 it prints out the `squashfuse_ll exited` version of the message, as does unprivileged on el9 because there overlayfs is also used instead of fuse-overlayfs (and also apptainer-suid on el9).

It's actually not a very good thing to leave a process running when exiting apptainer, so in some ways it's good to have a message, but it would be better if the message was more helpful.  I have experienced a lot of problems with a background apptainer subprocess not preventing the unmount of an auto-mounted FUSE filesystem (specifically the CernVM FileSystem) but not letting the FUSE process exit since it is still mounted in another namespace.
