### ISSUE TITLE
Loopback SSH inside container

### ISSUE THREAD

**Issue by RichardMuri** [apptainer/apptainer#2118]
I would like to be able to ssh from inside my container back into itself in a loopback. I'm not sure the preferred method to do this.

### Version of Apptainer

`singularity-ce version 4.1.2-1.el8`

### Expected behavior

I am using a launch script that was provided by an applicationI build inside of a container. The script is capable of launching application instances on multiples hosts; in this case it uses 127.0.0.1 as its only host. I expect connecting to localhost from within a container to connect back into the container.

### Actual behavior

The connection to localhost escapes my container and connects back to the actual machine. This breaks the script because the application it expects to exist is not available on the host OS.

### Steps to reproduce this behavior

1. Add localhost to your known hosts file
2. Launch a container that maps ~/.ssh into the container
3. ssh 127.0.0.1

### What OS/distro are you running

AlmaLinux 8.9 (Midnight Oncilla)

### How did you install Apptainer
It was installed by the maintainers of the cluster I use so I'm not sure, but probably via RPM.

**Comment by DrDaveD** [comment]
Since this is singularity-ce, please instead submit your issue to https://github.com/sylabs/singularity.
