### ISSUE TITLE
WIth ORAS source,  pull does not show progress bar and push fails on v1.3.0

### ISSUE THREAD

**Issue by maouw** [apptainer/apptainer#2122]
### Version of Apptainer

`apptainer version 1.3.0`

### Expected behavior

- `apptainer pull` from `oras://*` should display progress bar
- `apptainer push` to `oras://*` should succeed if reached 100%

### Actual behavior

- `apptainer pull` from `oras://ghcr.io/*` does not display progress bar
- `apptainer push`  to `oras://ghcr.io/*` shows progress bar but fails to complete even after reaching 100%

### Steps to reproduce this behavior

- Pull a container, or
- Build a container and push

Note: The images involved are very large (10+ GB)

### What OS/distro are you running

Ubuntu 22.04 `jammy` on `Pop! OS` and on GitHub Runners

### How did you install Apptainer

Install from `https://github.com/apptainer/apptainer/releases/download/v1.3.0/apptainer_1.3.0_amd64.deb`

**Comment by JasonYangShadow** [comment]
@maouw thanks so much for the report! I will take care of this issue and update the progress here.
