### ISSUE TITLE
Documentation is unclear or incomplete, how to use apptainer with lima. How to build container on MacBook.

### ISSUE THREAD

**Issue by sorenwacker** [apptainer/apptainer#2148]
Hi,

the documentation says "Apptainer is available via Lima", and then gives this quick notes:
```
$ /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
$ brew install qemu lima
Then do limactl start template://apptainer and limactl shell apptainer.
```
But then it does not explain how to use it, or what this actually does. 

After starting `limactl shell apptainer`, my prompt changes, and it looks like I am in a type of virtual environment. But then typing `apptainer` returns `command not found`.

How can I build a container on Mac?

**Comment by GodloveD** [comment]
You mean [here](https://apptainer.org/docs/user/latest/)?  I don't see any mention of Lima in the docs, but maybe I'm missing it.  If this is actually an issue in the Apptainer docs, please raise an issue (and maybe a PR??) [here](https://github.com/apptainer/apptainer-userdocs).

**Comment by DrDaveD** [comment]
This must be referring to the admin docs [here](https://apptainer.org/docs/admin/latest/installation.html#mac).

@afbjorklund is the expert on that.

**Comment by afbjorklund** [comment]
> After starting limactl shell apptainer, my prompt changes, and it looks like I am in a type of virtual environment.

This is expected...

> But then typing apptainer returns command not found.

... but this is not.

---

It is supposed to start a VM running Ubuntu LTS, and then install the latest Apptainer from the official PPA:

https://github.com/lima-vm/lima/blob/master/examples/apptainer.yaml

Hopefully there are some log files, which are located under `~/.lima/apptainer`, that tell what went wrong...

Using `apptainer.lima` (or just `apptainer` on Mac) is supposed to work too, but has some usability issues.

**Comment by afbjorklund** [comment]
> I don't see any mention of Lima in the docs, but maybe I'm missing it.

The user documentation mentions it here: https://apptainer.org/docs/user/latest/quick_start.html#installation

"using Apptainer on Mac and Windows machines are discussed in the installation section of the admin guide"

Currently there are no Mac-specific instructions, in the user documentation.

**Comment by sorenwacker** [comment]
I was refering to this `https://apptainer.org/docs/admin/main/installation.html`.
I am not sure what went wrong the first time I tried this. Now it works. 

Maybe this command was missing:

```
limactl create --name=apptainer template://apptainer
```

Then 
```
limactl start apptainer
```

and
```
limactl shell apptainer
```

**Comment by sorenwacker** [comment]
I was able to build containers with Lima after all, but then shipping them to the cluster and running them there did not work. Does the apptainer depend on the CPU architecture ? It seems containers that have been build on a newer MacBook don't run on Linux? Or might there be other issues, like the apptainer versions could be different on the cluster and on my local machine.

**Comment by afbjorklund** [comment]
`apptainer inspect` is supposed to be able to show you the architecture of a .sif file

As far as I know, there is no "multi-arch" or "manifest list" version of SIF

**Comment by sorenwacker** [comment]
Thank you for your comment. I will try that.

**Comment by afbjorklund** [comment]
One workaround is to create two VMs, and run one of the builds in "slow motion".

```
limactl start --name amd64 --arch x86_64 template://apptainer

limactl start --name arm64 --arch aarch64 template://apptainer
```

Setting something up with binfmt_misc would also work, but take some more effort...

See https://wiki.debian.org/QemuUserEmulation

It would run qemu-user instead of qemu-system.
