### ISSUE TITLE
OpenSSH Post-Install Script fails due to `groupadd` failure

### ISSUE THREAD

**Issue by kkaulen** [apptainer/apptainer#2153]
### Version of Apptainer

`apptainer version 1.3.0-1.el8`

### Expected behavior

Installation of `openssh-client` does not fail under Ubuntu 20.04. Possibly related to #1822 . 

### Actual behavior

Installation failed with this error output in the post-installation script of `openssh-client`:

```
Setting up openssh-client (1:8.2p1-4ubuntu0.11) ...
groupadd: failure while writing changes to /etc/group
addgroup: `/sbin/groupadd -g 101 ssh' returned error code 10. Exiting.
dpkg: error processing package openssh-client (--configure):
 installed openssh-client package post-installation script subprocess returned error exit status 1
Setting up libxext6:amd64 (2:1.3.4-0ubuntu1) ...
Setting up xauth (1:1.1-0ubuntu1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.14) ...
Errors were encountered while processing:
 openssh-client
E: Sub-process /usr/bin/dpkg returned an error code (1)
FATAL:   While performing build: while running engine: exit status 100
```

### Steps to reproduce this behavior

Use the following Apptainer definition file.

```
Bootstrap: docker
From: ubuntu:22.04


%post
    apt-get update && \
    apt-get -y install openssh-client
```

Run `apptainer build test.sif apptainer.def` and observe error.

### What OS/distro are you running

`Rocky Linux 8.9 (Green Obsidian)`

### How did you install Apptainer

I am not completely sure, as the error occurs on a compute cluster that I do not maintain. However, I suppose the installation was done by compiling from source, as I do not find a GH release corresponding to version 1.3.0-1.el8.

**Comment by kkaulen** [comment]
For a possible workaround, see my comment on the possibly related issue: https://github.com/apptainer/apptainer/issues/1822#issuecomment-2051581258

**Comment by DrDaveD** [comment]
Thanks for the report.  What are the messages you see from the beginning of the `apptainer build` command?

**Comment by kkaulen** [comment]
I get the following output in the beginning:
```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    Could not start root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Using --fix-perms because building from a definition file
INFO:     without either root user or unprivileged user namespaces
INFO:    Starting build...
Getting image source signatures
Copying blob 3c645031de29 done   |
Copying config 7af9ba4f0a done   |
Writing manifest to image destination
2024/04/16 10:37:10  info unpack layer: sha256:3c645031de2917ade93ec54b118d5d3e45de72ef580b8f419a8cdc41e01d042c
WARNING: The --fix-perms option modifies the filesystem permissions on the resulting container.
INFO:    Running post scriptlet
```

**Comment by DrDaveD** [comment]
Oh, this is a setuid installation with user namespaces disabled.   That is fakeroot mode 4 in the [documentation](https://apptainer.org/docs/user/latest/fakeroot.html).  That is known to fail for some package installations, including openssh-cilent.  Try to get your system administrator to re-enable user namespaces, which is the default on el8.  Otherwise you'll just have to build that container on another machine.
