### ISSUE TITLE
Possible clarification in built-in help for `apptainer verify`

### ISSUE THREAD

**Issue by pontus** [apptainer/apptainer#2159]
### Version of Apptainer

Git as of 17 Apr 2024 (8028a3889278621775ceefa52133f3abaf221d77)
```
.pontus@lalage:~/Utveckling/apptainer/builddir$ ./apptainer version
1.3.0+170-g8028a3889-dirty
pontus@lalage:~/Utveckling/apptainer/builddir$ 
```

In a recent discussion (https://apptainer.slack.com/archives/C02NGSXR84U/p1713286266725849), there was some confusion with `verify` as the built in help can be misinterpreted (read in a way that doesn't match what it does). The confusion was that it was read as `sif-id` specifying the signature object to use for verification

```
pontus@lalage:~/Utveckling/apptainer/builddir$ ./apptainer verify --help | grep sif-id
  -i, --sif-id uint32                      verify object with the specified ID
pontus@lalage:~/Utveckling/apptainer/builddir$ 
```

can `verify object with the specified ID` possibly be rephrased as `ID of object you want to verify (if not set, all relevant objects are verified)`or similar? I think the current text leans the right way, but it can be clearer and it might be helpful to to mention that it checks only that object if passed rather than most in the file.

This seems to be at https://github.com/apptainer/apptainer/blob/8028a3889278621775ceefa52133f3abaf221d77/cmd/internal/cli/verify.go#L78

**Comment by jrwds** [comment]
https://github.com/apptainer/apptainer-userdocs/pull/271 has a minor doc edit that might help clarify.

My confusion mostly lie in not understanding that signatures are verified per object. The initial error I had gotten of `Error encountered during signature verification: signature object 5 not valid: dsse: verify envelope failed: accepted signatures do not match threshold, Found: 0, Expected 1` made me think that I was thinking along the right lines, and that I needed both signatures to verify the container/group.

The error makes sense, and the --help for verify makes sense too; I think this is just a minor doc change for future readers. I had read "Each object has an ID, and belongs to a GROUP." in https://apptainer.org/docs/user/latest/signNverify.html#advanced-signing-sif-ids-and-groups with the assumption that the signatures themselves were also objects, given they had ID's (perhaps my OOP instincts) and thus also had groups (indirectly, through the link).

I had assumed too that the signatures were applied to the group object as a whole (1 object of 4 underlying objects), and so when verifying a container with only 1 group, one would just supply the .pub/.pem (thus verifying the only group object available to verify in the container). _If this were how Apptainer works, it would be unable to identify which underlying container objects were changed, hence why it is the way it is._
