### ISSUE TITLE
Encrypted containers are not releasing loop devices in 1.3.0

### ISSUE THREAD

**Issue by stefdoerr** [apptainer/apptainer#2175]
### Version of Apptainer

```
apptainer version 1.3.0
```

### Expected behavior

When an encrypted container stops executing it should free the loop device

### Actual behavior

In 1.3.0 each execution of an encrypted container occupies a loop device and never releases it. After some hundred executions eventually the OS runs out of loop devices and throws an error. In version 1.1.3, 1.2.0 and 1.2.5 it works correctly and releases the loop devices.

It's quite critical for us since we currently need to reboot our machines to free up the loop devices again.

### Steps to reproduce this behavior

Create encrypted.def

```
Bootstrap: docker
From: mambaorg/micromamba:jammy

%runscript
  ls -lh
```

build it with

```
sudo env APPTAINER_ENCRYPTION_PASSPHRASE=XXXXX TMPDIR=/tmp/ /usr/bin/apptainer build --encrypt --force encrypted.sif encrypted.def
```

then run

```
export APPTAINER_ENCRYPTION_PASSPHRASE=XXXXX 
apptainer run encrypted.sif

losetup --list  | grep encrypted
```
You will see that after the execution the loop device is still occupied. Try calling it a few more times and you will see the devices accumulate.

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer

Ubuntu apt

**Comment by DrDaveD** [comment]
Thanks for the report.  Fixed in #2177.
