### ISSUE TITLE
example bootstrap: yum container for Rocky Linux

### ISSUE THREAD

**Issue by anderbubble** [apptainer/apptainer#2196]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

GitHub main

### Expected behavior

There should be a `BootStrap: yum` example container for Rocky Linux at https://github.com/apptainer/apptainer/tree/main/examples.

### Actual behavior

There is no example container for Rocky Linux at https://github.com/apptainer/apptainer/tree/main/examples.

### References

See also: https://github.com/apptainer/apptainer/blob/main/examples/centos/Apptainer

**Comment by anderbubble** [comment]
@JasonYangShadow any chance you could do this? @mslacken mentioned he tried to do it a little while back and he ran into some trouble, but I'm not sure what.

@DrDaveD do the docs need to be updated, also? Or are these just here and otherwise unreferenced?

**Comment by GodloveD** [comment]
I have a def file saved in a sif on docker hub that I can supply when I'm at a keyboard.
