### ISSUE TITLE
Missing EGL ICD when using --nv

### ISSUE THREAD

**Issue by yghorbal** [apptainer/apptainer#2210]
### Version of Apptainer

`apptainer version 1.2.5`

### Expected behavior

When running with `--nv` apptainer needs to map EGL ICD `/usr/share/glvnd/egl_vendor.d/10_nvidia.json` same as NVIDIA Container Toolkit is doing per https://github.com/NVIDIA/nvidia-docker/issues/1520#issuecomment-1419071440
If not EGL initialisation fails (with `eglinfo`)

### Actual behavior

`/usr/share/glvnd/egl_vendor.d/10_nvidia.json` is not mapped and `eglinfo` fails

### Steps to reproduce this behavior

- install apptainer on a host with Nvidia GPU and proprietary drivers
- create a sif file `apptainer build --fakeroot eglinfo.sif eglinfo.recipe`

```
$ cat eglinfo.recipe
Bootstrap: docker
From: ubuntu:22.04
%post
    apt-get update -y
    apt-get install -y mesa-utils
    apt-get clean all
%runscript
    exec "${1+"$@"}"
```

- `apptainer run --nv eglinfo.sif eglinfo` (without the mapping)
```
[...]
Device platform:
eglinfo: eglInitialize failed
[...]
```
- `apptainer run --nv -B /usr/share/glvnd/egl_vendor.d/10_nvidia.json eglinfo.sif eglinfo` (with manually mapping the definition json)
```
[...]
Device platform:
EGL API version: 1.5
EGL vendor string: NVIDIA
EGL version string: 1.5
EGL client APIs: OpenGL_ES OpenGL
EGL extensions string:
[...]
```

### What OS/distro are you running

```
cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```

### How did you install Apptainer

from source

**Comment by GodloveD** [comment]
Looking at this and trying to gather more information.  

First, I will note that `10_nvidia.json` does seem to be part of the driver.  If I extract a `.run` file and look at the contents it's there.  So it does seem like a good candidate to automatically add into the container.  

However, we don't currently have a method for adding random files.  We can only add libraries and binaries.  To add libraries, we search `/etc/ld.so.cache` for the appropriate library locations.  To add binaries I believe we just search the `$PATH`.  I don't think that we should assume the location of the driver installation, so the question becomes "How do we locate (in a performant way) the `10_nvidia.json` file on a particular system?"

I'm tempted to suggest that this is rarely needed (since I think this is the first request that I'm aware of) and it should therefore be something the user binds if they need to.  Perhaps fix with documentation?  Unsure.  

Any idea how the NVIDIA container toolkit tackles this issue?

**Comment by yghorbal** [comment]
Hi, 

Sorry for the long delay! We install drivers through RPM packages provided by Nvidia (not the .run) 
The file `10_nvidia.json` is shipped with the `nvidia-driver-libs` package (which is a dependency for `nvidia-driver` package)
On the Nvidia Container Toolkit, they have a concept of a aggregation of _paths_ that represent _config_ These locations get searched for the list of files to be mounted (the `10_nvidia.json` is not the only one) see https://github.com/NVIDIA/nvidia-container-toolkit/blob/f13f1bdba4ae34506f301e53e01644791771c4d4/internal/discover/graphics.go#L66
The so called config locations searched can be user supplied and defaults to `/etc`, `/usr/local/share` and `/usr/share` as per https://github.com/NVIDIA/nvidia-container-toolkit/blob/f13f1bdba4ae34506f301e53e01644791771c4d4/internal/lookup/root/root.go#L59

**Comment by panda1100** [comment]
This is not direct answer to this issue but share sample definition file I used for ParaView +  GL Vendor-Neutral Dispatch library, just for your reference

### ParaView EGL build Container Definition File

Create definition file called `paraview_5.11.0-egl.def` based on Rocky Linux 9 image. Outline of this definition file is the following:

Install `libglnvd` The GL Vendor-Neutral Dispatch library and configuration file `10_nvidia.json` to use EGL library `libEGL_nvidia.so.0` supplied from NVIDIA. `10_nvidia.json` and `libEGL_nvidia.so.0` are included in NVIDIA GPU driver so that your NVIDIA GPU equipped host systems are most likely already has these files.


```
$ cat /etc/glvnd/egl_vendor.d/10_nvidia.json
{
    "file_format_version" : "1.0.0",
    "ICD" : {
        "library_path" : "libEGL_nvidia.so.0"
    }
}
```

Install EGL build ParaView from Kitware

`paraview_5.11.0-egl.def `

```
Bootstrap: docker
From: rockylinux:9
%post
dnf install -y libglvnd libglvnd-egl libglvnd-opengl wget
wget -P /etc/glvnd/egl_vendor.d https://gitlab.com/nvidia/container-images/opengl/-/raw/centos8/glvnd/runtime/10_nvidia.json
%post
dnf install -y libxcrypt-compat
mkdir -p /opt/ParaView/5.11.0
wget -O ParaView-5.11.0-egl.tar.gz "https://www.paraview.org/paraview-downloads/download.php?submit=Download&version=v5.11&type=binary&os=Linux&downloadFile=ParaView-5.11.0-egl-MPI-Linux-Python3.9-x86_64.tar.gz"
tar -C /opt/ParaView/5.11.0 -zxvf ParaView-5.11.0-egl.tar.gz --strip-components 1
rm ParaView-5.11.0-egl.tar.gz
%environment
export PATH=/opt/ParaView/5.11.0/bin:$PATH
%runscript
/opt/ParaView/5.11.0/bin/pvserver
Build ParaView container called paraview_5.11.0-egl.sif .
```

```
$ apptainer build paraview_5.11.0-egl.sif paraview_5.11.0-egl.def
```

Run Containerized EGL build ParaView server

```
$ apptainer run --nv paraview_5.11.0-egl.sif
Waiting for client...
Connection URL: cs://a16:11111
Accepting connection(s): a16:11111
```

**Comment by ehfd** [comment]
Also would like to point out the requirement of `/usr/share/vulkan/icd.d/nvidia_icd.json` for Vulkan:

```
{
    "file_format_version" : "1.0.0",
    "ICD": {
        "library_path": "libGLX_nvidia.so.0",
        "api_version" : "1.3.277"
    }
}
```

(`api_version` is different per driver version)

**Comment by ehfd** [comment]
> I'm tempted to suggest that this is rarely needed (since I think this is the first request that I'm aware of) and it should therefore be something the user binds if they need to. Perhaps fix with documentation? Unsure.

Note that it could be possible to just automatically write contents of these files at the start of `apptainer --nv` after detecting the files in the host, if bind mounting is tricky.

**Comment by ehfd** [comment]
```
INFO[0000] Using /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.555.58.02
INFO[0000] Auto-detected mode as 'nvml'
INFO[0000] Selecting /dev/nvidia0 as /dev/nvidia0
INFO[0000] Selecting /dev/dri/card0 as /dev/dri/card0
WARN[0000] Could not locate /dev/dri/controlD64: pattern /dev/dri/controlD64 not found
INFO[0000] Selecting /dev/dri/renderD128 as /dev/dri/renderD128
INFO[0000] Using driver version 555.58.02
INFO[0000] Selecting /dev/nvidia-modeset as /dev/nvidia-modeset
INFO[0000] Selecting /dev/nvidia-uvm-tools as /dev/nvidia-uvm-tools
INFO[0000] Selecting /dev/nvidia-uvm as /dev/nvidia-uvm
INFO[0000] Selecting /dev/nvidiactl as /dev/nvidiactl
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-egl-gbm.so.1.1.1 as /usr/lib/x86_64-linux-gnu/libnvidia-egl-gbm.so.1.1.1
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1.1.13 as /usr/lib/x86_64-linux-gnu/libnvidia-egl-wayland.so.1.1.13
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.555.58.02
WARN[0000] Could not locate libnvidia-vulkan-producer.so.555.58.02: pattern libnvidia-vulkan-producer.so.555.58.02 not found
64-bit library libnvidia-vulkan-producer.so.555.58.02: not found
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so as /usr/lib/x86_64-linux-gnu/nvidia/xorg/nvidia_drv.so
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/nvidia/xorg/libglxserver_nvidia.so.555.58.02 as /usr/lib/x86_64-linux-gnu/nvidia/xorg/libglxserver_nvidia.so.555.58.02
INFO[0000] Selecting /usr/share/glvnd/egl_vendor.d/10_nvidia.json as /usr/share/glvnd/egl_vendor.d/10_nvidia.json
INFO[0000] Selecting /usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json as /usr/share/egl/egl_external_platform.d/15_nvidia_gbm.json
INFO[0000] Selecting /usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json as /usr/share/egl/egl_external_platform.d/10_nvidia_wayland.json
INFO[0000] Selecting /usr/share/nvidia/nvoptix.bin as /usr/share/nvidia/nvoptix.bin
INFO[0000] Selecting /usr/share/X11/xorg.conf.d/10-nvidia.conf as /usr/share/X11/xorg.conf.d/10-nvidia.conf
WARN[0000] Could not locate X11/xorg.conf.d/nvidia-drm-outputclass.conf: pattern X11/xorg.conf.d/nvidia-drm-outputclass.conf not found
INFO[0000] Selecting /usr/share/vulkan/icd.d/nvidia_icd.json as /etc/vulkan/icd.d/nvidia_icd.json
WARN[0000] Could not locate vulkan/icd.d/nvidia_layers.json: pattern vulkan/icd.d/nvidia_layers.json not found
pattern vulkan/icd.d/nvidia_layers.json not found
INFO[0000] Selecting /usr/share/vulkan/implicit_layer.d/nvidia_layers.json as /etc/vulkan/implicit_layer.d/nvidia_layers.json
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libcuda.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libcuda.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libcudadebugger.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libcudadebugger.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvcuvid.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvcuvid.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-gpucomp.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-gpucomp.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-ngx.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-ngx.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-nvvm.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-nvvm.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-pkcs11-openssl3.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-pkcs11-openssl3.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-pkcs11.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-pkcs11.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.555.58.02
INFO[0000] Selecting /usr/lib/x86_64-linux-gnu/libnvoptix.so.555.58.02 as /usr/lib/x86_64-linux-gnu/libnvoptix.so.555.58.02
INFO[0000] Selecting /run/nvidia-persistenced/socket as /run/nvidia-persistenced/socket
WARN[0000] Could not locate /nvidia-fabricmanager/socket: pattern /nvidia-fabricmanager/socket not found
WARN[0000] Could not locate /tmp/nvidia-mps: pattern /tmp/nvidia-mps not found
INFO[0000] Selecting /lib/firmware/nvidia/555.58.02/gsp_ga10x.bin as /lib/firmware/nvidia/555.58.02/gsp_ga10x.bin
INFO[0000] Selecting /lib/firmware/nvidia/555.58.02/gsp_tu10x.bin as /lib/firmware/nvidia/555.58.02/gsp_tu10x.bin
INFO[0000] Selecting /usr/bin/nvidia-smi as /usr/bin/nvidia-smi
INFO[0000] Selecting /usr/bin/nvidia-debugdump as /usr/bin/nvidia-debugdump
INFO[0000] Selecting /usr/bin/nvidia-persistenced as /usr/bin/nvidia-persistenced
INFO[0000] Selecting /usr/bin/nvidia-cuda-mps-control as /usr/bin/nvidia-cuda-mps-control
INFO[0000] Selecting /usr/bin/nvidia-cuda-mps-server as /usr/bin/nvidia-cuda-mps-server
INFO[0000] Generated CDI spec with version 0.8.0
```

Fresh out of the container toolkit. Contains which JSON files they inject.

**Comment by GodloveD** [comment]
We had a nice discussion about this in the community meeting today.  I think that we probably want to add a new section to the `nvliblist.conf` file to add non-library and non-executable files.  The section should contain the full, absolute path to each file that should be added.  We'll add these files to the default conf file and then users can customize if they have files installed in non-standard locations or if there are other files that they need to be automatically added with `--nv`.

**Comment by ehfd** [comment]
Sounds good. But they do still need to be mapped adequately (for instance `/etc` vs `/usr/share`)

**Comment by DrDaveD** [comment]
Library files are already always mapped into /.singularity.d/libs and found via LD_LIBRARY_PATH.  We're talking here about non-library paths, so hopefully those can just be mapped straight through without any mapping.  I think we should probably support the syntax of the `-B` option though, where the host path and container path can both be listed separated by a colon, and if a colon is not present they are expected to be the same both inside and outside.

Note that at build time these files will be subject to the same constraint discussed in #1314 where the build script will have to create the mountpoint.

**Comment by JasonYangShadow** [comment]
@DrDaveD
sorry for a double confirmation for this issue. Just had a deep look at the source code. 
we are currently using `nvliblist.conf` to automatically locate the libraries and bins
https://github.com/JasonYangShadow/apptainer/blob/35d693d63ac960a558ef686753dacdf4767c10fa/etc/nvliblist.conf#L10

https://github.com/JasonYangShadow/apptainer/blob/35d693d63ac960a558ef686753dacdf4767c10fa/internal/pkg/runtime/launch/launcher_linux.go#L886

so we want to support locating and binding above needed configuration files (json files) as well?

**Comment by DrDaveD** [comment]
We want full paths listed in /etc/apptainer/nvliblist.conf to be bound in to the same location as the host if they exist on the host.

I'm not sure if we need to list all the files in the nvidia-container-toolkit but I suppose it's a good idea.  I assume they're all in /usr/share if they are installed.  On the machine that I have access to which has an nvidia gpu I see `/usr/share/glvnd/egl_vendor.d/` and `/usr/share/egl/egl_external_platform.d/` but they don't have the listed files, and the other directories `/usr/share/vulkan` and `/usr/share/nvidia` don't exist at all.

**Comment by JasonYangShadow** [comment]
I could not test the above PR because I do not have a Nvidia GPU device installed. Though I added unit test cases, a real test is better in this case. 😿

**Comment by DrDaveD** [comment]
@yghorbal can you test if #2572 does what you're looking for?
