### ISSUE TITLE
v1.3.1 Docker credentials not read from ~/.docker/config.json

### ISSUE THREAD

**Issue by kshakir** [apptainer/apptainer#2228]
### Version of Apptainer

```sh
$ apptainer --version
apptainer version 1.3.1-1.el7
$ 
```

### Expected behavior

If one only has a `~/.docker/config.json` then the credentials should be read from this file path, as [stated in the apptainer documentation](https://apptainer.org/docs/user/1.3/docker_and_oci.html#docker-cli-authentication).

### Actual behavior

Only the file `~/.apptainer/docker-config.json` is searched for credentials.

#### Remove your apptainer docker-config.json
```sh
# for example: rm ~/.apptainer/docker-config.json
```

#### Remove your docker configuration directory
```sh
# for example: rm ~/.docker/config.json
```

#### Login to DockerHub
```sh
$ apptainer registry login -u [elided] docker://docker.io
Password / Token: 
INFO:    Token stored in /[elided]/.apptainer/remote.yaml
$ 
```

NOTE: As we'll see, the token is NOT stored in that file… but that message isn't really the issue.

#### Try to pull a private docker image (this works)
```sh
# Don't need to pull the whole image, so using `timeout` which logs in, but then produces an error when terminated
$ timeout 3s apptainer -s build temp.sif docker://somerepo/someimg:sometag
FATAL:   While performing build: while creating squashfs: create command failed: exit status 1: 
$ 
```

#### Move the file containing the token to `~/.docker/config.json`

```sh
$ mkdir ~/.docker
$ mv ~/.apptainer/docker-config.json ~/.docker/config.json
$ 
```

#### (Optional) Verify your username and password are stored within the `~/.docker/config.json`
```sh
$ jq -r '.auths["docker.io"].auth' ~/.docker/config.json | base64 -d && echo
[elided]
$ 
```

#### Try to pull the same private image, but using ~/.docker/config.json (should work but doesn't)
```sh
$ timeout 3s apptainer -s build temp.sif docker://somerepo/someimg:sometag
FATAL:   While performing build: conveyor failed to get: while converting reference: reading manifest sometag in docker.io/someimg/sometag: requested access to the resource is denied
$ 
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.9 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.9:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
$ 
```

### How did you install Apptainer

Was probably installed via RPM by our I/T department.

### Other notes:

If this feels like a repeat, it is. This was filed as #1616 and then fixed in [v1.2.3](https://github.com/apptainer/apptainer/releases/tag/v1.2.3). I can only guess that [PR #1866](https://github.com/apptainer/apptainer/pull/1866/files#diff-1111a41c999ddca87c999faf1959c090a7db590e666403b4031d5dc85d5240eeL78-R90) recreated the issue.

For anyone else looking for a workaround, I recommend users on our cluster link the path apptainer is looking for credential info back to the place docker and others are looking for credential info:

```sh
$ ln -sf ~/.docker/config.json ~/.apptainer/docker-config.json 
```

I'm not sure of the full extent of the side effects of this symlink on `apptainer registry login`. But apptainer seems happy with the linking on our system, along with third-party tools like `gcloud auth configure-docker` that only write to the file `~/.docker/config.json`.

Alternatively, it's possible that apptainer only wants to support the `~/.apptainer/docker-config.json`, in which case this is a documentation bug, as referred to in the "expected behavior" above.

**Comment by DrDaveD** [comment]
@JasonYangShadow please take a look at this

**Comment by JasonYangShadow** [comment]
@kshakir thanks so much for the detailed investigation and report. Yeah, this issue is recreated by upgrading the oras-go library in 1.3.x.  I will take a look at this issue and will update here.

**Comment by JasonYangShadow** [comment]
@DrDaveD cc @ikaneshiro @cclerget 
I checked the code, apptainer uses `oci pull` func to pull images from docker registry
https://github.com/JasonYangShadow/apptainer/blob/291d31b443182ba1ad7a3ef5ce28546a8388b04e/internal/pkg/client/oci/pull.go#L41
the code is pretty much not changed in the last year. 
PR mentioned here https://github.com/apptainer/apptainer/pull/1669 are changes for oras protocol. 
Every time when I try pulling images from docker hub, I always get the following error
```
FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://jasonyangshadow/alpine:latest: reading manifest latest in docker.io/jasonyangshadow/alpine: requested access to the resource is denied
```
it looks like the `ocitypes.SystemContext` has the correct value, but the pulling always fails. 
Any ideas?

**Comment by DrDaveD** [comment]
The only idea I have is to try it with older versions to see if it used to work, and if so figure out when it changed.

**Comment by JasonYangShadow** [comment]
> The only idea I have is to try it with older versions to see if it used to work, and if so figure out when it changed.

Thanks! I traced back to old releases, found that starting from 1.2.0, this issue occurs

https://github.com/apptainer/apptainer/blob/98803e296e7e1524da973c4c800bd3c1d67f181d/internal/pkg/build/oci/oci.go#L244
this line start reporting errors since 1.2.0, might caused by the modification of `types.SystemContext` , still verifying that.
