### ISSUE TITLE
No access to usernames except myself in apptainer container

### ISSUE THREAD

**Issue by remtav** [apptainer/apptainer#2245]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

```bash
apptainer version 1.2.1
```

### Expected behavior

With a simple "ls -l", I expected to have access to owner usernames for files/directories. This works outside a container, but not inside.

![image](https://github.com/apptainer/apptainer/assets/34774759/45aff895-dd64-48e4-8ae0-cb99b08ccb63)

### Actual behavior

I only have access to user ids:

![image](https://github.com/apptainer/apptainer/assets/34774759/2cc0d618-6a67-40b4-816a-4d4144fa4554)

### Steps to reproduce this behavior

```bash
apptainer pull ubuntu-latest.sif docker://ubuntu:latest
ls -l /path/to/my/directory
```

### What OS/distro are you running

```sh
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

### How did you install Apptainer

Installed by my HPC. Unaware of installation details.

**Comment by DrDaveD** [comment]
Yes that's normal, expected behavior with the suid mode of Apptainer, which you must be using.  I think you can probably work around it with `-B /etc/passwd,/etc/group`.   In unprivileged user namespace mode, every user and group except the original user will show up as "nobody".
