### ISSUE TITLE
Problems getting the CernVM-FS client working from inside of a container.

### ISSUE THREAD

**Issue by JacekHoleczek** [apptainer/apptainer#2247]
I am having problems getting the CernVM-FS client working from inside of a container (I started a thread on the [Apptainer slack -> general](https://apptainer.slack.com/archives/C02NGSXR84U/p1716275438155519) channel).

The new "apptainer 1.3.1" on Ubuntu 22.04 (and the old "singularity-ce 3.11.3" on Ubuntu 18.04) report:

```
CernVM-FS: loading Fuse module... cannot create workspace directory /var/lib/cvmfs/shared (9 - cache directory/plugin problem)
```

Adding a `CVMFS_USER=root` to `/etc/cvmfs/default.local` file lets me "`mount -t cvmfs ...`", but when I later exit the container, it generates mysterious "`failed to unmount`" / "`fuse: reading device: Software caused connection abort`" errors and one is left with 8  "`cvmfs2`" processes running on the host.

I then tried to play with the "`--fusemount`" option but it also failed reporting some "fuse" related errors.

I have also been advised to try the [cvmfsexec](https://github.com/cvmfs/cvmfsexec?tab=readme-ov-file#singcvmfs-command-mode-4) package, but its description explicitly says that it must be a RedHat or some "derived" system. My hosts are RedHat/CentOS 7, RedHat/AlmaLinux 9, and Ubuntu 22.04 / 18.04, while my containers (with the built-in CernVM-FS client) are "AlmaLinux 9" and "Ubuntu 22.04". I would like to get them working with the new "apptainer 1.3.1" (I can skip the old "singularity-ce 3.11.3" on Ubuntu 18.04, if it's too difficult to get it working).

**Comment by DrDaveD** [comment]
As discussed on slack, I don't think there's much that apptainer can do about this.  I recommend instead making a cvmfsexec feature request to support Debian & Ubuntu. 

The singcvmfs mode of cvmfsexec makes use of the `--fusemount` option of apptainer or singularity to start up cvmfs.  Without singcvmfs it's very challenging to use that option to start cvmfs.
