### ISSUE TITLE
Guidance on Choosing Between Apptainer and SingularityCE for Computational Materials Science Applications.

### ISSUE THREAD

**Issue by hongyi-zhao** [apptainer/apptainer#2248]
Hello Apptainer Team,

I am a researcher in the field of computational materials science, frequently using tools such as VASP, CP2K, and LAMMPS for my computational studies. I am currently evaluating container solutions to enhance the reproducibility and portability of my research environments across different computing systems.

Given the close relationship and history between [Apptainer](https://github.com/apptainer) and [SingularityCE](https://github.com/sylabs/singularity), I am seeking advice on which container solution would be more suitable for my specific use case. Here are some specific questions I have:

1. Are there any significant differences in performance or compatibility in HPC environments between Apptainer and SingularityCE when running applications like VASP, CP2K, and LAMMPS?
2. Has Apptainer introduced any new features or enhancements that are particularly beneficial for computational sciences, which might not be present in SingularityCE?
3. Considering the need for easy configuration and robustness, which platform would you recommend for someone primarily focused on computational materials science?

Your insights will be incredibly valuable to me and will greatly influence my decision on which technology to adopt for my research.

Thank you very much for your time and assistance.

Best regards,
Zhao

**Comment by hongyi-zhao** [comment]
Based on the above discussion, it seems I can draw the following conclusions:

1. Use these two tools together, install them side by side.
2. In some cases, such as when building an image, do it in SingularityCE because it supports more images repository.
3. Use Apptainer when actually using the image in a production environment.

Am I right?

Regards,
Zhao

**Comment by GodloveD** [comment]
1. You can totally install and use both.  Just make sure that the `singularity` command in not symlinked to `apptainer`.
2. No not really.  You can configure Apptainer to use the Sylabs library.  In practice I don't think you are going to find much there that you can't get elsewhere.  And ORAS deprecates the Sylabs library tbh.  
3. Yeah, I would say that the only reason you may want to use SingularityCE is if you need some OCI support that is absent from Apptainer.  But in that case I would honestly just use Podman (better supported etc.)

**Comment by DrDaveD** [comment]
It's not a good idea to install both apptainer and singularity-ce in the same installation prefix.  In addition to the `singularity` symlink, there is the `run-singularity` program that clashes.  But if you compile from source and use different installation prefixes that works fine.

**Comment by DrDaveD** [comment]
> if you compile from source and use different installation prefixes that works fine.

Or actually you can install apptainer binaries with [install-unprivileged.sh](https://apptainer.org/docs/admin/1.3/installation.html#install-unprivileged-from-pre-built-binaries) into any prefix without recompiling.

**Comment by hongyi-zhao** [comment]
> But if you compile from source and use different installation prefixes that works fine.

This should be the method with maximum flexibility control.

> Or actually you can install apptainer binaries with [install-unprivileged.sh](https://apptainer.org/docs/admin/1.3/installation.html#install-unprivileged-from-pre-built-binaries) into any prefix without recompiling.

I looked at the script, and the implementation logic seemed quite complex.

**Comment by hongyi-zhao** [comment]
> 3\. Yeah, I would say that the only reason you may want to use SingularityCE is if you need some OCI support that is absent from Apptainer.  But in that case I would honestly just use Podman (better supported etc.)

Although Podman is a powerful container management tool with advantages like being daemonless and supporting rootless operation, it is primarily aimed at general containerized applications and is not specifically optimized for HPC scenarios.

**Comment by GodloveD** [comment]
Exactly.  So if you want OCI type stuff (cloud native, microservices, K8s orchestration, etc.) use Podman.  If you want HPC type stuff (running containerized apps as jobs with very little abstraction between you and the actual container) use Apptainer.  

Apptainer doesn't have any trouble using OCI containers and registries.  It just doesn't implement any OCI runtime.  I don't see any advantages to using an OCI compatible runtime within HPC.  So I'd just stick with Podman for my non-HPC needs.
