### ISSUE TITLE
Facing Library link not found issue when launching Monolix 2024 in container through apptainer 

### ISSUE THREAD

**Issue by bangarusamyk** [apptainer/apptainer#2255]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? 
1.3.2

### Expected behavior

What did you expect to see when you do...?
Monolix 2024 installation works fine in regular rocky 8 machine and in ubuntu through wsl.

### Actual behavior

What actually happened? Why was it incorrect?
After installing Monolix 2024R1 successfully, when I try to launch Monolix in rocky 8, 9, Ubuntu container through apptainer, it's showing error like shared library libqt6corelix.so.6 is not found. But this Library is bundled in Monolix installer and available in lib directory similar to other libs but still executable through the error

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
Monolix 2024 R1 installer available in lixoft download portal and installation can be done by following installation instructions.
https://lixoft.com/download/lin64-monolix-suite-2024r1/

### What OS/distro are you running
rocky8, rocky9, ubuntu 22
```sh
$ cat /etc/os-release

```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.
Installed unprecedented from pre build binaries.

**Comment by DrDaveD** [comment]
Can you provide us a .def file to build a container?

**Comment by bangarusamyk** [comment]
> Can you provide us a .def file to build a container?

Hi @DrDaveD ,

below is the sample .def file. Please download Monolix 2024 installer from lixoft download portal (https://lixoft.com/download/lin64-monolix-suite-2024r1/).

```
Bootstrap: library
From: rockylinux:8

%labels
    Author HPC Team
    Maintainer
    URL

%files

%environment

%post
    echo "Installing required packages..."
    dnf install -y epel-release
    dnf install -y xcb-util-wm xcb-util-image xcb-util-keysyms xcb-util-renderutil gcc-c++ pcre2-utf16 xcb-util-cursor libX11-xcb libxkbcommon-x11 libglvnd-glx libglvnd-opengl libXi libxkbfile libglvnd-egl  pcre2-utf16 libglvnd-opengl fontconfig
    mkdir -p /tmp/monolix
    echo "Installing Monolix"
    /tmp/monolixSuite2024R1 in --am --al --c -t /tmp/monolix

%runscript
    echo "Installation is completed successfully"
    /tmp/monolix/MonolixSuite2024R1/bin/monolix.sh

%test

%help
```

**Comment by DrDaveD** [comment]
This is not an apptainer problem.  You need to add that lib directory to $LD_LIBRARY_PATH.

I changed it to `Bootstrap: docker` and I also had to install nss.

At that point it was able to find all libraries but died with `No valid license found`.
