### ISSUE TITLE
How to Submit Jobs from Materials Studio GUI running on Microsoft Windows to Apptainer Container with DS BIOVIA Materials Studio Installed on Ubuntu 22.04.4 LTS.

### ISSUE THREAD

**Issue by hongyi-zhao** [apptainer/apptainer#2256]
Hi everyone,

I need help with submitting jobs from the Materials Studio GUI running on Microsoft Windows to an Apptainer container that has DS BIOVIA Materials Studio 2023 (v23.1.0.3829-x64-LINUX) installed, running on Ubuntu 22.04.4 LTS.

Issues and Questions:

1. How can I configure the job submission script on the Windows Materials Studio GUI to target the Apptainer container on the Ubuntu system?

2. What are the best practices to ensure seamless network communication and job execution within the Apptainer container?

Any detailed steps or advice on achieving this setup would be highly appreciated.

Thank you!

Regards, Zhao

**Comment by DrDaveD** [comment]
This would require knowledge of the specific system you're asking about which we don't have, sorry.  You'll need to ask somebody who knows that system.
