### ISSUE TITLE
"apptainer --nv" does not inject libcudadebugger.so.1, required by newer cuda-gdb

### ISSUE THREAD

**Issue by plopresti** [apptainer/apptainer#2261]
### Version of Apptainer

`apptainer version 1.2.5-1.el9
`
### Expected behavior

When I run `apptainer --nv shell /path/to/some.sif`, I expect cuda-gdb to work. Also I expect `ls /.singuarity.d/libs` to include libcudadebugger.so.1.

### Actual behavior

Newer cuda-gdb requires libcudadebugger.so.1 in LD_LIBRARY_PATH. Without it, attempts to "run" anything under cuda-gdb fails with `Could not find CUDA Debugger back-end. Please try upgrading/re-installing the GPU driver`

### Steps to reproduce this behavior

`apptainer shell --nv /path/to/newish-cuda-image.sif`
`ls /.singularity.d/libcudadebugger.so.1`
`cuda-gdb some-cuda-program`
`run`

### What OS/distro are you running

Alma 9 but it doesn't matter

### How did you install Apptainer

From EPEL

**Comment by GodloveD** [comment]
Seems legit to me.  Want to add it to the `nvliblist.conf` and create a PR?

**Comment by plopresti** [comment]
Did not realize it was that easy. Done; thanks!
