### ISSUE TITLE
feature request: feasibility or documentation of supplementary group (for `chgrp`)

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [apptainer/apptainer#2292]
### Version of Apptainer

```console
$ apptainer --version
apptainer version 1.2.5
$ 
```

### Expected behavior

I want to run in a container a daemon that attempts to run `chgrp`. I don't have the sources and cannot change the daemon.

I don't expect `chgrp` to have any effect. Actually, I would like it to be interpreted as a no-op, as the underlying file system does not have POSIX semantics anyway.

In short, I need to be able to run from within the container:
```sh
Apptainer> mkdir /tmp/foo
Apptainer> chgrp neuro /tmp/foo
Apptainer> 
```
This seems to imply that:
* The program expects the `neuro` group to exist.
* The program expects the current user to belong to the `neuro` group, as a supplementary group.
* The current user is:
   ```sh
   Apptainer> id
   uid=500(service) gid=500(service) groups=500(service)
   Apptainer> 
   ```
* I could add the supplementary group `neuro` to the container. But then, I don't know how to make the current user, defined at run-time, a member of the `neuro` group, defined at build-time.
   ```sh
   Apptainer> cat /etc/passwd
   [...]
   service:x:500:500:MEGIN Service Account:/nonexistent:
   Apptainer> 
   Apptainer> cat /etc/group
   [...]
   service:x:500:service
   neuro:x:1001:service
   Apptainer> 
   Apptainer> id
   uid=500(service) gid=500(service) groups=500(service)
   Apptainer> id service
   uid=500(service) gid=500(service) groups=500(service),1001(neuro)
   Apptainer> 
   ```
   As you can see, there is a subtle distinction between the "current account", which is named `service` and has no supplementary group, and the explicitly named account `service`  which belongs to the `neuro` supplementary group. The two accounts share the same UID 500, GID 500, user name `service`, and primary group name `service`.
* I could add the supplementary group `neuro` to the host. But then, inside the container, that supplementary group maps to a group with GID 65534 and no name.
   ```sh
   Apptainer> id
   uid=500(service) gid=500(service) groups=500(service),65534
   Apptainer> id service
   uid=500(service) gid=500(service) groups=500(service),1001(neuro)
   Apptainer> 
   ```

Wouldn't it make sense to be able to handle supplementary groups in Apptainer? If not, I believe the documentation should somehow describe how the current user/group pair inherited from the host and whatever users/groups defined inside the container interact - actually they don't.

### Actual behavior

```sh
Apptainer> mkdir /tmp/foo
Apptainer> chgrp neuro /tmp/foo
chgrp: changing group of '/tmp/foo': Invalid argument
Apptainer> 
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Apptainer

It has been installed by IT. I know it's been installed from a DEB file:
```console
$ dpkg-query -s apptainer
Package: apptainer
Status: install ok installed
Priority: optional
Section: admin
Installed-Size: 113386
Maintainer: Gregory M. Kurtzer <gmkurtzer@gmail.com>
Architecture: amd64
Version: 1.2.5
Depends: libc6 (>= 2.16), libfuse2 (>= 2.6), libseccomp2 (>= 2.5.0), zlib1g (>= 1:1.1.4), uidmap, squashfs-tools, squashfuse, fuse2fs, fuse-overlayfs, fakeroot
Conflicts: singularity-container
Conffiles:
 /etc/apptainer/apptainer.conf 657abb07fc1da7faaaafcda98352b57d
 /etc/apptainer/capability.json d41d8cd98f00b204e9800998ecf8427e
 /etc/apptainer/cgroups/cgroups.toml b4f23ff26ab4e5f1e351faae5455d94b
 /etc/apptainer/dmtcp-conf.yaml 6cc3f4cd7073ed12c56be3761e0994e2
 /etc/apptainer/ecl.toml 77ff6d540855c830c366a8f26074fcc4
 /etc/apptainer/global-pgp-public d41d8cd98f00b204e9800998ecf8427e
 /etc/apptainer/network/00_bridge.conflist 02ecdf34297e5810308fffdf93ef7a9b
 /etc/apptainer/network/10_ptp.conflist 6078f7e1ffcd9a91f4bfa7bb532a066a
 /etc/apptainer/network/20_ipvlan.conflist 7af2fa9b5a2a0286abcd55f9ca61084b
 /etc/apptainer/network/30_macvlan.conflist 9d85c48d79d9c7a18d876079c48365e2
 /etc/apptainer/network/40_fakeroot.conflist 01bdddd5be744d0507a32990fdfad6fc
 /etc/apptainer/nvliblist.conf 151e10f5e128dc8e8d74ca02197bcbcb
 /etc/apptainer/remote.yaml 5ddc740430f6253a859304726f10a4de
 /etc/apptainer/rocmliblist.conf 3211f7389c2a9740d759cbd3960600e4
 /etc/apptainer/seccomp-profiles/default.json a0e0254fb53da5b2fb56a70766660cc7
Description: container platform focused on supporting "Mobility of Compute" formerly known as Singularity
 Mobility of Compute encapsulates the development to compute model
 where developers can work in an environment of their choosing and
 creation and when the developer needs additional compute resources,
 this environment can easily be copied and executed on other platforms.
 Additionally as the primary use case for Apptainer is targeted
 towards computational portability, many of the barriers to entry of
 other container solutions do not apply to Apptainer making it an
 ideal solution for users (both computational and non-computational)
 and HPC centers.
Homepage: http://apptainer.org
$ 
```
The official Apptainer doesn't work on my Ubuntu 22.04 workstation (see #2291) so I am stuck with this version on an Ubuntu 20.04 server.

**Comment by DimitriPapadopoulos** [comment]
For the record, in my case, I plan on working around this by making `neuro` the primary group of the `service` account on the host, so that:
```sh
Apptainer> id
uid=500(service) gid=1001(neuro) groups=1001(neuro)
Apptainer> 
Apptainer> mkdir /tmp/foo
Apptainer> chgrp neuro /tmp/foo
Apptainer> 
```

Hopefully, the daemon won't call `chgrp` with different supplementary groups as arguments!

**Comment by DrDaveD** [comment]
This is a fundamental limitation of user namespaces.  It can only map one group.  If you are willing to risk using suid mode, installing apptainer-suid restores that capability.

The process inside apptainer retains access to all the supplemental groups of its parent process, it's just that you can't change the default group.
