### ISSUE TITLE
squashfuse_ll doesn't work with --fakeroot in old kernel

### ISSUE THREAD

**Issue by arozenfe** [apptainer/apptainer#2324]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run
```
apptainer version 1.3.2+294-gd636a0a66
```

### Expected behavior

I assume that my kernel (4.12.14-122.136 and 4.12.14-122.201) does not allow mount FUSE in unprivileged user namespace. `squashfuse_ll` works well without unprivileged user namespace, but fails inside. This means I have to use `apptainer` with `setuid`, and even then `fakeroot` doesn't work. Is there a way to tell `apptainer` not to use fuse mounts? Compile it a different way (again, assuming we compile it with `suid` enabled), or change something in the configuration? I've tried changing various entries in `apptainer.conf`, like `allow setuid-mount squashfs` and `allow setuid-mount extfs`, but nothing worked.

Up until now we were using `singularity version 3.8.7-1` which didn't require fuse mounts at all. 

### Actual behavior

```
apptainer exec --fakeroot /tmp/sles15sp4.sif /bin/bash
INFO:    A fusermount error may indicate that the kernel is too old
INFO:    The --unsquash option may work around it
FATAL:   container creation failed: image driver mount failure: image driver squashfuse_ll instance exited with error: squashfuse_ll exited: fusermount3: mount failed: Operation not permitted
```
I get the same error even if I use `--unsquash`.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp5"
```

Kernel version: 4.12.14-122.136-default and 4.12.14-122.201-default

### How did you install Apptainer

Source

**Comment by DrDaveD** [comment]
Wait, I take back the comment about user namespaces for the `allow setuid-mount` options.  Those don't help anything when user namespaces are not available, because in setuid mode the fuse mount is done as root anyway.

**Comment by DrDaveD** [comment]
I'm sorry, there are so many scenarios to keep in mind, it gets confusing to me too ... you're talking about a case where there are user namespaces, just not fuse mounts in user namespaces.  So yes I would expect setuid mode with `allow setuid-mount squashfs = yes` and /etc/subuid mount mapping to work with --fakeroot.   You're saying that in that case it still tried to use squashfuse_ll ?  Please double-check, that and if yes, please post the output of `apptainer -d`.

**Comment by DrDaveD** [comment]
I don't have access to a machine with an old kernel like that but I just verified on rocky8 that if I install apptainer-suid version 1.3.2 and set `allow setuid-mount squashfs = yes` that it does not attempt to use squashfuse_ll.  It looks for it, but it doesn't attempt to use it.

**Comment by arozenfe** [comment]
> I'm sorry, there are so many scenarios to keep in mind, it gets confusing to me too ... you're talking about a case where there are user namespaces, just not fuse mounts in user namespaces. So yes I would expect setuid mode with `allow setuid-mount squashfs = yes` and /etc/subuid mount mapping to work with --fakeroot. You're saying that in that case it still tried to use squashfuse_ll ? Please double-check that and if yes, please post the output of `apptainer -d`.

Yes, `allow setuid-mount squashfs` is set to `yes`:
```
$ grep '^allow setuid-mount squashfs' /usr/local/etc/apptainer/apptainer.conf
allow setuid-mount squashfs = yes
```

But it still tries to use `squashfuse_ll`:
```
$ apptainer exec --fakeroot /tmp/sles15sp4.sif /bin/bash
INFO:    A fusermount error may indicate that the kernel is too old
INFO:    The --unsquash option may work around it
FATAL:   container creation failed: image driver mount failure: image driver squashfuse_ll instance exited with error: squashfuse_ll exited: fusermount3: mount failed: Operation not permitted
```
If I try to use `--unsquash`, it will still fail because `fuse-overlayfs` also can't work inside unprivileged user namespace:
```
apptainer exec --fakeroot --unsquash /tmp/sles15sp4.sif /bin/bash
INFO:    Converting SIF file to temporary sandbox...
INFO:    A fusermount error may indicate that the kernel is too old
INFO:    Cleaning up image...
FATAL:   container creation failed: image driver mount failure: image driver fuse-overlayfs instance exited with error: fuse-overlayfs exited: fusermount3: mount failed: Operation not permitted
fuse-overlayfs: cannot mount: Operation not permitted
```

**Comment by arozenfe** [comment]
Eventually I made it work with `--unsquash` after setting `enable overlay = no`. Which is weird, because the configuration file says that:

> If 'yes', **kernel overlayfs will be tried** but if it doesn't work, the image driver (i.e. fuse-overlayfs) will be used instead

But it seems to always use `fuse-overlayfs`, and not the kernel overlayfs.

Anyway, when I set `enable overlay = no` to be able to use `fakeroot`, I can't use the `--writable-tmpfs`:

```
$ apptainer exec --writable-tmpfs /tmp/sles15sp4.sif /bin/bash
FATAL:   --writable-tmpfs requires 'enable overlay', but set to 'no' by administrator
```

**Comment by arozenfe** [comment]
I was able to solve the overlay issue by setting:
```
enable underlay = preferred
```

I see that:

> This option is deprecated and will be removed in a future release, because the implementation is complicated and the performance is similar to the kernel overlay driver and to fuse-overlayfs.

However, on my system, overlay mounts seem to not work even for **privileged** user namespace.

```
$ sudo unshare -r /usr/lib/apptainer/bin/fuse-overlayfs -f -o allow_other,lowerdir=/tmp/session/overlay-lowerdir:/tmp/session/rootfs,noacl /tmp/session/final
unknown argument ignored: lazytime
fusermount3: mount failed: Operation not permitted
fuse-overlayfs: cannot mount: Operation not permitted

$ sudo unshare -r mount -t overlay overlay -olowerdir=/tmp/session/overlay-lowerdir,upperdir=/tmp/session/upper,workdir=/tmp/session/rootfs /tmp/session/final
mount: /tmp/session/final: permission denied.

$ sudo unshare -m -r mount -t overlay overlay -olowerdir=/tmp/session/overlay-lowerdir,upperdir=/tmp/session/upper,workdir=/tmp/session/rootfs /tmp/session/final
mount: /tmp/session/final: permission denied.
```

So I think that removing underlay mounts in future will break apptainer on systems like mine.

**Comment by DrDaveD** [comment]
That makes total sense.  `--fakeroot` requires a privileged user namespace, so with such an old kernel it can't be used in combination with overlay.  So even with the `--underlay` option or `enable underlay = preferred` configuration it won't be able to be used in combination with `--writable-tmpfs` or `--overlay`.  

How long do you think systems like yours will still be in use?  It looks like SLES 12 End of Life is October of this year.

In summary, for that old of a kernel to use `--fakeroot` you needed:
1. suid installation
2. `allow setuid-mount squashfs = yes`
3. `enable underlay = preferred`

Are there any more messages we should add to make this more clear to people?  I think that one could be useful when `fusermount` is seen in an error message for `fuse-overlayfs`: if no overlay mode has been explicitly requested, it could suggest adding an `--underlay` option or `enable underlay = preferred` configuration.

**Comment by arozenfe** [comment]
The general support for SLES12SP5 ends at Oct 2024, but it also has LTSS (Long Term Service Pack Support) until Oct 2027, and then additional LTSS Core until 2030. We're going to use SLES12 until AT LEAST October 2027. I work in a large HPC organization, and around 95% of our servers are still SLES12SP5.

I don't see how `allow setuid-mount squashfs = yes` changes the behavior for `--fakeroot`. It doesn't seem to do anything in that case. We need `--unsquash`. On Singularity, when overlay isn't support, `--fakeroot` automatically triggers unsquash (and writes the message: "Converting SIF file to temporary sandbox..."). It could be nice if `apptainer` could do that as well.

Both `--underlay` and `enable underlay` are currently considered deprecated. Is it possible to revert the deprecation? 

Thanks!

**Comment by DrDaveD** [comment]
> On Singularity, when overlay isn't support, --fakeroot automatically triggers unsquash (and writes the message: "Converting SIF file to temporary sandbox..."). It could be nice if apptainer could do that as well.

That's because Singularity doesn't have the option of using fuse, so I don't think we will change that for the sake of the many more users where it works.  At least there's a message that says what to do.

> Both --underlay and enable underlay are currently considered deprecated. Is it possible to revert the deprecation?

We will discuss it at the next community meeting, but my expectation is that we won't want to remove the deprecation due to the effort of maintaining underlay.  There has already been a bug reported which we decided not to fix.  I don't see why we couldn't leave it in deprecation mode as-is for a fairly long time, however, and add a message to suggest using it where overlay doesn't work.

**Comment by DrDaveD** [comment]
> I don't see how `allow setuid-mount squashfs = yes` changes the behavior for `--fakeroot`. 

You're right.  I was thinking you needed it for non-fakeroot mode but that's not the case either because setuid mode can use fuse since apptainer-1.3.0 without a user namespace.

> It doesn't seem to do anything in that case. 

It should make a difference in non-fakeroot mode, although it will work both ways; by default it will use fuse but with the option it will go back to using kernel squashfs.

**Comment by DrDaveD** [comment]
I think the bottom line of what we'll change for this issue is my suggestion above:
> I think that one could be useful when fusermount is seen in an error message for fuse-overlayfs: if no overlay mode has been explicitly requested, it could suggest adding an --underlay option or enable underlay = preferred configuration.

**Comment by arozenfe** [comment]
I agree.
I also wanted to confirm that even though `--underlay` and `enable underlay` are considered deprecated, it will not be removed in a future release. Maybe instead of saying that it will be removed, you can change the comment in `apptainer.conf` to clarify this capability will not get supported anymore.

Thanks!
