### ISSUE TITLE
DMTCP checkpoint instructions don't work

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#2325]
In #2258 I wrote regarding the [apptainer checkpointing instructions](https://apptainer.org/docs/user/latest/checkpoint.html):

>The instructions were written prior to the 3.0.0 release and suggested using the master branch at the time if 2.x doesn't work. The current release is 3.0.0, and the instructions should be brought up to date to say to use the latest 3.x.x release.

That issue was closed due to fixing the immediate crash problem, so this is a followup for the more general DMTCP checkpointing problems.

In addition to the instructions referring to the wrong release, I couldn't get them to work completely with the 3.0.0 release, which is more concerning.

**Comment by angel-devicente** [comment]
I see the same problem in a Ubuntu 22.04 host with Apptainer 1.3.3, and DMTCP latest from their master branch. I modified the sample .def file to use `python:3.10-bookworm` and I could use checkpointing, but not reliably (after a restart, sometimes the connection to port 8888 is refused, and also stopping the instance doesn't happen cleanly and it gets killed after a timeout...)

```
[angelv@dial checkpoint]$ apptainer checkpoint create excheckpoint
INFO:    Checkpoint "excheckpoint" created.
[angelv@dial checkpoint]$ apptainer instance start --dmtcp-launch excheckpoint server.sif server 8888
INFO:    instance started successfully
[angelv@dial checkpoint]$ curl localhost:8888; echo
0
[angelv@dial checkpoint]$ curl -X POST localhost:8888 -d '1'; echo
1
[angelv@dial checkpoint]$ apptainer checkpoint instance server
INFO:    Using checkpoint "excheckpoint"
[angelv@dial checkpoint]$ apptainer instance stop server
INFO:    Stopping server instance of /scratch/angelv/checkpoint/server.sif (PID=4109189)
[angelv@dial checkpoint]$ apptainer instance start --dmtcp-restart excheckpoint server.sif server 8888
INFO:    instance started successfully
[angelv@dial checkpoint]$ curl localhost:8888; echo
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused

[angelv@dial checkpoint]$ apptainer instance stop server
INFO:    Stopping server instance of /scratch/angelv/checkpoint/server.sif (PID=4109493)
INFO:    Killing server instance of /scratch/angelv/checkpoint/server.sif (PID=4109493) (Timeout)
[angelv@dial checkpoint]$ apptainer instance start --dmtcp-restart excheckpoint server.sif server 8888
INFO:    instance started successfully
[angelv@dial checkpoint]$ curl localhost:8888; echo
1
[angelv@dial checkpoint]$ curl -X POST localhost:8888 -d '2'; echo
2
[angelv@dial checkpoint]$ apptainer checkpoint instance server
INFO:    Using checkpoint "excheckpoint"
[angelv@dial checkpoint]$ apptainer instance stop server
INFO:    Stopping server instance of /scratch/angelv/checkpoint/server.sif (PID=4109695)
INFO:    Killing server instance of /scratch/angelv/checkpoint/server.sif (PID=4109695) (Timeout)
[angelv@dial checkpoint]$ apptainer instance start --dmtcp-restart excheckpoint server.sif server 8888
INFO:    instance started successfully
[angelv@dial checkpoint]$ curl localhost:8888; echo
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused

[angelv@dial checkpoint]$ apptainer instance stop server
INFO:    Stopping server instance of /scratch/angelv/checkpoint/server.sif (PID=4109970)
INFO:    Killing server instance of /scratch/angelv/checkpoint/server.sif (PID=4109970) (Timeout)
[angelv@dial checkpoint]$ apptainer instance start --dmtcp-restart excheckpoint server.sif server 8888
INFO:    instance started successfully
[angelv@dial checkpoint]$ curl localhost:8888; echo
2
```

**Comment by JasonYangShadow** [comment]
> I see the same problem in a Ubuntu 22.04 host with Apptainer 1.3.3, and DMTCP latest from their master branch. I modified the sample .def file to use `python:3.10-bookworm` and I could use checkpointing, but not reliably (after a restart, sometimes the connection to port 8888 is refused, and also stopping the instance doesn't happen cleanly and it gets killed after a timeout...)
> 
> ```
> [angelv@dial checkpoint]$ apptainer checkpoint create excheckpoint
> INFO:    Checkpoint "excheckpoint" created.
> [angelv@dial checkpoint]$ apptainer instance start --dmtcp-launch excheckpoint server.sif server 8888
> INFO:    instance started successfully
> [angelv@dial checkpoint]$ curl localhost:8888; echo
> 0
> [angelv@dial checkpoint]$ curl -X POST localhost:8888 -d '1'; echo
> 1
> [angelv@dial checkpoint]$ apptainer checkpoint instance server
> INFO:    Using checkpoint "excheckpoint"
> [angelv@dial checkpoint]$ apptainer instance stop server
> INFO:    Stopping server instance of /scratch/angelv/checkpoint/server.sif (PID=4109189)
> [angelv@dial checkpoint]$ apptainer instance start --dmtcp-restart excheckpoint server.sif server 8888
> INFO:    instance started successfully
> [angelv@dial checkpoint]$ curl localhost:8888; echo
> curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
> 
> [angelv@dial checkpoint]$ apptainer instance stop server
> INFO:    Stopping server instance of /scratch/angelv/checkpoint/server.sif (PID=4109493)
> INFO:    Killing server instance of /scratch/angelv/checkpoint/server.sif (PID=4109493) (Timeout)
> [angelv@dial checkpoint]$ apptainer instance start --dmtcp-restart excheckpoint server.sif server 8888
> INFO:    instance started successfully
> [angelv@dial checkpoint]$ curl localhost:8888; echo
> 1
> [angelv@dial checkpoint]$ curl -X POST localhost:8888 -d '2'; echo
> 2
> [angelv@dial checkpoint]$ apptainer checkpoint instance server
> INFO:    Using checkpoint "excheckpoint"
> [angelv@dial checkpoint]$ apptainer instance stop server
> INFO:    Stopping server instance of /scratch/angelv/checkpoint/server.sif (PID=4109695)
> INFO:    Killing server instance of /scratch/angelv/checkpoint/server.sif (PID=4109695) (Timeout)
> [angelv@dial checkpoint]$ apptainer instance start --dmtcp-restart excheckpoint server.sif server 8888
> INFO:    instance started successfully
> [angelv@dial checkpoint]$ curl localhost:8888; echo
> curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
> 
> [angelv@dial checkpoint]$ apptainer instance stop server
> INFO:    Stopping server instance of /scratch/angelv/checkpoint/server.sif (PID=4109970)
> INFO:    Killing server instance of /scratch/angelv/checkpoint/server.sif (PID=4109970) (Timeout)
> [angelv@dial checkpoint]$ apptainer instance start --dmtcp-restart excheckpoint server.sif server 8888
> INFO:    instance started successfully
> [angelv@dial checkpoint]$ curl localhost:8888; echo
> 2
> ```

Thanks so much for the report!
Just to confirm, are you able to check the detailed instance log message when the following error occurs?
```
[angelv@dial checkpoint]$ curl localhost:8888; echo
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
```
the instance logs are located at `$HOME/.apptainer/instances/logs/${HOST}/${USER}/server.{err/out}`

for example, my local env:
```
[vagrant@localhost test]$ ls -al ~/.apptainer/instances/logs/localhost.localdomain/vagrant/server*
-rw-r--r--. 1 vagrant vagrant 1083 Oct  8 02:36 /home/vagrant/.apptainer/instances/logs/localhost.localdomain/vagrant/server.err
-rw-r--r--. 1 vagrant vagrant    0 Oct  8 02:21 /home/vagrant/.apptainer/instances/logs/localhost.localdomain/vagrant/server.out
```

**Comment by JasonYangShadow** [comment]
@ikaneshiro @DrDaveD cc @cclerget 

Updates on my local tests:
During my test, I can see the similar issue
```
[angelv@dial checkpoint]$ curl localhost:8888; echo
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
```

after checking the instance logs, it is mainly related to this issue
https://github.com/apptainer/apptainer/issues/2325#issuecomment-2328127435
which should be caused by python3 http server does not reuse the address by default, I tried using another python3 socket server code, which works fine locally for me

```
Bootstrap: docker
From: python:3.10-bookworm

%post
    mkdir /app
    cat > /app/server.py <<EOF
import socketserver
import argparse

count = 0

parser = argparse.ArgumentParser(description='Optional app description')
parser.add_argument('port', type=int, help='A required integer port argument')
args = parser.parse_args()

class Handler(socketserver.BaseRequestHandler):
    def handle(self):
        global count
        count += 1
        response = bytes("current count:{}\n".format(count), "ascii")
        self.request.sendall(response)

if __name__ == "__main__":
    with socketserver.TCPServer(('', args.port), Handler) as server:
        server.allow_reuse_address = True
        server.serve_forever()
EOF

%startscript
    python3 /app/server.py $@
```
the main change is that
1. changing to use `python:3.10-bookworm`
2. `server.allow_reuse_address = True`  # to reuse the same address and port

Following commands are my test case:
```
apptainer build -f server.sif server.def  ## build sif image using the above definition file

[vagrant@localhost test]$ apptainer checkpoint create ck
INFO:    Checkpoint "ck" created.  


[vagrant@localhost test]$ apptainer instance start --dmtcp-launch ck server.sif server 8888
INFO:    Instance stats will not be available - system configuration does not support cgroup management.
INFO:    squashfuse not found, will not be able to mount SIF or other squashfs files
INFO:    gocryptfs not found, will not be able to use gocryptfs
INFO:    Converting SIF file to temporary sandbox...
INFO:    instance started successfully

[vagrant@localhost test]$ curl --http0.9 localhost:8888
current count:1
[vagrant@localhost test]$ curl --http0.9 localhost:8888
current count:2

[vagrant@localhost test]$ apptainer checkpoint instance server
INFO:    Using checkpoint "ck"

[vagrant@localhost test]$ apptainer instance stop -F server
INFO:    Stopping server instance of /tmp/rootfs-3072566996/root (PID=650194)

[vagrant@localhost test]$ apptainer instance start --dmtcp-restart ck server.sif server 8888
INFO:    Instance stats will not be available - system configuration does not support cgroup management.
INFO:    squashfuse not found, will not be able to mount SIF or other squashfs files
INFO:    gocryptfs not found, will not be able to use gocryptfs
INFO:    Converting SIF file to temporary sandbox...
INFO:    instance started successfully

[vagrant@localhost test]$ curl --http0.9 localhost:8888
current count:3
[vagrant@localhost test]$ curl --http0.9 localhost:8888
current count:4

[vagrant@localhost test]$ apptainer instance stop -F server
INFO:    Stopping server instance of /tmp/rootfs-1793945577/root (PID=650521)

[vagrant@localhost test]$ apptainer instance start --dmtcp-restart ck server.sif server 8888
INFO:    Instance stats will not be available - system configuration does not support cgroup management.
INFO:    squashfuse not found, will not be able to mount SIF or other squashfs files
INFO:    gocryptfs not found, will not be able to use gocryptfs
INFO:    Converting SIF file to temporary sandbox...
INFO:    instance started successfully

[vagrant@localhost test]$ curl --http0.9 localhost:8888
current count:3
[vagrant@localhost test]$ curl --http0.9 localhost:8888
current count:4

[vagrant@localhost test]$ apptainer instance stop -F server
INFO:    Stopping server instance of /tmp/rootfs-3723304535/root (PID=650736)
```

we can run the last three steps multiple times (`apptainer instance start --dmtcp-restart` & `curl` & `apptainer instance stop`) to see that the state is successfully restored by DMTCP without issues.

Other issues I can see locally during my test are:
1. `dmtcp_restart is not found` which I believed is caused by my local environment, the generated dmtcp restart script, located at `$HOME/checkpoints/dmtcp/${CHECKPOINT}/dmtcp_restart_script.sh`, where `dmtcp_restart` is searched only in `/usr/bin` rather than `/usr/local/bin`. 
2. Permission denied when restoring process info, something related to unable to restore process's `_gid` states (permission denied) ,which I think is caused by DMTCP, this error rarely occurs.

my local dmtcp version is  
```
[vagrant@localhost test]$ dmtcp_command --version
dmtcp_command (DMTCP) 3.0.0
License LGPLv3+: GNU LGPL version 3 or later
    <http://gnu.org/licenses/lgpl.html>.
This program comes with ABSOLUTELY NO WARRANTY.
This is free software, and you are welcome to redistribute it
under certain conditions; see COPYING file for details.
```
DMTCP setup following this comment
https://github.com/apptainer/apptainer/issues/2473#issuecomment-2326784344

**Comment by angel-devicente** [comment]
Hello,

this looks promising. 

I tried with the new "server.py" (by recreating "server.dif") and it now behaves much more reliably.

I performed 100 iterations of: "curl ; curl ; checkpoint ; stop ; restart" and in almost all of them I got no errors, but for some reason, there were seven consecutive iterations starting at iteration 22 (and then another seven starting at 53)  where I got the "Connection refused errors". Not sure what to make of the repetition of seven failed iterations in both cases, perhaps there is a timeout somewhere, and since I'm doing this programatically and all iterations take the same time, then I get the same number of failed iterations?):

```
Iteration 22
increasing counter
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
performing checkpoint
INFO:    Using checkpoint "ck"
stopping server
INFO:    Stopping server instance of /scratch/angelv/checkpoint/server2.sif (PID=1039032)
restarting server
INFO:    instance started successfully
Iteration 23
increasing counter
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
performing checkpoint
INFO:    Using checkpoint "ck"
stopping server
INFO:    Stopping server instance of /scratch/angelv/checkpoint/server2.sif (PID=1039187)
restarting server
INFO:    instance started successfully
Iteration 24

```

**Comment by JasonYangShadow** [comment]
> Hello,
> 
> this looks promising.
> 
> I tried with the new "server.py" (by recreating "server.dif") and it now behaves much more reliably.
> 
> I performed 100 iterations of: "curl ; curl ; checkpoint ; stop ; restart" and in almost all of them I got no errors, but for some reason, there were seven consecutive iterations starting at iteration 22 (and then another seven starting at 53) where I got the "Connection refused errors". Not sure what to make of the repetition of seven failed iterations in both cases, perhaps there is a timeout somewhere, and since I'm doing this programatically and all iterations take the same time, then I get the same number of failed iterations?):
> 
> ```
> Iteration 22
> increasing counter
> curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
> curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
> performing checkpoint
> INFO:    Using checkpoint "ck"
> stopping server
> INFO:    Stopping server instance of /scratch/angelv/checkpoint/server2.sif (PID=1039032)
> restarting server
> INFO:    instance started successfully
> Iteration 23
> increasing counter
> curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
> curl: (7) Failed to connect to localhost port 8888 after 0 ms: Connection refused
> performing checkpoint
> INFO:    Using checkpoint "ck"
> stopping server
> INFO:    Stopping server instance of /scratch/angelv/checkpoint/server2.sif (PID=1039187)
> restarting server
> INFO:    instance started successfully
> Iteration 24
> ```

Thanks so much for the testing! Have you checked the instance logs?  They are located under `$HOME/.apptainer/instances/logs/${HOST}/${USER}/server.{err/out}`, those failures might be caused by other issues

**Comment by angel-devicente** [comment]
I was just checking them right now :-)

I get lines like:

```
[19] mtcp_restart.c:347 restore_brk:
  error: new/current break (0x11213000) != saved break (0x55dd7c018000)
[22] mtcp_restart.c:347 restore_brk:
  error: new/current break (0x11213000) != saved break (0x652ad1f66000)
[2024-10-08T09:58:35.539, 41000, 41003, WARNING] at socketconnection.cpp:724 in postRestart; REASON='JWARNING(_real_bind(_fds[0], (sockaddr *)&_bindAddr, _bindAddrlen) == 0) failed'
     (strerror((*__errno_location ()))) = Address already in use
     id() = 383f860d43ed254f-41000-6704ed33(99057)
Message: Bind failed.
[19] mtcp_restart.c:347 restore_brk:
  error: new/current break (0x11213000) != saved break (0x55dd7c018000)
[22] mtcp_restart.c:347 restore_brk:
  error: new/current break (0x11213000) != saved break (0x652ad1f66000)
[2024-10-08T09:58:44.502, 41000, 41003, WARNING] at socketconnection.cpp:724 in postRestart; REASON='JWARNING(_real_bind(_fds[0], (sockaddr *)&_bindAddr, _bindAddrlen) == 0) failed'
     (strerror((*__errno_location ()))) = Address already in use
     id() = 383f860d43ed254f-41000-6704ed33(99057)
Message: Bind failed.

```

**Comment by JasonYangShadow** [comment]
> I was just checking them right now :-)
> 
> I get lines like:
> 
> ```
> [19] mtcp_restart.c:347 restore_brk:
>   error: new/current break (0x11213000) != saved break (0x55dd7c018000)
> [22] mtcp_restart.c:347 restore_brk:
>   error: new/current break (0x11213000) != saved break (0x652ad1f66000)
> [2024-10-08T09:58:35.539, 41000, 41003, WARNING] at socketconnection.cpp:724 in postRestart; REASON='JWARNING(_real_bind(_fds[0], (sockaddr *)&_bindAddr, _bindAddrlen) == 0) failed'
>      (strerror((*__errno_location ()))) = Address already in use
>      id() = 383f860d43ed254f-41000-6704ed33(99057)
> Message: Bind failed.
> [19] mtcp_restart.c:347 restore_brk:
>   error: new/current break (0x11213000) != saved break (0x55dd7c018000)
> [22] mtcp_restart.c:347 restore_brk:
>   error: new/current break (0x11213000) != saved break (0x652ad1f66000)
> [2024-10-08T09:58:44.502, 41000, 41003, WARNING] at socketconnection.cpp:724 in postRestart; REASON='JWARNING(_real_bind(_fds[0], (sockaddr *)&_bindAddr, _bindAddrlen) == 0) failed'
>      (strerror((*__errno_location ()))) = Address already in use
>      id() = 383f860d43ed254f-41000-6704ed33(99057)
> Message: Bind failed.
> ```

nice! so it's still related to `bind failure` issues, and we can give the conclusion that it is caused by python3 demo file, the way of creating and shutting down the server can result in the failure of DMTCP socket port restoration.

**Comment by angel-devicente** [comment]
To check the logs I was running the loop again and the previous errors in the log files were generated by another two groups of seven failed iterations each, it cannot be a coincidence....)

**Comment by JasonYangShadow** [comment]
> To check the logs I was running the loop again and the previous errors in the log files were generated by another two groups of seven failed iterations each, it cannot be a coincidence....)

though I do not have a deep investigation on this, but I guess it might be repeatably allocating and releasing the same socket port might result in chances of conflicts. @DrDaveD @ikaneshiro @cclerget

**Comment by angel-devicente** [comment]
I have tried with a simple program that simply prints out consecutive numbers to a file (to avoid the sockets issue) and all seems to behave nicely. I do get errors like these in the logs, but as far as I can tell, the checkpoints are restored properly and the program is able to restart without issues.
```

[19] mtcp_restart.c:347 restore_brk:
  error: new/current break (0x11213000) != saved break (0x6196bbf64000)
[22] mtcp_restart.c:347 restore_brk:
  error: new/current break (0x11213000) != saved break (0x5941f3685000)
[2024-10-08T10:45:44.363, 41000, 41003, WARNING] at processinfo.cpp:494 in restoreProcessGroupInfo; REASON='JWARNING(setpgid(0, _gid) == 0) failed'
     _gid = 40000
     (strerror((*__errno_location ()))) = Operation not permitted
Message: Cannot change group information
[19] mtcp_restart.c:347 restore_brk:
  error: new/current break (0x11213000) != saved break (0x6196bbf64000)
[22] mtcp_restart.c:347 restore_brk:
  error: new/current break (0x11213000) != saved break (0x5941f3685000)
```
