### ISSUE TITLE
Running container inside container some time results in mount hook function failure

### ISSUE THREAD

**Issue by smuzaffar** [apptainer/apptainer#2328]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using?

```
apptainer version 1.3.2-1.el8
```

### Expected behavior

Container inside container should run properly. It works most of the time but for unknown reason it does not

### Actual behavior

On a AlmaLinux8 host, we start an AlmaLinux 8 container from /cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el8:x86_64 and bind mount `/etc/tnsnames.ora` from host inside container. Then from the AlmaLinux 8 container we start an other centos 6 container (/cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el6:x86_64) which sometimes failed with error
```
FATAL:   container creation failed: mount hook function failure: mount /etc/tnsnames.ora->/etc/tnsnames.ora error: while mounting /etc/tnsnames.ora: destination /etc/tnsnames.ora doesn't exist in container
```

Note that both host and almalinux 8 container use `apptainer version 1.3.2`. 

Any idea why it happens randomly?

**Comment by DrDaveD** [comment]
No, there shouldn't be any reason why it happens randomly.  Are you sure the conditions aren't varying between the times that it success and the times that it fails?

I see that the mount point /cvmfs/unpacked.cern.ch/registry.hub.docker.com/cmssw/el6:x86_64/etc/tnsnames.ora does exist, so it seems most likely toe me that there's a cvmfs issue happening on particular machines.  The binding happens before executing any code in the container so maybe there are other things missing too but that is the first thing that's noticed.

**Comment by smuzaffar** [comment]
thanks @DrDaveD , one thing I noticed that `/etc/tnsnames.ora` on host was updated around the time we get these errors. Could this be the cause of this errors? Note that we use APPTAINER_BINDPATH to mount `/etc/tnsnames.ora` 

```
export APPTAINER_BINDPATH=/cvmfs,/tmp,/data,/var/run/user,/run/user,/etc/pki/ca-trust,/cvmfs/grid.cern.ch/etc/grid-security:/etc/grid-security,/cvmfs/grid.cern.ch/etc/grid-security/vomses:/etc/vomses,/home,/etc/tnsnames.ora:/etc/tnsnames.ora,/data
```

[a]
Jul 19 07:02:46 cmsbuild116.cern.ch systemd[1]: nc_heartbeat.service: Succeeded.
Jul 19 07:02:46 cmsbuild116.cern.ch systemd[1]: Started Send request to specified server, indicating server is alive and well.
Jul 19 07:03:08 cmsbuild116.cern.ch puppet-agent[3042891]: (/Stage[main]/Hg_vocmssdt/File[/etc/tnsnames.ora]/content) content changed '{mtime}2024-07-18 07:09:48 +0200' to '{mtime}2024-07-19 04:11:15 UTC'
Jul 19 07:03:15 cmsbuild116.cern.ch puppet-agent[3042891]: Applied catalog in 12.28 seconds

**Comment by DrDaveD** [comment]
It looks like a good clue.  Perhaps there's a race condition; perhaps apptainer sees the inode of the old version but by the time it gets to open it the inode is gone.

**Comment by smuzaffar** [comment]
I can make a copy of it before starting the first container but is there any apptainer startup option which can help here?

**Comment by DrDaveD** [comment]
Not that I can think of

**Comment by smuzaffar** [comment]
So it was issue with changing `/etc/tnsnames.ora` on host. Mounting a copy (which do not change during the runtime of container) of `/etc/tnsnames.ora` fixed this issue
