### ISSUE TITLE
Overlay partition fails to mount with specific sif file

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#2335]
Originally reported by @ehfd on Slack.

### Version of Apptainer

1.3.3

### Expected behavior

Expect to be able to use an overlay partition in a sif file.

### Actual behavior

Apptainer exits with following messages:
```
INFO:    /proc/self/fd/3: Bad magic number in super-block.
INFO:    Please run e2fsck -fy /proc/self/fd/3.
FATAL:   container creation failed: mount hook function failure: mount /proc/self/fd/3->/var/lib/apptainer/mnt/session/overlay-images/0 error: while mounting image /proc/self/fd/3: fuse2fs failed to mount /var/lib/apptainer/mnt/session/overlay-images/0 in 10s
```

### Steps to reproduce this behavior

```
apptainer build nvidia-glx-desktop.sif docker://ghcr.io/selkies-project/nvidia-glx-desktop:latest
apptainer overlay create --size 8192 nvidia-glx-desktop.sif
apptainer exec nvidia-glx-desktop.sif id
```

It does not happen with all base sif files, for example with one built from docker://rockylinux:8.

### What OS/distro are you running

Rocky 8

### How did you install Apptainer

dnf install from epel

**Comment by ehfd** [comment]
Original repro: Ubuntu 22.04, v1.3.2-1, PPA install. Same situation.

**Comment by ehfd** [comment]
Because there is a full KDE desktop environment in this container, some system packages including `udev` and `fuse` are installed underneath. This may pose problems.

https://github.com/selkies-project/docker-nvidia-egl-desktop
https://github.com/selkies-project/docker-nvidia-glx-desktop

**Comment by DrDaveD** [comment]
I don't see the problem if I instead do
```
apptainer overlay create --size 8192 nvidia-glx-overlay.img
```
and pass in `--overlay nvidia-glx-overlay.img` to my exec command instead.  You may be able to use that as a workaround. 

Also avoid `--compat` since among other things that implies `--writable-tmpfs`.
