### ISSUE TITLE
apptainer instance start does not honor the Dockerfile CMD/ENTRYPOINT directive

### ISSUE THREAD

**Issue by ehfd** [apptainer/apptainer#2340]
This is mostly a question. I've seen https://github.com/apptainer/apptainer/issues/959, but I want to know the rationale why Dockerfile CMD/ENTRYPOINT are not honored by `apptainer instance start`.

### Version of Apptainer

Apptainer v1.3.3 and Sylabs v4.1.4

### Expected behavior

`apptainer instance run` honors `ENTRYPOINT` or `CMD` in a Dockerfile.

But `apptainer instance start` apparently does not while it should.

When using `apptainer instance stop [instance]`, `apptainer instance start` stops much faster than `apptainer instance run` (which has to even kill processes after waiting) because there are no processes that started. This is consistent with https://apptainer.org/docs/user/main/docker_and_oci.html#cmd-entrypoint-behaviour.

This breaks interoperability with Sylabs Singularity with the default runtime.

### Actual behavior

Nothing happens. I need to clarify the behavior of `runscript` and `startscript`, to decide whether to open this issue to Sylabs.

### Steps to reproduce this behavior

```bash
# Customize paths
export APPTAINER_SELKIES_OVERLAY=~/my_mounting_point/nvidia-egl-desktop.sif
export APPTAINER_SELKIES_SCRATCH_HOME=~/nvidia-egl-desktop
mkdir -pm755 "${APPTAINER_SELKIES_SCRATCH_HOME}"
# Change size of overlay storage
apptainer overlay create --sparse --size 1536 "${APPTAINER_SELKIES_OVERLAY}"
apptainer instance run --overlay "${APPTAINER_SELKIES_OVERLAY}" --nv --no-mount cwd --home "${APPTAINER_SELKIES_SCRATCH_HOME}:/home/ubuntu" --env "TZ=UTC,DISPLAY_SIZEW=1920,DISPLAY_SIZEH=1080,DISPLAY_REFRESH=60,DISPLAY_DPI=96,DISPLAY_CDEPTH=24,PASSWD=mypasswd,SELKIES_ENCODER=nvh264enc,SELKIES_VIDEO_BITRATE=8000,SELKIES_FRAMERATE=60,SELKIES_AUDIO_BITRATE=128000,SELKIES_BASIC_AUTH_PASSWORD=mypasswd" docker://ghcr.io/selkies-project/nvidia-egl-desktop:latest egl
```

### What OS/distro are you running

Ubuntu 22.04.4

### How did you install Apptainer

PPA

**Comment by DrDaveD** [comment]
As far as I know the behavior of `apptainer instance start` with respect to the docker entrypoint has not changed.  We added `apptainer instance run` in version 1.2.0.  Did SingularityCE change the behavior of instance start in an incompatible way?

**Comment by ehfd** [comment]
No, I confirm that there was nothing that changed. I was also confused. Closing in favor of https://github.com/sylabs/singularity/issues/3083.
