### ISSUE TITLE
Error while building from image: "failed to create symlink /image/rootfs/var/tmp"

### ISSUE THREAD

**Issue by Flamefire** [apptainer/apptainer#2347]
### Version of Apptainer

`apptainer version 1.3.3`

### Expected behavior

Building an encrypted container from an existing image works, e.g. `apptainer build --encrypt output.img input.img`

### Actual behavior

Failure during extracting the original image for some inputs:

> FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: 
> [some "WARNING:" lines]
>
>create_inode: failed to create symlink /image/rootfs/var/tmp, because File exists

**To Reproduce**

Intended command is: `singularity build --pem-path=/keys/image.pub output.img input.img`, but any build fails:

- `wget -O input.img https://depot.galaxyproject.org/singularity/pigz%3A2.3.4`
- `sudo singularity build --sandbox /tmp/img input.img`

**Expected behavior**

Encrypted image (or sandbox folder) is created

**OS / Linux Distribution**

Which Linux distribution are you using? Is it up-to-date?

Linux Mint 21.3 (Ubuntu 22.04 "jammy") fully patched

**Installation Method**

DEB from GitHub: `singularity-ce_4.1.4-jammy_amd64.deb`

**Additional context**

This is the same issue as with Singularity-CE I reported at https://github.com/sylabs/singularity/issues/3084 but mentioning it here to confirm that it does also apply to Apptainer

[Log with --debug](https://github.com/user-attachments/files/16142885/appt.log)

Console output
```
INFO:    Starting build...
FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating
WARNING: group file doesn't exist in container, not updating
WARNING: Skipping mount /etc/hosts [binds]: /etc/hosts doesn't exist in container
WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
WARNING: Skipping mount /var/lib/apptainer/mnt/session/tmp [tmp]: /tmp doesn't exist in container
WARNING: Skipping mount /var/lib/apptainer/mnt/session/var/tmp [tmp]: /var/tmp doesn't exist in container
WARNING: Skipping mount /var/lib/apptainer/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container

create_inode: failed to create symlink /image/rootfs/var/tmp, because File exists
Parallel unsquashfs: Using 4 processors
391 inodes (635 blocks) to write

[==============================================================| ] 634/635  99%

created 109 files
created 53 directories
created 281 symlinks
created 0 devices
created 0 fifos
created 0 sockets
: exit status 2
```

### How did you install Apptainer

DEB from GitHub: `apptainer_1.3.3_amd64.deb`

**Comment by DrDaveD** [comment]
Thanks for the report.  Let's wait to see if a fix from Singularity-CE is applicable.

**Comment by Flamefire** [comment]
I opened a PR over there: https://github.com/sylabs/singularity/pull/3105

Note that building `unsquashfs` from latest sources (and either installing it globally or adjusting the apptainer config to use it) also works after my report over there.

**Comment by Flamefire** [comment]
> Thanks for the report. Let's wait to see if a fix from Singularity-CE is applicable.

@DrDaveD This is now the case. I opened #2397 for that
