### ISSUE TITLE
Make fakeroot recommended in rpm

### ISSUE THREAD

**Issue by arozenfe** [apptainer/apptainer#2348]
Currently, `fakeroot` is required by the `apptainer` rpm.

https://github.com/apptainer/apptainer/blob/20b535379a92372cb62b5b603bb5197dcdbf468d/dist/rpm/apptainer.spec.in#L130

But `apptainer` doesn't actually need the `fakeroot` command to work; if it can't find the command, it will just use root-mapped namespace. Some dists don't provide this tool (not even on SLES15SP6).

Can we change the `Requires:` to `Recommends:`?

**Comment by DrDaveD** [comment]
I don't ever see `Recommends` used for rpms.  Will it install a package if it is available?  If not, I would rather put `%if` statements in the .spec to exclude trying to install it where it's not available.  Better yet would be to add it for sles to the packages included internally by `scripts/{download|compile|install|clean}-dependencies`.

**Comment by arozenfe** [comment]
It's being used by rpm packages managers such as `dnf` and `zypper`. It's a ["weak dependency"](https://docs.fedoraproject.org/en-US/packaging-guidelines/WeakDependencies/) concept. If the package is not available in the repositories, it won't be installed. 

> Weak dependencies may only be used in a package if the package still functions without the dependency present. It is acceptable, however, to create packages that have very limited functionality without adding any of its weak requirements. Weak dependencies should be used where possible to minimize the installation for reasonable use cases, especially for building virtual machines or containers that have a single purpose only and do not require the full feature set of the package.

Even if the package is available you can tell the package manager to only install "hard" dependencies and skip "weak" dependencies. For instance, in `dnf` you can pass `--setopt=install_weak_deps=False` flag, and in `zypper` the flag is `--no-recommends`.

What's the benefit of using the `fakeroot` command line?

**Comment by DrDaveD** [comment]
It's described in method 3 in the [fakeroot doc page](https://apptainer.org/docs/user/latest/fakeroot.html).  It adds to unprivileged user namespaces without /etc/subuid mappings the ability to pretend to have files owned by different user ids, so things like `chown` work.  Some rpm installations (my go-to example is `openssh`) don't work with only a root-mapped user namespace.

**Comment by DrDaveD** [comment]
Do you know who does packaging for apptainer for SUSE?  I tried installing it from an opensuse/leap:15 docker container and it's only version 1.3.0 and they did not follow the updated installation instructions for version 1.3.

**Comment by DrDaveD** [comment]
I see that the binaries (built on EL8) installed by `install-unprivileged.sh` work in an opensuse/leap:15 docker container and demonstrate the difference.  That includes a fakeroot command in the installation.  Install with
```
$ curl -s https://raw.githubusercontent.com/apptainer/apptainer/main/tools/install-unprivileged.sh | \
     bash -s - /tmp/apptainer
```
It turns out that on suse the openssh package does not demonstrate the difference, but the squid package does.
This command which ignores the fakeroot command included in the installation fails:
```
$ /tmp/apptainer/bin/apptainer exec --ignore-subuid --ignore-fakeroot-command --writable-tmpfs \
      docker://opensuse/leap:15 zypper install -y squid
```
but if you remove `--ignore-fakeroot-command` it works.

**Comment by arozenfe** [comment]
Ok, I understand. This problem only manifests when using `--ignore-subuid` or when `/etc/subuid` / `/etc/subgid` are not available or don't have appropriate mapping for the user. I would still call it a "weak dependency", as `apptainer` will work without the `fakeroot` command while using `/etc/subuid` and `/etc/subgid` mapping file. It's completely acceptable for an admin to decide not to install `fakeroot` command, and still use `apptainer` without this specific capability. I find it an appropriate use case for a weak dependency.

**Comment by DrDaveD** [comment]
I wouldn't mind much it being a weak dependency on SUSE, but on RHEL it's available in the optional EPEL and I want to make sure that people have installed it there.  Otherwise I'll be getting support requests from people asking why they can't install packages when building containers when all they needed to do was install the fakeroot command.

**Comment by arozenfe** [comment]
Ok, so I'll change my commit to make it Recommended only on SUSE.
