### ISSUE TITLE
Only can use half of all cpus to computing.

### ISSUE THREAD

**Issue by wahello** [apptainer/apptainer#2367]
#### `apptainer exec--cpus=48 /home/apptainer/images/abq-2024.sif sh `pwd`/start.sh`

My Compute has two slots on main board, with 48 processors(2 * 12 Core * 2 T )  in total by `cat /proc/cpuinfo`
if execute `apptainer exec  /home/apptainer/images/abq-2024.sif sh `pwd`/start.sh`, only use half of all cpus to computing.

### Version of Apptainer

1.3.3-1.el9

### Expected behavior

Run smoothly without any issues.

### Actual behavior

```
INFO:    Terminating squashfuse_ll after timeout
INFO:    Timeouts can be caused by a running background process
FATAL:   container creation failed: while applying cgroups config: while setting cgroup limits: openat2 /sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/user.slice/apptainer-732229.scope/cpu.max: no such file or directory

```

### Steps to reproduce this behavior

1. Build a rocky linux 8 image.
2. Execute It on rocky linux 9

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.
Via epel rpm.

**Comment by DrDaveD** [comment]
Please follow the links in the [apptainer cgroups documentation](https://apptainer.org/docs/user/latest/cgroups.html).  That links to the [apptainer admin security documentation](https://apptainer.org/docs/admin/latest/security.html) which links to the [rootless containers cgroups website](https://rootlesscontaine.rs/getting-started/common/cgroup2/).  That explains that controlling cpus isn't enabled by default and shows how to enable it in systemd.

Apptainer should give a more clear message when controlling one of the cgroup parameters is not allowed.

**Comment by wahello** [comment]
It may not apptainer's bug, only using half cpus of total on physical machine.
