### ISSUE TITLE
run abaqus 2024 mpirun error : mpirun: Unrecognized affinity setting  mpirun: Internal Error: Bad argument to mpirun. 

### ISSUE THREAD

**Issue by wahello** [apptainer/apptainer#2369]
It  can run on centos 7 host, while failed on rocky linux 9.

The image is based on roky linux 8.

### Version of Apptainer

1.3.2-1.el9

### Expected behavior

start computing 

### Actual behavior

 ```
mpirun error : mpirun: Unrecognized affinity setting  mpirun: Internal Error: Bad argument to mpirun. 

```

### Steps to reproduce this behavior

1. Build abaqus 2024 image
2. run: `apptainer exec /xxx/yyy/abq-2024.sif sh start.sh `
start.sh
```
#!/bin/env bash

abq2024  job=zzzz inp=zzzz.inp  cpus=48 int | "zzzz.log"

```

### What OS/distro are you running

```sh
$ cat /etc/os-release

NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"

```

### How did you install Apptainer

RPM

**Comment by DrDaveD** [comment]
Please instead contact whoever supports the abaqus image.   I have no idea what that is and this sounds like an application problem, not an apptainer problem.
