### ISSUE TITLE
User namespace creating failed

### ISSUE THREAD

**Issue by YifangLuo** [apptainer/apptainer#2370]
### Version of Apptainer
1.3.2

### Expected behavior
I am building a new container following [https://github.com/ML4GW/aframev2/tree/main/projects/data](url), which is using Apptainer. The expected result is `data.sif`, and it was successful on another server before.

### Actual behavior
I switched a server provider. The building failed, with error.

```
INFO:    Starting build...
Copying blob b5381d1371f0 skipped: already exists  
Copying blob b349bcb0e87e skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob f11c1adaa26e skipped: already exists  
Copying blob 90ca98f3e719 skipped: already exists  
Copying blob 2930e754fbf4 skipped: already exists  
Copying blob 19215b5611be skipped: already exists  
Copying blob 4f4fb700ef54 skipped: already exists  
Copying blob d1223905c327 skipped: already exists  
Copying blob 37f75da0042b skipped: already exists  
Copying blob 002030c16889 skipped: already exists  
Copying blob 1ea0c37c5191 skipped: already exists  
Copying config 3809fcde20 done   | 
Writing manifest to image destination
2024/07/18 17:45:22  info unpack layer: sha256:f11c1adaa26e078479ccdd45312ea3b88476441b91be0ec898a7e07bfd05badc
2024/07/18 17:45:24  info unpack layer: sha256:2930e754fbf462279f5e7c4ec8958e17bc48cf973c783ae4b4d58f05b82912a6
2024/07/18 17:45:24  info unpack layer: sha256:b349bcb0e87e5bf44760044cbce8f10943218f8f193de7ecd89703b3204b2dd8
2024/07/18 17:45:25  info unpack layer: sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
2024/07/18 17:45:25  info unpack layer: sha256:90ca98f3e719e87efca54fd8fc08b1f2f02ddf8f7d84ccd9364482ba61ec54b9
2024/07/18 17:45:25  info unpack layer: sha256:b5381d1371f0f88dbd1886992e5c66a49a1347034cc483c768d1ef5a6fe80da6
2024/07/18 17:45:25  info unpack layer: sha256:19215b5611be3052e1a6a68d92a9752a7b9b4df5b3ebb7dec3aa818e4e9af617
2024/07/18 17:45:25  info unpack layer: sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
2024/07/18 17:45:25  info unpack layer: sha256:37f75da0042b20eb2076c6c4e10b47b1d87758899293b5d1aab45be4c5955b91
2024/07/18 17:45:25  info unpack layer: sha256:d1223905c3279266f2e5e0baca4e47377e231ab87a695a8cedea811ba85033e5
2024/07/18 17:45:25  info unpack layer: sha256:002030c168895ab3d4fccccf8a6a2acd4912899542f323c749d12d4f0a678c33
2024/07/18 17:45:25  info unpack layer: sha256:1ea0c37c519139520d65d3f877e039d2eec4b1464a4d9699960b8ec2d67d89c1
INFO:    Copying . to /opt/aframe/projects/data/
INFO:    Copying ../../libs/utils to /opt/aframe/libs/utils
INFO:    Copying ../../libs/ledger to /opt/aframe/libs/ledger
INFO:    Copying ../../libs/priors to /opt/aframe/libs/priors
INFO:    Copying ../../ml4gw to /opt/aframe/ml4gw
INFO:    Copying ../../aframe to /opt/aframe/aframe
INFO:    Copying ../../pyproject.toml to /opt/aframe/pyproject.toml
INFO:    Running post scriptlet
ERROR  : Failed to create user namespace: user namespace requires to set /proc/sys/kernel/unprivileged_userns_clone to 1
FATAL:   While performing build: while running engine: exit status 1
```

### Steps to reproduce this behavior

I followed steps of `https://github.com/ML4GW/aframev2/tree/main/projects/data` (Actually, I don't think that was the problem). When executing
`apptainer build $AFRAME_CONTAINER_ROOT/new/data.sif apptainer.def`
The error occurred.
### What OS/distro are you running

```
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

In fact, I checked the setting, seems correct:
```
$ cat /proc/sys/kernel/unprivileged_userns_clone
$ 1

$ cat /proc/sys/user/max_user_namespaces
$ 3869608
```

I am using `root`, and I tried to install `apptainer-suid` but the problem exists.

### How did you install Apptainer
```
$ sudo add-apt-repository -y ppa:apptainer/ppa
$ sudo apt update
$ sudo apt install -y apptainer-suid
```

I looked through a lot of issues but nothing similar seems to have happened. If there is any information needing, I can provide it for you. Thanks a lot.

**Comment by YifangLuo** [comment]
Addendum: I have done similar work on another server of Vultr. Using Ubuntu 22.04, and everything seems to be fine(No namespaces error, so I think this situation is because of my new server instance, **especially its file system is `mount` related**). But I have removed that server instance so I cannot get more information of that server, sorry.

**Comment by YifangLuo** [comment]
> Can you run `unshare -r`? I expect that to give you the same error as apptainer.

```
(base) root@autodl-container-35834db7e0-dbc474c9:~/aframev2/projects/data# unshare -r
unshare: unshare failed: Operation not permitted
```

It failed. And the log gave me a message about permission, though I am running as root. Is it because of the file system? I don't know much about these things. Thanks.

**Comment by DrDaveD** [comment]
No that has nothing to do with the filesystem.  Maybe you are somehow running a newer kernel than usually comes with Ubuntu 22?  Starting in Ubuntu 23.10 a new restriction on user namespaces was added.  See Apptainer's [INSTALL.md](https://github.com/apptainer/apptainer/blob/main/INSTALL.md#apparmor-profile-ubuntu-2310).  Or maybe there are other system settings I'm not aware of for Ubuntu 22.04.  In any case it's clearly a problem with the configuration on your host, there's nothing that Apptainer can do about it.

**Comment by YifangLuo** [comment]
Thanks much for your information, and I will close this issue.
