### ISSUE TITLE
Attempting to build apptainer-suid from source. Build completes successfully, but no root access within container

### ISSUE THREAD

**Issue by ClarkMyWords** [apptainer/apptainer#2371]
Hi,

I'm trying to install Apptainer with suid privileges on Arch Linux. There is an official, supported Apptainer image for Arch [here](https://archlinux.org/packages/extra/x86_64/apptainer/) (with a default PKGBUILD [here](https://gitlab.archlinux.org/archlinux/packaging/packages/apptainer/-/blob/main/PKGBUILD?ref_type=heads)). This build is only without suid privileges.

I have tried to edit that PKGBUILD to include the `--with-suid` flag, in lieu of the `--without-suid` which is in it now. It appears to build perfectly fine, and I can install it on my system with no issue, but once I have the binary, I try to build a container, but I still do not have sudo permissions within the container.

I have used `apptainer -d build ...` to get the debug output, and, grepping the output, I see `16    | DEBUG   [U=1000, P=85650]    init()            Use starter binary /usr/lib/apptainer/bin/starter-suid` and other lines implying that the `starter-suid` binary is being invoked correctly.

However, upon entering my container and attempting to run even `sudo -v` I receive: 
```
sudo: /etc/sudo.conf is owned by uid 1000, should be 0
...
```

There may just be a simple fix which I am missing in the documentation, but I wanted to ask for support on that, or possibly if there's something I've missed in trying to edit those build parameters (Ideally, if I can get this working, I'd love to put up an `apptainer-suid` package on the Arch AUR for other uses in my use-case).

### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
apptainer --version
apptainer version 1.3.2
```

### Expected behavior

Apptainer should allow for sudo permissions once I have built the container with setuid permissions.

### Actual behavior
Even with a build with suid enabled, I am not able to run sudo in my container.

### Steps to reproduce this behavior

I am building on Arch Linux from [this PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/apptainer/-/blob/main/PKGBUILD?ref_type=heads). This should be functionally equivalent to building from source. I have taken that PKGBUILD and changed this:
```
  ./mconfig \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib \
    --localstatedir=/var/lib \
    -P release-stripped \
    --without-suid \
    -v

  make -C builddir
```
to this:
```
  ./mconfig \
    --prefix=/usr \
    --sysconfdir=/etc \
    --libexecdir=/usr/lib \
    --localstatedir=/var/lib \
    -P release-stripped \
    --with-suid \
    -v

  make -C builddir
```
Where the only difference should be `--without-suid` to `with-suid`.

This builds correctly, and using `apptainer -d` I can confirm that the binary is invoking `starter-suid`, but I still do not have root access in my container.

### What OS/distro are you running

Arch Linux

### How did you install Apptainer
Modified version of Arch Linux official package, as described above

I may well be missing something obvious, but I just wanted to reach out and see if anyone had a solution to this.

Thanks,
Clark

**Comment by DrDaveD** [comment]
Sorry but sudo is not going to work inside of an apptainer container no matter what you do.  sudo is a setuid program, and apptainer explicitly blocks that privilege escalation.  Apptainer is intended for use by scientific applications, not system code.  The `--fakeroot` option is primarily intended for building containers only.

**Comment by ClarkMyWords** [comment]
@DrDaveD Thank you! I've clearly misunderstood something my sysadmin told me. I'll ask him for clarification!
