### ISSUE TITLE
Building nested alpine linux apptainer containers

### ISSUE THREAD

**Issue by 1NF053C** [apptainer/apptainer#2372]
+ ./mconfig --without-suid '--prefix=/root/.local/share/apptainer'
Configuring for project `apptainer' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.21)... ./mconfig: /scif/apps/compute/apptainer/mlocal/checks/basechecks.chk: line 79: /scif/apps/compute/apptainer/mlocal/scripts/check-min-go-version: not found
mconfig: could not complete configuration
FATAL:   While performing build: while running engine: exit status 1

### Expected behavior

Expected Apptainer to be installed on Alpine Linux.

### Actual behavior

Received the following error:

+ ./mconfig --without-suid '--prefix=/root/.local/share/apptainer'
Configuring for project `apptainer' with languages: C, Golang
=> running pre-basechecks project specific checks ...
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: host Go compiler (at least version 1.21)... ./mconfig: /scif/apps/compute/apptainer/mlocal/checks/basechecks.chk: line 79: /scif/apps/compute/apptainer/mlocal/scripts/check-min-go-version: not found
mconfig: could not complete configuration
FATAL:   While performing build: while running engine: exit status 1

### Steps to reproduce this behavior

Create an apptainer def file that tries to install apptainer itself, like:

```sh
%appinstall compute

    apk update
    apk add --no-cache \
    build-base \
    linux-headers \
    libseccomp-dev \
    glib-dev \
    cryptsetup-dev \
    squashfs-tools \
    fakeroot \
    git

    wget https://golang.org/dl/go1.20.6.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.20.6.linux-amd64.tar.gz
    echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
    source /etc/profile

    git clone https://github.com/apptainer/apptainer.git
    cd apptainer

    APPTAINER_DIR="$XDG_DATA_HOME/apptainer"
    mkdir -p "$APPTAINER_DIR"

    ./mconfig --without-suid --prefix=$APPTAINER_DIR
    make -C ./builddir
    make -C ./builddir install
    export PATH="$PATH:$APPTAINER_DIR/bin"

    apptainer build -F --fakeroot ${XDG_DATA_HOME}/compute/app.sif ${XDG_CONFIG_HOME}/compute/include/app.def
```

### What OS/distro are you running

Alpine Linux container From: node:18-alpine
 on Ubuntu

### How did you install Apptainer

See commands above.

**Comment by DrDaveD** [comment]
mconfig has the following code:
```
sourcedir=`pwd -P`
...
makeit_scriptsdir=$sourcedir/mlocal/scripts
...
	if ! $makeit_scriptsdir/check-min-go-version go $hstgo_version >/dev/null; then
```

So what is the result of `pwd -P`?

**Comment by 1NF053C** [comment]
```sh
/scif/apps/compute/apptainer/mlocal/scripts/check-min-go-version: not found
```

**Comment by DrDaveD** [comment]
That's the result of `pwd -P`?  That doesn't make sense.

But I can guess from the fact that the error includes `/scif/apps/compute/apptainer/mlocal/checks/basechecks.chk` that your `pwd -P` is `/scif/apps/compute/apptainer` and what this means is that you have an incomplete copy of the source files for apptainer.

**Comment by 1NF053C** [comment]
Whoops yea, I meant to clone the repo into a specific dir.

I did that, and now `ls` can see the `check-min-go-version` executable at specified path, and `mconfig` seems to not be able to:

```sh
+ ls /root/.local/share/apptainer/mlocal/scripts
check-min-go-version  config_h.sh
+ pwd -P
+ cat /root/.local/share/apptainer/mlocal/scripts/check-min-go-version
#!/bin/bash
if [ $# != 2 ]; then
...
 checking: host Go compiler (at least version 1.21)... ./mconfig: /root/.local/share/apptainer/mlocal/checks/basechecks.chk: line 79: /root/.local/share/apptainer/mlocal/scripts/check-min-go-version: not found
mconfig: could not complete configuration
```

**Comment by 1NF053C** [comment]
to clarify:
```sh
    cat $(pwd -P)/mlocal/scripts/check-min-go-version # exists
    ./mconfig --without-suid --prefix=$APPTAINER_DIR # errors, cannot find above script at same path
```

**Comment by afbjorklund** [comment]
check-min-go-version is a bash script, so you need to `apk install bash` (by default, Alpine uses `ash`)

**Comment by DrDaveD** [comment]
Thanks, Anders!  That didn't occur to me.  Maybe that should be converted to a /bin/sh script.

**Comment by afbjorklund** [comment]
I think there are several other scripts, that also use bash (not sure if they are user or developer, though)

Eventually you will run into some Nix people or others, that will require you to use `#!/usr/bin/env bash`

**Comment by afbjorklund** [comment]
> Maybe that should be converted to a /bin/sh script.

Here is what "checkbashisms" complained about:

```console
$ checkbashisms ./mlocal/scripts/check-min-go-version
possible bashism in ./mlocal/scripts/check-min-go-version line 8 (${parm/?/pat[/str]}):
GOVERSION="${GOVERSION//go version go/}"
possible bashism in ./mlocal/scripts/check-min-go-version line 9 (${parm/?/pat[/str]}):
GOVERSION="${GOVERSION// *}"
possible bashism in ./mlocal/scripts/check-min-go-version line 15 (${parm/?/pat[/str]}):
GOMAJOR="${GOVERSION/.*}"
possible bashism in ./mlocal/scripts/check-min-go-version line 21 (${parm/?/pat[/str]}):
    GOMINOR="${GOMINOR/.*}"
possible bashism in ./mlocal/scripts/check-min-go-version line 24 (alternative test command ([[ foo ]] should be [ foo ])):
if ! [[ "$GOMINOR" =~ ^[0-9]$ ]]; then
possible bashism in ./mlocal/scripts/check-min-go-version line 30 (${parm/?/pat[/str]}):
MINMAJOR="${MINVERSION/.*}"
possible bashism in ./mlocal/scripts/check-min-go-version line 42 (${parm/?/pat[/str]}):
    MINMINOR="${MINMINOR/.*}"
```

**Comment by DrDaveD** [comment]
We don't have instructions for compiling on Alpine Linux in INSTALL.md.  Maybe we should just add that and add `bash` as one of the required packages.

**Comment by afbjorklund** [comment]
There are some things hiding in the .github folder

**Comment by DrDaveD** [comment]
We do build it in a ci check in .github/workflows/ci.yml

**Comment by afbjorklund** [comment]
> Can someone please challenge my thinking RE: files, symbolic links, virtualization, alpine linux, OS's or etc so I could learn how to troubleshoot this?

The first error was that the interpreter did not exist, while the script actually did exist (and was executable)

The "ash" shell from busybox reports the same error for both cases, which makes troubleshooting harder.

With the "bash" shell, they are different:

`bash: ./foo.sh: No such file or directory`

`bash: ./bar.sh: cannot execute: required file not found`

So you are working in a spartan environment.

With the go binaries that you download from go.dev, they depend on glibc - another thing you don't have...

`apk add gcompat`

https://wiki.alpinelinux.org/wiki/Running_glibc_programs

**Comment by afbjorklund** [comment]
So those are two things that need to be added to the documentation, if wanting to install on Alpine Linux.

`apk add bash gcompat`

**Comment by 1NF053C** [comment]
Thanks. I managed to work my way back to a previous issue where I cannot get newgidmap to execute:

```sh
VERBOSE [U=0,P=122]        init()                        Spawn master process
DEBUG   [U=0,P=122]        set_mappings_external()       Executing '/usr/bin/newgidmap * * * * ****** ***** >/dev/null'newgidmap: write to gid_map failed: Operation not permitted
ERROR   [U=0,P=122]        set_mappings_external()       'newgidmap' execution failed. Check that 'newgidmap' is setuid root or has setcap cap_setgid+eip.
ERROR   [U=65534,P=1]      init()                        Error while waiting event for user namespace mappings: Bad file descriptor
```

My `%post` section includes:

```sh
    which setcap

    echo $PATH

    # Verify newuidmap and newgidmap are installed
    which newuidmap
    which newgidmap # at /usr/bin/newgidmap

    setcap cap_setgid+eip /usr/bin/newgidmap
    chmod u+s /usr/bin/newgidmap # I don't think I need this since the above command worked
    
    ls -l /etc/subuid /etc/subgid # root is user and owner and has rw

    echo "root:100000:65536" | tee -a /etc/subuid /etc/subgid

    cat /etc/subuid # the above tee worked on both of these files
    cat /etc/subgid

    apptainer --debug build -F --fakeroot ${XDG_DATA_HOME}/compute/app.sif ${XDG_CONFIG_HOME}/compute/include/app.def
    # YET, the above build command runs into an error with newgidmap execution
```

**Comment by DrDaveD** [comment]
Now you're mixing up issues, but apptainer runs containers with the kernel "no new privileges" flag, so by design it does not allow any privilege escalation inside of containers.  That's not going to work, sorry. `allow setuid = yes` does not mean to allow setuid inside the container, it means to allow the use of starter-suid on the host.   Nesting of apptainer works, but only without user namespaces and not setuid (and not /etc/subuid).

**Comment by 1NF053C** [comment]
Sorry about that. I should've titled this issue building Nested Alpine Linux Containers.

Removing `--fakeroot` from the inner build step worked!

**Comment by DrDaveD** [comment]
That makes sense if it is already running in a root-mapped user namespace and your build doesn't need to do anything with any other user ids than root.  Closing.
