### ISSUE TITLE
Does Apptainer support running sif files inside Apptainer containers via Apptainer commands, i.e., initiating the running of new containers inside containers.

### ISSUE THREAD

**Issue by linxz-nice** [apptainer/apptainer#2390]

**Comment by DrDaveD** [comment]
If user namespaces are enabled, yes

**Comment by DrDaveD** [comment]
Oh, and assuming the kernel is new enough to support fuse mounts in user namespaces

**Comment by linxz-nice** [comment]
> Oh, and assuming the kernel is new enough to support fuse mounts in user namespaces

Ok, what is the minimum kernel requirement?

**Comment by DrDaveD** [comment]
https://apptainer.org/docs/admin/latest/installation.html#system-requirements
