### ISSUE TITLE
apptainer cpu-related options (and mpi?)

### ISSUE THREAD

**Issue by gsal** [apptainer/apptainer#2399]
Can someone please expand on the meaning of such options? 
When to use them? 
The docs one-line explanations are too brief for me.

    --cpu-shares int                CPU shares for container (default -1)
    --cpus string                   Number of CPUs available to container
    --cpuset-cpus string            List of host CPUs available to container
    --cpuset-mems string            List of host memory nodes available to container

I would like to be able to run a program in 1 and 2 nodes; we have 96 cpus per node.

Oh, and I forgot to ask whether this is related to mpi in anyway; like, what if I use mpi instead.

**Comment by DrDaveD** [comment]
There's more info at https://apptainer.org/docs/user/latest/cgroups.html, did you see that?  It is unrelated to mpi.

**Comment by gsal** [comment]
Thanks for that link; no, I hadn't seen it.
