### ISSUE TITLE
--pid : read unix @->@: read: connection reset by peer

### ISSUE THREAD

**Issue by CarstenBaker** [apptainer/apptainer#2403]
### Version of Apptainer
apptainer version 1.3.3

### Expected behavior

Apptainer to execute a command or run container using --pid option

### Actual behavior

Apptainer working correctly without '--pid' option.

With **--pid** option Apptainer fails with the following code:

**non-suid**
container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer

**suid**
container creation failed: mount hook function failure: mount tmpfs->/mnt/scratch/approot/var/apptainer/mnt/session error: while mounting tmpfs: can't mount tmpfs filesystem to /mnt/scratch/approot/var/apptainer/mnt/session: read unix @->@: read: connection reset by peer

### Steps to reproduce this behavior

```
apptainer pull ubuntu.sif docker://ubuntu:22.10
apptainer run --pid ubuntu.sif
apptainer exec --pid ubuntu.sif cat /etc/os-release
```
### What OS/distro are you running

```
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
```

### How did you install Apptainer

Installed from Source

without-suid using squashfuse-0.5.2 (installed and running as standard user)
```
git clone https://github.com/apptainer/apptainer.git
cd apptainer/
git checkout v1.3.3
./mconfig --without-suid --prefix=/mnt/scratch/apptain133
cd $(/bin/pwd)/builddir
make
make install

curl -LO https://github.com/vasi/squashfuse/releases/download/0.5.2/squashfuse-0.5.2.tar.gz
tar -xvzf squashfuse-0.5.2.tar.gz
cd squashfuse-0.5.2
./configure --prefix=/mnt/scratch/squashfuse
make
make install

export PATH=$PATH:/mnt/scratch/apptain133/bin:/mnt/scratch/squashfuse/bin

```
Command: apptainer -d run --pid ubuntu.sif
Error: FATAL   [U=1000,P=135752]  Master()                      container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer

with-suid
```
git clone https://github.com/apptainer/apptainer.git
cd apptainer
git checkout v1.3.3
./mconfig --with-suid --prefix=/mnt/scratch/approot
cd $(/bin/pwd)/builddir
make
make install
export PATH=$PATH:/mnt/scratch/approot/bin/

```
Command: apptainer -d run --pid ubuntu.sif
Error: FATAL   [U=0,P=135687]     Master()                      container creation failed: mount hook function failure: mount tmpfs->/mnt/scratch/approot/var/apptainer/mnt/session error: while mounting tmpfs: can't mount tmpfs filesystem to /mnt/scratch/approot/var/apptainer/mnt/session: read unix @->@: read: connection reset by peer

Not sure if genuine issue or config setup wrong to be able to use --pid ?

**Comment by CarstenBaker** [comment]
Tested using RockyLinux9 and it works correctly,  possibly an issue with RockyLinux 8.10

```
cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
```

**Comment by DrDaveD** [comment]
I tried it with the rpm installed from EPEL on Rocky 8.10 and it works fine.  Can you try that for comparison?

Or try [install-unprivileged.sh](https://apptainer.org/docs/admin/latest/installation.html#install-unprivileged-from-pre-built-binaries) which also works for me.

You didn't fully follow the [1.3 INSTALL.md instructions for compiling fuse dependencies](https://github.com/apptainer/apptainer/blob/release-1.3/INSTALL.md#compiling-dependent-fuse-based-packages) although it's not clear to me why that would make a difference for this case.

**Comment by CarstenBaker** [comment]
Both of these methods work correctly.

Think my question was more about whether it should still work and to check I wasn't missing anything obvious with the newer version and without SUID.  

Now I am confident it should work I will work backwards to work out which parts I have missed on install.   
I should have better documented my install method in this report, I followed the steps but didn't put them down in this bug report which wasn't helpful (apologies!).

**Comment by CarstenBaker** [comment]
Here is a good lesson in posting detailed bug reports !!

I have gone through the install and worked out the issue is with **go** and not with **apptainer** directly.

If I use go version **1.22.2** I can replicate the issue on multiple test machines but it works correctly with go version **1.21.2**
 
```
# RockyLinux 8.10

# Install dependencies
sudo dnf groupinstall -y 'Development Tools'
sudo dnf install -y epel-release
sudo dnf install -y \
    libseccomp-devel \
    squashfs-tools \
    fakeroot \
    cryptsetup \
    wget git

# Install go 
# This version always fails for me
export GOVERSION=1.22.2 OS=linux ARCH=amd64
wget -O /tmp/go${GOVERSION}.${OS}-${ARCH}.tar.gz   https://dl.google.com/go/go${GOVERSION}.${OS}-${ARCH}.tar.gz
sudo tar -C /usr/local -xzf /tmp/go${GOVERSION}.${OS}-${ARCH}.tar.gz
echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.bashrc
source ~/.bashrc

git clone https://github.com/apptainer/apptainer.git
cd apptainer
git checkout v1.3.3
./mconfig --with-suid --prefix=/mnt/scratch/approot
cd $(/bin/pwd)/builddir
make
make install

export PATH=$PATH:/mnt/scratch/approot/bin/apptainer

apptainer pull ubuntu.sif docker://ubuntu:22.10
apptainer run --pid ubuntu.sif

FATAL:   while extracting ubuntu.sif: root filesystem extraction failed: extract command failed: FATAL:   container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer
: exit status 255

```

Not sure if anyone else can test to confirm. 
I noticed the minimum version of go for apptainer was bumped to 1.21 but didn't see if there was a maximum or supported version ?

**Comment by DrDaveD** [comment]
Did you really do `make install` (meaning /mnt/scratch/approot was writable by the unprivileged user) or did you do `sudo make install`?  If I do `sudo make install` on Rocky8.10 with go1.22.2 I get a different error with `--pid`:
```
FATAL:   container creation failed: mount hook function failure: mount tmpfs->/usr/local/var/apptainer/mnt/session error: while mounting tmpfs: can't mount tmpfs filesystem to /usr/local/var/apptainer/mnt/session: connection is shut down
```
However, if I add `-u` to make it run in a user namespace then I get a similar error, but not "while extracting" the sif:
```
FATAL:   container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer
```

**Comment by DrDaveD** [comment]
And I do not see any problem with go 1.22.4.  Can you confirm?  We could just chalk it up to a go bug that has since been fixed.

**Comment by CarstenBaker** [comment]
I ran 'make install' without sudo, we are trying to avoid having any root ownership on apptainer files. 
We have a previous SUID install under a root user but thought it was time to go for user namespace and fuse as that now seems to be the preferred method (plus in my mind it seems a safer/better option going forward)

/mnt/scratch was writable for the user, I used the lazy method for testing
`chmod 777 /mnt/scratch`

But get the same issues even if installed under /home/$USER/apptainer

Will test with go 1.22.4 and 1.22.6 tomorrow on the cluster (where the issue was first reported), but happy to mark it down as a bug that's been resolved as it just seems to be that go version that it doesn't like (easiest fix for us is to avoid using that version).

Cheers for the help

**Comment by DrDaveD** [comment]
> I ran 'make install' without sudo

Oh then I would not use the mconfig `--with-suid` option.  I'm a little surprised it didn't complain somewhere that you were trying to run starter-suid that was not setuid root.

**Comment by CarstenBaker** [comment]
Oh yeah, that was my fault for flipping between SUID and non-SUID when testing.
It does moan on the last line of install that the permissions for SUID are incorrect if you do it this way, just tried it.

Tested with go 1.22.4 and 1.22.6 and both are fine, bug seems to be directly related to 1.22.2 so will mark it down as avoid this version in future.
