### ISSUE TITLE
Installing Apptainer 1.3.3 tries to create apparmor profile on Ubuntu 22.04

### ISSUE THREAD

**Issue by aicampbell** [apptainer/apptainer#2416]
While trying to install Apptainer 1.3.3 on Ubuntu 22.04, I get the following error:

```
Setting up apptainer (1.3.3) ...
AppArmor parser error for /etc/apparmor.d/apptainer in profile /etc/apparmor.d/apptainer at line 2: Could not open 'abi/4.0': No such file or directory
```

The release notes state this should only occur when using Ubuntu 24.04 or higher
"Added apparmor profiles for ubuntu 24.04 or higher distros."

Is version 1.3.3 incompatible with Ubuntu 22.04 or is this a potential bug ?

### Version of Apptainer

What version of Apptainer (or Singularity) are you using? 

1.3.3

### What OS/distro are you running

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

### How did you install Apptainer

Installed .deb using 
`sudo dpkg -i apptainer_1.3.3_amd64.deb`

**Comment by DrDaveD** [comment]
Yes, that is fixed in the main branch by #2364 and will be fixed when we have a 1.3.4 release.  Meanwhile I recommend sticking with version 1.3.2 on Ubuntu 22.  Or if you could build the .deb package from source from the main branch that would be great.
