### ISSUE TITLE
Update of PPA for Ubuntu requested

### ISSUE THREAD

**Issue by ronaldlehnigk** [apptainer/apptainer#2423]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

1.3.3

### Expected behavior

We are heavily relying on Apptainer for our entire workflow now - thanks so much for the great work! My problem: I am installing Apptainer in an Ubuntu Docker Image to conduct some CI/CD testing and would like to use the latest Apptainer version for that. Installing version 1.3.3. is not possible as the PPA doesn't seem to be up to date. Is there a reason for that or was it just forgotten or planned for a later point? 

```
$ docker run -it godlovedc/apptainer bash
[root@2af37e18c636 /]# apptainer --version
apptainer version 1.2.5-1.el9
```

is also not up to date :-)

### Actual behavior

What actually happened? Why was it incorrect?

```
$ add-apt-repository -y ppa:ysenda/apptainer-${APPTAINER_VERSION}
ERROR: ppa 'ysenda/apptainer-1.3.3' not found
```

### Steps to reproduce this behavior

```
$ add-apt-repository -y ppa:ysenda/apptainer-${APPTAINER_VERSION}
ERROR: ppa 'ysenda/apptainer-1.3.3' not found
```

### What OS/distro are you running

Ubuntu 24.04 LTS

### How did you install Apptainer

PPA for Ubuntu

**Comment by afbjorklund** [comment]
https://launchpad.net/~apptainer/+archive/ubuntu/ppa says 1.3.2

**Comment by DrDaveD** [comment]
Yes, the update to Ubuntu PPA is being postponed until 1.3.4 is released.

**Comment by ronaldlehnigk** [comment]
> Yes, the update to Ubuntu PPA is being postponed until 1.3.4 is released.

Alright, I see there are good reasons. I will close the issue then.
