### ISSUE TITLE
package apptainer for use with MacOS `brew`

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#243]
package apptainer for use with MacOS `brew`

this also needs to include an analysis of default bind mounts and their applicability on non-linux systems.

also needs to support both M1 ARM and x64 architectures

**Comment by afbjorklund** [comment]
There is a singularity formula:  https://formulae.brew.sh/formula/singularity

`  depends_on :linux` (no idea what it means, to run apptainer on macOS ?)

But you _could_ `brew install lima`, and use the singularity/apptainer yaml ?

**Comment by kaczmarj** [comment]
homebrew works on macos and linux, and it looks like `depends_on :linux` means the singularity formula can only be installed on linux. see https://docs.brew.sh/Cask-Cookbook#stanza-depends_on -- it doesn't mention :linux but it does describe `depends_on`

**Comment by afbjorklund** [comment]
Since singularity/apptainer can only be installed on linux, that "dependency" seems reasonable to me.

This will run on mac, though: https://github.com/lima-vm/lima/blob/master/examples/singularity.yaml

**Comment by afbjorklund** [comment]
Now apptainer is available:

```
brew install --HEAD lima
limactl start template://apptainer
export LIMA_INSTANCE=apptainer
lima apptainer ...
```

**Comment by DrDaveD** [comment]
Great, thanks Anders.  Closing.

**Comment by afbjorklund** [comment]
I made a PR to cut it down even further:

`brew install lima`
`apptainer ...`

But it has not been merged (or released) yet.
