### ISSUE TITLE
Getting error message "WARNING: fakeroot with unprivileged installation" with compiled version of apptainer that did *not* use the --without-suid flag and suid allowed in configuration

### ISSUE THREAD

**Issue by jwimberl** [apptainer/apptainer#2441]
### Version of Apptainer

```
apptainer version 1.3.3
```

### Expected behavior

The version of apptainer installed via dnf appeared to be an unprivileged installation, because `apptainer run --fakeroot -net` yielded the warning message

```
WARNING: fakeroot with unprivileged installation or 'allow setuid = no' could not use 'fakeroot' network, fallback to 'none' network
```
Since the file `/etc/apptainer/apptainer.conf` included the line `allow setuid = yes`, and didn't also include any `allow setuid = no` that might override the former, I presumed that the issue must be that this binary was an unprivileged installation originally compiled with the flag `./mconfig --without-suid`. So, I compiled apptainer 1.3.3, checked out from source, with

```
 ./mconfig --prefix=/home/myusername
 make -C ./builddir/
 sudo make -C ./builddir install
 ```

Since this is not compiled with the `--without-suid` flag, and since both the files `/etc/apptainer/apptainer.conf` and `./builddir/apptainer.conf` contain `allow setuid = yes` and not `allow setuid = no`, I expected that I would no  longer get the `WARNING: fakeroot` message as both indicated preconditions are no longer met. (I am not sure which conf file will be used in this case so I checked both).

### Actual behavior

I still get the exact same warning message.

### Steps to reproduce this behavior

```
APPTAINER_VERSION=1.3.3
wget https://github.com/apptainer/apptainer/releases/download/v$SINGULARITY_VERSION/apptainer-$SINGULARITY_VERSION.tar.gz
tar -xzf apptainer-$SINGULARITY_VERSION.tar.gz
cd apptainer-$SINGULARITY_VERSION 
./mconfig --prefix=/home/myusername
make -C ./builddir/
sudo make -C ./builddir install
# check the appropriate apptainer.conf file and set `allow setuid = yes`
~/bin/apptainer run --fakeroot --net /path/to/sif/file bash
```

### What OS/distro are you running

```sh
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
```

### How did you install Apptainer

Source (see above) without the `--without-suid` flag

**Comment by jwimberl** [comment]
Looking through mconfig I saw that, besides `--without-suid`, there is an option `--with-suid`. Is it possible that omitting `--without-suid` is not equivalent to including `--with-suid`?

**Comment by DrDaveD** [comment]
Yes, it is not equivalent.  `--without-suid` is the default since version 1.1.0.   If you want suid when compiling from source, you need to add `--with-suid`. 

You can install a suid version from EPEL by `dnf install apptainer-suid`.

**Comment by jwimberl** [comment]
OK, thanks for the confirmation! I think the published docs, e.g. at

- https://apptainer.org/docs/admin/1.0/installation.html#unprivileged-non-setuid-installation
-https://apptainer.org/docs/admin/1.0/security.html#setuid-user-namespaces

do not make this clear, because they still refer to adding the `--without-suid` flag when suid is not desired, rather than the converse.

**Comment by DrDaveD** [comment]
That's because you're looking at an old version.  It changed at 1.1.
