### ISSUE TITLE
Staged build hangs when copying files from one stage to another, when using apptainer-suid and user namespaces are set to 0

### ISSUE THREAD

**Issue by secondspass** [apptainer/apptainer#2453]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
$ apptainer --version
apptainer version 1.3.3-1
```

### Expected behavior

When I have apptainer and apptainer-suid installed, and number of user namespaces are set to 0 (with `sudo sysctl -w user.max_user_namespaces=0`) and then I try to build the below def file with `apptainer -d build stagedbuild.sif stagedbuild.def`, I expect it to build correctly without errors.

stagedbuild.def
```
Bootstrap: docker
From: ubuntu:latest
Stage: devel

%post
touch blah
echo "hello" > /blah



Bootstrap: docker
From: ubuntu:latest
Stage: final

%files from devel
/blah /blahtwo

%post
echo "hi"
```

### Actual behavior
During the build, at the stage where the file `blah` is copied from the `devel` stage to the `final` stage, `apptainer build` just hangs. When I run the build with the debug output `apptainer -d ..` I see the below at the point it starts hanging. There is no more output beyond this point, it just hangs.
```
WARNING [U=1000,P=1790]    unpackRootfs()                The --fix-perms option modifies the filesystem permissions on the resulting container.
DEBUG   [U=1000,P=1790]    unpackRootfs()                Modifying permissions for file/directory owners
DEBUG   [U=1000,P=1790]    copyFilesFrom()               Copying files from stage: devel
INFO    [U=1000,P=1790]    copyFilesFrom()               Copying /blah to /blahtwo
DEBUG   [U=1000,P=1790]    CopyWithTar()                 Using unprivileged CopyWithTar (uid=1000, gid=1000)
```

### Steps to reproduce this behavior

Install apptainer and apptainer-suid 1.3.3 

```
$ sudo rpm -i apptainer-1.3.3-1.x86_64.rpm
$ sudo rpm -i apptainer-suid-1.3.3-1.x86_64.rpm
```

Set number of user namespaces to 0
```
sudo sysctl -w user.max_user_namespaces=0
```

Build the above mentioned stagedbuild.def with 
```
$ apptainer -d build stagedbuild.sif stagedbuild.def
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="39 (Workstation Edition)"
ID=fedora
VERSION_ID=39
VERSION_CODENAME=""
PLATFORM_ID="platform:f39"
PRETTY_NAME="Fedora Linux 39 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:39"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f39/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=39
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=39
SUPPORT_END=2024-11-12
VARIANT="Workstation Edition"
VARIANT_ID=workstation

```

### How did you install Apptainer

I wget the rpms from the Github releases page and then install it with the `rpm` command.

```
$ sudo rpm -i apptainer-1.3.3-1.x86_64.rpm
$ sudo rpm -i apptainer-suid-1.3.3-1.x86_64.rpm
```

**Comment by DrDaveD** [comment]
Thanks for the report.  After I got past the problem I just reported in #2455, I am able to reproduce your issue also on Rocky8.  It looks to me like the [code](https://github.com/apptainer/apptainer/blob/release-1.3/pkg/util/archive/copy.go#L38) is assuming user namespaces, although at this point I don't know why it is hanging instead of giving an error.  I also don't know what should be done about it.  You are using [fakeroot mode 4](https://apptainer.org/docs/user/latest/fakeroot.html) which is extremely limiting in any case.  Before the introduction of that mode, fakeroot did require user namespaces so the assumption in the CopyWithTar() function would have been a correct assumption.

**Comment by JasonYangShadow** [comment]
I am not able to reproduce this issue, receiving a similar error shown in this issue https://github.com/apptainer/apptainer/issues/2455

```
[vagrant@localhost ~]$ apptainer build test.sif stagebuild.def
ERROR  : Failed to create container process: No space left on device

[vagrant@localhost ~]$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"

[vagrant@localhost ~]$ apptainer version
1.3.3-1
```

**Comment by DrDaveD** [comment]
Try it with what the 1.3.4 message suggests: `--ignore-subuid`.  That's what I meant about getting past that problem.
