### ISSUE TITLE
Unable to set ptrace scope

### ISSUE THREAD

**Issue by wkaisertexas** [apptainer/apptainer#2454]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

```console
apptainer version 1.3.0-1.el7
```

### Expected behavior

I should be able to set the ptrace_scope within the container to allow debuggers to attach to processes.

```bash
echo "kernel.yama.ptrace_scope = 0" >> /etc/sysctl.conf
sysctl -p
```

### Actual behavior

In the output of this file, I get told that I am not allowed to set this permission.

### Steps to reproduce this behavior

Write a define file 
### What OS/distro are you running

```sh
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer

Apptainer was installed by the University of Virginia's research computing, I am unsure as to how they installed apptainer.

**Comment by DrDaveD** [comment]
Setting sysctl parameters require root access.  You don't get root access in a container unless you run it as root.

**Comment by wkaisertexas** [comment]
Okay thanks. I think that was a little ambiguous to me
