### ISSUE TITLE
Bind Mounts and Non-Primary SSSD Groups - High GIDs (>65534) replaced by nobody/65534

### ISSUE THREAD

**Issue by cody-eding** [apptainer/apptainer#2467]
### Version of Apptainer

```
[edingco@c001 ~]$
apptainer version 1.3.1-1.el9
```

### Expected behavior

On our Red Hat 9-based HPC cluster we use SSSD to provide AD user authentication and AD group integration. We have "project" folders that are owned by a single user but have non-primary AD group permissions set so that many users can read/write inside of them:

```
[edingco@c001 ~]$ ls -la /mnt/projects | grep edingco
drwxrws---  10 edingco       edingco_project        4096 Nov  8  2023 edingco_project
```

Or, with the `-n` flag:

```
[edingco@c001 ~]$ ls -lan /mnt/projects | grep edingco
drwxrws---  10 209041577 209094731 4096 Nov  8  2023 edingco_project
```

I have these paths bind mounted into an Apptainer container via apptainer.conf:

```
[edingco@c001 ~]$ cat /etc/apptainer/apptainer.conf | grep projects
bind path = /mnt/projects
```

Inside of the container, I would expect to see the folder owned by my account (`edingco`) with a group ownership of `edingco-project`.

My account has a UID of `209041577`. The GID of the `edingco-project` group is `209094731`.

```
[edingco@c001 ~]$ id edingco
uid=209041577(edingco) gid=209000513(domain users),209094731(edingco_project)
```

### Actual behavior

The bind-mounted folder inside the running Apptainer container is correctly owned by my user. But the group has been switched to `nobody`:

```
[edingco@c001 ~]$ ls -la /mnt/projects | grep edingco
drwxrws--- 10 edingco nobody       4096 Nov  8  2023 edingco_project
```

Again, with the `-n` flag:

```
[edingco@c001 ~]$ ls -lan /mnt/projects | grep edingco
drwxrws--- 10 209041577     65534 4096 Nov  8  2023 edingco_project
```

Apptainer has correctly passed the GID into `/etc/group`:

```
[edingco@c001 ~]$ cat /etc/group | grep edingco
edingco_project:x:209094731:edingco
```

`id` returns the correct information from SSSD from inside the container as well:

```
[edingco@c001 `]$ id edingco
uid=209041577(edingco) gid=209000513(domain users),209094731(edingco_project)
```

### Steps to reproduce this behavior

1. Create a folder/file owned by a non-primary group with GID greater than 65534 on the host system (i.e. use an AD group as the group owner).
2. Bind mount the folder file inside of an Apptainer container.

Based on #868, I might be able to use `newgrp` or `sg` to kick off the Apptainer container to change my primary group to that of the project folder. But this feels clunky, and I would need to account for HPC users who are members of multiple project groups and rely on them to identify which group they need at runtime (we are providing this container as an interactive session through Open OnDemand).

### What OS/distro are you running

Both the host system and container are running RHEL 9.4.

```
[edingco@c001 ~]$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="9.4 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.4 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"

```

### How did you install Apptainer

Installed from RPM.

**Comment by DrDaveD** [comment]
That is a consequence of user namespaces.  Only one group is supported by user namespaces in the Linux kernel, there's nothing we can do about it.  If you install apptainer-suid and are willing to live with that risk then it should work as you expect.

**Comment by cody-eding** [comment]
Ah, ok, that makes sense. I think I was under the impression we had apptainer-suid installed but that is apparently not the case. 

Thanks!
