### ISSUE TITLE
passing non-word chars via env-file

### ISSUE THREAD

**Issue by stdweird** [apptainer/apptainer#2475]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.3.3-1.el8
```

### Expected behavior

Passing an env with `apptainer run --env 'ABC=def(x)' the container` works (`echo $ABC` shows the expected output).

However, i cannot get this to work with `--env-file`. (I also tried adding `--no-eval`)

### Actual behavior

```
[]$cat envfile 
ABC=x(y)
[]$apptainer run --env 'ABC=def(x)' thecontainer 
Apptainer> echo $ABC
def(x)
Apptainer> exit
[]$apptainer run --env-file envfile  thecontainer 
FATAL:   while setting environment: while processing envfile: while evaluating environment script: while parsing script: apptainer:1:6: a command can only contain words and redirects; encountered (
[]$apptainer run --no-eval --env-file envfile  thecontainer 
FATAL:   while setting environment: while processing envfile: while evaluating environment script: while parsing script: apptainer:1:6: a command can only contain words and redirects; encountered (
```

### Steps to reproduce this behavior

See previous step

### What OS/distro are you running

```sh
RHEL8.8
```

### How did you install Apptainer

rpm

**Comment by stdweird** [comment]
if you escape the characters in the envfile that trigger the error, the error is gone, but the escape chars themself are still there.
```
[]$cat envfile
ABC=x\(y\)
[]$apptainer run --env-file envfile  thecontainer 
Apptainer> echo $ABC
x\(y\)
```

**Comment by DrDaveD** [comment]
Did you try using double quotes as it shows in the [documentation](https://apptainer.org/docs/user/latest/environment_and_metadata.html#env-file-option)?
