### ISSUE TITLE
Squashfuse not mounting: version 'FUSE_3.12' not found

### ISSUE THREAD

**Issue by stamenminkov** [apptainer/apptainer#2477]
### Version of Apptainer

`1.3.3`, latest release

### Expected behavior

I've just installed `Apptainer` and I'm testing the basic behaviour with the simple _lolcow_. Was expecting this to go smooth , however the image is not mounting.

### Actual behavior

For some reason `squashfuse` is failing to do the mount, stating that it needs `FUSE-3.12 `:
```
>$ apptainer run docker://godlovedc/lolcow
INFO:    Using cached SIF image
FATAL:   container creation failed: image driver mount failure: image driver squashfuse_ll instance exited with error: squashfuse_ll
exited: .../software/squashfuse/0.5.1-GCCcore-13.2.0/bin/squashfuse_ll: /lib64/libfuse3.so.3: version `FUSE_3.12' not found (required
by .../software/squashfuse/0.5.1-GCCcore-13.2.0/bin/squashfuse_ll)
```

This is pretty weird, as my `squashfuse` installation is based on `FUSE-3.16.2`, which should be more than enough. I've also tested the installation with `FUSE-3.12` itself, but nothing changes, same error appears.

Also, `squashfuse` itself seems to be working, the problem is when I install `Apptainer` with `squashfuse` as a dependence - it's that moment in which the error message appears.

### Steps to reproduce this behavior

--

### What OS/distro are you running

RHEL-9.2

### How did you install Apptainer

As a module via **EasyBuild**, same as I've installed `squashfuse` and the rest of the dependencies. Attaching here the recipe for the record:

[Apptainer-1.3.3-GCCCore-13.2.0.txt](https://github.com/user-attachments/files/16850805/Apptainer-1.3.3-GCCCore-13.2.0.txt)

The build and the installation work fine for `Apptainer`, the error appears after that, when trying to run the _lolcow_.

**Comment by afbjorklund** [comment]
Sounds like a missing rpath or something, causing it to find the 3.10 from the OS (rather than your custom 3.16)

**Comment by DrDaveD** [comment]
This looks like a problem with your host squashfuse build, not with apptainer.  Please ask the easybuild community for help.

**Comment by stamenminkov** [comment]
Thank you both, I'll have a further look !
