### ISSUE TITLE
Update CONTRIBUTING.md to include list of committers per LF technical charter

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#25]
The technical charter requires the CONTRIBUTING.md file in the repository to contain a list of TSC members/committers, or to document an alternative method of designation.

Re: https://apptainer.org/technical-charter section 2(b)

**Comment by DrDaveD** [comment]
While we're at it also look for g@sylabs.io email address in other files, I noticed that in a debian file.
