### ISSUE TITLE
apptainer ubuntu ppa is out of date

### ISSUE THREAD

**Issue by gdevenyi** [apptainer/apptainer#2505]
The latest version of apptainer available in official ppa is 1.3.2: https://launchpad.net/~apptainer/+archive/ubuntu/ppa

While 1.3.3 and 1.3.4 have been released here.

1.3.4 is particularly important because apptainer is broken on 24.04(noble) without the apparmor fixes or a manual workaround.

**Comment by DrDaveD** [comment]
@panda1100, what's the status of that?

**Comment by afbjorklund** [comment]
The 1.3.3 was skipped for the PPA, since the fix needed fixes:

* https://github.com/apptainer/apptainer/issues/2423

**Comment by panda1100** [comment]
@DrDaveD @afbjorklund @gdevenyi version 1.3.4 will be available within an hour or two, just built packages on PPA.
