### ISSUE TITLE
FATAL: .... /<myhome>/build-temp- >341338364/rootfs/etc/gshadow: unpriv.lclearxattrs: unpriv.llistxattr: permission denied

### ISSUE THREAD

**Issue by gsal** [apptainer/apptainer#2522]
same installation
apptainer worked for me 2 months ago
apptainer no longer works today

- this is the first time I am trying to use it after the latest upgrade to our Linux environment
- We went from Rocky 9.3 to Rocky 9.4
- I heard that NFS version also changed from 3 to 4, and
- possibly some SELinux settings also changed

Any idea what could be the problem? 

### Version of Apptainer
apptainer version 1.3.3-1.el9

### Expected behavior
To get a writable container

### Actual behavior
fatal error message

### Steps to reproduce this behavior
Simply issuing the following command:
`apptainer build --sandbox secondsif/ docker://rockylinux:9.3`

### What OS/distro are you running

```sh
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
```

### How did you install Apptainer
I don't remember; it was IT who installed it for me sometime back, probably via the typical yum/dnf route, and such installation worked for many months and it now stopped working....see reported changes above.

**Comment by gsal** [comment]
Hhhmmm....continuing to test. 

I had a colleague try the apptainer command, it worked for him; but, he's got his own machine and his home directory in the same box. 

Then, I asked him to login to the same DCV node where I am logged in...it did not work for him either. 

So, something about having a local HOME vs NFS mounted. 

Back to debugging.

**Comment by DrDaveD** [comment]
There is a note in the [admin doc](https://apptainer.org/docs/admin/latest/installation.html#fakeroot-with-uid-gid-mapping-on-network-filesystems) advising against using /etc/subuid mappings when building a sandbox in a network filesystem.  Does it behave differently with `--ignore-subuid`?

**Comment by gsal** [comment]
No, it does not behave differently with `--ignore-subuid`.  That's fine, I am not using /etc/subuid....the lack of need for a server is the reason why I prefer podman over docker....and the lack of need for entries in /etc/subuid is the reason why I prefer apptainer over podman. 

Because of the NFS vs local directory, I simply changed directory to the local /tmp and now I am able to execute the apptainer build command.  That's good, but this is new behavior; this was not the case with 9.3, NFS3 and "less SELinux enforcement"?

Thanks for link to the admin doc.

**Comment by gsal** [comment]
I guess I will be closing this issue.  

NFS mounted directory is only a problem when attempting to create a write-able container; then again, this only be necessary during testing, interactively, with human intervention. Once the contents of the container is known, the typical apptainer build command for creating read-only containers works just fine, no matter whether the working directory is NFS mounted or not.
