### ISSUE TITLE
apptainer instance doesn't log when command is run via exec

### ISSUE THREAD

**Issue by alexschroeter** [apptainer/apptainer#2524]
### Version of Apptainer

``` 
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.5 LTS
Release:        22.04
Codename:       jammy
```
`apptainer version 1.3.4`

### Expected behavior
When starting an instance, I expect the output of that instance to be logged to the log file shown in `apptainer instance list --json`.

### Actual behavior
Logs seem only to be generated when running with `apptainer instance run`

#### Incorrect behavior
```
aschroeter@Watson:~/deployer$ apptainer instance list
INSTANCE NAME    PID    IP    IMAGE
aschroeter@Watson:~/deployer$ apptainer instance start docker://ubuntu test
INFO:    Using cached SIF image
INFO:    Instance stats will not be available - requires cgroups v2 with systemd as manager.
INFO:    squashfuse not found, will not be able to mount SIF or other squashfs files
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    gocryptfs not found, will not be able to use gocryptfs
INFO:    Converting SIF file to temporary sandbox...
INFO:    instance started successfully
aschroeter@Watson:~/deployer$ apptainer instance list
INSTANCE NAME    PID      IP    IMAGE
test             12319          /tmp/rootfs-214947865/root
aschroeter@Watson:~/deployer$ apptainer instance list --json
{
        "instances": [
                {
                        "instance": "test",
                        "pid": 12319,
                        "img": "/tmp/rootfs-214947865/root",
                        "ip": "",
                        "logErrPath": "/home/aschroeter/.apptainer/instances/logs/Watson/aschroeter/test.err",
                        "logOutPath": "/home/aschroeter/.apptainer/instances/logs/Watson/aschroeter/test.out"
                }
        ]
}
aschroeter@Watson:~/deployer$ apptainer exec instance://test ls
__pycache__  app.py 
aschroeter@Watson:~/deployer$ cat ~/.apptainer/instances/logs/Watson/aschroeter/test.out 
```

#### Correct behavior
```
aschroeter@Watson:~/deployer$ apptainer instance run docker://ubuntu test ls
INFO:    Using cached SIF image
INFO:    Instance stats will not be available - requires cgroups v2 with systemd as manager.
INFO:    squashfuse not found, will not be able to mount SIF or other squashfs files
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    gocryptfs not found, will not be able to use gocryptfs
INFO:    Converting SIF file to temporary sandbox...
INFO:    instance started successfully
aschroeter@Watson:~/deployer$ cat ~/.apptainer/instances/logs/Watson/aschroeter/test.out 
__pycache__
app.py
```

### What OS/distro are you running

```sh
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer

Clones git repo, checked out 1.3.4, mconfig, make, make install

**Comment by DrDaveD** [comment]
What output do you expect the instance start to have?  I don't think it has any output.

By the way, you seem to have missed the instructions for [installing dependent fuse packages](https://github.com/apptainer/apptainer/blob/release-1.3/INSTALL.md#compiling-dependent-fuse-based-packages), although in this case I don't think it interfered with anything you were trying to do.

**Comment by alexschroeter** [comment]
I didn't expect instance start to have any output but I expected the command passed to that instance via exec to show up in the instance log.

**Comment by DrDaveD** [comment]
Oh, I see.  No, that's not the way it works.  The instance log is just for output from the instance start or instance run.  It would be very surprising to most people to not see the output of an exec command from where it is run.

**Comment by alexschroeter** [comment]
Thank you, that explains why it is handling this way. I was only looking into this workaround of starting the instance and running with `exec` because `instance run` doesn't allow passing `--pwd`. Is this also special behavior of instance, or did I miss something in the documentation? In any case, I will close the issue since it seems to work as intended, from your explanation.
