### ISSUE TITLE
Feature request: disable LD_PRELOAD importing from host

### ISSUE THREAD

**Issue by koysean** [apptainer/apptainer#2537]
### Version of Apptainer

```
apptainer version 1.3.2
```

### Description of Request

This is a feature / build configuration request.

My site has an `LD_PRELOAD` library injected into every app execution. The `apptainer` call needs to have this `LD_PRELOAD` set, but commands run within the container should not use this `LD_PRELOAD` variable.

I can work around it with `apptainer --env LD_PRELOAD= [...]` but since this is a shared installation on a computing cluster, I would rather resolve this at build-time or through some global configuration.

I would appreciate any suggestions or where in the source code an appropriate patch could go.

### Expected behavior

The container should run without `LD_PRELOAD` imported from the host.

### Actual behavior

When running apptainer, `LD_PRELOAD` gets imported into the container, which causes this error:
```
ERROR: ld.so: object '/soft/xalt/3.0.2-202408282050/lib64/libxalt_init.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```
with every command.

### How did you install Apptainer

From source via Spack.

**Comment by DrDaveD** [comment]
Does exporting `APPTAINERENV_LD_PRELOAD=""` work for you?

**Comment by koysean** [comment]
Setting that at runtime does indeed work, and I can use that as a workaround for now. Thanks for your help!
