### ISSUE TITLE
Consider resetting PKG_CONFIG_PATH by default, like PATH and LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by kcgthb** [apptainer/apptainer#2563]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
$ apptainer --version
apptainer version 1.3.2-1.el7
```
### Expected behavior

`PKG_CONFIG_PATH` on the host may contain information about available software and libraries, and passing it unmodified to the container environment could lead to all sorts of issues, exactly like for `PATH` and `LD_LIBRARY_PATH` that are [already sanitized](https://apptainer.org/docs/user/main/environment_and_metadata.html#environment-from-the-host) by default.

For instance, for `LD_LIBRARY_PATH`:
```
$ echo $LD_LIBRARY_PATH
/share/software/user/open/openssl/3.0.7/lib64
$ apptainer exec docker://alpine sh -c 'echo $LD_LIBRARY_PATH'
/.singularity.d/libs
```

One would expect the same behavior for `PKG_CONFIG_PATH`, to avoid "contaminating" the container with information about library paths that are specific to the host.

Using `--cleanenv` is not really an option, since many other host environment variables may be relevant in the container. But there are probably not many use cases where `PKG_CONFIG_PATH` is.

### Actual behavior

`PKG_CONFIG_P{ATH` is unfortunately passed to the container unmodified

```
$ echo $PKG_CONFIG_PATH
/share/software/user/open/openssl/3.0.7/lib64/pkgconfig
$ apptainer exec docker://alpine sh -c 'echo $PKG_CONFIG_PATH'
/share/software/user/open/openssl/3.0.7/lib64/pkgconfig
```

### Steps to reproduce this behavior

See above

Thanks!

**Comment by DrDaveD** [comment]
Perhaps that's worth doing, but on the other hand it seems to me to be a very little used application that is affected.  There are variables for other applications that are probably more widely used that apptainer also doesn't mess with, such as PYTHONPATH.  So I'm not sure where it would end.

**Comment by kcgthb** [comment]
That's a good point. But there already are exceptions for `PATH` and `LD_LIBRARY_PATH`, which are treated differently, so why just those two? :)

**Comment by DrDaveD** [comment]
Probably because PATH affects everyone and LD_LIBRARY_PATH affects a large number, I think.

**Comment by kcgthb** [comment]
Ok. One possibility would by for site admins to globally define `APPTAINERENV_*` variables to empty values (like `export APPTAINERENV_PKG_CONFIG_PATH=""`), but that leads to execution warning when entering a container, which is less than ideal :\

```
WARNING: Environment variable PKG_CONFIG_PATH already has value [], will not forward new value [/share/software/user/open/openssl/3.0.7/lib64/pkgconfig] from parent process environment
```

**Comment by DrDaveD** [comment]
Do you have a modified version of apptainer?  I don't see how that message can come from unmodified code.  That message comes when a variable is listed in `alwaysPassKeys` in internal/pkg/util/env/create.go, and `PKG_CONFIG_PATH` is not in the list.

**Comment by kcgthb** [comment]
Interesting! No, no modified version, we're running Apptainer straight from the EPEL RPM (`apptainer-1.3.2-1.el7.x86_64`)

**Comment by DrDaveD** [comment]
Oh now I see I misread the code, because `mustAddToHostEnv` returns true by default.

**Comment by DrDaveD** [comment]
So it's doing the right thing by not forwarding the parent's value, it just shouldn't be a warning.

**Comment by kcgthb** [comment]
Indeed :)
Anyway to hide the warning?

I see that `internal/pkg/util/env/create.go` has a `alwaysOmitKeys` which already contains `PATH` and `LD_LIBRARY_PATH`. Would it make sense to add more variables there, or (better) add the possibility to get a list from the configuration file? Like a `omit envvars` list of environment variables to ignore in `apptainer.conf` ?

**Comment by DrDaveD** [comment]
I see that when I [reviewed the PR that initially added this message](https://github.com/apptainer/apptainer/pull/131#pullrequestreview-850846612) I noted that it was a new warning message.  I couldn't see a problem with it at the time, but maybe it should just be a debug message instead of a warning.

Regarding adding a configuration option for omitting more environment variables, I'd be reluctant to do that, especially since there's another way to do it.

**Comment by kcgthb** [comment]
Ok, I agree that moving that WARNING message to DEBUG seems like the best compromise, then.

**Comment by kcgthb** [comment]
Hi!

I'd like to re-open and revisit this issue in light of a use case I didn't envision before: when environment variables are set in containers' definition files, and need to be preserved. Using `APPTAINERENV_*` will not only override the value of the environment variable set on the host, but it will also override the value that's pre-defined in the container.

Imagine a `.def` file that defines `PYTHONPATH=/opt` in the `%environment section`:
```
Bootstrap: docker
From: alpine

%environment
    export PYTHONPATH="/foo"

%runscript
    echo "PYTHONPATH=$PYTHONPATH"
```

If we want to avoid that host-local PYTHONPATHs "leak" to containers, we can set `APPTAINERENV_PYTHONPATH=""` globally to [override](https://apptainer.org/docs/user/latest/environment_and_metadata.html#environment-from-the-host) it. 

Now, imagine that there's a `PYTHONPATH` defined on the host, when the container starts, say `PYTHONPATH=/path/on/host`. In that case, with `APPTAINERENV_PYTHONPATH=""` the value that's set in the container definition file is lost as well:
```
$ export PYTHONPATH=/path/on/host
$ export APPTAINERENV_PYTHONPATH=""
$ apptainer run test.sif
PYTHONPATH=
```

If we don't set `APPTAINERENV_PYTHONPATH`, when the container doesn't explicitly redefine `PYTHONPATH`, then the environment variable from the host is leaked to the container, and that can cause issues as well.

Is there a way to just prevent host environment variables to be transmitted to the container environment, *without* overriding them when they're already defined in the container?

**Comment by kcgthb** [comment]
Yes, `-e` certainly works, but it's too much as it unsets *all* the host environment variables. And there are plenty of those variables that need to be passed on to the container environment (user-specific environment variables, those defining storage locations, like `$PROJECT` or `$SCRATCH`, and so on). 

We don't want to completely clean the user environment, but just prevent *some* specific env vars that alter software behavior (like `$PYTHONPATH`, `$CPATH`, etc) from leaking to containers and potentially causing issues there. While preserving those variables if they're defined in the container.

A concrete example is a user defining a `PYTHONPATH` in their `.bashrc` that point to a directory in their `$HOME`, and using a Python-based container that has different versions of the same Python packages: the `PYTHONPATH` env var will leak to the container, and since the user's `$HOME` dir is bind-mounted in the container (and needs to be for other reasons), that will conflict with the container own packages.

Looking at the [order of precedence](https://apptainer.org/docs/user/latest/environment_and_metadata.html#environment-variable-precedence) I guess we would need an extra check in the last step, that would become:
> Restore environment variables from the host, if they have not already been set in the container, and the `--cleanenv` / `--containall` options were not specified, *and those variables are not part of the exclusion list*

and we could have the exclusion list provided:
* either via the command line (exactly like `--env` today) as maybe `--drop-env MYVAR1,MYVAR2` and `--drop-env-file file`
* or as an environment variable (like `APPTAINERENV_*`), maybe as `APPTAINERDROPENV_MYVAR`, `APPTAINERDROPENV_MYVAR2`...


Not sure what the best approach would be, but the bottom line is that we need a way to selectively drop environment variables from the host environment, while passing the rest of that host environment to the container, without overriding variables that are already pre-defined there (and which should take precedence IMO). 
Does that make sense?

**Comment by DrDaveD** [comment]
Do you have your own script for launching apptainer?  Can you just do `unset` on those variables before invoking apptainer, or set them to empty?

**Comment by DrDaveD** [comment]
I suppose there could be a `--no-env` option listing environment variables to not import from the host.  It would need to be discussed with the development team.  Please create a new issue with your request.

**Comment by kcgthb** [comment]
Thanks! I've created #2890 for this.
