### ISSUE TITLE
OCI images imported into singularity without --fakeroot have permissions issues

### ISSUE THREAD

**Issue by deliciouslytyped** [apptainer/apptainer#2564]
I hope I'm just missing something here. If this information isn't enough, I'll go and get more details and a reproducer, I just wanted to get this posted.
The issue is relatively simple:

In `docker build` (or presumably any other OCI containers, from any source) files will be owned by root or whatever UIDs/GIDs are inside the distro, unless otherwise set.

Singularity without --fakeroot, and the implicit sandbox construction that causes, is much faster than passing --fakeroot, so I would prefer to run Singularity without fakeroot. So really, what I want is to be able to use a container image, with my current IDs.

Running without --fakeroot runs into permissions issues caused by the user running under their normal ID in the container, which on an HPC cluster can be wildly different from what the containerized distro expects.

I would prefer that the solution doesn't involve chmodding files to a given set of hardcoded IDs or similar in the container build, so that other users can also use the images. (Doing this, if I understand correctly, also inflates the size of the OCI images, because changing the metadata means every involved file is copied up to another layer.)

Is there a solution to this / could singularity offer a solution to this?

These look related?
https://github.com/apptainer/singularity/issues/4671
https://github.com/apptainer/singularity/pull/4522

### Version of Apptainer
```
$ singularity --version
singularity-ce version 4.0.1
```

**Comment by DrDaveD** [comment]
That is singularity-ce, so submit our issue instead at https://github.com/sylabs/singularity.
