### ISSUE TITLE
Conversion of Docker image leads to broken env variables

### ISSUE THREAD

**Issue by PhilipVinc** [apptainer/apptainer#2576]
I'm using Apptainer 1.3.4

I've tried to generate some Apptainer images starting from some Docker images.
However, the singularity images are broken.

This is my singularity definition file
```bash
$ cat container_definition
Bootstrap: docker
From: rocm/jax:latest-py3110

%post
    pip install jaxopt diffrax
    pip install matplotlib
```

The resulting image is broken because of the following error which happens both during container generation and whenever I try to run the container
```bash
source: /.singularity.d/env/10-docker2singularity.sh:2:8: invalid var name
```

Looking at the content of the auto-generated 10-docker2singularity.sh:2:8 I see the following first two lines
```bash
$ head -n 3 /.singularity.d/env/10-docker2singularity.sh
#!/bin/bash
export XLA_CLONE_DIR:/workspace/jax-xla-repo="${XLA_CLONE_DIR:/workspace/jax-xla-repo:-}"
export XLA_BRANCH="${XLA_BRANCH:-"rocm-jaxlib-v0.4.21"}"
```

The original docker image works correctly, so I believe this is an apptainer problem

**Comment by DrDaveD** [comment]
I have looked into this.  The [parsing code](https://github.com/apptainer/apptainer/blob/release-1.3/internal/pkg/build/sources/conveyorPacker_oci.go#L522) is seeing a case where the env contains both `XLA_CLONE_DIR:/workspace/jax-xla-repo` and`XLA_CLONE_DIR=/workspace/jax-xla-repo`.   It's unclear how that's supposed to be interpreted, and it could be argued that it's a flaw in the container, but it does make sense for the parsing code to be updated to not treat something as a variable assignment if it has any character that is not acceptable in a variable name.
