### ISSUE TITLE
support subid from /etc/nsswitch module

### ISSUE THREAD

**Issue by steverweber** [apptainer/apptainer#2599]
### Version of Apptainer

`apptainer version 1.3.4`

### Expected behavior

```
apptainer build my.sif my.def
finds subid info without INFO: notice.
```

### Actual behavior

```
apptainer build my.sif my.def
## INFO:    User not listed in /etc/subuid, trying root-mapped namespace
```

Why was it incorrect?

```
Its not _incorrect_. User is not in the /etc/subuid or /etc/subgid file
because using a `/etc/nsswitch` module to handle subid. I wrote a custom
one however others might be using sssd to handle subid and also hit this.
getsubids $USER
0: my 1013078736 65536
getsubids -g $USER
0: my 1013078736 65536
```

### How did you install Apptainer

```
apt install -y software-properties-common
add-apt-repository -y ppa:apptainer/ppa
apt update
apt install -y apptainer
```

**Comment by steverweber** [comment]
perhaps a simple fix is to have IsUIDMapped check if `getsubids` is on the path and if it is exec it and check the output.  I assume there will be other bugs if we follow the rabbit.

https://github.com/apptainer/apptainer/blob/e6fc6f0d5862a372241a8bec50b980036e37975e/internal/pkg/fakeroot/fakeroot.go#L392

**Comment by DrDaveD** [comment]
This should now be supported in the main branch in preparation for 1.4.0, added in #2433.  Please try it out and reply here if it works for you.

**Comment by steverweber** [comment]
Sweet! I'll wait for a 1.4.0 release or attempt to build from source!
