### ISSUE TITLE
Build crashes: ERROR: unpackSIF failed: root filesystem extraction failed: extract command failed: free(): invalid pointer

### ISSUE THREAD

**Issue by Heng-Zhou** [apptainer/apptainer#2600]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

Apptainer: 1.3.4
Singularity: singularity-ce version 4.2.1-jammy

### Expected behavior

What did you expect to see when you do...?

Build the container without any error.

### Actual behavior

What actually happened? Why was it incorrect?
```
ERROR:   unpackSIF failed: root filesystem extraction failed: extract command failed: free(): invalid pointer
FATAL:   container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer
: exit status 255
FATAL:   While performing build: packer failed to pack: while unpacking local image: root filesystem extraction failed: extract command failed: free(): invalid pointer
FATAL:   container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer
: exit status 255
```
There is an error during building, but there should be no errors, so it is incorrect.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

1) Build a base OS on Ubuntu 22.04.5 LTS

Definition file (baseos.def):
```
Bootstrap: docker
From: jupyter/datascience-notebook

%files
    /lib/modules/6.8.0-47-generic

%post
    apt -y update && apt -y upgrade
```

Build it using command `sudo singularity build -F baseos.sif baseos.def`

2) Copy generated `baseos.sif` file from Ubuntu machine to RedHat machine.

3) Build on RedHat 8.8 on top of the base OS `baseos.sif`

Definition file (test.def):
```
Bootstrap: localimage
From: baseos.sif
```

Build it using command `apptainer build -F test.sif test.def`, and the above error occurs.

### What OS/distro are you running

```sh
$ cat /etc/os-release

```

For step 1):
```
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

```
For step 2):
```
NAME="Red Hat Enterprise Linux"
VERSION="8.8 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.8 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.8
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.

Singularity on Ubuntu is installed from `apt install` command
Apptainer on RedHat is built from source.

Thank you in advance for help solve this building issue.

**Comment by DrDaveD** [comment]
Why is a path from /lib/modules being included?  Those are only relevant to kernels, and since the kernel is shared between the host and the container, they should be ignored inside of a container.

If the problem is also happening in singularity-ce, I suggest reporting the problem at https://github.com/sylabs/singularity, and reference this issue.

**Comment by DrDaveD** [comment]
I tried to reproduce your problem and did not succeed.  I built the initial sif on Ubuntu 22.04.5 with apptainer 1.3.4 although I had to change the %files line to `/lib/modules/6.8.0-48-generic`.  Also, my EL8 version is Rocky 8.10 and not 8.8.  The second build using apptainer 1.3.4 worked without errors.

Did you happen to use a network filesystem for your scratch space on the EL8 system?  If so, please try it on a local filesystem.

**Comment by Heng-Zhou** [comment]
@DrDaveD: After I deleted specific commands in `%post`, I forgot to delete `%files`. Sorry about that. 

Now I have deleted `%files` section, but the same building crash occurs.

`APPTAINER_TMPDIR` is set to `/tmp` on RedHat which is a local filesystem (I have checked that using `lsblk`), not a network filesystem. Could the scratch space of Apptainer be defined by other environment variables?

I think the problem lies in building the BaseOS with singularity first on Ubuntu 22.04 and then apptainer on RedHat using the generated BaseOS. If you follow my steps (not both apptainer), you should reproduce the same error. "free(): invalid pointer" is a common programming bug when dealing with pointers not successfully allocated.

Singularity works without any problem if singularity is used in both building steps. Unfortunately, I have no control over what tool to use on each OS, so I would appreciate it greatly if you can give a thorough troubleshooting. Thank you.

**Comment by Heng-Zhou** [comment]
@DrDaveD: I think I have narrowed the problem down to Bootstrap of the definition file.

If the Bootstrap is `docker`, there is no reported errors when building with apptainer:
```
Bootstrap: docker
From: ubuntu
```

However, if the Bootstrap is `library`, the reported error occurs when building with apptainer (command: `apptainer build -F test.sif test.def`):
```
Bootstrap: library
From: ubuntu
```
The whole output of building is:
```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under the fakeroot command
WARNING: SINGULARITY_CACHEDIR and APPTAINER_CACHEDIR have different values, using the latter
WARNING: 'nodev' mount option set on /dev/shm, it could be a source of failure during build process
INFO:    Starting build...
INFO:    Using cached image
INFO:    Verifying bootstrap image /tmp/cache/library/sha256.7a63c14842a5c9b9c0567c1530af87afbb82187444ea45fd7473726ca31a598b
ERROR:   unpackSIF failed: root filesystem extraction failed: extract command failed: free(): invalid pointer
FATAL:   container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer
: exit status 255
FATAL:   While performing build: packer failed to pack: root filesystem extraction failed: extract command failed: free(): invalid pointer
FATAL:   container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer
: exit status 255

```

**Comment by DrDaveD** [comment]
Now I'm confused about when exactly you do that step and with what tool, because you didn't previously say anything about a library bootstrap.

Please give step-by-step instructions again to reproduce.   The full build output was helpful, because it shows you're using the apptainer "fake fakeroot" mode, without /etc/subuid mapping.  That's probably significant.

**Comment by Heng-Zhou** [comment]
Below are the steps to reproduce the building error. The error occurs in two situations :1) the Bootstrap is `library`, 2) use local image as base OS.

Steps for situation 1).

- Create a definition file named `test.def` as below:
```
Bootstrap: library
From: ubuntu
```
- Build with the command
`apptainer build -F test.sif test.def`

There is a building error. The whole output of messages and errors are as follows:
```
WARNING: SINGULARITY_TMPDIR and APPTAINER_TMPDIR have different values, using the latter
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
WARNING: SINGULARITY_TMPDIR and APPTAINER_TMPDIR have different values, using the latter
INFO:    The %post section will be run under the fakeroot command
WARNING: SINGULARITY_CACHEDIR and APPTAINER_CACHEDIR have different values, using the latter
INFO:    Starting build...
INFO:    Verifying bootstrap image test.sif
INFO:    Extracting local image...
ERROR:   unpackSIF failed: root filesystem extraction failed: extract command failed: free(): invalid pointer
FATAL:   container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer
: exit status 255
FATAL:   While performing build: packer failed to pack: while unpacking local image: root filesystem extraction failed: extract command failed: free(): invalid pointer
FATAL:   container creation failed: while getting /proc/self/ns/user file descriptor: while requesting file descriptors send: read unix @->@: read: connection reset by peer
: exit status 255
```

Steps for situation 2).
- Create a definition file named `test.def` as below:
```
Bootstrap: docker
From: ubuntu:22.04
```
- Build with command
`apptainer build -F test.sif test.def`
An Singularity container file is generated successully named `test.sif`. This shows that Apptainer can build if Bootstrap is `docker`.
- Modify the definition file `test.def` to be:
```
Bootstrap: localimage
From: test.sif
```
- Build with command
`apptainer build -F test.sif test.def`
The same building error occurs as above.

Thank you and looking forward to any help with this issue.

**Comment by DrDaveD** [comment]
You did this on what host operating system?  It doesn't fail for me on rocky8:
```
WARNING: SINGULARITY_TMPDIR and APPTAINER_TMPDIR have different values, using the latter
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
WARNING: SINGULARITY_TMPDIR and APPTAINER_TMPDIR have different values, using the latter
INFO:    The %post section will be run under the fakeroot command
WARNING: SINGULARITY_CACHEDIR and APPTAINER_CACHEDIR have different values, using the latter
INFO:    Starting build...
INFO:    Downloading library image
28.4MiB / 28.4MiB [=========================================] 100 % 3.8 MiB/s 0s
INFO:    Verifying bootstrap image /scratch/tmp/cache/library/sha256.7a63c14842a5c9b9c0567c1530af87afbb82187444ea45fd7473726ca31a598b
INFO:    Creating SIF file...
INFO:    Build complete: issue2600.sif
```

**Comment by Heng-Zhou** [comment]
The administrator of the HPC I am working on helped me figure out the reason and fix the issue. Thank you all. This ticket is now closed.

**Comment by DrDaveD** [comment]
What was the problem?

**Comment by Heng-Zhou** [comment]
They suspected that the issue comes from the Go 1.22 or GCC-13.3.0 used in building Apptainer 1.3.4. So, they built Apptainer 1.3.5 using Go 1.21.6 and GCC 11.3.0 and it works.
