### ISSUE TITLE
mksquashfs mem default

### ISSUE THREAD

**Issue by steverweber** [apptainer/apptainer#2601]
A default on `mksquashfs mem` would have prevent crashes on a HPC I manage.

apptainer version 1.3.4

workaround

```
sed -i '/#<CUSTOM/,/#CUSTOM>/d' /etc/apptainer/apptainer.conf
<<EOF cat >> /etc/apptainer/apptainer.conf
#<CUSTOM
mksquashfs mem = 1G
#CUSTOM>
EOF
```

**Comment by steverweber** [comment]
perhaps related to defaults for mksquashfs https://github.com/apptainer/apptainer/issues/1823

**Comment by DrDaveD** [comment]
Was that a reduction in the amount of memory that was needed?   Maybe if it didn't spawn so many processes you would have been OK?

Was this on a login node or a compute node?

**Comment by steverweber** [comment]
A small compute node with physical 32G mem however SLURM cgroup limited the session to something perhaps 3 to 6G?

The crash was during `apptainer build`
I likely stumbled on to the fix from: https://github.com/apptainer/singularity/issues/5434

A default of `mksquashfs mem = 1G` might be too small? 2G might be better.


recreating my environment is complex. but perhaps this might help.

```
# NOTE using podman and nfs filesystem with fuse-overlay_1.14
git clone https://github.com/steverweber/autogrow4
cd autogrow4/docker
./autogrow_in_docker.py \
    --override_sudo_admin_privileges yes \
    --json_file=./examples/sample_autogrow_docker_json_multithreading.json
podman images
rm -f autogrow4_oci.tar
podman save -o autogrow4_oci.tar localhost/autogrow4
#NOTE: autogrow4_oci.tar is 3.7G
apptainer build autogrow4.sif docker-archive://autogrow4_oci.tar
... some error like: FATAL ERROR:Failed to create thread
```

**Comment by steverweber** [comment]
adding env vars might be the best option to allow HPC admins to keep things performant and safe for the user session.

```
APPTAINER_MKSQUASHFS_PROCS=$(( $(nproc) / 2 + 1 ))
APPTAINER_MKSQUASHFS_MEM='1G'
```

Because I need things to just work; my current solution is to use safer slower values in `apptainer.conf`

```
# this might require ~4G total?
mksquashfs prod = 4
mksquashfs mem = 1G
```

The other fix would be better error message.
"ERROR:Failed to create thread" say something regarding:
`review apptainer.conf 'mksquashfs proc' and 'mksquashfs mem' values`

Also perhaps the default installed `apptainer.conf ` could use a remark in the files..
```
# mksquashfs would requires 6 * 2G memory ... im guessing here.
#mksquashfs proc = 6
#mksquashfs mem = 2G
```

**Comment by steverweber** [comment]
good points. I'll stand up a handful of nodes for interactive jobs and container management. I was mostly "kicking the tires".
I'll close this ticket because the other ticket has things handled. Thanks for the quick comments!
