### ISSUE TITLE
bind external path in singularity run

### ISSUE THREAD

**Issue by Overcraft90** [apptainer/apptainer#2622]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer version 1.1.9`

### Expected behavior

Correct help instruction for the Deep Variant tool e.g. without the following error prompted at `stdout`

```
2024-11-12 15:40:09.008692: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /hpc/apps/cuda/cuda_12.2.2/lib64/:/.singularity.d/libs
2024-11-12 15:40:09.008745: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /hpc/apps/cuda/cuda_12.2.2/lib64/:/.singularity.d/libs
2024-11-12 15:40:09.008752: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
```

### Actual behavior

The tool runs smoothly until it engages GPU in the second step of the processing; this causes the run to abort and returns the previous message. In theory, the application should run to completion using the following:

```
singularity run --nv -e --bind ${INPUT} --bind ${OUTPUT} --bind ${TMP} /hpc/home/ngrmtt1/deepvariant_1.6.0-gpu.sif \
  /opt/deepvariant/bin/run_deepvariant \
  --model_type=WGS \
  --ref=INLUP_amiga.fa \
  --reads=${INPUT}/${BAM} \
  --intermediate_results_dir=${TMP} \
  --output_vcf=${OUTPUT}/${VCF}.vcf.gz \
  --output_gvcf=${OUTPUT}/${VCF}.g.vcf.gz \
  --make_examples_extra_args="min_mapping_quality=1,keep_legacy_allele_counter_behavior=true,normalize_reads=true" \
  --num_shards=16
```
however, it seems to not be able to see the environment variable export `LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/hpc/apps/cuda/cuda_12.2.2/lib64/`, which I set outside the container, and recall in phase of launching with `--bind /hpc/apps/cuda/cuda_12.2.2/lib64`. On the other hand, running singularity shell and exporting the variable within the container seems to work, but I'm unsure whether it can be used in a conventional script. Ideally, I'm looking for a way to export environment variable along with singularity run.

### Steps to reproduce this behavior

Run the above code-block even with provided test files. 

### What OS/distro are you running

```sh
NAME="Rocky Linux"
VERSION="9.2 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.2"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.2 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.2"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.2"

```

### How did you install Apptainer

The IT team did it, so not sure about the actual procedure.

**Comment by DrDaveD** [comment]
Those libraries are not in the standard list in /etc/apptainer/nvliblist.conf, even in the latest apptainer version.  Please ask your system administrator to add the there and let us know if that fixes the problem.  Perhaps they should be added to the standard list.

**Comment by Overcraft90** [comment]
@DrDaveD and @GodloveD I fixed the issue. As you pointed out it was a problem at development stage. `Deep Variant v1.6.0` was built with an older CUDA driver compared to the one loaded on the cluster - unfortunately I have no control, nor I can ask to play too much with CUDA versions on the cluster - which led to this problem.

After getting back to the `Deep Variant` developers, they already had in plan a new release which match the more updated CUDA drivers, which in turn suppressed the error in question. Thanks, I think we can close for now.
