### ISSUE TITLE
capability.json: permission denied error

### ISSUE THREAD

**Issue by doliv071** [apptainer/apptainer#2652]
### Version of Apptainer

```
[12:44] $ apptainer --version
apptainer version 1.3.4
```

### Expected behavior

The container should run without requiring `sudo`

### Actual behavior

The container fails with permission error related to `capability.json`
```
[12:19] $ apptainer run test.sif 
FATAL:   while opening capability config file: open /usr/local/etc/apptainer/capability.json: permission denied
```
The container will run just fine with sudo.

```
[12:55] $ sudo apptainer run test.sif 
PRETTY_NAME="Ubuntu 24.04 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo
```

### Steps to reproduce this behavior

I can fix the issue by changing the permission of the capability.json file (in `/usr/local/etc/apptainer/` on my system) from 640 to 644. And similarly reproduce the issue by changing it back to 640.  

### What OS/distro are you running

```bash
[12:56] $ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer

using the clone and compile method as directed in the documentation (no special arguments set and NOT using the `--with-suid` flag) https://github.com/apptainer/apptainer/blob/main/INSTALL.md

**Comment by DrDaveD** [comment]
I've never seen that before.  Are there other files with the same problem?  The default is for the file to be empty and mode 644.  In fact the [install step in the Makefile](https://github.com/apptainer/apptainer/blob/release-1.3/mlocal/frags/build_runtime.mk#L85) explicitly sets the umask to 022 so it shouldn't even matter what the umask was when the install is run.  Might there have been some other process that modified the default capability.json and changed the permissions?

**Comment by doliv071** [comment]
Thanks for looking into this for me. I installed on a fresh system using the same procedure as before and the `capability.json` has the correct permissions. I had a previous install of singularity-ce on the other system, before I realized singularity had split, so maybe the incorrect permission is a leftover from that installation? 

Anyway, not a bug, just a me problem.
