### ISSUE TITLE
Refactor mksquashfs use with gocryptfs

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#2683]
Currently the build-with-gocryptfs implementation invokes `mksquashfs` twice without any parameters, ignoring the options used when SIF files are created without gocryptfs.  Refactor the use of mksquashfs to use common code in all 3 cases.  Also, the first squashfs layer should use compression by default and not the second layer, so the common function should have a boolean flag to say whether or not to compress.  Currently neither layer is compressed, so make sure that the compression does not cause a compatibility problem (I don't think it will, squashfs should mount with or without compression).

Related to #1022.

**Comment by JasonYangShadow** [comment]
> Currently the build-with-gocryptfs implementation invokes `mksquashfs` twice without any parameters, ignoring the options used when SIF files are created without gocryptfs. Refactor the use of mksquashfs to use common code in all 3 cases. Also, the first squashfs layer should use compression by default and not the second layer, so the common function should have a boolean flag to say whether or not to compress. Currently neither layer is compressed, so make sure that the compression does not cause a compatibility problem (I don't think it will, squashfs should mount with or without compression).
> 
> Related to #1022.

After re-reading the code, it looks like that gocryptfs will invoke `mksquashfs` with parameters
The steps are as follows:
1. https://github.com/JasonYangShadow/apptainer/blob/12008da192388e6cd512b32a5dac80369a6d4047/internal/pkg/build/assemblers/sif.go#L171C2-L171C8 (SIFAssembler flags are set)
2. When invoking gocryptfs encryption, flags are passed into Create function https://github.com/JasonYangShadow/apptainer/blob/12008da192388e6cd512b32a5dac80369a6d4047/internal/pkg/build/assemblers/sif.go#L203
3. When calling `mksquashfs` inside, the opts are appended https://github.com/JasonYangShadow/apptainer/blob/12008da192388e6cd512b32a5dac80369a6d4047/internal/pkg/image/packer/gocryptfs.go#L160

As far as I can see, if `GzipFlag` https://github.com/JasonYangShadow/apptainer/blob/main/internal/pkg/build/assemblers/sif.go#L34
is enabled after `ensureGzipComp`
https://github.com/JasonYangShadow/apptainer/blob/main/internal/pkg/build/build.go#L229
function gets the test passed, then gocryptfs will also use `Gzip` for the compression (For both invokes, the first and second invokes). It follows the same logic for privileged case
https://github.com/JasonYangShadow/apptainer/blob/main/internal/pkg/build/assemblers/sif.go#L216

**Comment by DrDaveD** [comment]
Oh you are right, I misread the code.  This is already using common code for option handling.

**Comment by DrDaveD** [comment]
I don't think it should be using gzip for both levels, but I'll figure out how to fix that in my PR for #1022.

**Comment by JasonYangShadow** [comment]
> I don't think it should be using gzip for both levels, but I'll figure out how to fix that in my PR for #1022.

yeah, should support multiple compression methods and maybe expose a -comp flag to the build command for end-users to choose available methods.
