### ISSUE TITLE
invalid memory address or nil pointer dereference during build

### ISSUE THREAD

**Issue by anderbubble** [apptainer/apptainer#337]
### Version of Apptainer:

What version of Apptainer are you using? Run:

```
$ apptainer --version
apptainer version 1.0.1-1.fc35
```

### Expected behavior

Built container.

### Actual behavior

```
apptainer build --fakeroot --update --sandbox spack hdfview.def
INFO:    Starting build...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xaaaad2d9ca50]

goroutine 1 [running]:
github.com/apptainer/apptainer/internal/pkg/build.(*Build).Full(0x400015e180, 0xaaaad32f7398, 0x40003cbf80, 0x0, 0x0)
	github.com/apptainer/apptainer/internal/pkg/build/build.go:403 +0x1880
github.com/apptainer/apptainer/cmd/internal/cli.runBuildLocal(0xaaaad32f7398, 0x40003cbf80, 0xaaaad3a04300, 0xffffe3b732df, 0x5, 0xffffe3b732e5, 0xb)
	github.com/apptainer/apptainer/cmd/internal/cli/build_linux.go:266 +0x155c
github.com/apptainer/apptainer/cmd/internal/cli.runBuild(0xaaaad3a04300, 0x40001cc180, 0x2, 0x4)
	github.com/apptainer/apptainer/cmd/internal/cli/build_linux.go:135 +0x408
github.com/spf13/cobra.(*Command).execute(0xaaaad3a04300, 0x400003c200, 0x4, 0x4, 0x0, 0x0)
	github.com/spf13/cobra@v1.3.0/command.go:860 +0xaa8
github.com/spf13/cobra.(*Command).ExecuteC(0xaaaad3a03e00, 0xaaaad3a04300, 0x0, 0x0)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x55c
github.com/spf13/cobra.(*Command).Execute(0xaaaad3a03e00, 0x0, 0x0)
	github.com/spf13/cobra@v1.3.0/command.go:902 +0x30
github.com/spf13/cobra.(*Command).ExecuteContext(0xaaaad3a03e00, 0xaaaad32f7398, 0x40003cbf80, 0x0, 0x0)
	github.com/spf13/cobra@v1.3.0/command.go:895 +0x60
github.com/apptainer/apptainer/cmd/internal/cli.ExecuteApptainer()
	github.com/apptainer/apptainer/cmd/internal/cli/apptainer.go:593 +0x238
main.main()
	github.com/apptainer/apptainer/cmd/apptainer/cli.go:22 +0x4c
```

### Steps to reproduce this behavior

Not certain. There's a lot going on in my environment. I'm on an M1 Macbook for one, running on fc35. I'm building a container sif bootstrapping from a localimage sandbox. And I'm building a series of dependent containers from GNU make. It doesn't happen for every container build, but it happens every time it gets to this point in my build process.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="35 (Workstation Edition)"
ID=fedora
VERSION_ID=35
VERSION_CODENAME=""
PLATFORM_ID="platform:f35"
PRETTY_NAME="Fedora Linux 35 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:35"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f35/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=35
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=35
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

```

### How did you install Apptainer

```
$ rpmbuild --rebuild https://github.com/apptainer/apptainer/releases/download/v1.0.1/apptainer-1.0.1-1.src.rpm
$ sudo dnf -y upgrade .rpmbuild/RPMS/aarch64/apptainer-1.0.1-1.fc35.aarch64.rpm
$ apptainer --version
apptainer version 1.0.1-1.fc35
```

Output above was generated from an installation where the `.spec` file was modified to include `./mconfig -P debug` as suggested at https://apptainer.slack.com/archives/C02NGSXR84U/p1647639109764939?thread_ts=1647493698.623429&cid=C02NGSXR84U, at which point

```
$ sudo dnf reinstall .rpmbuild/RPMS/aarch64/apptainer-*.rpm
```

**Comment by DrDaveD** [comment]
Please provide hdfview.def so we can try to reproduce this.

I wonder if the problem is specific to aarch64.  Are you able to try it on the same O.S. on x86?

**Comment by anderbubble** [comment]
hdfview.def is at https://github.com/anderbubble/spacktainer/blob/master/hdfview.def

The spack sandbox that it builds from is at https://github.com/anderbubble/spacktainer/blob/master/spack.def

But note that there are more dependencies, the flow of which can be seen in this Makefile: https://github.com/anderbubble/spacktainer/blob/master/Makefile

It's a bit more stateful than a typical apptainer container build, because I'm trying to make use of spack as a cache for prebuilt dependencies. I think it's probably clear what I'm trying to do--that Makefile is pretty small--but let me know if you have any questions.

Meanwhile, I'll try to replicate the issue on an x86 host.

**Comment by anderbubble** [comment]
fwiw, this has fallen so far off my plate that I don't think I'll be likely to return to this particular error again. I'll close this out, and plan to open something new if I happen to encounter a new error.
