### ISSUE TITLE
Singularity pull image question

### ISSUE THREAD

**Issue by ryao-mdanderson** [apptainer/apptainer#365]
Greetings the support team:

This is referring back to an issue https://github.com/apptainer/singularity/issues/5792. I realize that ticket has been closed. I reviewed the posts and https://github.com/apptainer/singularity/issues/5329, my issue is different from @DrDaveD had. My command is a regular singularity pull "singularity pull docker://godlovedc/lolcow", tried on both singularity versions 3.5.2 and 3.7.0. They stuck on "Getting image source signatures". There are no informative message after this line.

I have tried a few things. I thought the account used for pull a docker image is a service account, it does not have a docker authentication credential, there is no .docker inside $HOME. However, on the same system, I notice a regular user without .docker inside his $HOME, but can pull the image without a problem.

I thought the account $HOME resides an NFS file system, i.e. /home/account is a symbolic link to an NFS file system, it might matter. However, I notice other regular user account has $HOME in an NFS file system, he can pull the image without a problem.

I wonder if there is a similar ticket address this? Is there any other debugging approach to identify the problem?
Thank you very much.

**Comment by DrDaveD** [comment]
I am not aware of similar tickets.  You could use `singularity -d` to get debug info, that might help narrow it down, or perhaps strace to see where it is getting stuck.  You could see if it's something in your environment by running singularity under `env -i`.

**Comment by ryao-mdanderson** [comment]
@DrDaveD : I appreciate your reply and suggestions.
Yes, I did run with 'env -i' and '--debug' mode, it stuck on the same message:

$ singularity --debug pull docker://godlovedc/lolcow
DEBUG   [U=1944426582,P=2893]persistentPreRun()            Singularity version: 3.7.0
DEBUG   [U=1944426582,P=2893]persistentPreRun()            Parsing configuration file /risapps/rhel7/singularity/3.7.0/etc/singularity/singularity.conf
DEBUG   [U=1944426582,P=2893]handleConfDir()               /home/ris_hpc_apps/.singularity already exists. Not creating.
DEBUG   [U=1944426582,P=2893]getCacheParentDir()           environment variable SINGULARITY_CACHEDIR not set, using default image cache
DEBUG   [U=1944426582,P=2893]parseURI()                    Parsing docker://godlovedc/lolcow into reference
INFO    [U=1944426582,P=2893]pull()                        Converting OCI blobs to SIF format
DEBUG   [U=1944426582,P=2893]newBundle()                   Created temporary directory "/tmp/bundle-temp-645431617" for the bundle
DEBUG   [U=1944426582,P=2893]newBundle()                   Created directory "/tmp/build-temp-540523754/rootfs" for the bundle
DEBUG   [U=1944426582,P=2893]ensureGzipComp()              Ensuring gzip compression for mksquashfs
DEBUG   [U=1944426582,P=2893]ensureGzipComp()              Gzip compression by default ensured
INFO    [U=1944426582,P=2893]Full()                        Starting build...
DEBUG   [U=1944426582,P=2893]Get()                         Reference: godlovedc/lolcow
Getting image source signatures
^C 
 -- it stuck, I use control-C to terminate. then seeing the following 2 lines.
DEBUG   [U=1944426582,P=2893]func2()                       User requested cancellation with interrupt
DEBUG   [U=1944426582,P=2893]cleanUp()                     Cleaning up "/tmp/build-temp-540523754/rootfs" and "/tmp/bundle-temp-645431617" 

I am puzzled for further debug approaches. Thank you very much.

**Comment by DrDaveD** [comment]
I would try strace next.  It won't work with setuid singularity, but if the problem happens with the `--user` option too you could use strace -f

**Comment by ryao-mdanderson** [comment]
@DrDaveD : Thanks.
 The problem only happens for this particular account. May I know what is the appropriate command to include strace in 'singularity pull'?

**Comment by DrDaveD** [comment]
strace is a wrapper.  Just prefix your singularity command with `strace -f -o /tmp/outfile`

**Comment by ryao-mdanderson** [comment]
@DrDaveD Thank you.

 I used the 

 and let it run 3 minutes, terminated by Control-C.  /tmp/strace-out , seeing the following at the end of the file:
 23727 futex(0xc000232548, FUTEX_WAKE_PRIVATE, 1) = 1
23738 <... epoll_pwait resumed>[], 128, 119, NULL, 0) = 0
23739 <... futex resumed>)              = 0
23727 nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
23739 epoll_pwait(4,  <unfinished ...>
23738 epoll_pwait(4,  <unfinished ...>
23739 <... epoll_pwait resumed>[], 128, 0, NULL, 0) = 0
23738 <... epoll_pwait resumed>[], 128, 0, NULL, 3393686) = 0
23739 epoll_pwait(4,  <unfinished ...>
23738 futex(0xc00007ed48, FUTEX_WAKE_PRIVATE, 1) = 1
23727 <... nanosleep resumed>NULL)      = 0
23738 ioctl(2, TIOCGWINSZ <unfinished ...>
23729 <... futex resumed>)              = 0
23738 <... ioctl resumed>, {ws_row=32, ws_col=102, ws_xpixel=714, ws_ypixel=448}) = 0
23727 nanosleep({tv_sec=0, tv_nsec=20000},  <unfinished ...>
23738 futex(0xc000232d48, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>

I do not find 'error' or 'warning' in the files. there is a few connection time out message, I also read about sigalstack() nanosleep() etc functions, unfortunately, I don't have enough knowledge to capture the information that is useful. Do you have a pointer? Thanks!

**Comment by DrDaveD** [comment]
Please run it once more, with additional strace options `-tt -s1024` and attach the whole strace output file to the issue.  Github only allows certain file extensions, so give the file a name ending in `.txt`.

**Comment by ryao-mdanderson** [comment]
@DrDaveD : Again, thank you for your help.
I reran with the command: strace -f -o /tmp/strace-out.txt -tt -s1024 singularity --debug pull docker://godlovedc/lolcow
after running 2 minutes, I terminated the run by 
[strace-out.txt](https://github.com/apptainer/apptainer/files/8448339/strace-out.txt)
Control-C
Please see the attached strace-out.txt output.

**Comment by DrDaveD** [comment]
I'm sorry for the delay, I was away.

If you look in the strace output for the message `Getting image source signatures` very soon thereafter it tries to open /risapps/ris_hpc_apps/.local/share/containers/cache/blob-info-cache-v1.boltdb so it does indeed look very much like the boltdb corruption issue.  Did you try the workaround in the [documentation](https://apptainer.org/docs/user/main/build_env.html#boltdb-corruption-errors)?

**Comment by ryao-mdanderson** [comment]
@DrDaveD :  Thank you for your reply!
Yes, I did try the work around in the above documentation link before I posted this issue. I just removed /risapps/ris_hpc_apps/.local/share/containers/cache/blob-info-cache-v1.boltdb (it was size 0 dated March 27, 2022). Then, I use singularity 3.7.0,  pull again: singularity pull docker://godlovedc/lolcow 
It still stuck on "Getting image source signatures", notice blob-info-cache-v1.boltdb is size 0 with today's timestamp.

/risapps is NFS mounted on the server, I wonder if this matter?

**Comment by DrDaveD** [comment]
My home directory is also nfs-mounted and I don't have the problem.  Do you know what filesystem is underlying the NFS interface?

**Comment by ryao-mdanderson** [comment]
@DrDaveD 
The other user's home in a different NFS mounted file system, is okay to pull the image. I agree with your answer.
In /etc/fstab, /risapps is mounted as:
  10.68.0.243:/risapps2                    /risapps           nfs     vers=3,intr,bg     1 0
Do you mean to find what file system type for 10.68.0.243:/risapps2? such as, xfs, ext4? I can certainly ask for the people who maintain the NFS server.

**Comment by DrDaveD** [comment]
Yes, that's what I mean

**Comment by ryao-mdanderson** [comment]
@DrDaveD 
The top level '/ ' is xfs, I think /risapps2 is also type xfs.

**Comment by ryao-mdanderson** [comment]
@DrDaveD 
Another finding, for a regular account
under .local/share/containers/ , it has directory cache and storage, there are many overlay* directory under storage;
however,
there is no storage directory under /ris_hpc_apps/.local/share/containers/, I created a directory storage and pull the image again, storage has size 0, it still stuck at "Gettign image source signatures:.

**Comment by ryao-mdanderson** [comment]
Should a storage configure file exist?  I did not find storage.conf under ~/.local/share/containers/storage/ (actually, storage directory does not exist), I created storage and create a storage.conf, still does not work.

**Comment by ryao-mdanderson** [comment]
@DrDaveD One thing puzzled me, 
for a regular account which is able to pull the image, seeing image layer with large size
ls -l ~/.singularity/cache/oci-tmp/
.......
-rwx------ 1 ryao rists  526999552 Apr 18 11:13 7441b30e7fa79d4a371056a5d9d07b26600865bc41cfa4d65d16b6889175f8a5

however, every time this account  pull an image, only see zero size tmp_xxxxxx, how this file(s) created?
ls -lrt ~/.singularity/cache/oci-tmp
........
-rwx------ 1 ris_hpc_apps rists 0 Apr 20 22:26 tmp_258789386
-rwx------ 1 ris_hpc_apps rists 0 Apr 20 22:46 tmp_483940485

Thank you for your help.

**Comment by DrDaveD** [comment]
I ran the docker image and see the problem is that pip and torch are under /home/appuser/.local.  That's not only not in the PATH and PYTHONPATH when running under singularity, the directory is mode 700 so you can't even do a workaround of changing those values.  This is one of those cases where a docker image does not translate directly into a fully functional singularity/apptainer image.  The base image would need to have some change in order to make it work for both.

**Comment by DrDaveD** [comment]
There appears to be some kind of general issue with singularity creating files on this account.  I am suspecting a locking issue.  In your strace output, I see that sigularity creates the boltdb file and then calls flock on it and I don't see flock returning.  Perhaps that's the problem with the image layers as well.  NFS mounts have locking options.  Are they the same in the case where it works and where it doesn't work?

I don't know anything about storage.conf.  I don't have one in my home directory.

**Comment by ryao-mdanderson** [comment]
@DrDaveD 👍 

I agree, the storage.conf is not the key.

Thanks for this reminder, I tested with another user account in the same file system as ris_hpc_apps account, it appears that user account also stuck on the same step. So the problem seems to narrow down the file system, it might have some weird problem that we don't realize. I find out NFS mount can have the option 'nolock' (disable file locking), it is usually for older NFS server, our NFS server are not old. But it is worth to try by mounting with this option. 

Again, I really appreciate your time and efforts to guide me along.

**Comment by ryao-mdanderson** [comment]
@DrDaveD 👍 

I agree, the storage.conf is not the key.

Thanks for this reminder, I tested with another user account in the same file system as ris_hpc_apps account, it appears that user account also stuck on the same step. So the problem seems to narrow down the file system, it might have some weird problem that we don't realize. I find out NFS mount can have the option 'nolock' (disable file locking), it is usually for older NFS server, our NFS server are not old. But it is worth to try by mounting with this option. 

Again, I really appreciate your time and efforts to guide me along.

**Comment by ryao-mdanderson** [comment]
after adding 'nolock' option to NFS mount of the file system, account ris_hpc_apps is able to singularity pull an image. This seems to fix the problem. Thanks @DrDaveD !

**Comment by RobbieTheK** [comment]
We're hitting this issue on Bright Computing with RHEL 9 and I just tried adding `nolock` to` /etc/fstab` on a compute node but does the presence of `local_lock=all` override this?

`mountname:/cm/shared on /cm/shared type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,nolock,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=10.197.33.254,mountvers=3,mountport=4002,mountproto=udp,local_lock=all,addr=x.x.x.x,_netdev)`

Attached is the strace
[strace.txt](https://github.com/apptainer/apptainer/files/11033540/strace.txt)

**Comment by DrDaveD** [comment]
According to [`nfs(5)` ](https://linux.die.net/man/5/nfs):
```
NOTE: When used together, the 'local_lock' mount option will be overridden by 'nolock'/'lock' mount option. 
```

Please re-do the strace using the options I recommended [above](#issuecomment-1092259762) so we can see where the hang is.

**Comment by RobbieTheK** [comment]
> According to [`nfs(5)` ](https://linux.die.net/man/5/nfs):

I tried it no difference.

> strace -f -o /tmp/strace-out.txt -tt -s1024 singularity --debug pull docker://godlovedc/lolcow

[strace-out.txt](https://github.com/apptainer/apptainer/files/11034605/strace-out.txt)

**Comment by DrDaveD** [comment]
I'm not sure your problem is related to this closed issue, it may be more related to that other one you referenced.

Please open a new issue with the relevant info, including the debug output and this strace output.

**Comment by RobbieTheK** [comment]
OK I [created issue 1225](https://github.com/apptainer/apptainer/issues/1225)
