### ISSUE TITLE
missing VERSION file in release tarball?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [apptainer/apptainer#373]
Doing this fails:
```
$ wget https://github.com/apptainer/apptainer/archive/refs/tags/v1.0.1.tar.gz
$ tar xfz v1.0.1.tar.gz
$ cd apptainer-1.0.1/
$ ./mconfig
E: Not inside a git repository and no VERSION file found. Abort.
```
It's not entirely obvious how this is supposed to work, but it'd be preferable to not offer a tarball unless it can be built from.

**Comment by DrDaveD** [comment]
That tarball is always automatically generated by github and I don't know how to turn it off.  Instead use the link to [apptainer-1.0.1.tar.gz](https://github.com/apptainer/apptainer/releases/download/v1.0.1/apptainer-1.0.1.tar.gz) which is generated with a custom script.
