### ISSUE TITLE
side by side package install

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#39]
side by side package install

e2e tests need to be updated to verify correctness of this for various supported platforms

see example on PR #3 

```
dist/rpm/apptainer.spec.in
%attr(4755, root, root) %{_libexecdir}/singularity/bin/starter-suid
%{_bindir}/singularity
%attr(4755, root, root) %{_libexecdir}/apptainer/bin/starter-suid
%{_bindir}/apptainer
  
Contributor
@DrDaveD DrDaveD 14 hours ago
Need a %{_bindir}/singularity as well as %{_bindir}/apptainer.
```

===

noting: need some indications of administrator intent when "Singularity" is installed on top of Apptainer, or Apptainer is installed over Singularity

**Comment by PaulCharlton** [comment]
please add label for "v1.0.0" blocker

**Comment by DrDaveD** [comment]
Also use %{name} instead of apptainer throughout.
