### ISSUE TITLE
squashfuse SIF mount fails when working directory is under an autofs-controlled mountpoint

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#403]
In the current main branch, if the current working directory is under an autofs-mounted filesystem, a squashfuse mount of a SIF file fails with an error
```
FATAL:   container creation failed: mount /proc/self/fd/7->/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/7: squashfuse failed to mount /var/apptainer/mnt/session/rootfs in 2s
```
If I put a wrapper script around squashfuse I see an error
```
Can't open squashfs image: No such file or directory
```
and in fact /proc/self/fd/7 is not open.  It is related to the fact that when the current directory is under an autofs path, the keepAutofsMount() function keeps an open file descriptor, causing the file descriptor numbers to be changed.

**Comment by cclerget** [comment]
Looks like an issue within squashfuse driver, in this case the image before executing squashfuse point to `/proc/self/fd/7` but for squashfuse at the execution it become `/proc/self/fd/3` with extra files, so you need to reflect the path for params.Source to become `/proc/self/fd/3` :

```
	d.cmd = exec.Command(d.cmdpath, "-f", "-o", optsStr, params.Source, params.Target)
	sylog.Debugf("Executing %v", d.cmd.String())
	var stderr bytes.Buffer
	d.cmd.Stderr = &stderr
	if path.Dir(params.Source) == "/proc/self/fd" {
		d.cmd.ExtraFiles = make([]*os.File, 1)
		targetFd, _ := strconv.Atoi(path.Base(params.Source))
		d.cmd.ExtraFiles[0] = os.NewFile(uintptr(targetFd), params.Source)
	}
	d.cmd.SysProcAttr = &syscall.SysProcAttr{
		AmbientCaps: []uintptr{
			uintptr(capabilities.Map["CAP_SYS_ADMIN"].Value),
		},
	}
```
