### ISSUE TITLE
Cannot run apptainer with non-readable home directory

### ISSUE THREAD

**Issue by james-simone** [apptainer/apptainer#409]
### Version of Apptainer:

What version of Apptainer are you using? Run:

```
$ apptainer --version
apptainer version 1.0.1+228-gdacd7d62e

```

### Expected behavior

$ /srv/software/singularity-3.8.5/bin/singularity --version
singularity version 3.8.5

$ singularity run --home=/tmp lolcow_latest.sif
INFO:    Converting SIF file to temporary sandbox...
Something clever

### Observed behavior

$ apptainer run --home=/tmp lolcow_latest.sif
FATAL:   Failed to retrieve information for /nashome/s/sXXXXXX/.apptainer: stat /nashome/s/sXXXXXX/.apptainer: permission denied

Apptainer attempts to access the user's home directory which is not accessible from the server running the container.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Scientific Linux"
VERSION="7.9 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"

```

### How did you install Apptainer

Built from source, git tag: dacd7d62e

**Comment by ikaneshiro** [comment]
Hi @james-simone, I've opened https://github.com/apptainer/apptainer/pull/410 to fix this issue. Could you test out if you have some time?

**Comment by james-simone** [comment]
Your patch fixes the fatal error.

```
$ cd /work1/myproject
$ singularity run --home=/work1/myproject alpine.sif
WARNING: Failed to retrieve information for /nashome/s/sXXXX/.apptainer: stat /nashome/s/sXXXX/.apptainer: permission denied
< You look tired. >
$
```

Q) Is there a way to have Apptainer look elsewhere rather than in ~/.apptainer ? An environment variable would be nice.

Also, I suggest changing the log message from "Failed to" to "Unable to" otherwise users will report Apptainer has a Failure.

**Comment by DrDaveD** [comment]
I made the separate issue in #471.
