### ISSUE TITLE
Image compatilibty break follow up for PR #3

### ISSUE THREAD

**Issue by cclerget** [apptainer/apptainer#41]
Comments captured from #3 for the follow up regarding image build:

![Screenshot 2021-12-07 at 15-16-05 Apptainer rename by PaulCharlton · Pull Request #3 · apptainer apptainer](https://user-images.githubusercontent.com/3274134/145045449-ae28072c-3754-4087-bac1-aa3326fd4839.png)
![Screenshot 2021-12-07 at 15-15-32 Apptainer rename by PaulCharlton · Pull Request #3 · apptainer apptainer](https://user-images.githubusercontent.com/3274134/145045456-649e574b-edc1-4f19-be65-5f6d9dc22b8b.png)

**Comment by PaulCharlton** [comment]
this should be merged with #40
