### ISSUE TITLE
Feature request: progress indicator during `apptainer push`

### ISSUE THREAD

**Issue by anderbubble** [apptainer/apptainer#437]
Apptainer should support an optional progress indicator during push, with percentage complete as well as bytes transferred / total bytes to transfer.

**Comment by JasonYangShadow** [comment]
@anderbubble 
It looks like it has one progress bar during push?
![image](https://user-images.githubusercontent.com/2051711/179655220-ec8cbc13-051a-4b55-ba2f-2c87edf469e8.png)

**Comment by anderbubble** [comment]
@JasonYangShadow that sure does look like what I want; maybe it only works for `library://` push, and not `oras://` push?

**Comment by JasonYangShadow** [comment]
@anderbubble yes, oras protocol does not implement the progress bar function for push, let me handle it. I will update the latest progress here. 
Thanks so much for the feature request!

**Comment by panda1100** [comment]
@JasonYangShadow +1 for this feature!
https://github.com/apptainer/apptainer/blob/main/internal/app/apptainer/push.go
https://github.com/apptainer/apptainer/blob/main/internal/pkg/client/oras/oras.go

**Comment by olesenm** [comment]
Thanks @panda1100 for picking up on this.

**Comment by JasonYangShadow** [comment]
@DrDaveD 
Not sure if we can catch up with the stable 1.2.0 release, just adding a milestone 1.2.0 here. 
I will prioritize this ticket.

**Comment by DrDaveD** [comment]
Unless we need another release candidate for another reason, I would rather put this in 1.2.1.

**Comment by JasonYangShadow** [comment]
> Unless we need another release candidate for another reason, I would rather put this in 1.2.1.

Good to me. Thanks!

**Comment by panda1100** [comment]
I'm going to test this PR #1587, Thank you!

**Comment by panda1100** [comment]
@JasonYangShadow oras pull also doesn't have progress bar.
I would like to add that to this RFE.

**Comment by panda1100** [comment]
I confirmed oras push now has progress bar with your PR!!
Super cool!
