### ISSUE TITLE
evaluate changes to `examples/legacy` and perhaps revert to original contents after PR #3

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#44]
evaluate changes to `examples/legacy` and perhaps revert to original contents after PR #3

**Comment by ikaneshiro** [comment]
After looking at the contents of this directory, I suggest we remove it. The examples contained within it generally exist within the parent directory and several of the examples will not work with the Apptainer build system or the 3.x Singularity build system (e.g. https://github.com/apptainer/apptainer/blob/main/examples/legacy/2.1/arch.def).

Thoughts?

**Comment by cclerget** [comment]
:+1: to remove it, legacy artifacts kept during transition from v2 to v3 I think
