### ISSUE TITLE
signature by an unknown key should not break ECL verification whitelist or whitestrict

### ISSUE THREAD

**Issue by anderbubble** [apptainer/apptainer#463]
### Version of Apptainer:

What version of Apptainer are you using? Run:

```
$ apptainer --version
apptainer version 1.0.2-1
```

### Expected behavior

Given an apptainer with two signatures:

```
[janderson@rocky2 ~]$ apptainer verify hello-world.sif
Verifying image: hello-world.sif
[LOCAL]   Signing entity: Jonathon Anderson (demo) <janderson@ciq.co>
[LOCAL]   Fingerprint: 3E210337B54FD9C73D3E3D02ED3E0CC6080CB924
Objects verified:
ID  |GROUP   |LINK    |TYPE
------------------------------------------------
1   |1       |NONE    |Def.FILE
2   |1       |NONE    |JSON.Generic
3   |1       |NONE    |JSON.Generic
4   |1       |NONE    |FS
[GLOBAL]  Signing entity: Jonathon Anderson <janderson@civilfritz.net>
[GLOBAL]  Fingerprint: 38B839FA8F263C6BBAE9F1ECEC2553E72D06512D
Objects verified:
ID  |GROUP   |LINK    |TYPE
------------------------------------------------
1   |1       |NONE    |Def.FILE
2   |1       |NONE    |JSON.Generic
3   |1       |NONE    |JSON.Generic
4   |1       |NONE    |FS
Container verified: hello-world.sif
```

One of which is whitelisted

```
[[execgroup]]
  tagname = "group1"
  mode = "whitelist"
  dirpath = "/home/janderson"
  keyfp = ["38B839FA8F263C6BBAE9F1ECEC2553E72D06512D"]
```

Execution should succeed, since the container has a whitelisted signature.

### Actual behavior

```
[janderson@rocky2 ~]$ apptainer run hello-world.sif 
FATAL:   while checking container image with ECL: image signature not valid: integrity: signature object 5 not valid: openpgp: signature made by unknown entity
```

Only one of the signatures is in the global keyring, so it fails. But this should be ignored, since there is sufficient verification to allow the container to run.

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.6 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.6"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.6 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

```

### How did you install Apptainer

```
dnf install https://github.com/apptainer/apptainer/releases/download/v1.0.2/apptainer-1.0.2-1.x86_64.rpm
```

**Comment by DrDaveD** [comment]
@anderbubble Is this also a change to sif?  If so I'll wait to cut a release there until you have done this one.

**Comment by anderbubble** [comment]
@DrDaveD I believe it will be. I don't currently see any mechanism in sif to verify individual signatures: it's all or nothing. So I think I need to add a new function to allow individual signatures to be verified, and then apptainer would use that to verify only the signatures that are used in the list.

But I'm certainly open to correction / direction / advice.

**Comment by anderbubble** [comment]
@DrDaveD I'm sorry for holding this up. I haven't been able to give it the attention it's needed, particularly being still so new to golang.

The error starts here:

- [loadImages](https://github.com/apptainer/apptainer/blob/d21764e79a89b15b87ccc8c6c335d70b42a8a59a/internal/pkg/runtime/engine/apptainer/prepare_linux.go#L1223-L1224)
- -> [ShouldRunFp](https://github.com/apptainer/apptainer/blob/d21764e79a89b15b87ccc8c6c335d70b42a8a59a/internal/pkg/syecl/syecl.go#L276-L283)
- -> [ShouldRun](https://github.com/apptainer/apptainer/blob/d21764e79a89b15b87ccc8c6c335d70b42a8a59a/internal/pkg/syecl/syecl.go#L242)
- -> [Verify](https://github.com/apptainer/sif/blob/a6b2bbb2b6ee0e0ab569cc296301ca952cb48812/pkg/integrity/verify.go#L712)
- -> [verifyWithKeyRing](https://github.com/apptainer/sif/blob/a6b2bbb2b6ee0e0ab569cc296301ca952cb48812/pkg/integrity/verify.go#L180)

verifyWithKeyRing only and always attempts to verify all signatures; but the goal here is to only care about verification of signatures that are involved in an applicable ECL.

Now that [verifyWithKeyRing returns a multierror](https://github.com/apptainer/sif/blob/a6b2bbb2b6ee0e0ab569cc296301ca952cb48812/pkg/integrity/verify.go#L179-L195), it might be feasible to verify all signatures, but then just check the signatures in the list against the errors in the multierror.

[verifySignature returns other errors besides SignatureNotValidError](https://github.com/apptainer/sif/blob/a6b2bbb2b6ee0e0ab569cc296301ca952cb48812/pkg/integrity/verify.go#L111-L117), so I'll want to be careful to only handle SignatureNotValidErrors, and pass on anything else as a true error from ShouldRun.

I'll continue digging into this. I feel like I have a clearer picture of how to go about this right now than before, but @ikaneshiro and @JasonYangShadow I'd be very interested in any feedback you might have.
