### ISSUE TITLE
Update to using gopkg.in/yaml.v3

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#473]
There's a new major version of gopkg.in/yaml, version v3.  I tried to upgrade to it, but the `UnmarshalStrict()` API function has been removed.  According to the [release announcement](https://ubuntu.com/blog/api-v3-of-the-yaml-package-for-go-is-available) it is supposed to be replaced by the use of the `Decoder.KnownFields` functionality but I haven't located a good example of how to use it.  Instead I found issues (such as go-yaml/yaml#602) and an open PR (go-yaml/yaml#691) that discuss various things about it that are insufficient and they have been unresolved for a long time.

**Comment by Xyaren** [comment]
Try this:

```go
file, err := os.Open(path)
if err != nil {
	log.Fatalf("Error opening file %v", err)
}
var r MyStruct
decoder := yaml.NewDecoder(file)
decoder.KnownFields(true)
err = decoder.Decode(&r)
if err != nil {
	log.Fatalf("Error reading file %v", err)
}
```

**Comment by DrDaveD** [comment]
Thank you.  I see that looks very similar to sylabs/singularity/pull/1398 which I expect we will get up to after the 1.2 release.

**Comment by DrDaveD** [comment]
Completed in #1444.
