### ISSUE TITLE
Support unprivileged encrypted SIF files

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#484]
One of the last remaining significant features that can't be run without suid and with unprivileged user namespaces is encrypted SIF files.  That could probably be supported with something like [gocryptfs](https://nuetzlich.net/gocryptfs/comparison/).

**Comment by blazejpawlak** [comment]
That would be a killer feature for many of us, since we cannot allow for root access in environments. Any chance you want to include this one in your roadmap for 2023?

**Comment by DrDaveD** [comment]
It is being actively developed now for 1.2.0

**Comment by DrDaveD** [comment]
Btw we weren't able to figure out how to make an unprivileged encryption/decryption compatible with the way that suid apptainer does it now.  So people will need to encrypt with version 1.2.0 or later.  Not ideal, but the previous method relied on a kernel feature that as far as we know cannot be duplicated unprivileged.

**Comment by blazejpawlak** [comment]
Understood, this will be a breaking change, and I guess it's a rational decision to facilitate even more use cases for the user base out there.

What's the approximate ETA of 1.2.0?

**Comment by DrDaveD** [comment]
> What's the approximate ETA of 1.2.0?

It mostly depends on when this feature gets finalized, hopefully within the next couple of months.
