### ISSUE TITLE
Make an e2e test for nested apptainer commands

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#524]
Make an e2e test for nested gpu flags in order to complete #523.

**Comment by JasonYangShadow** [comment]
looks like GPU-related tests are skipped in the GitHub ci build. also, I do not have a local environment for running the Nvidia GPU test.

**Comment by DrDaveD** [comment]
That's true, it is hard to test from ci.  I do have access to a local Nvidia machine, so I could test the e2e test interactively.

**Comment by DrDaveD** [comment]
In fact there is no testing of nested Apptainer at all, so I think there should be additional tests doing with other things as wel.  I have gotten started on it, creating a script to do nested Apptainer, but I think I probably won't get this done before 1.1.0 so I changed the milestone to 1.1.1.
