### ISSUE TITLE
Apptainer home directory

### ISSUE THREAD

**Issue by manmeet3591** [apptainer/apptainer#546]
I am trying to pull an image from docker hub using apptainer pull and its not working because /tmp is full. Is there a way to change the home directory ? Thank you

$ apptainer pull docker://manmeet3591/ubuntu_anaconda:latest
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 5d3b2c2d21bb done  
Copying blob 5d3b2c2d21bb done  
Copying blob 3fc2062ea667 done  
Copying blob 75adf526d75b done  
Copying blob 6b6ea4c7a6be done  
Copying blob cadbcfe79d1c done  

Copying config 3578474e60 done  
Writing manifest to image destination
Storing signatures
FATAL:   While making image from oci registry: error fetching image to cache: while building SIF from layers: conveyor failed to get: writing blob: write /tmp/bundle-temp-[2094984273](callto:2094984273)/oci-put-blob1495208066: no space left on device

**Comment by zzxtty** [comment]
Try setting APPTAINER_CACHEDIR ( which is the new SINGULARITY_CACHEDIR variable ).

**Comment by DrDaveD** [comment]
Yes, APPTAINER_CACHEDIR is a good idea, and possibly also APPTAINER_TMPDIR.  There's not currently a way to set the home directory, although in the main branch (for upcoming version 1.1.0) the home directory for those types of files is determined by the HOME environment variable.
