### ISSUE TITLE
Fun with symbolic links

### ISSUE THREAD

**Issue by zzxtty** [apptainer/apptainer#547]
### Version of Apptainer

apptainer version 1.0.3-1

### Expected behavior

The underlying system has a set of directories under /nan/ceph/network/system/ - these directories contain software for specific operating systems. For instance, there is an el7 and an el8 directory. Each physical server will have a symbolic link appropriate for the OS:
 
`ln -s /nan/ceph/network/system/el8 /software/system`

When creating the apptainer image part of the script will create the /software directory, and add an appropriate system link for the container OS:

```
%post
  mkdir /nan
  mkdir /software
  ln -s /nan/ceph/network/local/generic /software/local
  ln -s /nan/ceph/network/system/el7 /software/system
```
When running the container on an EL8 server you would expect to see the EL7 directory inside the container. This is what happens in most cases, however....

### Actual behavior

When starting the container from the /software/system directory the incorrect directory is available in the container:

```
% cd /software/system
% pwd
/nan/ceph/network/system/el8
% apptainer shell ./antspy/0.3.3/antspy2
Apptainer> ls /software/system/
```

This returns the contents of the el8 directory, not el7, which is where the link points:

```
Apptainer> ls -l /software/system     
lrwxrwxrwx. 1 root root 28 Jul 18 11:09 /software/system -> /nan/ceph/network/system/el7
Apptainer> 
```

Now the really odd bit:

```
Apptainer> ls -ld /nan/ceph/network/system/el[78]
drwxr-xr-x. 8 root root 57595382006 Jul 15 07:34 /nan/ceph/network/system/el7
drwxr-xr-x. 8 root root 57595382006 Jul 15 07:34 /nan/ceph/network/system/el8
Apptainer> 
```

The above directories are real directories, but should be different. On the host system:

```
% ls -ld /nan/ceph/network/system/el[78]
drwxr-xr-x. 104 root root 835233940538 Jul  5 12:35 /nan/ceph/network/system/el7
drwxr-xr-x.   8 root root  57595382006 Jul 15 07:34 /nan/ceph/network/system/el8
```

If I restart the container from another directory I see the correct behaviour:
```
% cd /
% apptainer shell /software/system//antspy/0.3.3/antspy2
Apptainer> ls -ld /nan/ceph/network/system/el[78]
drwxr-xr-x. 104 root root 835233940538 Jul  5 12:35 /nan/ceph/network/system/el7
drwxr-xr-x.   8 root root  57595382006 Jul 15 07:34 /nan/ceph/network/system/el8
Apptainer>
```

Bind paths set in the apptainer.conf file:
```
bind path = /etc/localtime
bind path = /etc/hosts
bind path = /data
bind path = /nan
```

### What OS/distro are you running

```
% cat /etc/redhat-release 
AlmaLinux release 8.6 (Sky Tiger)
%
```

/nan/ceph is a ceph filesystem, version 14.2.22.

### How did you install Apptainer

RPM:  apptainer-1.0.3-1.x86_64.rpm

**Comment by DrDaveD** [comment]
I think that's just a side effect of the fact that apptainer bind mounts the current working directory into the container as a convenience for the user.  It's not really a problem for you, right?  Just something surprising?

**Comment by zzxtty** [comment]
I guess it is not really a problem as the work around is to start the container from another location. However, I would describe it as unexpected behaviour, especially for end users. Starting the container from /bin can render commands like "ls" unusable. I had assumed that only your home directory and specific binds were honoured, perhaps this was the case for older versions.

**Comment by DrDaveD** [comment]
Nothing looks likely to have changed in 3.5.0, but 3.5.1 had
```
Corrects the behavior of underlay with non-empty / symlinked CWD and
absolute symlink binds targets.
```
and 3.5.2 had
```
Fixes container execution errors when CWD is a symlink.
```
@cclerget Please take a look.
