### ISSUE TITLE
Issue with loop device creation when using /dev/loop-control

### ISSUE THREAD

**Issue by cclerget** [apptainer/apptainer#548]
With changes introduced by https://github.com/apptainer/apptainer/pull/323, apptainer is requesting to kernel to allocate/create a loop device without the need to call mknod if the loop device is missing in `/dev`.

A side effect was noticed when apptainer is running inside a docker container, apptainer detect the presence of `/dev/loop-control` but the loop device is not created inside the container `/dev`, it is created on host `/dev` as docker is not binding `/dev` but recreate it.

**Comment by sudosays** [comment]
I have been able to replicate this bug with the following
Apptainer version: 1.0.1

```
apptainer exec docker://alpine echo "hello"
```
Produces:
```
FATAL:   container creation failed: mount /proc/self/fd/3->/var/lib/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: failed to attach loop device: could not open /dev/loop0: no such device or address
```
Same with a different docker container `docker://ubuntu:latest`
