### ISSUE TITLE
Overlay SIF similar to --volumes-from in Docker

### ISSUE THREAD

**Issue by JesseFarebro** [apptainer/apptainer#562]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
1.0.2-1.el7
```

### Expected behavior

I'm wondering if it's possible to overlay from a SIF image. Specifically, I'm publishing a docker "data image", i.e.,

```docker
FROM scratch
COPY . /overlay
```
and I publish this to a Docker registry. I then want to `singularity pull` this image and then overlay it on another container. Doing this you run into a lot of weird edge cases, e.g.,

```
apptainer exec --compat --overlay overlay.sif:ro base.sif ls /overlay
```
doesn't fail, it just doesn't seem to do anything? I was really hoping the desired behavior would overlay `/overlay` in `base.sif`. You can manage to get things to work via:

```
apptainer exec --compat --bind overlay.sif:/overlay:image-src=overlay/,id=4 base.sif ls /overlay
```
but this isn't ideal as for my use case I don't necessarily know what the directory I need to overlay is (it's also not ideal to have to handcode the partition id, I wish the partition was created as an overlay because the base image is scratch).

Furthermore, the following doesn't fail and does nothing (although this seems to be as expected?)
```
apptainer exec --compat --bind overlay.sif:/:image-src=/,id=4 ls /overlay
```

### Actual behavior

What actually happened? Why was it incorrect?

Nothing happens, not even an error when doing `--overlay overlay.sif:ro`.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

1. Build a data docker image as above.
2. Build a SIF `overlay.sif` from the docker archive.
3. Run `apptainer exec --compat --bind overlay.sif:ro docker://debian:bullseye-slim ls /overlay`.

### What OS/distro are you running

CentOS 7.

### How did you install Apptainer

N/A, installed on a managed cluster.

### Feature Request

1. Would it be possible to support Docker "data images", if the base image is `scratch` perhaps the layer could be treated as an overlay partition type.
2. Support for overlaying a sif container which only contains an overlay partition type.

**Comment by DrDaveD** [comment]
Keep in mind that a SIF file is not directly mounted, it is a set of partitions.  I believe that if the squashfs partition is marked overlay it might work.  You can probably do that with an `apptainer sif` command.

An overlay also has to be in the format expected by overlayfs, that is, with an "upper" and "work" directory.  Additional files go in the "upper" directory.  The "work" directory I believe is mostly for keeping track of removals and it is in a format that's best left only to be created by overlayfs.  I suggest creating an ext3 overlay first as described in the [documentation](https://apptainer.org/docs/user/main/persistent_overlays.html), then run apptainer as root with --overlay to create the additions you want, then you can directly mount the ext3 to see what its contents are.

**Comment by DrDaveD** [comment]
I don't see an option to modify the flags, so you'd probably need to dump the partition (to a file, redirect stdout), then delete the partition, and add it back with the overlay parttype.

**Comment by JesseFarebro** [comment]
I'll go ahead and close this as it's probably out-of-scope. I since learnt about ORAS and OCI Artifacts and once support has matured for these specs it seems this will be a good solution for what I want to achieve. Until then I've just decided to manually pull the single layer and create a squashfs overlay.
