### ISSUE TITLE
Inconsistent key command private / secret flags

### ISSUE THREAD

**Issue by dtrudg** [apptainer/apptainer#567]
### Version of Apptainer

main

### Expected behavior

Flags for key operations are consistent across key commands.

### Actual behavior

The `apptainer key remove` command now accepts `--private / -r` `--public / -p` `--both / -b` to control which keys are removed, from #555 

The `apptainer key list` and `apptainer key export` commands work on public keys by default, and have a `--secret / -s` flag to export secret (private) keys.

Ideally, key commands would have consistent flags / operation for public / private key selection.

### How did you install Apptainer

GH main branch source.

**Comment by DrDaveD** [comment]
Thanks for the report, DT.  Assigning to @JasonYangShadow

**Comment by DrDaveD** [comment]
So, probably we should just change the `--private / -r` to `--secret / -s` for consistency.

**Comment by JasonYangShadow** [comment]
> So, probably we should just change the `--private / -r` to `--secret / -s` for consistency.

Yes, reflected the change here
https://github.com/apptainer/apptainer/pull/572

**Comment by DrDaveD** [comment]
Fixed by #572
