### ISSUE TITLE
add "corrupted container" to registry and change e2e test for corrupted container to use it.

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#58]
add "corrupted container" to registry and change e2e test for corrupted container to use it.

re: library://sylabs/tests/verify_corrupted:1.0.1 -> oras://ghcr.io/apptainer/verify_corrupted:1.0.1

_Originally posted by @PaulCharlton in https://github.com/apptainer/apptainer/issues/54#issuecomment-991921867_

**Comment by PaulCharlton** [comment]
@ikaneshiro is this one you can do ?

**Comment by ikaneshiro** [comment]
`oras://ghcr.io/apptainer/verify_corrupted:1.0.2` has been created

**Comment by PaulCharlton** [comment]
@ikaneshiro confirmed this works -- this issue may be closed
