### ISSUE TITLE
Source release fails to configure

### ISSUE THREAD

**Issue by mboisson** [apptainer/apptainer#587]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

Version 1.1.0 rc1

### Expected behavior

From the download of the source tarball, i.e. 
https://github.com/apptainer/apptainer/archive/refs/tags/v1.1.0-rc.1.tar.gz
the build should work. It should not require us to clone the git repository.

### Actual behavior

$ ./mconfig
E: Not inside a git repository and no VERSION file found. Abort.

### Steps to reproduce this behavior

Download the source tarball. Run ./mconfig.

### What OS/distro are you running

Not relevant

### How did you install Apptainer

Trying to

**Comment by mboisson** [comment]
A colleague pointed out that this tarball works: 
https://github.com/apptainer/apptainer/releases/download/v1.1.0-rc.1/apptainer-1.1.0-rc.1.tar.gz 

I guess the auto-generated Github tarballs are broken.

**Comment by DrDaveD** [comment]
Yes it's true, and there's no way for to remove them.  The INSTALL.md instructions show getting the tarball that works.
