### ISSUE TITLE
squashfuse not mentioned in documentation

### ISSUE THREAD

**Issue by HennerM** [apptainer/apptainer#592]
### Version of Apptainer
```
apptainer version 1.1.0-rc.1
```

### Expected behavior

I expected `apptainer exec something.sif /bin/bash` to have the same behaviour as `singularity exec something.sif /bin/bash`

### Actual behavior

Without manually installing squasfuse I get the following:
```
INFO:    squashfuse not found, will not be able to mount SIF
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    Converting SIF file to temporary sandbox...
```
Fixed by `sudo apt-get install squashfuse`

I didn't find anything on the documentation that squashfuse is required, or why it is required. It would be good to have that clarified. 

### Steps to reproduce this behavior

1. uninstall squasfuse
2. `exec` a SIF that was built with a previous Singularity version

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04.6 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.6 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

### How did you install Apptainer

Installed from source from the GitHub tar.gz archive, using instructions in the Getting Started guide

**Comment by DrDaveD** [comment]
Yes, as announced the docs are not yet up to date.  Please follow instead the instructions in [INSTALL.md](https://github.com/apptainer/apptainer/blob/main/INSTALL.md).  In fact I'm in the process of updating the docs to just point to INSTALL.md instead of duplicating the instructions.
