### ISSUE TITLE
Running a graphical Nvidia GPU accelerated program in a container gives GLIBC version mismatch error

### ISSUE THREAD

**Issue by amit112amit** [apptainer/apptainer#598]
### Version of Apptainer

`apptainer version 1.0.3-2.fc36`

### Expected behavior
1. A GUI window (`glxgears`) should pop up with host NVIDIA GPU-accelearted graphics.
2. `nvidia-smi` command on the host should show `glxgears` as a process utilizing the GPU.

### Actual behavior
I get the following errors
```bash
/usr/bin/glxgears: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLX.so.0)
/usr/bin/glxgears: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLdispatch.so.0)
```

### Steps to reproduce this behavior
1. Create a Container Definition file
```bash
cat << EOF >> glx_test.def
Bootstrap: docker
From: centos:centos7

%post
    yum -y install xauth xeyes glx-utils mesa-dri-drivers

%environment
    export LIBGL_DEBUG=verbose
    export LC_ALL=C
EOF
```
2. Build a container from the definition file
`apptainer build --fakeroot glxgears_test.sif glx_test.def`

3. Run `glxgears` in the container with GPU support
`apptainer exec --nv glxgears_test.sif glxgears`

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
*Nvidia drivers, CUDA, and Nvidia container toolkit are installed on the host*
The output of `nvidia-smi` on the host is
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.57       Driver Version: 515.57       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   34C    P8    N/A /  N/A |      4MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1858      G   /usr/libexec/Xorg                   2MiB |
+-----------------------------------------------------------------------------+
```
The output of `nvidia-container-cli list` on the host is
```
/dev/nvidiactl
/dev/nvidia-uvm
/dev/nvidia-uvm-tools
/dev/nvidia-modeset
/dev/nvidia0
/usr/bin/nvidia-smi
/usr/bin/nvidia-debugdump
/usr/bin/nvidia-persistenced
/usr/bin/nvidia-cuda-mps-control
/usr/bin/nvidia-cuda-mps-server
/usr/lib64/libnvidia-ml.so.515.57
/usr/lib64/libnvidia-cfg.so.515.57
/usr/lib64/libcuda.so.515.57
/usr/lib64/libnvidia-opencl.so.515.57
/usr/lib64/libnvidia-ptxjitcompiler.so.515.57
/usr/lib64/libnvidia-allocator.so.515.57
/usr/lib64/libnvidia-compiler.so.515.57
/usr/lib64/libnvidia-ngx.so.515.57
/usr/lib64/libnvidia-encode.so.515.57
/usr/lib64/libnvidia-opticalflow.so.515.57
/usr/lib64/libnvcuvid.so.515.57
/usr/lib64/libnvidia-eglcore.so.515.57
/usr/lib64/libnvidia-glcore.so.515.57
/usr/lib64/libnvidia-tls.so.515.57
/usr/lib64/libnvidia-glsi.so.515.57
/usr/lib64/libnvidia-fbc.so.515.57
/usr/lib64/libnvidia-rtcore.so.515.57
/usr/lib64/libnvoptix.so.515.57
/usr/lib64/libGLX_nvidia.so.515.57
/usr/lib64/libEGL_nvidia.so.515.57
/usr/lib64/libGLESv2_nvidia.so.515.57
/usr/lib64/libGLESv1_CM_nvidia.so.515.57
/usr/lib64/libnvidia-glvkspirv.so.515.57
/lib/firmware/nvidia/515.57/gsp.bin
```

### How did you install Apptainer
I installed `apptainer` from the official repository using the following command
`sudo dnf install -y apptainer`

**Comment by DrDaveD** [comment]
I believe this is a known issue with the way --nv works by binding from the host, when the host glibc vintage is significantly different from the one in the container.  You haven't tried it with an older singularity version, have you?  I expect the same issue.

Just a few days ago somebody reported on Slack the same issue but they had a different message with the `--nvccli` option, which uses nvidia-container-cli directly.  In apptainer that is only supported without the setuid-flow.  That non-setuid support has improved with the apptainer 1.1.0 release candidate, and improved even further in #594 which was merged last week, after the first release candidate.  So if you'd be willing to compile from the current main branch to test out `--nvccli` that would be great.  

The only other workaround would probably be to use host and container operating systems that are more closely matched.

**Comment by amit112amit** [comment]
Thank you for the reply @DrDaveD. I compiled the main branch from source to test out the `--nvccli` option as you suggested. I got the following errors
```bash
[amit@fedora Software]$ apptainer exec --nvccli glxgears_old.sif glxgears
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
INFO:    Consider using either `--fakeroot` or sandbox built with `--fix-perms`
FATAL:   container creation failed: /usr/bin not writable in the container
[amit@fedora Software]$ apptainer exec --fakeroot --nvccli glxgears_old.sif glxgears
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
FATAL:   container creation failed: nvidia-container-cli failed with exit status 1: nvidia-container-cli: mount error: file creation failed: /usr/local/var/apptainer/mnt/session/final/usr/bin/nvidia-smi: no data available
[amit@fedora Software]$ sudo apptainer exec --fakeroot --nvccli glxgears_old.sif glxgears
[sudo] password for amit: 
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
FATAL:   could not use fakeroot: no mapping entry found in /etc/subuid for root
[amit@fedora Software]$ sudo apptainer exec --nvccli glxgears_old.sif glxgears
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
No protocol specified
Error: couldn't open display :0
[amit@fedora Software]$ 
```
I am sorry, I am not able to understand the last output or how to fix it.

Actually, some time ago while I was still using Fedora 36, I got the same GLIBC error. But it was solved after I installed `nvidia-container-toolkit`. But after a few updates, I started getting the error again. Unfortunately, I didn't keep track of what all packages got updated. I tried downgrading the Nvidia drivers, and the singularity package but I am still getting the error. I am filing a bug report because it was working at one point.

**Comment by DrDaveD** [comment]
I don't know what to tell you about nvidia-smi returning no data with --fakeroot.  I assume nvidia-smi works outside of apptainer.  I don't have access to a Fedora system with a GPU to try to reproduce.  I have access to a centos7 system with an nvidia GPU but don't have root access there.

It might be worth trying to see if you get different results if you use a sandbox built with `--fix-perms` as the other suggestion said.

It's possible the last sudo command would work if you could get the environment permissions for writing to X11 passed through sudo.  Try first to get an ordinary X11 program to work under sudo.

**Comment by amit112amit** [comment]
Yes, `nvidia-smi` is working outside `apptainer`. I have pasted a sample output in the original post.

I created a sandbox with `--fix-perms` using the following command `apptainer build --sandbox --fix-perms ./sand_glxgears/ glxgears_old.sif`.  I tried to run `glxgears` as follows. The `glxgears` window opened up. The output clearly says that the `i915` driver is being used. I also confirmed using `nvidia-smi -l 2` on the host that the NVIDIA GPU was not being used.
```bash
[amit@fedora Software]$ /usr/local/apptainer/bin/apptainer exec --nvccli ./sand_glxgears/ glxgears
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/amit/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/amit/.drirc: No such file or directory.
libGL: pci id for fd 4: 8086:191b, driver i965
libGL: OpenDriver: trying /usr/lib64/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/i965_dri.so
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/amit/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/amit/.drirc: No such file or directory.
libGL: Using DRI3 for screen 0
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /home/amit/.drirc: No such file or directory.
313 frames in 5.0 seconds = 62.436 FPS
300 frames in 5.0 seconds = 59.995 FPS
300 frames in 5.0 seconds = 59.995 FPS
300 frames in 5.0 seconds = 59.998 FPS
```
I was able to make the `sudo` version of the `exec` command access `X11` by binding `$XAUTHORITY` in the container. The `glxgears` window showed up but it was not using the NVIDIA GPU as can be seen by the output below:
```bash
[amit@fedora Software]$ sudo /usr/local/apptainer/bin/apptainer exec --nvccli -B $XAUTHORITY glxgears_old.sif glxgears
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
libGL: pci id for fd 4: 8086:191b, driver i965
libGL: OpenDriver: trying /usr/lib64/dri/tls/i965_dri.so
libGL: OpenDriver: trying /usr/lib64/dri/i965_dri.so
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
libGL: Using DRI3 for screen 0
libGL: Can't open configuration file /etc/drirc: No such file or directory.
libGL: Can't open configuration file /root/.drirc: No such file or directory.
303 frames in 5.0 seconds = 60.435 FPS
300 frames in 5.0 seconds = 59.995 FPS
```
Please let me know if I can try anything else.

**Comment by DrDaveD** [comment]
You did get further, there's no message anymore about nvidia-smi not working.  Does nvidia-smi work with that fix-permed sandbox?

Is there an /etc/drirc file on the host?  If so does it help to bind that in? I don't think the --nv option knows about that by default.   Maybe there's a mismatch between the nvidia-container-cli command and your drivers.  I really have no idea.

**Comment by amit112amit** [comment]
The result of `fix-perm` sandbox was the same as the one with `sudo` and `Xauthority`. I have included both the outputs in the previous post. But I am not sure if `nvidia-smi` was called because the Intel driver is being used as reported in the outputs.

There is no `/etc/drirc` file on the host.

It may be possible that there is a mismatch between `nvidia-container-cli` and the `nvidia` drivers on Fedora 36. I have tried downgrading the NVIDIA driver but still, it does not work. Actually, `nvidia-container-toolkit` does not support Fedora officially. The general advice available on the internet is to install the RHEL version of `nvidia-container-toolkit`. So I have installed the RHEL 9 version. I have tested that on RHEL 9, `apptainer` is able to run glxgears on the NVIDIA GPU.

So it seems there is no solution for this error on Fedora 36.

**Comment by DrDaveD** [comment]
> The result of `fix-perm` sandbox was the same as the one with `sudo` and `Xauthority`.

Ok but at least they were better than the fakeroot sif which had the `nvidia-smi: no data available` error.  I was asking if you could run just `nvidia-smi` under either of the two conditions where glxgears at least ran, to see if that gives us any more information.
 
> So it seems there is no solution for this error on Fedora 36.

Yes but it sounds like it's likely to be an issue with the nvidia software and nothing apptainer can do about it.

**Comment by amit112amit** [comment]
>  I was asking if you could run just nvidia-smi under either of the two conditions where glxgears at least ran, to see if that gives us any more information.
Ok. I am sorry that I did not understand it clearly at first. I have now run a `bash` shell in the `--fix-perms` sandbox and run a `nvidia-smi` from within the container. The output is same as running `nvidia-smi` from outside the container. I have pasted the output below:
``` terminal
[amit@fedora Software]$ apptainer build --sandbox --fix-perms ./my_glx/ glx_test.def
[amit@fedora Software]$ apptainer exec --nvccli -w ./my_glx bash
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
Apptainer> nvidia-smi
Sat Aug 13 14:36:03 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   35C    P8    N/A /  N/A |      3MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1848      G   /usr/libexec/Xorg                   2MiB |
+-----------------------------------------------------------------------------+
```

> Yes but it sounds like it's likely to be an issue with the nvidia software and nothing apptainer can do about it.

Thank you for your time and ideas @DrDaveD. I will close the issue here.

**Comment by GodloveD** [comment]
Going back to your original issue with the `--nv` flag, I am able to replicate on a Fedora 36 laptop with an NVIDIA GPU.  And I'm also able to fix the issue.  

#### The short answer
Make a backup copy and edit `$APPTAINER_HOME/etc/apptainer/nvliblist.conf` (where `$APPTAINER_HOME` refers to the base of your installation. In your case the file may just be located in `/etc` since you installed from rpm.)

Remove the following:
```
libGLdispatch.so
libglx.so
libGLX.so
```
Try again and your original container should run glxgears.  If you have a laptop like mine you may have to set the following before running the container to force the laptop to use the discrete (NVIDIA) graphics card instead of integrated graphics.
```
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0 __GLX_VENDOR_LIBRARY_NAME=nvidia
```
#### The long answer

The `--nv` and `--nvccli` options work differently.  The `--nvccli` option can obtain system-specific information about the GPU driver and user-side libraries that are installed as well as where to find them.  The `--nv` option on the other hand is pretty dumb.  It has a list of all the user-libraries that might be important to run GPU enabled containers (`nvliblist.conf`).  It looks through all libraries installed on the host system and whatever matches it bind mounts into the container.  

This dumb strategy usually works, in part because the user facing libraries that allow programs to interact with the NVIDIA kernel module are most often compiled to allow compatibility with older glibc versions.

Now, there has be some disagreement in the past about which libraries actually belong in `nvliblist.conf`.  And I think this issue shows why.  It sounds like we now have a situation where a few libraries on the Fedora 36 host are compiled using the latest greatest glibc and can't link to the glibc in the container.  But luckily, these libraries are already installed in the container as well (at `/usr/lib64`).  Furthermore, the libraries in the container are properly compiled against the glibc in the container.  

So the solution is to delete the offending libraries from `nvliblist.conf`.  This will work as long as the containers you try to run on this host have `libGLdispatch.so*`, and `lib<glx,GLX>.so*` installed in them if they rely on them.

**Comment by amit112amit** [comment]
Thank you very much for providing the solution @GodloveD. I have switched my laptop OS to Debian 11 due to this issue. I don't have Fedora 36 installed anymore. I also have an NVIDIA Optimus laptop. So I can confirm that even on Debian 11, I need to export the special variables to launch `glxgears` using the NVIDIA GPU in the container.

I have a question. I understand that to get `glxgears` to work with NVIDIA GPU, I should use the `--nv` option and remove the `libGLdispatch` and `lib<glx,GLX>.so` libraries from the `nvliblist.conf` on the host. Does the `--nvccli` option work out of the box for you on Fedora 36 with the latest `apptainer` version?

**Comment by GodloveD** [comment]
Good question @amit112amit.  Looks like the answer is _no_. :sob: 
```
$ apptainer --version
apptainer version 1.1.0-rc.2

$ nvidia-container-cli list
/dev/nvidiactl
/dev/nvidia-uvm
/dev/nvidia-uvm-tools
/dev/nvidia-modeset
/dev/nvidia0
/usr/bin/nvidia-smi
/usr/bin/nvidia-debugdump
/usr/bin/nvidia-persistenced
/usr/bin/nvidia-cuda-mps-control
/usr/bin/nvidia-cuda-mps-server
/usr/lib64/libnvidia-ml.so.515.57
/usr/lib64/libnvidia-cfg.so.515.57
/usr/lib64/libcuda.so.515.57
/usr/lib64/libnvidia-opencl.so.515.57
/usr/lib64/libnvidia-ptxjitcompiler.so.515.57
/usr/lib64/libnvidia-allocator.so.515.57
/usr/lib64/libnvidia-compiler.so.515.57
/usr/lib64/libnvidia-ngx.so.515.57
/usr/lib64/vdpau/libvdpau_nvidia.so.515.57
/usr/lib64/libnvidia-encode.so.515.57
/usr/lib64/libnvidia-opticalflow.so.515.57
/usr/lib64/libnvcuvid.so.515.57
/usr/lib64/libnvidia-eglcore.so.515.57
/usr/lib64/libnvidia-glcore.so.515.57
/usr/lib64/libnvidia-tls.so.515.57
/usr/lib64/libnvidia-glsi.so.515.57
/usr/lib64/libnvidia-fbc.so.515.57
/usr/lib64/libnvidia-rtcore.so.515.57
/usr/lib64/libnvoptix.so.515.57
/usr/lib64/libGLX_nvidia.so.515.57
/usr/lib64/libEGL_nvidia.so.515.57
/usr/lib64/libGLESv2_nvidia.so.515.57
/usr/lib64/libGLESv1_CM_nvidia.so.515.57
/usr/lib64/libnvidia-glvkspirv.so.515.57
/usr/lib/libnvidia-ml.so.515.57
/usr/lib/libcuda.so.515.57
/usr/lib/libnvidia-opencl.so.515.57
/usr/lib/libnvidia-ptxjitcompiler.so.515.57
/usr/lib/libnvidia-allocator.so.515.57
/usr/lib/libnvidia-compiler.so.515.57
/usr/lib/vdpau/libvdpau_nvidia.so.515.57
/usr/lib/libnvidia-encode.so.515.57
/usr/lib/libnvidia-opticalflow.so.515.57
/usr/lib/libnvcuvid.so.515.57
/usr/lib/libnvidia-eglcore.so.515.57
/usr/lib/libnvidia-glcore.so.515.57
/usr/lib/libnvidia-tls.so.515.57
/usr/lib/libnvidia-glsi.so.515.57
/usr/lib/libnvidia-fbc.so.515.57
/usr/lib/libGLX_nvidia.so.515.57
/usr/lib/libEGL_nvidia.so.515.57
/usr/lib/libGLESv2_nvidia.so.515.57
/usr/lib/libGLESv1_CM_nvidia.so.515.57
/usr/lib/libnvidia-glvkspirv.so.515.57
/lib/firmware/nvidia/515.57/gsp.bin

$ apptainer exec --nvccli glx_rocky.sif glxgears
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
INFO:    Consider using either `--fakeroot` or sandbox built with `--fix-perms`
FATAL:   container creation failed: /usr/bin not writable in the container

$ apptainer exec --fakeroot --nvccli glx_rocky.sif glxgears
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
FATAL:   container creation failed: nvidia-container-cli failed with exit status 1: nvidia-container-cli: mount error: file creation failed: /opt/apptainer/1.1.0-rc.2/var/apptainer/mnt/session/final/usr/bin/nvidia-smi: no data available

$ apptainer build --fakeroot --fix-perms glx_rocky glx_rocky.sif 
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
INFO:    Verifying bootstrap image glx_rocky.sif
WARNING: integrity: signature not found for object group 1
WARNING: Bootstrap image could not be verified, but build will continue.
INFO:    Creating SIF file...
INFO:    Build complete: glx_rocky

$ apptainer exec --nvccli glx_rocky glxgears
INFO:    Setting 'NVIDIA_VISIBLE_DEVICES=all' to emulate legacy GPU binding.
INFO:    Setting --writable-tmpfs (required by nvidia-container-cli)
FATAL:   container creation failed: nvidia-container-cli failed with exit status 1: nvidia-container-cli: mount error: file creation failed: /opt/apptainer/1.1.0-rc.2/var/apptainer/mnt/session/final/usr/bin/nvidia-smi: no data available
```
Am I doing something wrong here @DrDaveD?  As you can see above I have the latest RC of apptainer installed from source at `/opt/apptainer/1.1.0-rc.2`.  Could the error be related to the non-standard installation location?  

And as a side note why the heck does the nvidia-container-cli want to write to `/usr/bin` in the container??

**Comment by DrDaveD** [comment]
I really don't know what it takes to make it work on Fedora, sorry.  The history in this issue is probably about the best thing for summarizing my ideas.

I believe that nvidia-container-cli is trying to create bind mount points in `/usr/bin`, although I'm not sure.
