### ISSUE TITLE
Intermittent cleanup errors

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#613]
In version 1.1.0-rc.1 I occasionally see a message like this after exiting from an interactive bash on a centos7 host:
```
ERROR:   Cleanup error: while unmounting /var/apptainer/mnt/session/rootfs directory: device or resource busy
```
I always go back and try to do the exact same thing I did before and can never reproduce and catch it happening to debug.

**Comment by DrDaveD** [comment]
This should be changed to an Info or possibly Verbose message since it doesn't seem to cause any problems

**Comment by y9c** [comment]
What is the cause of this message? I have this message show up all the time.

**Comment by DrDaveD** [comment]
If you can come up with a way to reliably reproduce it, please post it.

It's a non-fatal error when cleaning up.  We could make it a debug message so it wouldn't annoy people, but I keep hoping that someone will figure out a way to reproduce it so I could instead fix it to have a clean shut down.  I see it occasionally but have never been able to reproduce it when I have tried.  It's in the code that's unmounting bind mounts, and that code was needed in order to unmount underlying FUSE mounts.  I don't think I have ever seen it leave behind FUSE processes but I worry that it might happen sometime.

**Comment by y9c** [comment]
Hi @DrDaveD, I built a docker image which is 50% by chance to trigger this error. 

test by:

```
apptainer run docker://y9ch/debug_apptainer
```

Dockerfile:

```
# x86_64
FROM debian:bullseye-slim

RUN DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt-get -y --no-install-recommends install apt-utils curl python3 python3-pip && apt-get clean && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install --no-cache-dir panoptes-ui
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY ./entrypoint /pipeline/
RUN chmod +x /pipeline/entrypoint
ENTRYPOINT ["/pipeline/entrypoint"]
```

**Comment by DrDaveD** [comment]
Hmm, it's not giving me the message.  What is your host os and apptainer version number?

**Comment by y9c** [comment]
Thanks @DrDaveD 

Host machine:

```
$ lsb_release -a

No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

```
$ apptainer --version
apptainer version 1.1.4
```

**Comment by y9c** [comment]
Could you repeat the command multiple times? Is it ~50% chance on my machine.

**Comment by DrDaveD** [comment]
Yes I did repeat it multiple times on my centos7 VM and didn't get the message.  However, when I run it on ubuntu 22.04 under vagrant on my Mac laptop I got the message 5 out of 5 attempts.   Thank you, now I have something I can use for debugging.
