### ISSUE TITLE
Make e2e tests for adding on packages with `--fakeroot --writable-tmpfs`

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#617]
There should be e2e tests very much like the ones in #607 for adding the same packages on top of an existing sif file with an action command including options `--fakeroot --writable-tmpfs`.  The same additional hidden options should be added to action commands.

**Comment by JasonYangShadow** [comment]
@DrDaveD just to confirm, are these tests still for `apptainer build`?
Besides, it looks like that putting `--fakeroot --writable-tmpfs` together is not expected?
https://github.com/apptainer/apptainer/blob/22520a1f1cda6d419a8ea700720b4c93cec826be/cmd/internal/cli/build_linux.go#L188

**Comment by DrDaveD** [comment]
No, this is for an action command such as 'exec ..... true'.  The `--writable-tmpfs` option uses overlayfs to make an existing image appear writable.
