### ISSUE TITLE
remove dependencies on remote commercial services (key server) for compliance with LF open-source license

### ISSUE THREAD

**Issue by PaulCharlton** [apptainer/apptainer#62]
defer remove dependencies on remote commercial services (key server) for compliance with LF open-source license

remote key server

target release: Apptainer v1.0.0

_Originally posted by @PaulCharlton in https://github.com/apptainer/apptainer/issues/53#issuecomment-991943166_

**Comment by DrDaveD** [comment]
I believe that the key server did not need to be removed because it was using a standard protocol.  @gmkurtzer?

**Comment by DrDaveD** [comment]
We agreed that I would just pull in a fork of the code into apptainer repo container-key-client.

**Comment by DrDaveD** [comment]
https://github.com/apptainer/container-key-client is ready.
