### ISSUE TITLE
`--writable-tmpfs` in suid mode gets too small of space

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#636]
The default filesystem size used by `--writable-tmpfs` in suid mode is set by the `sessiondir max size` apptainer.conf configuration and defaults to only 16M.  That's not of much use, and the comment in that setting in apptainer.conf doesn't say it is related or applies to only suid mode.

**Comment by JasonYangShadow** [comment]
this issue requires @cclerget 's confirmation?

**Comment by DrDaveD** [comment]
I think this can just be an update to the comments in apptainer.conf.
