### ISSUE TITLE
INSTALL.md instructions incomplete for Rocky 8.6 as fuse2fs is missing

### ISSUE THREAD

**Issue by scaleoutsean** [apptainer/apptainer#642]
### Version of Apptainer

1.1.0.rc.2-1

### Expected behavior

Apptainer is installed

### Actual behavior

Apptainer fails to install due to fuse2fs not being available in Rocky 8.6:

```
$ sudo rpm -i apptainer-1.1.0.rc.2-1.x86_64.rpm 
error: Failed dependencies:
	fuse2fs is needed by apptainer-1.1.0~rc.2-1.x86_64

$ sudo dnf install -y fuse2fs
Last metadata expiration check: 0:05:53 ago on Sun 21 Aug 2022 03:36:17 PM CST.
No match for argument: fuse2fs
Error: Unable to find a match: fuse2fs

```

### Steps to reproduce this behavior

- Follow INSTALL.md for CentOS/RHEL
- `sudo rpm -i apptainer-1.1.0.rc.2-1.x86_64.rpm` 

### What OS/distro are you running

```sh
$ cat /etc/redhat-release 
Rocky Linux release 8.6 (Green Obsidian)
```

**Comment by DrDaveD** [comment]
Oh, thanks for bringing that to my attention, I should have anticipated that.  Please work around it by installing from epel-testing instead.

Unfortunately I don't know of a good solution that will work everywhere with the single rpm.  With yum install the instructions say to install `/usr/*bin/fuse2fs` but that doesn't work with rpm.  I guess the best I can do with the single rpm is require e2fsprogs (for el9) and people who install from the binary distribution for el7 will have to install fuse2fs from epel themselves.  I could put in a %pre check to at least tell people what they need to do.
