### ISSUE TITLE
Allow specifying platform when pulling Docker container

### ISSUE THREAD

**Issue by rgov** [apptainer/apptainer#645]
### Version of Apptainer

Singularity v3.9.9

### Expected behavior

Use case: I do my daily work on an arm64-based computer, but I want to be able to prepare .sif files that run in my x86_64-based HPC environment.

I would therefore like to specify the platform to use when running `singularity pull foo.sif docker://blahcorp/foo`. It is unclear whether it defaults to my local architecture/platform or to something else.

There is no mention of "platform" on http://apptainer.org/docs/user/main/docker_and_oci.html

**Comment by DrDaveD** [comment]
There is no singularity 3.9, you must be using singularity-ce.  Confirm with `singularity --version`, and if so please submit your issue instead to https://github.com/sylabs/singularity.

Having said that, you might be looking for the `--arch` option.

**Comment by rgov** [comment]
Thanks.

I was using the Docker container https://quay.io/repository/singularity/singularity which comes from https://www.github.com/singularityhub/singularity-docker which indeed builds from https://github.com/sylabs/singularity...
