### ISSUE TITLE
singularity not cleanup crypt when signal terminated

### ISSUE THREAD

**Issue by nihilee** [apptainer/apptainer#649]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

apptainer 1.0.3

### Expected behavior

when singularity child process was killed by sigterm, should cleanup its crypt automatically

### Actual behavior

after kill the starter-suid process，a crypt not closed
```
$sudo dmsetup info -C
Name                                 Maj Min Stat Open Targ Event  UUID
349bdc51-323e-4c72-b455-f6e766abf971 253   2 L--r    0    1      0 CRYPT-LUKS2-c16902f5cc6d4044a0e36fe10347aa53-349bdc51-323e-4c72-b455-f6e766abf971
```

### Steps to reproduce this behavior

```
singularity exec encrpy.sif
# kill {pid} of starter-suid process
losetup
# a crypt not closed
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

### How did you install Apptainer

RPM

**Comment by DrDaveD** [comment]
What signal did you send?  You killed the "Apptainer runtime parent"?  The other signals I tried seem to be ignored.  If it is kill -9, I'm not sure there's anything that Apptainer can do.

**Comment by nihilee** [comment]
> What signal did you send? You killed the "Apptainer runtime parent"? The other signals I tried seem to be ignored. If it is kill -9, I'm not sure there's anything that Apptainer can do.

kill -15, I think. I test kill the parent and child, both of them will stop the Apptainer and crypt remained. ignored? you mean cannot kill the Apptainer process and its child process?

**Comment by DrDaveD** [comment]
I believe it is correct behavior for Apptainer itself to ignore signals.  I think the expectation is that batch systems will send the kill signal to the entire process group, and that Apptainer should wait for the children to die gracefully.  I did a `kill -15` with a `-` on the process id of the starter-suid process, and in my example I was running an interactive bash which also ignores `kill -15`.  I tried it just now where the running process was `sleep` and the `kill -15` of the process group successfully killed the sleep and Apptainer properly cleaned up the dmsetup..  

So I'd like to know if you can give detailed instructions on how to repeat the problem without kill -9, if there is a way.

**Comment by nihilee** [comment]
> I believe it is correct behavior for Apptainer itself to ignore signals. I think the expectation is that batch systems will send the kill signal to the entire process group, and that Apptainer should wait for the children to die gracefully. I did a `kill -15` with a `-` on the process id of the starter-suid process, and in my example I was running an interactive bash which also ignores `kill -15`. I tried it just now where the running process was `sleep` and the `kill -15` of the process group successfully killed the sleep and Apptainer properly cleaned up the dmsetup..
> 
> So I'd like to know if you can give detailed instructions on how to repeat the problem without kill -9, if there is a way.

I also found that may not a apptainer problem, actually it happens when I use PBS qdel or qsig stop a job, so PBS send a wrong signal to apptainer?

**Comment by DrDaveD** [comment]
I think that a batch system ought to first send kill -15 to the process group, wait a couple seconds for the job to cleanup, and then send kill -9.  I believe that at least HTCondor does that, I don't know about the other batch systems.

**Comment by nihilee** [comment]
emm... it seems that qdel dont give apptainer enough time to umount and cleanup, I will figure out what it happens...thank you!!
