### ISSUE TITLE
/etc/subuid-based fakeroot with --writable-tmpfs in suid flow has many failures

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#651]
Lots of different failures happen with various operating system SIF images when attempting to install openssh in the suid flow and --writable-tmpfs, even after increasing the `sessiondir max size`.  For instance on a centos7 SIF it says:
```
error: unpacking of archive failed on file /usr/bin/fipscheck;630678a2: cpio: open
...
error: unpacking of archive failed on file /etc/prelink.conf.d/fipscheck.conf;630678a2: cpio: chmod
```
It works with either `--userns`, a sandbox, or with `--overlay` instead of `--writable-tmpfs`.  What's the difference with `--writable-tmpfs`?

**Comment by DrDaveD** [comment]
It's something to do with that tmpfs upper layer, because it fails the same way with `--overlay /dev/shm/overlay/` (where /dev/shm/overlay is a user-owned directory).  Maybe because it doesn't have support for extended attributes?

**Comment by DrDaveD** [comment]
I have made a simpler reproducer on centos7 with apptainer-suid installed and /etc/sub[ug]id set up, like this:
```
$ apptainer build centos7.sif docker://centos:7
$ apptainer exec --pwd / -f --writable-tmpfs centos7.sif touch usr/lib64/fipscheck/fipscheck.hmac
/usr/bin/touch: cannot touch 'usr/lib64/fipscheck/fipscheck.hmac': Permission denied
```
but if I add a `-u` option to apptainer it gets no errors. 

I put a shell wrapper around fuse-overlayfs, adding `--debug`, redirecting stdout & stderr to a file, and running strace on it.  I found this behavior while it was trying to create the fipscheck.hmac file:
```
openat(4, "usr/lib64", O_RDONLY|O_NONBLOCK) = 41
fstat(41, {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
mkdirat(9, "3", 040555)                 = 0
openat(9, "3", O_RDONLY)                = 42
...
flistxattr(41, "", 1048576)             = 0
renameat(9, "3", 5, "usr/lib64")        = -1 ENOENT (No such file or directory)
```
and after that it goes through a series of steps trying to make a "usr/lib64" which ends up with EACCES.

The corresponding entries with `-u` were:
```
openat(4, "usr/lib64", O_RDONLY|O_NONBLOCK) = 41
fstat(41, {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
mkdirat(9, "8", 040555)                 = 0
openat(9, "8", O_RDONLY)                = 42
...
flistxattr(41, "", 1048576)             = 0
renameat(9, "8", 5, "usr/lib64")        = 0
```

**Comment by JasonYangShadow** [comment]
maybe userns help fuse-overlayfs pass some checks, but fakeroot is not enough. 

trying with different combinations,  it looks like --writable-tmpfs has special needs for userns
```
vagrant@vagrant:/tmp$ apptainer exec --fakeroot  --userns --ignore-subuid --pwd / --writable-tmpfs centos7.sif touch usr/lib64/fipscheck/fipscheck.hmac
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    Using fakeroot command combined with root-mapped namespace
vagrant@vagrant:/tmp$ apptainer exec --userns --ignore-subuid --pwd / --writable-tmpfs centos7.sif touch usr/lib64/fipscheck/fipscheck.hmac
/usr/bin/touch: cannot touch ‘usr/lib64/fipscheck/fipscheck.hmac’: Permission denied
vagrant@vagrant:/tmp$ apptainer exec --fakeroot --pwd / --writable-tmpfs centos7.sif touch usr/lib64/fipscheck/fipscheck.hmac
/usr/bin/touch: cannot touch ‘usr/lib64/fipscheck/fipscheck.hmac’: Permission denied
vagrant@vagrant:/tmp$ 
```
