### ISSUE TITLE
Support recent linux capabilities

### ISSUE THREAD

**Issue by geonmo** [apptainer/apptainer#669]
### Version of Apptainer

```bash
 singularity-3.8.7-1.el8.x86_64                                                                                                                               
```
### Expected behavior

Support **CAP_CHECKPOINT_RESTORE** in specific apptainer container
* See [latest capabilites](https://github.com/torvalds/linux/blob/master/include/uapi/linux/capability.h)

### Actual behavior

After checking [the code](https://github.com/apptainer/apptainer/blob/0c99585981fb439b1b3d90091a5507da38539ced/pkg/util/capabilities/capabilities.go), it does not appear to be supported yet.

### Steps to reproduce this behavior

Not yet support

### What OS/distro are you running

```bash
Rocky Linux release 8.6 (Green Obsidian)
```

### How did you install Apptainer

RPM from EPEL repo

**Comment by DrDaveD** [comment]
What difference in behavior would there be if this were supported?  What doesn't work now?

**Comment by geonmo** [comment]
@DrDaveD The CAP_SYS_ADMIN privilege is required to create a checkpoint for a running process on a singularity container using CRIU and to be able to restart it in the future. This is not possible for the actual service because we must grant administrator privileges to that user. CAP_CHECKPOINT_RESTORE, the capability we requested, supports Checkpoint/Restore without administrator privileges. This is applied to the latest kernel(5.9), but backported for RHEL8 or derived os. Therefore, the CAP is also available in CentOS8. As I know, the Singularity Code does not have that part of the content, but I'm not sure if it's just a help message or if it affects the application of the feature. If there is no problem with the actual application, I will close the issue.

**Comment by geonmo** [comment]
```bash
[root@node0 ~]# cat /usr/src/kernels/4.18.0-372.13.1.el8_6.x86_64/include/uapi/linux/capability.h | grep CAP_CHECKPOINT
#define CAP_CHECKPOINT_RESTORE	40
#define CAP_LAST_CAP         CAP_CHECKPOINT_RESTORE
[root@node0 ~]# singularity capability add --user geonmo CAP_SYS_ADMIN
WARNING: Adding 'CAP_SYS_ADMIN' capability will likely allow user geonmo to escalate privilege on the host
WARNING: Use 'singularity capability drop --user geonmo CAP_SYS_ADMIN' to reverse this action if necessary
[root@node0 ~]# singularity capability add --user geonmo CAP_CHECKPOINT_RESTORE
WARNING: Ignoring unknown capabilities: [CAP_CHECKPOINT_RESTORE]
[root@node0 ~]# cat /etc/redhat-release 
Rocky Linux release 8.6 (Green Obsidian)

```

**Comment by DrDaveD** [comment]
@ikaneshiro what do you think?

**Comment by geonmo** [comment]
I haven't tested it, but it looks like the code I want is updated. 

The code has been updated on the Sylab side. So, I will close this issue.
