### ISSUE TITLE
Mixed messages of Singularity being EOL:ed or not

### ISSUE THREAD

**Issue by HenrikBengtsson** [apptainer/apptainer#680]
Tried to post this over at the old Singularity repo, but it got auto-closed. Just in case you're not aware...

From https://apptainer.org/news/community-announcement-20211130/ that this README links to:

Is Singularity EOL?
No, Singularity IS Apptainer and Apptainer has a LONG life ahead!

Yet, the GitHub description field of https://github.com/apptainer/singularity says:

Singularity has been EOL'ed, see Apptainer

**Comment by DrDaveD** [comment]
Thanks, I changed the description to "Singularity has been renamed to Apptainer".
