### ISSUE TITLE
The mconfig `-b` option results in a make error

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#698]
### Version of Apptainer

1.1.0-rc.3

### Expected behavior

A successful build with the mconfig `-b` option

### Actual behavior

A compile error:

```
 GO cmd/starter/c/starter
# command-line-arguments
../cmd/starter/main_linux.go:13:21: fatal error: config.h: No such file or directory
 // #include <config.h>
                     ^
compilation terminated.
make: *** [cmd/starter/c/starter] Error 2
```

### Steps to reproduce this behavior

```
./mconfig -b buildtree
cd buildtree
make
```

### What OS/distro are you running

CentOS7

### How did you install Apptainer

Trying to compile from source

**Comment by glm729** [comment]
Identical fault when (probably rather foolishly) attempting to build from source on a Raspberry Pi 4. Found this ticket when searching for mentions of `config.h` in the tickets list.  On tag `v1.1.0-rc.3`.


Commands, run from repository root, resulting in the compile error shown above:

```sh
./mconfig -b ./builddir -p /usr/local
cd builddir
make -j $(nproc)
```


Omitting `-b ./builddir` results in a successful installation, on both Raspberry Pi 4 and an amd64 machine running Windows 10 WSL2, both Ubuntu 20.04:

```sh
./mconfig --prefix=/usr/local
cd builddir
make -j $(nproc)
sudo make install -j $(nproc)
```


----


| | |
| :-------------------- | :------------------------------ |
| **System**            | Raspberry Pi 4                  |
| **OS / Distribution** | Ubuntu 20.04                    |
| **Go version**        | 1.19.1, precompiled for aarch64 |
| **Apptainer version** | v1.1.0-rc.3                     |

**Comment by DrDaveD** [comment]
That's very interesting.  It would imply that the problem was not with the change of name but just with the fact of passing `-b`.

However, I cannot reproduce that behavior on CentOS7, and I can't see anything wrong with the code that handles `-b`.  On the other hand, I think I found that the root cause is [this line of code](https://github.com/apptainer/apptainer/blob/v1.1.0-rc.3/cmd/starter/main_linux.go#L12) in starter.go where it is explicitly including the directory `builddir`.

**Comment by glm729** [comment]
@DrDaveD Good point, and indeed that's an error on my part!  Passing `builddir` works, this appears to be the default, but passing `buildtest` (or indeed anything other than `builddir`) leads to a failure to find `config.h`.  Apologies for my error!

So, this works:

```sh
./mconfig -b ./builddir -p /usr/local
```

but this does not:

```sh
./mconfig -b ./buildtest -p /usr/local
```
