### ISSUE TITLE
--prefix seems not to be honoured in respect to apptainer.conf

### ISSUE THREAD

**Issue by Jaapdijkshoorn** [apptainer/apptainer#726]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

`apptainer version 1.1.0`

### Expected behavior

What did you expect to see when you do...?

I expect that the 'default' location of apptainer.conf should be /opt/apptainer/etc/apptainer.conf
When i do:

`./mconfig -p /opt/apptainer` or `./mconfig --prefix=/opt/apptainer`

### Actual behavior

What actually happend? Why was it incorrect?

`  -c, --config string   specify a configuration file (for root or
                        unprivileged installation only) (default
                        "/opt/apptainer/sw/1.1.0/sw/1.1.0/etc/apptainer/apptainer.conf")`

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.

From Source

**Comment by DrDaveD** [comment]
How exactly do you get that message about `-c`?  I don't see it.

**Comment by DrDaveD** [comment]
Oh, I see the message in `apptainer -h`, but I cannot reproduce the problem.  I get
```
  -c, --config string   specify a configuration file (for root or
                        unprivileged installation only) (default
                        "/opt/apptainer/etc/apptainer/apptainer.conf")
```

**Comment by DrDaveD** [comment]
This looks like correct behavior to me.  Yes for non-setuid root it does support relocation.  There's not a way to disable it.  Why do you consider it a problem?

**Comment by Jaapdijkshoorn** [comment]
Well we like to install several versions sometimes. But what is see now is this:

if i put the apptainer binary in this directory: `/home/jaap/jaap` i get the following default pathe for the config if a run `./apptainer -h`

```
  -c, --config string   specify a configuration file (for root or
                        unprivileged installation only) (default
                        "/home/jaap/etc/apptainer/apptainer.conf")
```

what thought would happen is that it does not matter where i put the `apptainer` binary,  i always would get /opt/apptainer/etc/apptainer/apptianer.conf as the default. Sice i prefixed it with --prefix=/opt/apptainer.

**Comment by DrDaveD** [comment]
That's a reasonable expectation, it's what most programs do, but Apptainer has a relocation feature so it behaves differently.  It's a feature, not a bug.
