### ISSUE TITLE
Image bind while using underlay requires pre-existing bind point in container

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#728]
### Version of Apptainer

1.1.0

### Expected behavior

When I bind anything into a container I expect it to create the bind mountpoint if it is missing.

### Actual behavior

Binding an image into a container while running in non-suid flow gets an error, for example
```
WARNING: skipping mount of /var/apptainer/mnt/session/data-images/0/work: stat /var/apptainer/mnt/session/data-images/0/work: no such file or directory
INFO:    Cleanup error: while unmounting /var/apptainer/mnt/session/final directory: device or resource busy
FATAL:   container creation failed: mount /var/apptainer/mnt/session/data-images/0/work->/data error: while mounting /var/apptainer/mnt/session/data-images/0/work: destination /data doesn't exist in container
```

### Steps to reproduce this behavior

After installing apptainer without apptainer-suid:
```
apptainer overlay create --sparse --size=5000 data.img
apptainer exec -B data.img:/data:image-src=/work docker://centos:7 true
```
Either changing /data to /mnt or installing apptainer-suid makes it work.

### What OS/distro are you running

CentOS7

### How did you install Apptainer

```
yum --enablerepo=epel-testing install apptainer
```

**Comment by DrDaveD** [comment]
This behavior also exists with suid when `enable overlay = no` so that underlay is used.  I was also able to reproduce that behavior with singularity-3.8.7 so it is not a new bug.  It's just more obvious because now using underlay is the default.

**Comment by glm729** [comment]
I've found an odd bug that may be similar, but I am unsure.  The error message
looks a little different.  Please let me know if I should open another ticket
for this one.

This is a bizarre setup (again), which, in short, is to bypass administrator
restrictions and a slightly-outdated version of Apptainer.  To be clear though,
the system admin knows I'm doing this, but can't change lots of things for only
my use-cases, so encouraged me to experiment.

It's another nested Apptainer setup -- the outer version is 1.0.3, and the inner
version is 1.1.2.  This is related to my attempts in [this ticket][t0].  I've
masked the paths here, but I've checked them carefully and I am absolutely
certain that they exist.  I've also found a workaround.

Here's the command I am running:

```bash
apptainer exec \
    --bind="/project_directory/Apptainer/data/sif:/data/sif:rw" \
    --bind="/project_directory/Apptainer/data/def:/data/def:ro" \
    rocky_dev.sif \
    apptainer build \
        --fakeroot --fix-perms \
        /data/sif/rocky_test.sif \
        /data/def/rocky_test.def
```

Here's the error message I get:

```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
INFO:    Verifying bootstrap image /data/sif/rocky_dev.sif
WARNING: integrity: signature not found for object group 1
WARNING: Bootstrap image could not be verified, but build will continue.
INFO:    Running post scriptlet
FATAL:   container creation failed: mount /project_directory/Apptainer/data/sif->/data/sif error: while mounting /project_directory/Apptainer/data/sif: mount source /project_directory/Apptainer/data/sif doesn't exist
FATAL:   While performing build: while running engine: exit status 255
```

The workaround appears to be consistent, and I am hoping that it sheds some
light on where the error might be occurring.  In short, it works if I start an
instance, then execute the command using the instance:

```bash
apptainer instance start \
    --bind="/project_directory/Apptainer/data/sif:/data/sif:rw" \
    --bind="/project_directory/Apptainer/data/def:/data/def:ro" \
    rocky_dev.sif \
    rocky_dev

apptainer exec instance://rocky_dev \
    apptainer build \
        --fakeroot --fix-perms \
        /data/sif/rocky_test.sif \
        /data/def/rocky_test.def

apptainer instance stop rocky_dev
```


[t0]: https://github.com/apptainer/apptainer/issues/783
