### ISSUE TITLE
Running Apptainer in Alpine missing files

### ISSUE THREAD

**Issue by afbjorklund** [apptainer/apptainer#735]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using?

`1.0.3`

### Expected behavior

What did you expect to see when you do...?

Using `singularity run` failed, out-of-the-box

### Actual behavior

What actually happend? Why was it incorrect?

```
FATAL:   Unable to handle docker://alpine uri: while building SIF from layers: unable to create new build: while searching for mksquashfs: exec: "/usr/bin/mksquashfs": stat /usr/bin/mksquashfs: no such file or directory
```

```
FATAL:   while extracting /home/anders.linux/.apptainer/cache/oci-tmp/bc41182d7ef5ffc53a40b044e725193bc10142a1243f395ee852a8d9730fc2ad: exec: "/usr/bin/unsquashfs": stat /usr/bin/unsquashfs: no such file or directory
```

```
FATAL:   container creation failed: mount /etc/localtime->/etc/localtime error: while mounting /etc/localtime: mount source /etc/localtime doesn't exist
```

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

`apptainer run`

### What OS/distro are you running

```sh
$ cat /etc/os-release

PRETTY_NAME="Alpine Linux v3.16"
```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.

```console
$ sudo apk add apptainer
fetch https://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
(1/5) Installing lz4-libs (1.9.3-r1)
(2/5) Installing lzo (2.10-r3)
(3/5) Installing squashfs-tools (4.5.1-r0)
(4/5) Installing libseccomp (2.5.2-r1)
(5/5) Installing apptainer (1.0.3-r4)
Executing busybox-1.35.0-r17.trigger
OK: 113 MiB in 82 packages
```

The reason for running Alpine Linux, is so that apptainer can run in [alpine-lima](https://github.com/lima-vm/alpine-lima)

This allows for a smaller download for the end user, compared to Fedora or Rocky.

```
61M	alpine-lima-std-3.16.0-x86_64.iso
428M	Fedora-Cloud-Base-36-1.5.x86_64.qcow2
2.5G	Rocky-8-GenericCloud-8.6.20220702.0.x86_64.qcow2
```

**Comment by DrDaveD** [comment]
apptainer 1.1.0 changed the way helper programs are searched for, doing it more dynamically at run time instead of compile time generating a configuration option.  Please try it with 1.1.0 instead of 1.0.3.

**Comment by afbjorklund** [comment]
Will try again, once the distribution package (apk) has been updated.

https://github.com/alpinelinux/aports/blob/master/testing/apptainer/APKBUILD

Either if the distro does it, or if I figure out how to build an updated version.

**Comment by OTLabs** [comment]
`testing/apptainer: upgrade to 1.1.0` submission is under review now, https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/39533

**Comment by afbjorklund** [comment]
I went with Fedora as the middle ground, for the "apptainer" example in lima...

It is nice that is available in Alpine too, but requires user to do some customization*

\* currently the "lima-alpine" is **only** available in the "Rancher Desktop" edition

But the lima user can start with alpine, and then just `apk add` whatever runtime.

**Comment by afbjorklund** [comment]
Tested again with the new 1.1.2 package, and only the localtime issue remains.

`limactl start --name=alpine-apptainer template://alpine`
INFO[0049] READY. Run `limactl shell alpine-apptainer` to open the shell. 

```console
lima-alpine-apptainer:/home/anders/lima$ sudo apk add apptainer
ERROR: unable to select packages:
  apptainer (no such package):
    required by: world[apptainer]
```

FIX: need to add "testing" to the /etc/apk/repositories

```
https://dl-cdn.alpinelinux.org/alpine/v3.16/main
https://dl-cdn.alpinelinux.org/alpine/v3.16/community
https://dl-cdn.alpinelinux.org/alpine/edge/testing
```

```
FATAL:   container creation failed: mount /etc/localtime->/etc/localtime error: while mounting /etc/localtime: mount source /etc/localtime doesn't exist
: exit status 255
```

FIX: `echo UTC | sudo tee /etc/localtime`

----

And then it seems to work OK, maybe squashfuse and fuse2fs should be added as dependencies ?

```console
lima-alpine-apptainer:/home/anders/lima$ sudo apk add apptainer
(1/6) Installing fakeroot (1.25.3-r3)
(2/6) Installing lz4-libs (1.9.3-r1)
(3/6) Installing lzo (2.10-r3)
(4/6) Installing squashfs-tools (4.5.1-r0)
(5/6) Installing libseccomp (2.5.2-r1)
(6/6) Installing apptainer (1.1.2-r0)
Executing busybox-1.35.0-r17.trigger
OK: 99 MiB in 84 packages
```

```console
lima-alpine-apptainer:/home/anders/lima$ apptainer run docker://busybox
INFO:    Using cached SIF image
INFO:    squashfuse not found, will not be able to mount SIF
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    Converting SIF file to temporary sandbox...
Apptainer> exit
INFO:    Cleaning up image...
```

**Comment by afbjorklund** [comment]
You can install `squashfuse_ll` using the documentation:

https://github.com/apptainer/apptainer/blob/release-1.1/INSTALL.md#installing-improved-performance-squashfuse_ll

Two of the steps need to be modified, to work on Alpine:

`apk add autoconf automake libtool pkgconfig fuse3-dev zlib-dev`

`sudo cp squashfuse_ll /usr/libexec/apptainer/bin`

Then it will be able to mount, without the temporary sandbox.

```console
lima-alpine-apptainer:/home/anders/apptainer$ apptainer run docker://busybox
INFO:    Using cached SIF image
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
Apptainer> exit

```

**Comment by DrDaveD** [comment]
I think this should be fixed in alpine.  Please submit an issue there.

**Comment by afbjorklund** [comment]
> I think this should be fixed in alpine. Please submit an issue there.

It is under way: (actually it is in the "alpine-lima" downstream distro)

* https://github.com/lima-vm/alpine-lima/issues/89

Adding squashfuse_ll to the apk package would be a separate issue.

I think it would be rather similar to the existing one for rpm and deb ?

**Comment by DrDaveD** [comment]
The latter is the issue I was thinking of.

**Comment by afbjorklund** [comment]
> I think this should be fixed in alpine. Please submit an issue there.

I made an attempt at a package for it: https://github.com/afbjorklund/aports/commit/fb1d881e651e5161e8847a91eb746b36e76ced74

Based on similar packages, like "[catatonit](https://github.com/alpinelinux/aports/tree/master/community/catatonit)" for podman.

And the apptainer instructions, from the [INSTALL.md](https://github.com/apptainer/apptainer/blob/release-1.1/INSTALL.md#installing-improved-performance-squashfuse_ll).

But I haven't created a gitlab account, and don't really want to maintain it...

@OTLabs maybe you can make use of it ?

I added the smoke test for it, under `tests()`

**Comment by afbjorklund** [comment]
Apptainer 1.2.5 is now available in the (optional) edge community repository:

https://pkgs.alpinelinux.org/packages?name=apptainer

It still requires the same workarounds as above, including package installations:

squashfuse
`FATAL:   while extracting /home/anders.linux/.apptainer/cache/oci-tmp/7eed7258228162ab1ce9a87f0af5a225b07ce694d249d2d805473ed33fcfb016: root filesystem extraction failed: extract command failed: WARNING: passwd file doesn't exist in container, not updating`

tzdata
`FATAL:   container creation failed: mount hook function failure: mount /etc/localtime->/etc/localtime error: while mounting /etc/localtime: mount source /etc/localtime doesn't exist`


```console
lima-alpine:/home/anders/lima$ sudo apk add squashfuse
(1/1) Installing squashfuse (0.5.0-r0)
Executing busybox-1.36.1-r2.trigger
OK: 103 MiB in 94 packages
lima-alpine:/home/anders/lima$ sudo apk add tzdata
(1/1) Installing tzdata (2023d-r0)
OK: 106 MiB in 95 packages
lima-alpine:/home/anders/lima$ sudo setup-timezone -z UTC
lima-alpine:/home/anders/lima$ apptainer run docker://busybox
INFO:    Using cached SIF image
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    gocryptfs not found, will not be able to use gocryptfs
Apptainer> 
```

So it seems to be at an impasse.

**Comment by OTLabs** [comment]
No luck even with `sudo apk add fuse2fs gocryptfs`?

**Comment by afbjorklund** [comment]
> No luck even with `sudo apk add fuse2fs gocryptfs`?

I'm sure that would have fixed those issues as well...
(didn't test to install them, as those features are optional)

**Comment by afbjorklund** [comment]
No complaints, after adding the required packages.

```console
lima-alpine:/home/anders/lima$ ls -l /etc/localtime
ls: /etc/localtime: No such file or directory
lima-alpine:/home/anders/lima$ sudo apk add apptainer
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.18/community/x86_64/APKINDEX.tar.gz
ERROR: unable to select packages:
  apptainer (no such package):
    required by: world[apptainer]

lima-alpine:/home/anders/lima$ sudo setup-timezone -z UTC
lima-alpine:/home/anders/lima$ ls -l /etc/localtime
lrwxrwxrwx    1 root     root            17 Jan  3 08:02 /etc/localtime -> /etc/zoneinfo/UTC
lima-alpine:/home/anders/lima$ echo "https://dl-cdn.alpinelinux.org/alpine/edge/community" | sudo tee -a /etc/apk/repositories 
https://dl-cdn.alpinelinux.org/alpine/edge/community
lima-alpine:/home/anders/lima$ sudo apk add apptainer squashfuse fuse2fs gocryptfs
fetch https://dl-cdn.alpinelinux.org/alpine/edge/community/x86_64/APKINDEX.tar.gz
(1/10) Installing fakeroot (1.31-r2)
(2/10) Installing lz4-libs (1.9.4-r4)
(3/10) Installing lzo (2.10-r5)
(4/10) Installing squashfs-tools (4.6.1-r1)
(5/10) Installing libseccomp (2.5.4-r2)
(6/10) Installing apptainer (1.2.5-r0)
(7/10) Installing fuse (2.9.9-r4)
(8/10) Installing fuse2fs (1.47.0-r2)
(9/10) Installing gocryptfs (2.4.0-r4)
(10/10) Installing squashfuse (0.5.0-r0)
Executing busybox-1.36.1-r2.trigger
Executing eudev-3.2.11-r8.trigger
OK: 111 MiB in 97 packages

lima-alpine:/home/anders/lima$ apptainer --version
apptainer version 1.2.5
lima-alpine:/home/anders/lima$ apptainer run docker://ghcr.io/apptainer/lolcow
INFO:    Converting OCI blobs to SIF format
INFO:    Starting build...
Getting image source signatures
Copying blob 16ec32c2132b done  
Copying blob 5ca731fc36c2 done  
Copying config fd0daa4d89 done  
Writing manifest to image destination
Storing signatures
2024/01/03 08:06:45  info unpack layer: sha256:16ec32c2132b43494832a05f2b02f7a822479f8250c173d0ab27b3de78b2f058
2024/01/03 08:06:46  info unpack layer: sha256:5ca731fc36c28789c5ddc3216563e8bfca2ab3ea10347e07554ebba1c953242e
INFO:    Creating SIF file...
INFO:    underlay of /etc/localtime required more than 50 (77) bind mounts
 _____________________________
< Wed Jan 3 08:06:54 UTC 2024 >
 -----------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```

Actually, "tzdata" was not required for UTC timezone.
(the `/etc/zoneinfo/UTC` file is provided by alpine default)

But `/etc/timezone` is not required by libc, UTC is default.
So it is only apptainer that requires this file to be present.

```
INFO:    underlay of /etc/localtime required more than 50 (77) bind mounts
```

**Comment by OTLabs** [comment]
Looks good! I assume you can try to drop `squashfs` from `sudo apk add apptainer squashfuse fuse2fs gocryptfs`, as kernel has a built-in support for it.

**Comment by afbjorklund** [comment]
I'm not so sure:

```
INFO:    squashfuse not found, will not be able to mount SIF
FATAL:   container creation failed: mount hook function failure: mount /proc/self/fd/3->/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3: squashfuse not found
```

I think it only works for `apptainer-suid`?

**Comment by OTLabs** [comment]
Oh, I see. Yeah.
