### ISSUE TITLE
Make sure documentation matches behavior of binding $PWD

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#742]
I see a few places in the user guide that mention that `$PWD` is bound in to the container by default.  However, it is my observation that it is not bound in if the bind point does not already exist in the container.  For example if I am in a directory `/scratch/tmp` when I start and there's no `/scratch` in the container, it moves my directory to $HOME and does not bind in `/scratch/tmp`.

I tested previous versions and see this behavior has been happening since singularity-3.6.0.  I suspect it's related to this in the 3.6.0 release announcement:
```
- Restored the CWD mount behaviour of v2, implying that CWD path is not recreated inside container and any symlinks in the CWD path are not resolved anymore to determine the destination path inside container.
```
which describes changes in apptainer/singularity#5114.  This may have been unintended consequences and a bug, but if it is intended then the documentation should be updated.

Investigate this along with #547 which appears to be another bug related to the same change and/or its successors.

**Comment by grisuthedragon** [comment]
We struggled around this problem as well when running apptainer inside a CI runner on gitlab. There everything lives and works inside '/builds'. For a better user experience, it would be nice if the pwd/cwd mount works again as described at the moment (but not implemented). 

At the moment (apptainer 1.1.3) we get the following debug messages:
```
VERBOSE: Not mounting CWD, /builds/ci-images/apptainer/demo doesn't exist within container
VERBOSE: Not mounting CWD, while getting /builds/ci-images/apptainer/demo information: stat /usr/local/apptainer/var/apptainer/mnt/session/final/builds/ci-images/apptainer/demo: no such file or directory
```
Beside fixing the documentation, we need an option to create the mount points in the container.

**Comment by ashwin-nayak** [comment]
The current solution for working with apptainer deployed through CI was to unset the `APPTAINER_BIND` during build and then to set `APPTAINER_BIND` specifically to `$PWD` during `exec`/`run` processes. 

Seems rather hacky and would love a different solution to this!

**Comment by DrDaveD** [comment]
See related problem in #1143
