### ISSUE TITLE
Add instructions in INSTALL.md to filter E2E tests to run

### ISSUE THREAD

**Issue by cclerget** [apptainer/apptainer#743]
By example, to run only e2e tests in ACTIONS group:

```
./scripts/e2e-test -v -run TestE2E/PAR/ACTIONS
```

To run sequential tests only:

```
./scripts/e2e-test -v -run TestE2E/SEQ
```

**Comment by DrDaveD** [comment]
And if you see errors about missing buildcfg variables, do
```
make -C builddir $PWD/internal/pkg/buildcfg/config.go
```

**Comment by DrDaveD** [comment]
This was created quite a while ago and not yet done, but if I recall correctly, the existence of this ability was the reason why @cclerget thought it was unnecessary to import sylabs/singularity#860.
