### ISSUE TITLE
Slow %post I/O performance when using root-mapped namespace (edit: due to fakeroot ruining things)

### ISSUE THREAD

**Issue by Micket** [apptainer/apptainer#744]
### Version of Apptainer

`1.1.0`

### Expected behavior

%post section should run much faster even root-mapped namespace is used.

As an example to demonstrate the performance hit I'm seeing; this tiny recipe is a good example:

```
Bootstrap: docker
From: rockylinux:8.5.20220308

%post
    # Make image writable with overlays (from before --fix-perms existed)
    chmod a+rwX -fR /usr
```

This image is very small; the chmod step take more than a second.
(note: I do see performance hit when doing other stuff in %post as well, but this tiny recipe shows the most extreme scenario)

### Actual behavior

What actually happened? Why was it incorrect?

Building this as recipe as root or with a user with a subuid/gid mapping, it's super fast. Less then a second.

When trying to build relying on root-mapped namespace;
```
[ohmanm@vera2 ~]$ apptainer build test.sif /apps/containers/RockyLinux/RockyLinux-8.5.20220308.def 
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Starting build...
Getting image source signatures
Copying blob 1a930d163dca done  
Copying config 211bb129b4 done  
Writing manifest to image destination
Storing signatures
2022/10/05 16:58:54  info unpack layer: sha256:1a930d163dcafa193dc2c3c005d9c220ae1c07a48cad5f7feed0066ada0b998f
INFO:    Running post scriptlet
+ chmod a+rwX /usr
```
it takes a tremendously long time for such a small image; over 6 minutes. 
Other more complex recipes went from 3 minutes to 24 minutes when relying on root-mapped namespace.

I'm not very familiar with how this stuff works, but i happened to read in the source code that this "root-mapped namespace" was like running through `unshare -r`. So i just tested that explicitly;

```
[non_mapped_user@vera2]$ unshare -r apptainer build test.sif RockyLinux-8.5.20220308.def
```

and that is also really fast!  So, there is something different happening when apptainer does it internally. 
But I can't see where it does wrong
```
VERBOSE [U=156653,P=3556363]preRun()                      Implying --fakeroot because building from Deffile file unprivileged
INFO    [U=156653,P=3556363]fakerootExec()                User not listed in /etc/subuid, trying root-mapped namespace
DEBUG   [U=156653,P=3556363]UnshareRootMapped()           Re-executing to root-mapped unprivileged user namespace
DEBUG   [U=0,P=3556376]    persistentPreRun()            Apptainer version: 1.1.0-1.el8
```
all seems fine to me.

In all cases, if one is really patient, works just fine. I couldn't see any errors or warnings anywhere. 

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

As far as i know, completely standard Rocky 8.5 machine.
Empty /etc/sub{uid,gid}.

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="8.5 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.5"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"
```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.

rpmbuild with provided spec file with modification to build the patched squashfuse_ll.
Only apptainer rpm is installed, no suid stuff.

**Comment by Micket** [comment]
I'm not sure how i missed this throughout my testing; but it just noticed all the fast builds did *not* use fakeroot. The slow %post always occured always when

```
INFO:    The %post section will be run under fakeroot
```

I wonder; why the different treatment between a user with a maping in subuid/gid vs a user relying on root-mapped namespace?
As long as you have a namespace, should that be able to handle %post section just as well without fakeroot? Isn't that the primary reason to use these namespaces to begin with?

Since there was no flag or option to disable fakeroot at runtime, but i did a quick and (very) dirty test; i hid /bin/fakeroot to prevent apptainer from auto-enabling it, and indeed performance was great again!
This also explains my success with `unshare -r apptainer build test.sif test.def`; it tricked apptainer into thinking i was already root thus no need for fakeroot.

**Comment by DrDaveD** [comment]
Thank you for the report!  I hadn't noticed but indeed a recursive chmod is an extremely slow operation under the fakeroot command.

We could submit a report to the fakeroot project but I'm not sure if anything can be done about it.  I ran 'top' during the operation and see the `faked` process running.  I believe that for each file the fakeroot command is communicating with the `faked` process for some reason.  I guess it is so a later `stat` call will return the permissions that have been changed-to on a file even if the user did not actually have permission to change it.  That would make sense.

Hopefully there won't be many people trying to do recursive ch* commands during their builds.  A more selective `find`-based command with `xargs` works a lot more efficiently, although unfortunately xargs is not installed by default on el8 and so it needs to be installed first:
```
dnf install -y /usr/bin/xargs
find /usr -type d ! -perm -200|xargs chmod u+w
```

> I wonder; why the different treatment between a user with a mapping in subuid/gid vs a user relying on root-mapped namespace?
> As long as you have a namespace, should that be able to handle %post section just as well without fakeroot? Isn't that the primary reason to use these namespaces to begin with?

The reason for using the fakeroot command is for things that attempt to do operations that will fail without the additional user ids provided with `/etc/sub[ug]id` mapping, such as chown.  For example installing the package `openssh`.

> Since there was no flag or option to disable fakeroot at runtime, 

Actually, there is a hidden `--ignore-fakeroot-command` option.

**Comment by Micket** [comment]
> The reason for using the fakeroot command is for things that attempt to do operations that will fail without the additional user ids provided with /etc/sub[ug]id mapping, such as chown. For example installing the package openssh.

I see. Thank you for explaining, it's very helpful because I've been very lost here. To be honest, i'm still very lost!
I've tried to read up on what "root-mapped namespace" is exactly, and to me understanding it's basically as if one had set up only 1 mapping; UID -> 0?
And, if fakeroot is used anyway, what's the need for the namespace?

I'm also very confused by an error message if one tries to map fewer than 65k uids;
```
FATAL:   could not use fakeroot: mapping entries...
```
so, providing the mapping one is still using fakeroot? Or is this some other type of fakeroot then? Because the performance is completely different.


-----

I don't actually need to do this these big recursive chmod anymore, since it looks like `--fix-perms` will just take care that. But i did use it to basically change permissions for basically every file, to allow the overlay to do whatever it wants.

I also saw this come up when unpacking tarballs. I just tested a software with a 1.2GB, ~26800 file (which isn't very much at all) tarball which ends up taking 20 minutes compared to ~1m if sub[ug]id's are mapped or if `--owner=0 --group=0 --no-same-owner --no-same-permissions` tar flags are specified.

But turns out that this is a known issue for 10 years now!
https://bugs.mageia.org/show_bug.cgi?id=340
here they seem to indicate that --with-icp=tcp is a source of slowdown. Aha, finally a lead!

I see EPEL provides fakeroot, fakeroot-sysv, fakeroot-tcp. 
```
[ohmanm@vera2 tmp]$ time fakeroot-sysv tar xf /apps/sources/d/DIANA/dianaLinux-10.5.tar.gz 

real	0m23.739s
user	0m22.464s
sys	0m6.119s
[ohmanm@vera2 tmp]$ time fakeroot-tcp tar xf /apps/sources/d/DIANA/dianaLinux-10.5.tar.gz 

real	0m49.777s
user	0m22.133s
sys	0m6.095s
[ohmanm@vera2 tmp]$ time fakeroot tar xf /apps/sources/d/DIANA/dianaLinux-10.5.tar.gz 

real	0m49.460s   <-- looks like it's defaulting to tcp!
user	0m21.946s
sys	0m6.094s
```
so...
```
# update-alternatives --list
...
fakeroot                auto    /usr/bin/fakeroot-tcp
```
Oh!!!
```
# update-alternatives --set fakeroot /usr/bin/fakeroot-sysv
```
and lets give it another try
```
[ohmanm@vera2 ~]$ time apptainer build test.sif test.def
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Starting build...
Getting image source signatures
Copying blob 1a930d163dca skipped: already exists  
Copying config 211bb129b4 done  
Writing manifest to image destination
Storing signatures
2022/10/06 03:56:29  info unpack layer: sha256:1a930d163dcafa193dc2c3c005d9c220ae1c07a48cad5f7feed0066ada0b998f
INFO:    Running post scriptlet
+ chmod a+rwX -fR /boot /bin /sbin /lib /lib32 /lib64 /usr /etc /var /opt
+ :
INFO:    Adding help info
INFO:    Creating SIF file...
INFO:    Build complete: test.sif

real	0m8.008s
user	0m44.763s
sys	0m1.781s
```
Bingo! Back to full speed! Hooray! Staying up til 4:00 AM payed off for once.

**Comment by DrDaveD** [comment]
> I've tried to read up on what "root-mapped namespace" is exactly, and to me understanding it's basically as if one had set up only 1 mapping; UID -> 0?

That's correct.

> And, if fakeroot is used anyway, what's the need for the namespace?

The root-mapped namespace simulates root a little closer, such as allowing overriding some permissions on your own files.  For example if you had a directory mode 555 you wouldn't be able to write to it yourself but under `unshare -r` you can. 

> so, providing the mapping one is still using fakeroot? 

Yes, it's a different type of fakeroot.  https://apptainer.org/docs/user/main/fakeroot.html has the details.

Regarding the performance difference with fakeroot-sysv, that's good to know, but I'm not convinced that it's worth documenting.  Perhaps it is, but it's one more complication for people.  It might be better to try to convince the EPEL provider to switch the default.  The default is fakeroot-sysv on Debian.  I could probably change apptainer to prefer fakeroot-sysv regardless of the alternatives setting.

**Comment by DrDaveD** [comment]
Changed in #763.
