### ISSUE TITLE
Segfault when running SLC6 images on Debian 11

### ISSUE THREAD

**Issue by pavel-demin** [apptainer/apptainer#749]
### Version of Apptainer

```
apptainer version 1.1.0
```

### Expected behavior

I expect apptainer to run Scientific Linux 6 images on Debian 11.

### Actual behavior

apptainer segfaults.

```
$ apptainer -d exec cmssw_5_3_32 bash
...
DEBUG   [U=1001,P=75042]   Master()                      Child exited due to signal 11
Segmentation fault
```

### Steps to reproduce this behavior

I use the following commands to reproduce the problem on Debian 11:
```
apptainer build cmssw_5_3_32 docker://cmsopendata/cmssw_5_3_32-slc6_amd64_gcc472
apptainer -d exec cmssw_5_3_32 bash
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### How did you install Apptainer

```
wget https://github.com/apptainer/apptainer/releases/download/v1.1.0/apptainer_1.1.0_amd64.deb
apt-get install ./apptainer_1.1.0_amd64.deb
```

**Comment by pavel-demin** [comment]
I think that to reproduce the problem the host system (the one providing the kernel) should be Debian 11 and not SL7. I have no problem running the same SLC6 image on SL7. The segfault occurs when the host system is Debian 11.

I have just installed a virtual machine with Debian 11 following the instructions at [this link](http://pavel-demin.github.io/red-pitaya-notes/development-machine) and I can reproduce the problem on this virtual machine. Besides, `apptainer build` is extremely slow when running on this virtual machine.

**Comment by pavel-demin** [comment]
I have found a solution to this problem in the apptainer documentation:

https://apptainer.org/user-docs/2.5/troubleshooting.html#segfault-on-bootstrap-of-centos-image

So this is a known issue with a known workaround.

**Comment by DrDaveD** [comment]
Oh, cool, I was unaware of that.  For some reason it dropped out of the current documentation.  It looks like it was not carried forward from singularity-2 to singularity-3 documentation.
