### ISSUE TITLE
symbol lookup error: singularity: undefined symbol: seccomp_notify_respond

### ISSUE THREAD

**Issue by prehensilecode** [apptainer/apptainer#754]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
singularity: symbol lookup error: singularity: undefined symbol: seccomp_notify_respond
```

Installed via EPEL: `apptainer-1.1.0-1.el8.x86_64`

### Expected behavior

What did you expect to see when you do...?

Expected version string to be printed.

### Actual behavior

What actually happened? Why was it incorrect?

`apptainer` threw an error about a missing symbol. No version string produced.

### Steps to reproduce this behavior

How can others reproduce this issue/problem?

Just do: `apptainer --version`

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.1 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.1"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.1 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.1:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.1
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.1"

```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.

RPM via EPEL: `apptainer-1.1.0-1.el8.x86_64`

**Comment by DrDaveD** [comment]
I bet the epel build machine was on a newer version of rhel8 than 8.1 so it doesn't support such an old version.  The current version is 8.6.  Can you upgrade?  Otherwise I'm afraid you'll need to install from source.

**Comment by prehensilecode** [comment]
Sorry: upgrading is not feasible. This is on an HPC cluster with dependencies on vendor-specific OFED (InfiniBand) drivers, among other things.

**Comment by DrDaveD** [comment]
Well it's worth a try to see if the binary in the [1.1.0 release assets](https://github.com/apptainer/apptainer/releases/tag/v1.1.0) will work.  Otherwise follow the instructions to [install from source](https://github.com/apptainer/apptainer/blob/main/INSTALL.md).

**Comment by prehensilecode** [comment]
Can the package then specify version numbers of dependencies, maybe libseccomp (plus others)? In RHEL 8.1, it is libseccomp 2.4.1-1.el8. This would avoid people unwittingly installing something that will not work.

**Comment by DrDaveD** [comment]
I'm afraid I don't know how to specify in an rpm spec file how to require at least the version on the build machine.

**Comment by prehensilecode** [comment]
https://rpm-software-management.github.io/rpm/manual/dependencies.html

**Comment by DrDaveD** [comment]
Do you see something there that says Require whatever version is currently installed?  I don't see it.

**Comment by prehensilecode** [comment]
I meant, require a specific version of a dependency, and if that version is not already install, fail.

So, in the current [apptainer.spec.in](https://github.com/apptainer/apptainer/blob/main/dist/rpm/apptainer.spec.in), it only does

```
BuildRequires: libseccomp-devel
```

with no version number. I suggest you do a ">= something" where "something" is replaced by the version you have in your build system. 

And, add a similar "Requires" line with "libseccomp >= something". So, if an OS does not have an appropriate version of libseccomp (which RHEL 8.1 does not), the installation would fail. Because I assume that if you needed libseccomp-devel for the build, you would need libseccomp for execution.

For distribution via RPM in EPEL (or any other widely used repo), if it installs, it should run. However it does install, but it doesn't run.

**Comment by DrDaveD** [comment]
The problem with that though is that it would be a one-time fix and then forgotten.  It wouldn't be a permanent solution to this type of problem.

**Comment by prehensilecode** [comment]
Can you clarify what type of problem this is?

It seems to be a packaging issue. The (built) package requires a set of dependencies, each with a minimum version. It seems to be a common thing, where one package says, e.g. (completely made up) httpd requires OpenSSL >= 1.1.5 so if the system has only OpenSSL 1.0.x the package would not install.

This is already done with many packages. I can't upgrade, say, httpd because I do not have the appropriate version of OpenSSL that is required. I am proposing that the Apptainer RPM also specify minimum versions of its dependencies. At least, specify the versions used to build the RPM. In that way, when one upgrades apptainer, `dnf/yum` will not apply the upgrade because the system lacks appropriate versions of the dependencies.

Currently, the upgrade succeeds giving no indication that a "broken" version of apptainer has been installed, "broken" in the sense that it cannot run because the system does not have a new enough version of `libseccomp`. 

What negative effect would there be to specifying `libseccomp >= something` where "something" is the version used on the build system?

**Comment by DrDaveD** [comment]
It's one thing if a package inherently requires a specific version of a package because of some feature, and something different if the requirement is coming from a build system.

I see two potential issues with coding a specific version number in the rpm:
1. If someone were to build from source again on a different build system, a different version of libseccomp will work.  That's probably the case for you, if you were to build the rpm again from source on your 8.1 machine.
2. The build system is a moving target.  Next week the libseccomp might be updated again and cause it to not work on any older system than that version, and making the specific version number listed in the .spec file incorrect for that build.  I don't have any control over what package versions are available on the EPEL build system.

I think this may be an inherent limitation of RPM.  Debian doesn't have this problem.

The rpm built on github is made on centos7, so it probably will work on your 8.1 machine since it is older.  It would be good to know if that is the case.
