### ISSUE TITLE
`--overlay` with ext3 format image file fails with apptainer >=1.1.0

### ISSUE THREAD

**Issue by wresch** [apptainer/apptainer#757]
### Version of Apptainer

apptainer version 1.1.2

but we observed the same issue with 1.1.0. 1.0.1 and current singularityCE versions (3.10.3) did not experience this issue.

### Expected behavior / Actual behaviour / Steps to reproduce

```console
$ wget https://hpc.nih.gov/~wresch/test.img
$ apptainer --version
apptainer version 1.0.1
$ apptainer exec docker://debian which java
$ apptainer exec --overlay test.img docker://debian which java
/usr/bin/java
$ module load apptainer/1.1.2
$ apptainer --version
apptainer version 1.1.2
> apptainer exec --overlay test.img docker://debian which java
FATAL:   container creation failed: hook function for tag prelayer returns error: setup of overlay upper dir failed: /var/apptainer/mnt/session/overlay-images/0/upper is not writable: permission denied
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

same behavior on rocky 8.5

### How did you install Apptainer

compiled from source tarball
```sh
tar -xzf apptainer-1.1.2.tar.gz
cd apptainer-1.1.2
./mconfig \
    --with-suid \
    --prefix=${APPDIR} \
    --localstatedir=/var
make -C builddir && sudo make -C builddir install
```
gcc 9.2.0
golang 18.1.0
we don't enable user namespaces and the only config change we make is turning off pid namespaces

**Comment by DrDaveD** [comment]
Try it with [--overlay test.img:ro](https://apptainer.org/docs/user/1.1/persistent_overlays.html#fakeroot-with-overlay).  If you just use --overlay it now assumes that you might want to write to it, in which case you'll need [--fakeroot](https://apptainer.org/docs/user/1.1/persistent_overlays.html#fakeroot-with-overlay) in order to do anything useful.

**Comment by wresch** [comment]
That works. Sorry about not realizing one could specify `:ro` and opening an issue. Thanks alot.

**Comment by DrDaveD** [comment]
That error message could be improved to suggest using `:ro` or `--fakeroot`.  Reopening to track that.

**Comment by DrDaveD** [comment]
Or maybe better would be to continue with a warning if it is not writable rather than failing
