### ISSUE TITLE
Installation on /cvmfs/oasis.opensciencegrid.org isn't portable

### ISSUE THREAD

**Issue by chrisburr** [apptainer/apptainer#764]
(Apologies if this is the wrong place to report.)

In https://github.com/apptainer/apptainer/issues/760#issuecomment-1274143403 I noticed that the installation on /cvmfs/oasis.opensciencegrid.org doesn't work on my machine:

```bash
$ /cvmfs/oasis.opensciencegrid.org/mis/apptainer/1.0.3/bin/apptainer
/cvmfs/oasis.opensciencegrid.org/mis/apptainer/1.0.3/bin/apptainer: line 8: arch: command not found
/cvmfs/oasis.opensciencegrid.org/mis/apptainer/1.0.3/bin/apptainer: cannot determine arch
```

I'd suggest using `uname -m` instead (I've also included a handful of minor fixes that [`shellcheck`](shellcheck) suggests):

```bash
#!/bin/sh
# Written by Dave Dykstra

HERE="$(cd "${0%/*}" && /bin/pwd)"
PARENT="${HERE%/*}"
APPTVERSION="${PARENT##*/}"
BASEPATH="${PARENT%/*}"
ARCH="$(uname -m)"
if [ -z "$ARCH" ]; then
    echo "$0: cannot determine arch" 2>&1
    exit 1
fi
APPTDIR="$BASEPATH/$ARCH/$APPTVERSION"
if [ ! -d "$APPTDIR" ]; then
    echo "$0: $APPTDIR not found" 2>&1
    exit 1
fi
exec "$APPTDIR/bin/apptainer" "$@"
```

As your name is in this file, cc @DrDaveD

**Comment by DrDaveD** [comment]
Yeah this isn't a good place for that.  I guess the OSG JIRA would make the most sense, and I don't have those scripts in github anywhere at this point.  I updated the one for apptainer-1.1.2 with your suggestions, though.
