### ISSUE TITLE
will container encrypted pem path capture by some monitor thread?

### ISSUE THREAD

**Issue by Broderick890** [apptainer/apptainer#765]
Hi,the encrypted container  is great! I want deploy the system to the client. But I am worry about some monitor thread will capture the pem path when decrypted the container. Will it take place? Thank you very match!

**Comment by DrDaveD** [comment]
What do you mean by "monitor thread"?

**Comment by DrDaveD** [comment]
I am not aware of any such monitoring tools.  Does that answer your question?
