### ISSUE TITLE
cannot run with user namespace, fuse error

### ISSUE THREAD

**Issue by LaHaine** [apptainer/apptainer#778]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).
`apptainer version 1.1.2-1.el7`

### Expected behavior
It should run the container
### Actual behavior
Error message:
`
FATAL:   container creation failed: mount /proc/self/fd/3->/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3: squashfuse_ll exited with status 1: fuse: failed to exec fusermount3: No such file or directory
`
After installing fuse3 package, the error has changed:
`
FATAL:   container creation failed: mount /proc/self/fd/3->/var/apptainer/mnt/session/rootfs error: while mounting image /proc/self/fd/3: squashfuse_ll exited with status 1: fusermount3: mount failed: Operation not permitted
`

### Steps to reproduce this behavior

How can others reproduce this issue/problem?
Run this command as a unprivileged user:
`
singularity exec --userns docker://debian hostname
`
The system has SELinux enabled.
### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Scientific Linux"
VERSION="7.9 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.9"
PRETTY_NAME="Scientific Linux 7.9 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.9:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"

```

### How did you install Apptainer

Write here how you installed Apptainer (or Singularity). Eg. RPM, source.
RPM from EPEL-testing

**Comment by LaHaine** [comment]
[apptainer-debug.txt](https://github.com/apptainer/apptainer/files/9775974/apptainer-debug.txt)
By the way, with --unsquash option, it is working fine.

**Comment by LaHaine** [comment]
It was caused by the older Kernel version 3.10.0-1062.1.2.el7.x86_64. With 
3.10.0-1160.76.1.el7.x86_64, everything works fine.

A better error message would be nice though.

**Comment by DrDaveD** [comment]
That's a tough one to figure out when to show a different message, short of looking up the kernel version and parsing the version number.  I'm not sure we want to go there.  The record of this issue should help people find out what to do.  The [admin guide](https://apptainer.org/docs/admin/main/installation.html#system-requirements) lists the system requirements.

It's very odd that the O.S. was 7.9 and yet the kernel was that old.  That kernel version came with 7.8.

**Comment by DrDaveD** [comment]
On the other hand, I could have it parse the error message looking for "fusermount".  That will only happen when the kernel is too old.
