### ISSUE TITLE
` /.singularity.d/libs/faked: not found` on basic Linux base images

### ISSUE THREAD

**Issue by multimeric** [apptainer/apptainer#783]
### Version of Apptainer

1.1.0

### Expected behavior

The `%post` script to run without error.

### Actual behavior

```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
INFO:    Starting build...
Getting image source signatures
Copying blob 89f7571df241 skipped: already exists
Copying config 4c80aca018 done
Writing manifest to image destination
Storing signatures
2022/10/14 13:43:25  info unpack layer: sha256:89f7571df2412a90204607fca55a41d4a0ead0ac428005a72b6a821d74d362ca
INFO:    Running post scriptlet
/.singularity.d/libs/fakeroot: eval: line 140: /.singularity.d/libs/faked: not found
fakeroot: error while starting the `faked' daemon.
sh: you need to specify whom to kill
FATAL:   While performing build: while running engine: exit status 1
```

What actually happened? Why was it incorrect?

### Steps to reproduce this behavior

Create an `error.def` with the following contents:
```
Bootstrap: docker
From: busybox:1.35.0
%post
    echo "Hello"
```

Then `apptainer build error.cif error.def`

### What OS/distro are you running

```sh
$ CentOS Linux 7
```

### How did you install Apptainer

As an environment module.

### Discussion

Notably this happens when the base image is `busybox`, or `alpine`, but not `ubuntu`. I guess this error only happens when using "simple" Linux distros that are missing certain features?

**Comment by glm729** [comment]
I am also seeing this, with Apptainer version 1.1.2 running inside an Alpine
Linux image, which itself is running in Apptainer version 1.1.0.  It looks like
I'm running into a different error, as the error code is 255, not 1, but I'm not
sure if the `sh` error in your case is masking the error I'm running into.


```
$ apptainer exec sandbox/alpine_apptainer/ apptainer build --fakeroot --fix-perms --sandbox TEST_alpine/ def/alpine.def
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 213ec9aee27d skipped: already exists
Copying config 29f453b10b done
Writing manifest to image destination
Storing signatures
2022/10/14 15:33:58  info unpack layer: sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49
WARNING: The --fix-perms option modifies the filesystem permissions on the resulting container.
INFO:    Running post scriptlet
FATAL:   container creation failed: mount /.singularity.d/libs/faked->/usr/local/var/apptainer/mnt/session/libs/faked error: while mounting /.singularity.d/libs/faked: mount source /.singularity.d/libs/faked doesn't exist
FATAL:   While performing build: while running engine: exit status 255
```


I tried to install all of the requirements for running Apptainer in Alpine, but
I have probably missed something.  I could also try this with another base image
(e.g. Ubuntu), but it also gives the same error (from memory!) with an Arch
Linux-based setup, but again, I have probably missed a dependency or so.


----


<details>
  <summary>Alpine Apptainer def file</summary>

  ```
  # -*- mode: sh; -*-
  # vim: ft=sh sw=2
  Bootstrap: docker
  From: alpine:3.16

  %post

    # ---- Set variables for installations ----

    _INST_DIR="$(mktemp -d)"

    _A_VERSION='v1.1.2'
    _A_URL='https://github.com/apptainer/apptainer.git'

    # ---- Install general system packages ----

    apk update
    apk upgrade --no-cache

    apk add --no-cache --virtual=alpine_apptainer__general \
      bash \
      bash-completion \
      coreutils \
      curl \
      diffutils \
      file \
      gawk \
      git \
      go \
      gzip \
      less \
      libtool \
      make \
      perl \
      pigz \
      vim \
      wget \
      xz \
      zip \
      zlib

    # ---- Install Apptainer-specific requirements ----

    apk add --no-cache --virtual=alpine_apptainer__depends \
      cryptsetup \
      fakeroot \
      fuse-overlayfs \
      libc-dev \
      libseccomp-dev \
      libressl-dev \
      libuuid \
      linux-headers \
      squashfs-tools \
      util-linux-dev

    # ---- Clone, build, and install Apptainer ----

    cd "$_INST_DIR"

    git clone "$_A_URL"

    cd apptainer

    git checkout "$_A_VERSION"

    ./mconfig --prefix=/usr/local

    cd ./builddir

    make -j $(nproc)

    make install -j $(nproc)

    # ---- Clean up ----

    cd "$APPTAINER_ROOTFS"

    rm -rf "$_INST_DIR"
  ```
</details>

**Comment by glm729** [comment]
Slightly different error message for a Rocky Linux-based image, after installing the dependencies for CentOS/RHEL as shown in [INSTALL.md](https://github.com/apptainer/apptainer/blob/main/INSTALL.md#install-system-dependencies):

```
$ apptainer exec sif/rocky_apptainer.sif apptainer build --fakeroot --fix-perms --sandbox TEST_alpine/ def/alpine.def
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob 213ec9aee27d skipped: already exists
Copying config 29f453b10b done
Writing manifest to image destination
Storing signatures
2022/10/14 17:35:50  info unpack layer: sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49
WARNING: The --fix-perms option modifies the filesystem permissions on the resulting container.
INFO:    Running post scriptlet
FATAL:   exec /.singularity.d/libs/fakeroot failed: a shared library is likely missing in the image
FATAL:   While performing build: while running engine: exit status 255
```

**Comment by DrDaveD** [comment]
No solutions yet, but some observations.

A simpler reproducer for the original problem:
```
apptainer shell -f docker://busybox:1.35.0
```
which ends in
```
INFO:    Using fakeroot command combined with root-mapped namespace
/.singularity.d/libs/fakeroot: eval: line 140: /.singularity.d/libs/faked: not found
fakeroot: error while starting the `faked' daemon.
sh: you need to specify whom to kill
```

@glm729 I can successfully do something similar to your second case, if building something based on centos7 instead of alpine (with the outer container being rockylinux with apptainer installed from epel).  So both of your cases seem to have to do with alpine.

**Comment by DrDaveD** [comment]
No solutions, but some observations and a suggestion for debugging.

A simpler reproducer for the original problem:
```
apptainer shell -f docker://busybox:1.35.0
```
which ends in
```
INFO:    Using fakeroot command combined with root-mapped namespace
/.singularity.d/libs/fakeroot: eval: line 140: /.singularity.d/libs/faked: not found
fakeroot: error while starting the `faked' daemon.
sh: you need to specify whom to kill
```

@glm729 I can successfully do something similar to your second case, if building something based on centos7 instead of alpine (with the outer container being rockylinux with apptainer installed from epel).  So both of your cases seem to have to do with alpine.

I'm not going to be able to look into this soon, but I suggest you try building apptainer with this patch to help you debug it:
```
diff --git a/internal/pkg/runtime/engine/apptainer/process_linux.go b/internal/p
index d48a8ea..aaba8eb 100644
--- a/internal/pkg/runtime/engine/apptainer/process_linux.go
+++ b/internal/pkg/runtime/engine/apptainer/process_linux.go
@@ -895,7 +895,8 @@ func runActionScript(engineConfig *apptainerConfig.EngineCon
        if err == nil && getEnvVal(penv, "FAKEROOTKEY") == "" {
                // fakeroot command exists but we're not running nested
                sylog.Verbosef("Running command with %v", filepath.Base(fakeroot
-               args = append(fakeargs, args...)
+               sylog.Infof("NOT running with %v", fakeargs)
+               // args = append(fakeargs, args...)

                // Without this workaround fakeroot does not work
                //  properly in a user namespace. It is especially
```

**Comment by glm729** [comment]
@DrDaveD Can confirm that building a Rocky Linux image within a Rocky Linux image completes successfully!  However, building the same Rocky Linux image fails if using the Alpine image as the outer image, showing the first error message I added here.  I'm not sure what this means, overall.  An interim solution for me is to switch the base images to Rocky Linux, rather than Alpine, with their corresponding package handling changes.


----


Passed with this:

```bash
$ apptainer exec sif/rocky_apptainer.sif apptainer build --fakeroot --fix-perms --sandbox TEST_rocky/ def/rocky.def
```

and failed with this:

```bash
$ apptainer exec sif/alpine_apptainer.sif apptainer build --fakeroot --fix-perms --sandbox TEST_rocky/ def/rocky.def
```

Base Rocky def file:

```
Bootstrap: docker
From: rockylinux:9.0

%post
  dnf update -y
```

**Comment by DrDaveD** [comment]
(I'm sorry, I just noticed that the patch I posted was cut off on the right. I updated the comment to fix it).

Ok but it would still be good if you could figure out what is happening in alpine.  It's a lot smaller than rockylinux.

**Comment by glm729** [comment]
Absolutely, I will give that a shot today.  And indeed the images are
significantly different in size, the Rocky Linux SIF is at least double the size
of the Alpine image.

I'll add that patch and rebuild -- should this be rebuilt in the outer image /
host system, or within the Apptainer image being used to run the nested
Apptainer?

**Comment by glm729** [comment]
@DrDaveD I gave the patch a shot -- I prepared a sandbox of the Alpine image
until just before compiling Apptainer, added the patch, compiled and installed,
then made a SIF.  Unfortunately I am seeing the same problem as before, and
interestingly an attempt to work around the problem (as mentioned [here][t0])
does not work for Alpine:

```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49
Copying config sha256:29f453b10b9d66c8f9d886a82b11008624373954b03e2446eb76b3f065dd1abb
Writing manifest to image destination
Storing signatures
2022/10/18 09:52:50  info unpack layer: sha256:213ec9aee27d8be045c6a92b7eac22c9a64b44558193775a1a7f626352392b49
WARNING: The --fix-perms option modifies the filesystem permissions on the resulting container.
INFO:    Running post scriptlet
FATAL:   container creation failed: mount /.singularity.d/libs/faked->/usr/local/var/apptainer/mnt/session/libs/faked error: while mounting /.singularity.d/libs/faked: mount source /.singularity.d/libs/faked doesn't exist
FATAL:   While performing build: while running engine: exit status 255
```

The error is the same as above when running `exec` without an instance, but
naturally does not mention the instance start and stop.  I note that the info
message added in does not appear -- maybe something else is failing before it
reaches this?


Command run:

```bash
apptainer exec \
    --bind="$_PRJDIR/sif:/data/sif:rw" \
    --bind="$_PRJDIR/def:/data/def:ro" \
    "$_PRJDIR/sif/alpine_apptainer__test.sif" \
    apptainer build \
        --fakeroot --fix-perms \
        /data/sif/alpine_test.sif \
        /data/def/alpine_test.def
```


[t0]: https://github.com/apptainer/apptainer/issues/728

**Comment by DrDaveD** [comment]
The patch should be where you use `--fakeroot`.  You should get the new INFO message and it won't actually run fakeroot but tell you what it would have done.  Then you can run the command it gives you by hand and try to figure out where it is going wrong.

**Comment by glm729** [comment]
Hmmm, I may have done something a bit wrong, in that case -- I didn't get the info message, but the build of Apptainer where `--fakeroot` is used is built with the patch in place.  The output above is what I saw, and it doesn't show the new INFO message.

The SIF was made from the patched sandbox, so that should (in theory) have worked.  Running `apptainer --version` appears to show the patched state:

```
$ apptainer shell alpine_apptainer__test.sif
Apptainer> apptainer --version
apptainer version 1.1.2-dirty
```

I'll double-check the source to make sure that the patch I've applied is in place properly!

**Comment by DrDaveD** [comment]
That comment refers to running a nested apptainer within another apptainer that is using `--fakeroot`, not the other way around that you're doing it.  Anyway, try it with the simpler reproducer I mention in that message of just using it in a single apptainer:
```
apptainer shell --fakeroot docker://busybox:1.35.0
```

**Comment by glm729** [comment]
I should perhaps have clarified before -- I cannot use `sudo` or fakeroot in the outer image on the remote system, hence why I've been attempting to create an environment in which I can do so.  I also have no control over the Apptainer build on the remote system, which is currently version 1.0.3.

I realise my use-cases might be quite different to what @multimeric intended, and apologies for highjacking the thread!  Should I open a separate ticket, or is there nothing more I can test given my restriction on (fake)root access?

**Comment by DrDaveD** [comment]
If unprivileged user namespaces are enabled, there should be no reason why you can't run unprivileged apptainer directly on the host.  fakeroot should work at that level too with apptainer 1.1.0, as long as you have available the necessary dependencies.  Is that the problem, that there's no fakeroot command installed on the host?  You are using sif files, so you apparently at least have squashfuse, right?

**Comment by glm729** [comment]
Fakeroot is not available, and it also looks like squashfuse is not present -- maybe this is the key problem.  The system relies on Slurm and modules for resource allocation and selection, and when loading the module for Apptainer 1.0.3 (the most recent available version) I get nothing for `which squashfuse`.  Conversely, my local machine (for which I have admin) _does_ find a binary for squashfuse, but I installed this via the package manager.  No other module mentioning squashfuse is available to load.

Running computational tasks using the images works fine though, so maybe squashfuse is present but is not in my path (perhaps there's another shell variable or config option?).  I might need to ask the sysadmin(s) about this, as I haven't got read permission for certain directories (e.g. `/usr`) to look for installed software.

**Comment by DrDaveD** [comment]
Yes please ask the system admin to install fakeroot, and probably also fuse2fs and fuse-overlayfs if they are not installed.

squashfuse (actually squashfuse_ll) is most likely installed along with apptainer under libexec/apptainer/bin, since the install from source instructions say to put it there.

**Comment by glm729** [comment]
I think I am not able to ask the admin to install fakeroot and the fuse utils,
so this may be a stopping point for me at the moment.  However, I'm getting set
up with a VM for which I am the administrator, so I can test it in that
environment too (~2 weeks).

In any case, thank you for the help!  I might have pushed the boundaries of
Apptainer's use-cases in ways that should not be tried, but hopefully it might
help someone!

**Comment by DrDaveD** [comment]
There is no need for the fuse package itself, although the libraries are needed.  It is possible to compile the library and fakeroot yourself.  We just don't provide instructions for how to do that, at least not yet.  If fakeroot is in your prefix/libexec/apptainer/bin then that's a convenient place for apptainer to find it.

**Comment by glm729** [comment]
Hmmm, I could have a go and see where it gets me, I should be able to test this
a bit more by the end of this week.  I saw a mention of `LD_PRELOAD` at some
point (probably [here][man0]), related to an Alpine-specific fix, so I should
try that one too.

On a bit of a side note, I also ran into [this problem][tk0] (i.e. identical
error message) when building an openSUSE image from within another openSUSE
image, which was running the Zypper-installed Apptainer (1.1.2-2.1) plus with
fakeroot installed (also via Zypper).


[man0]: https://man.archlinux.org/man/fakeroot.1.en
[tk0]: https://github.com/apptainer/apptainer/issues/603

**Comment by glm729** [comment]
Apologies for the delay!  I got a bit stuck into some other projects, but tried again with getting fuse and fakeroot working in between a few things.

It appears that the sysadmin may have predicted the move!  Building fuse and fakeroot is not possible on the system on which I've been running into the odd problems.  Hopefully the other server will be set up soon, then installing (and accessing) fuse and fakeroot shouldn't be a problem, as I should have admin control of that image.

**Comment by scimerman** [comment]
I can confirm the issue:
if I pull the alpine to our centos 7 machine with command
`singularity build --sandbox --writable-tmpfs --fix-perms --fakeroot --notest alpine-sandbox docker://alpine`
alpine definition

**Comment by scimerman** [comment]
Actually at closer inspection, on the apptainer build on the first command, it ends successfully but when running that container with fakeroot it fails:
```
$ apptainer shell --fakeroot alpine-sandbox/
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    No user namespaces available, using only the fakeroot command
/.singularity.d/libs/fakeroot: eval: line 140: /.singularity.d/libs/faked: not found
fakeroot: error while starting the `faked' daemon.
sh: you need to specify whom to kill
```
and if run under normal user, indeed there is no folder `.singularity.d/` where for centos 7 image there is.

```
$ apptainer shell --fakeroot alpine-sandbox/
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    No user namespaces available, using only the fakeroot command
/.singularity.d/libs/fakeroot: eval: line 140: /.singularity.d/libs/faked: not found
fakeroot: error while starting the `faked' daemon.
sh: you need to specify whom to kill
```

**Comment by scimerman** [comment]
Dear @DrDaveD and everyone, today I have updated apptainer on one of my test machines. From version `1.1.3` to `1.1.4` the latest available for the CentOS 7.9. I noticed that the issue has been resolved:
```
$ apptainer --version
apptainer version 1.1.4-2.el7
$ cat lolcow.def 
Bootstrap: docker
From: alpine:latest

%post
   echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
   apk update
   apk add cowsay

%runscript
   cowsay $(date)

$ apptainer build alpine_lolcow.sif lolcow.def 
INFO:    Starting build...
Getting image source signatures
Copying blob c158987b0551 skipped: already exists  
Copying config 79c58fdfff done  
Writing manifest to image destination
Storing signatures
2023/01/02 17:06:08  info unpack layer: sha256:c158987b05517b6f2c5913f3acef1f2182a32345a304fe357e3ace5fadcad715
INFO:    Running post scriptlet
+ echo http://dl-cdn.alpinelinux.org/alpine/edge/testing
+ apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.17/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
v3.17.0-320-g38723e0931 [https://dl-cdn.alpinelinux.org/alpine/v3.17/main]
v3.17.0-320-g38723e0931 [https://dl-cdn.alpinelinux.org/alpine/v3.17/community]
v3.17.0-2625-g5b9e82f1b2 [http://dl-cdn.alpinelinux.org/alpine/edge/testing]
OK: 23896 distinct packages available
+ apk add cowsay
(1/3) Installing libbz2 (1.0.8-r4)
(2/3) Installing perl (5.36.0-r0)
(3/3) Installing cowsay (3.04-r2)
Executing busybox-1.35.0-r29.trigger
OK: 45 MiB in 18 packages
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete: alpine_lolcow.sif
$ ./alpine_lolcow.sif cowsay Moo
 _____________________________ 
< Mon Jan 2 17:27:04 UTC 2023 >
 ----------------------------- 
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
$
```
:heavy_check_mark:

and also for the connected issue with fakeroot option suggested above
```
$ apptainer exec --fakeroot docker://alpine:latest id
INFO:    Using cached SIF image
uid=0(root) gid=0(root) groups=0(root),65534(nobody)
```
:heavy_check_mark:
Which otherwise still fails on our production machines with version 1.1.3. Now we have a good reason to update our clusters and make our users happy again :wink: 

Regards

**Comment by DrDaveD** [comment]
@scimerman It looks like you may have accidentally have been running on a machine with `/etc/subuid` and unprivileged user namespaces enabled, because I don't see the messages you had before
```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    No user namespaces available, using only the fakeroot command
```
I don't think anything related to this problem changed between 1.1.3 and 1.1.4.

@glm729 You may want to try the new [install-unprivileged.sh script](https://apptainer.org/docs/admin/latest/installation.html#install-unprivileged-from-pre-built-binaries) to install a copy of 1.1.4 with all of its dependencies including fakeroot and squashfuse_ll.

**Comment by scimerman** [comment]
@DrDaveD I checked and indeed I ran on one of the test machines where I had unprivileged user namespaces enabled. Sorry for the false flag.

**Comment by DrDaveD** [comment]
I compiled an apptainer with my suggested patch [above](#issuecomment-1279213080), and it printed
```
INFO:    NOT running with [/.singularity.d/libs/fakeroot -f /.singularity.d/libs/faked -l /.singularity.d/libs/libfakeroot.so]
```
If I run the command by hand I then see the same errors
```
/.singularity.d/libs/fakeroot: eval: line 140: /.singularity.d/libs/faked: not found
fakeroot: error while starting the `faked' daemon.
sh: you need to specify whom to kill
```
Those files do all exist, but doing ldd /.singularity.d/libs/faked shows
```
	/lib64/ld-linux-x86-64.so.2 (0x7fe76d253000)
	libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fe76d253000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fe76d253000)
Error relocating /.singularity.d/libs/faked: __strdup: symbol not found
Error relocating /.singularity.d/libs/faked: __memcpy_chk: symbol not found
Error relocating /.singularity.d/libs/faked: __printf_chk: symbol not found
Error relocating /.singularity.d/libs/faked: __fprintf_chk: symbol not found
```
so this is a case of incompatible libc which the apptainer fakeroot implementation doesn't support.

I spent considerable time trying to see if I could find a workaround.  The gcompat and libc6-compat alpine packages only eliminate the missing `__strdup` symbol, not the others.  There's another [solution](https://github.com/sgerrand/alpine-pkg-glibc) that gives a more complete glibc in alpine for those who need it, but I tried it via two docker containers that look pretty well supported ([frolvad/alpine-glibc](https://hub.docker.com/r/frolvlad/alpine-glibc/) and [jeanblanchard/alpine-glibc](https://hub.docker.com/r/jeanblanchard/alpine-glibc)) but I haven't been able to figure out how to make them work.  They install the glibc library and support tools under /usr/glibc-compat and I see using the command `/usr/glibc-compat/bin/ldd /.singularity.d/libs/faked` that it does resolve the missing symbols, but I can't get it to execute faked using the glibc-compat library.  I must be missing something fundamental in how it's supposed to work.

**Comment by ghbrown** [comment]
I believe @glm729 noted this in their first message, but here is the error when building an Ubuntu image on an Arch Linux host (`apptainer version 1.3.0`).
This result also seems to support the libc conclusion of @DrDaveD in the previous post.

---

Example def file from [docs](https://apptainer.org/docs/user/latest/build_a_container.html):
```
Bootstrap: docker
From: ubuntu:20.04

%post
    apt-get -y update
    apt-get -y install cowsay lolcat

%environment
    export LC_ALL=C
    export PATH=/usr/games:$PATH

%runscript
    date | cowsay | lolcat
```

Result of  `apptainer build lolcow.sif lolcow.def`:
```
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    The %post section will be run under fakeroot
WARNING: 'nodev' mount option set on /tmp, it could be a source of failure during build process
INFO:    Starting build...
Getting image source signatures
Copying blob d4c3c94e5e10 skipped: already exists
Copying config 2abc4dfd83 done   |
Writing manifest to image destination
2024/05/15 21:27:25  info unpack layer: sha256:d4c3c94e5e10ed15503bda7e145a3652ee935c0b2e9de9b5c98df7ec0a0cd925
INFO:    Running post scriptlet
/.singularity.d/libs/faked: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_ABI_DT_RELR' not found (required by /.singularity.d/libs/faked)
/.singularity.d/libs/faked: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /.singularity.d/libs/faked)
/.singularity.d/libs/faked: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/faked)
fakeroot: error while starting the `faked' daemon.
/.singularity.d/libs/fakeroot: 1: kill: Usage: kill [-s sigspec | -signum | -sigspec] [pid | job]... or
kill -l [exitstatus]
FATAL:   While performing build: while running engine: exit status 1
```

**Comment by DrDaveD** [comment]
@ghbrown I'm sorry for the delay in responding, but you ran into a different issue, one that many people trip over.  That's what happens when you use the fakeroot command (because /etc/subuid is not set up) and your host glibc is newer than the one in the container.

In your case and in the other cases discussed here, a workaround for the error can be to add the apptainer option `--ignore-fakeroot-command` to not attempt to bind in the fakeroot command from the host and use it.  This results in some limitations to fakeroot mode, which may or may not be a problem depending on what you're trying to do.  For the simple alpine package install that works:

```
$ cat issue783-alpine-cowsay.def
Bootstrap: docker
From: alpine:latest

%post
   echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories
   apk update
   apk add cowsay

%runscript
    cowsay $(date)
$ apptainer build --ignore-subuid --ignore-fakeroot-command issue783-alpine-cowsay.sif issue783-alpine-cowsay.def
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    fakeroot command not found
INFO:    Installing some packages may fail
INFO:    Starting build...
Copying blob c6a83fedfae6 skipped: already exists
Copying config 0f1ba21672 done   |
Writing manifest to image destination
2024/07/26 09:46:30  info unpack layer: sha256:c6a83fedfae6ed8a4f5f7cbb6a7b6f1c1ec3d86fea8cb9e5ba2e5e6673fde9f6
INFO:    Running post scriptlet
+ echo http://dl-cdn.alpinelinux.org/alpine/edge/testing
+ apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
v3.20.2-19-ga9bc4d9eff9 [https://dl-cdn.alpinelinux.org/alpine/v3.20/main]
v3.20.2-21-g30ed104df72 [https://dl-cdn.alpinelinux.org/alpine/v3.20/community]
v20240606-3484-g93b480bd4b2 [http://dl-cdn.alpinelinux.org/alpine/edge/testing]
OK: 31674 distinct packages available
+ apk add cowsay
(1/3) Installing libbz2 (1.0.8-r6)
(2/3) Installing perl (5.38.2-r0)
(3/3) Installing cowsay (3.04-r2)
Executing busybox-1.36.1-r29.trigger
OK: 48 MiB in 17 packages
INFO:    Adding runscript
INFO:    Creating SIF file...
INFO:    Build complete: issue783-alpine-cowsay.sif
```

However if you try to install squid instead of cowsay, it shows an ERROR (although oddly it does not give a non-zero exit code):

```
$ cat issue783-alpine-squid.def
Bootstrap: docker
From: alpine:latest

%post
   apk update
   apk add squid
$ apptainer build --ignore-subuid --ignore-fakeroot-command issue783-alpine-squid.sif issue783-alpine-squid.def
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    fakeroot command not found
INFO:    Installing some packages may fail
INFO:    Starting build...
Copying blob c6a83fedfae6 skipped: already exists
Copying config 0f1ba21672 done   |
Writing manifest to image destination
2024/07/26 09:51:08  info unpack layer: sha256:c6a83fedfae6ed8a4f5f7cbb6a7b6f1c1ec3d86fea8cb9e5ba2e5e6673fde9f6
INFO:    Running post scriptlet
+ apk update
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
v3.20.2-19-ga9bc4d9eff9 [https://dl-cdn.alpinelinux.org/alpine/v3.20/main]
v3.20.2-21-g30ed104df72 [https://dl-cdn.alpinelinux.org/alpine/v3.20/community]
OK: 24154 distinct packages available
+ apk add squid
(1/7) Installing libacl (2.3.2-r0)
(2/7) Installing popt (1.19-r3)
(3/7) Installing logrotate (3.21.0-r1)
(4/7) Installing libcap2 (2.70-r0)
(5/7) Installing libgcc (13.2.1_git20240309-r0)
(6/7) Installing libstdc++ (13.2.1_git20240309-r0)
(7/7) Installing squid (6.9-r0)
Executing squid-6.9-r0.pre-install
ERROR: 2 errors updating directory permissions
Executing busybox-1.36.1-r29.trigger
OK: 19 MiB in 21 packages
INFO:    Creating SIF file...
INFO:    Build complete: issue783-alpine-squid.sif
```

This error does not occur if you are using /etc/subuid fakeroot.

I *thought* a workaround would be to install the native alpine fakeroot package, but when I try that I still get the same error.  Indeed, if I run an alpine container interactively, the fakeroot command does not seem to do what it is supposed to at all, it gets "Invalid argument" on a chown:

```
$ cat issue783-alpine-squid.def
Bootstrap: docker
From: alpine:latest

%post
    apk update
    apk add fakeroot
    fakeroot sh -c '
        apk add squid
    '
$ apptainer build --ignore-subuid --ignore-fakeroot-command issue783-alpine-squid.sif issue783-alpine-squid.def
...
$ apptainer shell -f --ignore-subuid --ignore-fakeroot-command issue783-alpine-squid.sif
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
INFO:    fakeroot command not found, using only root-mapped namespace
Apptainer> touch /tmp/f1
Apptainer> fakeroot sh -c 'chown bin /tmp/f1; ls -l /tmp/f1'
chown: /tmp/f1: Invalid argument
-rw-r--r--    1 bin      root             0 Jul 26 11:28 /tmp/f1
```

So chown reports an error even though fakeroot did keep track of the requested ownership change.  I need to do some more investigation, because I am seeing similar behavior with a rocky8 container, yet if I let apptainer run the fakeroot command then I can do a chown inside the %post section and it gets no errors.  I don't understand yet what the difference is.

**Comment by DrDaveD** [comment]
Ah, the difference is in [this line of code](https://github.com/apptainer/apptainer/blob/release-1.3/internal/pkg/runtime/engine/apptainer/process_linux.go#L950) which sets the environment variable `FAKEROOTDONTTRYCHOWN=1` to allow fakeroot to run successfully inside user namespaces.

So, the workaround to build for alpine when any package that deals with multiple accounts is to use something like this:
```
$ cat issue783-alpine-squid.def
Bootstrap: docker
From: alpine:latest

%post
    apk update
    apk add fakeroot
    FAKEROOTDONTTRYCHOWN=1 fakeroot sh -c '
        apk add squid
    '
$ apptainer build --ignore-fakeroot-command issue783-alpine-squid.sif issue783-alpine-squid.def
```

I took out the `--ignore-subuid` in this case because I had only been using that in order to test for this issue even though my system has /etc/subuid mapping set up.  The better way around is to avoid the fakeroot command completely and use /etc/subuid if you can.

I don't know if there's anything that needs to be changed in Apptainer in order to make it easier for people to discover this.  Perhaps if there's an error message containing "fakeroot:" when it invokes the fakeroot command it could at least suggest using `--ignore-fakeroot-command`.  Possibly it could also point to a documentation section that explains how to invoke the fakeroot command within a %post section for various OSes.
