### ISSUE TITLE
Unprivileged users can no longer start instances from SIF container files

### ISSUE THREAD

**Issue by epakarin** [apptainer/apptainer#789]
apptainer version 1.1.0-1.el7   on Centos 7.9

This is something that on Singularity worked just fine, unprivileged user 1000:

[units@localhost -] singularity instance start -B/wrk:~/wrkdir container.sif instancename

INFO:    instance started successfully

Unfortunately for some reason at epel, they decided to replace singularity-3.8.7-1.el7 with apptainer, which cannot do this:

[units@localhost -] singularity instance start -B/wrk:~/wrkdir container.sif instancename

ERROR  : Failed to create user namespace: user namespace disabled
                                                              
FATAL:   failed to start instance: while running /usr/libexec/apptainer/bin/starter: exit status 1

No I didn't request a user namespace (with --userns), no kernel features have been disabled, I haven't even booted the machine. The only change is that epel maintainers decided I need to switch to Apptainer. But, it would be really nice to have this feature work again.

**Comment by DrDaveD** [comment]
Apptainer is the new name for singularity, so that's why it has been replaced in epel.

Unlike singularity, apptainer 1.1 is only unprivileged by default.  Please see the [installation instruction docs](https://apptainer.org/docs/admin/main/installation.html).  It needs either unprivileged user namespaces enabled (preferred) or the optional apptainer-suid rpm installed.

**Comment by epakarin** [comment]
That's solid information, thank you. If the apptainer-suid package is the actual equivalent to the old singularity, it might be safer if that were the one selected by default when yum-cron replaces singularity on RHEL 7 hosts.

**Comment by DrDaveD** [comment]
That depends on what you mean by safer.  We believe that [setuid-root is inherently less secure than unprivileged user namespaces](https://apptainer.org/docs/user/main/security.html#setuid-user-namespaces).  That's why we made apptainer be non-setuid root by default.

**Comment by epakarin** [comment]
Yes, and apptainer is free and welcome to make that choice, and its developers aren't accountable to me for the defaults they choose, whatever they may be.

I mean safe choice in the context of maintaining a package for RHEL, where it generally is not desirable for packages marked as updates to introduce wildly different behaviors, e.g. making already running instances unreachable via singularity instance <command>, or breaking scripts that launch or interact with instances.

**Comment by DrDaveD** [comment]
That's true for RHEL but not for EPEL, where apptainer is hosted.

**Comment by epakarin** [comment]
> That's true for RHEL but not for EPEL, where apptainer is hosted.

Cannot agree with that. EPEL policy wrt package updates is

> The packages in the repository should, if possible, be maintained in similar ways to the Enterprise Packages they were built against. In other words: have a mostly stable set of packages that normally do not change at all and only changes if there are good reasons for it — so no "hey, there is a new version, it builds, let’s ship it" mentality. This is the spirit of a stable enterprise environment.

> Some examples of what package updates that are fine or not

> A major version update
> Let’s assume package foo is shipped in EPEL 8 as version 1.0.1; upstream developers now ship 2.0.0; the ABI changes or the config files need manual adjustments
> This update should be avoided if possible at all. If there really is no other way to fix a serious bug then follow the [incompatible upgrades policy](https://docs.fedoraproject.org/en-US/epel/epel-policy-incompatible-upgrades/). In the case of a library package changing soname, consider shipping a compat package that provides the current soname at the same time you ship the new soname.

From that referred policy:

> For other - non-security - incompatible updates, the maintainer MUST NOT push those types of changes. Consider shipping an alternatively named new package (e.g. foo2) to provide the newer version.

And by shipping an alternatively named new package, I'm pretty sure they don't mean automatically replacing an old package with a renamed package that contains considerable and potentially configuration-breaking changes.

Security updates in this case means patches to vulnerabilities that actively compromise systems, not just any update that arbitrarily or generally improves the security of a product.

**Comment by DrDaveD** [comment]
Ok, thanks for pointing that out to me.  I wasn't aware of it.  I'll ask on epel-devel what to do about it.

I think that in practice there has to be additional exceptions.  Progress can't stand still for the entire lifecycle of an EPEL release.

**Comment by DrDaveD** [comment]
I was told to send a belated announcement to epel-announce, which I did.
