### ISSUE TITLE
Suggestions for lima HOME and APPTAINER_HOME

### ISSUE THREAD

**Issue by afbjorklund** [apptainer/apptainer#804]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
1.1.2-1.fc36
```

### Expected behavior

When running `apptainer` over `lima`, there are two different HOME directories involved.

One is on the host, which could be for instance `/Users/anders` or `/home/anders` or so.

Then there is one in the Fedora VM, which is usually something like `/home/anders.linux`

The VM user is the one that stores the `~/.apptainer` directory, with the cache and such.

But the host home directory is mapped (as read-only) using the default remote mounts:

```yaml
mounts:
- location: "~"
- location: "/tmp/lima"
  writable: true
```

See https://github.com/lima-vm/lima#readme

### Actual behavior

Currently I have set `APPTAINER_HOME=$HOME` in the wrapper script calling lima:

```
exec lima APPTAINER_HOME="$HOME" apptainer "$@"
```

Note: "lima" is a small shell wrapper for "limactl shell $LIMA_INSTANCE"

This works well, but has the side effect that the host home is _always_ being used.
So there is no `/home/anders.linux` or `/root` used in the container, only `/home/anders` (r/o)

Should I leave the default HOME as it was, and add the host HOME as a new mount ?
This is how it is being done for docker and podman, but they don't map home by default...

`limactl shell docker docker run -it -v $HOME:$HOME --rm alpine`

`limactl shell podman podman run -it -v $HOME:$HOME --rm docker.io/library/alpine`

The next question is, how _does_ one add an extra bind mount - like `-B $HOME:HOME` ?
Is there some environment variable that can be used - or should one be added perhaps.

`limactl shell apptainer apptainer run -u -B $HOME:$HOME docker://alpine`

----

The main goal is being able to run something like this, from the Mac:

`apptainer run docker://python:alpine python hello.py`

This will actually run a ssh command to the VM, and read the hello.py over reverse-sshfs.

But currently, it has the side effect of using a "strange" (and read-only) mountpoint for HOME.

Need some suggestions on the best way forward ?

**Comment by afbjorklund** [comment]
Current behaviour:
```console
$ apptainer.lima --quiet run docker://alpine pwd
/home/anders/lima
$ apptainer.lima --quiet run --fakeroot docker://alpine pwd
/home/anders/lima
```

Normal behaviour:
```console
$ limactl shell apptainer apptainer --quiet run docker://alpine pwd
/home/anders.linux
$ limactl shell apptainer apptainer --quiet run --fakeroot docker://alpine pwd
/root
```

----

Another thing to watch out for, is that writing to the home directory will not work:

`apptainer.lima build alpine.sif docker://alpine`

```
INFO:    Creating SIF file...
FATAL:   While performing build: while creating SIF: while creating container: open /home/anders/lima/alpine.sif: read-only file system
```

So might have to use something like /var/tmp/alpine.sif, to get a writeable location.

```
INFO:    Creating SIF file...
INFO:    Build complete: /var/tmp/alpine.sif
```

Using the regular /tmp works too, but since it is a tmpfs it is limited by half RAM (2 GiB)

And need to use `/tmp/lima` as the working directory though, if wanting to get it back...

Might have to bundle `run-singularity` too, so that executing a .sif file would work ?

```console
$ apptainer build /tmp/lima/alpine.sif docker://alpine
...
$ /tmp/lima/alpine.sif
Apptainer>
```

Note that this happens on the **local** system, which could be Mac or Windows (or Linux)

**Comment by DrDaveD** [comment]
I'm not really following all the steps and what exactly the issue is, but you can set $APPTAINER_HOME to two parts "source:dest".  Does that help?  You can also set general binds in the comma-separated $APPTAINER_BIND or $APPTAINER_BINDPATH, and each of those can also be of the form "source:dest".  If you want to disable the usual home directory mounting you can add option `--no-home` or set `APPTAINER_NO_HOME=1`, but keep in mind that then you need to somehow set $HOME.

**Comment by afbjorklund** [comment]
The main "issue" was that the `~/.bashrc` from the host followed into the apptainer container instance.
But then I discovered that this is the _desired_ behaviour, and it does work the same way on Linux.

I guess everyone have their home on NFS and have already adapted it to be portable and flexible...
So now the only thing is that the HOME is in a "strange" place, but then again that shouldn't matter ?

As long as people use $HOME and not something silly like /home/$USER, it should be fine

And with the current setup, it does copy all the dotfiles from the Mac into the apptainer - as intended.

**Comment by afbjorklund** [comment]
I guess the main question was if it is OK that the home directory is read-only, like it currently is...

```
Apptainer> touch ~/.cache/foo
touch: cannot touch '/home/anders/.cache/foo': Read-only file system
```

My suspicion is that this will break a lot of software, so will try to use APPTAINER_BINDPATH

**Comment by afbjorklund** [comment]
This fixes the issue, now both scenarios work:

* https://github.com/lima-vm/lima/pull/1125

**Comment by DrDaveD** [comment]
Good, so it looks like nothing needs to be done here.
