### ISSUE TITLE
%environment omits, allows overwriting of EUID

### ISSUE THREAD

**Issue by anderbubble** [apptainer/apptainer#837]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).

```
apptainer version 1.1.2-1.el9
```

### Expected behavior

`%environment` scriptlet should have an `EUID` variable set during execution, and should not allow it to be set / overridden.

Should output

```
EUID: readonly variable
```

### Actual behavior

`%environment` scriptlet does not have an `EUID` variable set during execution, and allows it to be set / overridden by the scriptlet.

### Steps to reproduce this behavior

```
%environment
EUID=$(/usr/bin/id -u)
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.0 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.0"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.0 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.0"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.0"
```

### How did you install Apptainer

EPEL.

**Comment by dtrudg** [comment]
A readonly EUID is a bash-ism. AFAIK Singularity / Apptainer has only guaranteed POSIX /bin/sh behavior in `%environment`.

Under a POSIX `/bin/sh` it's perfectly possible to set EUID. Note that invoking `bash` as `/bin/sh` (such as on RHEL and derivatives) does not give you a true POSIX `/bin/sh`.

See behavior under alpine's `/bin/sh`:

```
09:57 am $ singularity run docker://alpine
INFO:    Using cached SIF image
Singularity> export EUID=100000000
Singularity> 
```

**Comment by cclerget** [comment]
@dtrudg The shell interpreter already mimic bash behavior, actually it set readonly UID/GID variables https://github.com/mvdan/sh/blob/master/interp/api.go#L610, we could also set readonly EUID/EGID variables in https://github.com/apptainer/apptainer/blob/main/internal/pkg/util/fs/files/action_script.sh. I don't see any problem to set those variables in addition to UID/GID

**Comment by DrDaveD** [comment]
bash does not have `EGID` but I'm OK with making `EUID` readonly.  We would also have to also set it to the correct value, right?  Could we just set it to the value of `$UID` and assume that's close enough?

**Comment by anderbubble** [comment]
To be clear, I'm not particularly concerned with EUID being read-only; only with it being set.

I'm investigating implementation right now that would simply set EUID, and make it the same value as UID.

**Comment by anderbubble** [comment]
Worth noting: EUID _is_ set in an `apptainer shell` environment; just not during `%environment`.

**Comment by anderbubble** [comment]
I went ahead and submitted the upstream PR. Personally, I think that's a better fix than this.

**Comment by anderbubble** [comment]
Potential fix upstream: https://github.com/mvdan/sh/pull/958

**Comment by anderbubble** [comment]
This was merged upstream at https://github.com/mvdan/sh/commit/d3feb15bed3a4d5b0481d32119e340c297d1d9cf, but hasn't been included in a release yet.

**Comment by DrDaveD** [comment]
It was a challenge to merge into the 1.1 branch so we're deferring this to 1.2
