### ISSUE TITLE
Fail to find GPU driver

### ISSUE THREAD

**Issue by noc-turne** [apptainer/apptainer#846]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

`apptainer --version` (or `singularity --version`).
![image](https://user-images.githubusercontent.com/86636997/198551420-47d275f8-0952-4271-8d25-56e81bbb4f9c.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/86636997/198552782-873241bd-49a7-4e4f-aa12-a633b4795042.png)
I can't find the Nvidia driver, while outside the container, I'm able to find it.

What else configuration should I do except using --nv?

**Comment by DrDaveD** [comment]
The `--nv` option has to be before the image name.  Try that first.

**Comment by DrDaveD** [comment]
It may indeed be about the warning.  Try it without the `--writable` flag.  If that works but you really need the `--writable` flag, then you will need to pre-create the mountpoint directories and files in your container.  I expect that using the `apptainer -d` debug option should show you (along with a lot of other information you don't care about) what points it wasn't able to bind mount.

**Comment by noc-turne** [comment]
Thanks. I tried building from mirror without --writable instead of from sandbox, but it still couldn't work, with the same error. I checked the debug information with only the following possible error massage.
![image](https://user-images.githubusercontent.com/86636997/198685214-48cb7537-d6c1-4c72-a2d9-f5598b4a5211.png)
![image](https://user-images.githubusercontent.com/86636997/198686114-0319c42d-3261-472d-9385-0b5a44bc4ddf.png)
Is it the reason? How to solve that?

**Comment by DrDaveD** [comment]
If you're not using `--writable` then I'm not sure what's happening.  Those debug messages alone aren't helpful.  

Can you give me instructions to reproduce the problem?  Can I get the container from "mirror"?  If not then tell me the host operating system, the full command line you're using now, and attach the whole debug output.  That can be done by redirecting the debug the output to a file with a name ending in `.txt` and then attaching it the way you're attaching images.

**Comment by noc-turne** [comment]
Sorry, I have to ask my leader whether I can give you the "mirror". Now I can tell you the following information.
1.host operating system and gpu information: 
![image](https://user-images.githubusercontent.com/86636997/198695118-1b57c09d-1818-457e-b498-4975cbe417da.png)
![image](https://user-images.githubusercontent.com/86636997/198696731-8fe072a5-c4db-4101-8829-6fa2f0325ec6.png)
2.the full command
because I run it in a computer cluster, I use "srun -p caif_dev apptainer shell --nv --writable tmp/daoxin2", "srun -p caif_dev" is the order to run it in the calculating node, it is not relevant.
[debug information.txt](https://github.com/apptainer/apptainer/files/9890609/debug.information.txt)

**Comment by DrDaveD** [comment]
I wanted to see it without the `--writable` flag, but oh, I forgot that with the `--nv` option most mountpoints are not needed inside the container because they get put into `/.singularity.d/libs`.  You do see `/.singularity.d/libs/libnvidia-ml.so` inside the container?  Maybe you have a different version of nvidia software than we're used to.  The error message says to add that directory to your PATH.  Apptainer adds it to $LD_LIBRARY_PATH, not $PATH.  I would have assumed that's what they meant, but maybe nvidia-smi is literally using $PATH.  Try adding `/.singularity.d/libs` (separated with a colon of course) in $PATH.

**Comment by noc-turne** [comment]
As you say, I do find libnvidia-ml.so in /.singularity.d/libs and $LD_LIBRARY_PATH does have /.singularity.d/libs in the container, , but when I add /.singularity.d/libs to $PATH, it still doesn't work.
![image](https://user-images.githubusercontent.com/86636997/198707383-91944cca-a533-447a-a753-4cdc1076ca06.png)
Here is the debug information with the order "srun -p caif_dev apptainer shell --nv xxx.sif"
[debug information.txt](https://github.com/apptainer/apptainer/files/9890969/debug.information.txt)
You can get the mirror through apptainer build docker://registry.sensetime.com/pavi/parrots:pt1.9_pat0.20.0b0_cuda10.1, after setting the environment variables "export APPTAINER_DOCKER_USERNAME=tangding" and "export APPTAINER_DOCKER_PASSWORD=tang5U6ding". I think it can work.

**Comment by DrDaveD** [comment]
I deleted the mirror information from your message so it's not in the permanent record, but I saved it.  Unfortunately I cannot connect to the mirror.  It is apparently not available to the internet.  Maybe you can upload the container to a public registry such as dockerhub.

The next thing I would probably do is use strace on nvidia-smi to try to reverse engineer what it is trying to do.  If it's not in the container (it probably isn't) it can probably be bound in from the host.

**Comment by noc-turne** [comment]
Thanks for deleting the mirror information. There is no docker in our computer cluster, and actually I'm not very familiar with apptainer, so where can I refer to use apptainer to push the mirror to dockerhub? I haven't seen relevant issues and documents. In fact, it's very late in our time zone, I'll talk to you later. Thanks again for help.

**Comment by DrDaveD** [comment]
Actually apptainer cannot push to dockerhub.  Docker and podman can do that.  You could put the files of the container in a tarball and upload it somewhere I could download it from like dropbox or google drive.

**Comment by noc-turne** [comment]
Sorry, my leader doesn't allow me to give you the mirror. But I solved the problem in a surprising way. I changed the place of "/.singularity.d/libs" in $LD_LIBRARY_PATH from behind to front, and it worked(nvidia-smi can normally work)
![image](https://user-images.githubusercontent.com/86636997/198955397-75932393-4db1-472e-8681-d26b3f0d9ce3.png)
(It's also okay to delete the "/.singularity.d/libs" behind)
I don't know why it can work. I do so because when I run the basic centos.sif I found $LD_LIBRARY_PATH only has one path "/.singularity.d/libs". And when I change  $LD_LIBRARY_PATH in my mirror to only "/.singularity.d/libs", it works. Later I use the way above. Maybe you can come up with an explanation about why it can work. Thanks a lot.

**Comment by DrDaveD** [comment]
Good for you, but that is surprising.  I wonder if /usr/local/nvidia/lib in your PATH has some different version of nvidia libraries that is confusing it.
