### ISSUE TITLE
--without-suid, uidmap: Unable to use `sudo`: `unable to allocate pty: Operation not permitted`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [apptainer/apptainer#847]
### Version of Apptainer

1.0.0

Per below, I do not run `apptainer` with root permissions. I instead use the `--without-suid` build option which leverages `uidmap`.

### Expected behavior

`sudo echo Hey` in a fakeroot container should print out `Hey`.

### Actual behavior

Instead, it says as follows:
```
$ apptainer --silent exec --writable --fakeroot image.sif.sandbox \
   env -i PATH=/usr/sbin:/usr/bin:/bin sudo echo Hey
sudo: unable to allocate pty: Operation not permitted
```

If I install `strace` in the container and run the command through it, I see the following bit:
```
chown("/dev/pts/3", 0, 5)               = -1 EPERM (Operation not permitted)
```

### Steps to reproduce this behavior

See:
https://github.com/EricCousineau-TRI/repro/tree/e2792668/shell/apptainer_stuff/figure_out_sudo

### What OS/distro are you running

```sh
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

### How did you install Apptainer

I installed it with minimal permissions (`--without-suid`, `uidmap`).
Exact build commands I ran:
https://gist.github.com/EricCousineau-TRI/df9777773c6a6c07c06ddef2f4f82fa3

**Comment by EricCousineau-TRI** [comment]
Gotcha, I think that all makes sense (at high-level for me, at least :sweat_smile:).

With regards to workflows, I simply want something that I can (a) "mock" `sudo` and (b) pretend that I'm using nominal user assets.
This would allow me to do `apt install` and my nominal user-flavored workflows (e.g. leveraging `~/.bash_aliases` customizations, `tmux` config, etc.) in the same container execution when operating with minimal containment - and it allows me to test tooling that uses `sudo` (for better or worse ;).

I've been able muck / hack around towards this workflow as follows:
https://github.com/EricCousineau-TRI/repro/tree/master/shell/apptainer_stuff ([permalink](https://github.com/EricCousineau-TRI/repro/tree/6c88c1deac8e78ee789f9557384a5c225f918691/shell/apptainer_stuff))
- Use a [stubbed `sudo`](https://github.com/EricCousineau-TRI/repro/blob/6c88c1deac8e78ee789f9557384a5c225f918691/shell/apptainer_stuff/fake_sudo.sh)
- [Futz with `~/.bashrc` entrypoint mechanics](https://github.com/EricCousineau-TRI/repro/blob/6c88c1deac8e78ee789f9557384a5c225f918691/shell/apptainer_stuff/bash_apptainer.sh#L9-L29) to make `/root` seem like `/home/{user}`

With this setup, I can generally do my full span of development in the containers without needing any concrete UID escalation. (And of course, using `udev` rules and what not to lower UID access barrier, etc.).

Not the most robust, but seems good enough such that any user can run it w/o needing any super user privileges.
It *could* be useful if a user wants soft superuser privileges and doesn't have sudo access (e.g. Unversity students on cloud resources that have access restrictions and haven't enabled elevation for Apptainer execution).

Still need to dig into nuance on `subuid`, `NO_NEW_PRIVS`, etc. Thanks for the pointers!

**Comment by DrDaveD** [comment]
I suggest that you use `--fakeroot` to do your installs, then exit and re-enter without using `--fakeroot`.

Upgrading to Apptainer 1.1 might also help, as it has new support for more things running unprivileged.  It does do better with setting $HOME when running with `--fakeroot`.

**Comment by EricCousineau-TRI** [comment]
Awesome, thanks! I'm now using `--fakeroot` for installs, then re-entering without as you've suggested.
I've also upgraded to apptainer v1.1.4.

Using this setup + stubbed sudo (per above) enables me to use most of our internal dev tooling workflow.

Should I close this issue as "workaround available" (stubbed sudo), or is there anything that might be doable to have `apptainer` itself provide a simple best-effort stub?

**Comment by DrDaveD** [comment]
I will go ahead and close this.  I can't think of how `apptainer` could help with a sudo stub.

**Comment by deliciouslytyped** [comment]
The pty permissions specifically may actually probably be solved by remountting devpts with mount -t devpts devpts /dev/pts assming you are in / have made a situation where you can mount that.
