### ISSUE TITLE
Support unprivileged arbitrary UID/GID mapping 

### ISSUE THREAD

**Issue by GodloveD** [apptainer/apptainer#848]
### Version of Apptainer

```
$ apptainer version
1.1.3
```
### Expected behavior

Now that the `--fakeroot` option can be used to map the user's UID on the host to UID 0 in the container **without privilege**, it seems like it should be possible to map host UID/GIDs to container UID/GIDs also without privilege.  @cclerget has suggested that the `--userns` and `--security` options could potentially be used in combination to effect this mapping. 

### Actual behavior

This still requires privilege in Apptainer.  

### Steps to reproduce this behavior

For example, I've created the user `ruser` with UID `1234` in a container called rstudio-server.sif.  I'd like to run as that user in the container, but the following produces a fatal error instead. 
```
$ apptainer shell -u --security=uid:1234 rstudio-server.sif 
FATAL:   uid security feature requires root privileges
```

### What OS/distro are you running

```
$ cat /etc/os-release 
NAME="Fedora Linux"
VERSION="36 (Workstation Edition)"
ID=fedora
VERSION_ID=36
VERSION_CODENAME=""
PLATFORM_ID="platform:f36"
PRETTY_NAME="Fedora Linux 36 (Workstation Edition)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:36"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=36
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=36
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```

### How did you install Apptainer

From source tarball.

**Comment by DrDaveD** [comment]
You're OK with that being the only UID in the container?  Everything inside the container would still be mapped to the original user's ID on the outside.
