### ISSUE TITLE
Restore library:// URI

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#85]
As discussed on the [mailing list](https://groups.google.com/u/1/a/lbl.gov/g/singularity/c/e-t6Ag-srBQ), support for the library protocol that was removed in #69 can be restored.

**Comment by PaulCharlton** [comment]
@DrDaveD this is a simple git reversal of commit #69 and some housekeeping for the new package reference

**Comment by DrDaveD** [comment]
Yes, I started with a git reversal of most but not all of it, I'm working on it.
