### ISSUE TITLE
Apptainer ignores nss_wrapper settings

### ISSUE THREAD

**Issue by holzman** [apptainer/apptainer#852]
### Version of Apptainer

```apptainer version 1.1.3```

### Expected behavior

`nss_wrapper` allows the use of user-managed passwd/group/host files.  It can be particularly useful running in a containerized environment like Kubernetes/OpenShift.

Expected behavior is to start alpine as UID 2000, username "user".

### Actual behavior

```DEBUG   [U=2000,P=63]      InitImageDrivers()            squashfuse_ll supports -o uid
DEBUG   [U=2000,P=63]      InitImageDrivers()            Setting ImageDriver to fuseapps
FATAL   [U=2000,P=63]      StageOne()                    user: unknown userid 2000
VERBOSE [U=2000,P=7]       wait_child()                  stage 1 exited with status 255
```
### Steps to reproduce this behavior
```FROM ubuntu:20.04

RUN apt-get -y update && apt-get install -y wget libnss-wrapper
RUN cd /tmp && wget https://github.com/apptainer/apptainer/releases/download/v1.1.3/apptainer_1.1.3_amd64.deb &&  apt-get install -y ./apptainer_1.1.3_amd64.deb

RUN mkdir -p /home/user && chown 2000:3000 /home/user && mkdir /etc/sssd
RUN echo "user:*:2000:3000:User H. Name:/home/user:/bin/bash" > /etc/sssd/passwd
RUN echo "usergroup:*:3000:user\nroot:x:0:" > /etc/sssd/group

ENV LD_PRELOAD=libnss_wrapper.so NSS_WRAPPER_PASSWD=/etc/sssd/passwd NSS_WRAPPER_GROUP=/etc/sssd/group HOME=/uscms/user

USER 2000
CMD apptainer --debug run docker://alpine
```

**Comment by DrDaveD** [comment]
@cclerget Is this because the environment is cleared in some of the stages?

**Comment by holzman** [comment]
@DrDaveD: looks to me like it is - when apptainer exec's the starter, it clears the environment (preserving it in `ENGINE_CONFIG*`).  The starter (in C) also cleans the environment as well.   If I add `LD_PRELOAD` and `NSS_WRAPPER_{PASSWD,GROUP}` in the code, I get much further trying to run apptainer inside OpenShift/OKD, failing further on.

Before I ask you to put any real work in on this, let me confirm that I can indeed get a hacked-up version working, though :)

**Comment by holzman** [comment]
Ok, this isn't worth spending time on.  Since apptainer mounts tmpfs volumes, we'd need to also grant `CAP_SYS_ADMIN` to the outside container as well as modify some SELinux permissions (container runs as `container_t`, `/dev/shm/` is `system_u:object_r:tmpfs_t`).
