### ISSUE TITLE
User namespaces documentation typo? 

### ISSUE THREAD

**Issue by dkoppstein** [apptainer/apptainer#854]
### Version of Apptainer

1.1

### What version of Apptainer (or Singularity) are you using? Run

n/a

### The [user namespace documentation](https://apptainer.org/docs/admin/1.1/user_namespace.html) of Apptainer states the following: 

Network namespaces can be disabled on most Linux-based systems like this:

```
sudo sh -c 'echo user.max_user_namespaces=15000 \
    >/etc/sysctl.d/90-max_net_namespaces.conf'
sudo sysctl -p /etc/sysctl.d /etc/sysctl.d/90-max_net_namespaces.conf
```

However, shouldn't this be ` >/etc/sysctl.d/90-max_user_namespaces.conf` and `sudo sysctl -p /etc/sysctl.d/90-max_user_namespaces.conf` rather than `90-max_net_namespaces.conf`? Especially since this will get overwritten by the next command disabling network namespaces: 

```
echo "user.max_net_namespaces = 0" \
     >/etc/sysctl.d/90-max_net_namespaces.conf
sysctl -p /etc/sysctl.d/90-max_net_namespaces.conf
```

**Comment by DrDaveD** [comment]
Thanks so much for pointing that out.  It has been wrong since apptainer/singularity-admindocs#88 over 2 years ago and is also in the sylabs documentation.
