### ISSUE TITLE
Bare Metal installation

### ISSUE THREAD

**Issue by mrbluecoat** [apptainer/apptainer#856]
https://apptainer.org/docs/admin/main/installation.html#installation-on-linux says

> Apptainer can be installed on any modern Linux distribution, on bare-metal or inside a Virtual Machine.

But I can't find information on how to install Apptainer on bare metal. Is there documentation or an OS like Flatcar that provides this?

**Comment by DrDaveD** [comment]
I think it's probably just a misunderstanding about what is meant by the "bare-metal".  In this context it just means non-Virtual Machine.

**Comment by mrbluecoat** [comment]
I see. Usually bare metal means 'without a host operating system'. Thanks for that clarification.
