### ISSUE TITLE
EPEL updating RHEL7 systems to apptainer when not supported

### ISSUE THREAD

**Issue by dmd** [apptainer/apptainer#859]
We just did a `yum update` on our RHEL 7.9 system, and Singularity 3.8.7 was updated to Apptainer.

Apptainer does not work on stock RHEL 7.9 (I believe because of lack of kernel support for unprivileged user namespaces?).

Impact: All users were suddenly unable to run any of their jobs; not the outcome I'd want from a `yum update`.

Workaround: I rolled back with:

```
yum uninstall apptainer
yum --setopt=obsoletes=0 install singularity-3.8.7
```

However, the package in EPEL should be flagged to not update to Apptainer on a RHEL7 system.

**Comment by DrDaveD** [comment]
We're sorry about the breakage, but we knew that was going to happen to a subset of installations especially on EL7.  We tried to announce it as widely as we could.  The RHEL 7.9 kernel does support unprivileged user namespaces, but it needs to be enabled.   See https://apptainer.org/docs/admin/main/user_namespace.html#rhel-centos-7.  For reasons to enable it see https://apptainer.org/docs/user/main/security.html#setuid-user-namespaces.  The alternative is to install the extra `apptainer-suid` rpm.
