### ISSUE TITLE
Overlay mounting fails with --fakeroot

### ISSUE THREAD

**Issue by multimeric** [apptainer/apptainer#864]
### Version of Apptainer

1.1.0 (unfortunately I don't have access to the latest version)

### Expected behavior

I expect mounting to work identically between `--fakeroot` mode and normal mode. ie I expect to work like this non-fakeroot invocation:
```
$ apptainer shell --writable-tmpfs docker://ubuntu
WARNING: DEPRECATED USAGE: Environment variable SINGULARITY_HOME will not be supported in the future, use APPTAINER_HOME instead
INFO:    Using cached SIF image
Apptainer>
```

(and then the shell opens correctly)

### Actual behavior

```
apptainer shell --writable-tmpfs --fakeroot docker://ubuntu
WARNING: DEPRECATED USAGE: Environment variable SINGULARITY_HOME will not be supported in the future, use APPTAINER_HOME instead
INFO:    Using cached SIF image
INFO:    User not listed in /etc/subuid, trying root-mapped namespace
WARNING: DEPRECATED USAGE: Environment variable SINGULARITY_HOME will not be supported in the future, use APPTAINER_HOME instead
INFO:    Using cached SIF image
INFO:    Using fakeroot command combined with root-mapped namespace
INFO:    squashfuse not found, will not be able to mount SIF
INFO:    fuse2fs not found, will not be able to mount EXT3 filesystems
INFO:    Converting SIF file to temporary sandbox...
INFO:    fuse-overlayfs not found, will not be able to use overlay
INFO:    Cleaning up image...
FATAL:   container creation failed: mount overlay->/stornext/System/data/tools/apptainer/apptainer-1.1.0/var/apptainer/mnt/session/final error: while mounting overlay: can't mount overlay filesystem to /stornext/System/data/tools/apptainer/apptainer-1.1.0/var/apptainer/mnt/session/final: operation not permitted
```

### Steps to reproduce this behavior

`apptainer shell --writable-tmpfs --fakeroot docker://ubuntu`

### What OS/distro are you running

CentOS Linux 7

### How did you install Apptainer

Environment module.

**Comment by DrDaveD** [comment]
The `--writable-tmpfs` option uses overlay, so you need the `fuse-overlayfs` command in order to use that on CentOS 7.

**Comment by multimeric** [comment]
Can you explain why it works when I don't have `--fakeroot`, considering that I don't have `fuse-overlayfs` installed at all?

**Comment by DrDaveD** [comment]
Oh, right, I overlooked that and also the fact that you said it was installed from an Environment module, I'm sorry.  My only explanation is that the Environment module is already compiled with setuid-root.  When using the `--fakeroot` option apptainer for security reasons cannot take advantage of its setuid mode for most things and so runs essentially unprivileged.  (I believe the only exception is for processing /etc/subuid and /etc/subgid mappings, which you don't have anyway).

**Comment by multimeric** [comment]
Well the weird thing is that we *don't* have setuid:
```bash
ls -l $(which apptainer)
-rwxr-xr-x 1 root grp_its_unix_adm 53878648 Oct  6 17:20 /stornext/System/data/tools/apptainer/apptainer-1.1.0/bin/apptainer
```

So I believe there must be some behaviour that lets this mounting work, but only if `--fakeroot` isn't set?

**Comment by DrDaveD** [comment]
It's not the apptainer command itself that is setuid.  Look in /stornext/System/data/tools/apptainer/apptainer-1.1.0/libexec/bin for starter-suid.

**Comment by multimeric** [comment]
Good call, this is more informative
```
ls -l /stornext/System/data/tools/apptainer/apptainer-1.1.0/libexec/
total 0
drwxr-sr-x 5 ghangas.r grp_its_unix_adm 2 Oct  6 17:07 apptainer
```

I guess this means it has `setgid`? Does this explain the behaviour I've seen?

**Comment by DrDaveD** [comment]
No it's not setgid.  I just forgot about that extra directory level.  See /stornext/System/data/tools/apptainer/apptainer-1.1.0/libexec/apptainer/bin

**Comment by multimeric** [comment]
```
 ls -l /stornext/System/data/tools/apptainer/apptainer-1.1.0/libexec/apptainer/bin
total 49152
-rwxr-xr-x 1 root grp_its_unix_adm 22243480 Oct  6 17:20 starter
-rwsr-xr-x 1 root grp_its_unix_adm 21879224 Oct  6 17:20 starter-suid
```

**Comment by DrDaveD** [comment]
So that's why the difference.  When running with `--fakeroot` you need the additional fuse programs.
