### ISSUE TITLE
Running Apptainer as user with multiple linux groups

### ISSUE THREAD

**Issue by aicampbell** [apptainer/apptainer#868]
### Version of Apptainer
Two versions tested:
```
$ apptainer --version  
apptainer version 1.1.2
```
```
apptainer --version
apptainer version 1.1.0-rc.2+2-g3ff6bbac8

```

### Expected behavior

When I run the container, I expected all of the user's groups to be mapped in the container. This is especially important when trying to access folders limited to specific groups on our hpc cluster.

### Actual behavior
The container only maps the default/primary group and not all of the groups.
From the host:
```
id
uid=1000(aidan) gid=1000(aidan) groups=1000(aidan),3(sys),964(docker),982(rfkill),998(wheel)

```
Then from the container:
```
$ singularity shell lolcow.simg 
Apptainer> id
uid=1000(aidan) gid=1000(aidan) groups=1000(aidan),65534(nogroup)

```

### What OS/distro are you running
Tested on both Ubuntu and EndeavourOS
```
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
```
```
NAME=EndeavourOS
PRETTY_NAME=EndeavourOS
ID=endeavouros
ID_LIKE=arch
BUILD_ID=rolling

```

### How did you install Apptainer
Followed tutorial on apptainer.org

**Comment by DrDaveD** [comment]
Unfortunately the kernel unprivileged user namespaces feature only allows one group to be mapped and there's nothing that can be done about that.  In theory if there were `/etc/subid` and `/etc/subgid` mappings apptainer could take advantage of that for this purpose, although currently it only tries to use them with the `--fakeroot` option.

**Comment by ad12** [comment]
@aicampbell did you find a workaround for this?

**Comment by NickHastings** [comment]
Is there perhaps a way to tell apptainer to use a group other than the primary group?

**Comment by DrDaveD** [comment]
You can change the default group with `newgrp` before running apptainer.

**Comment by NickHastings** [comment]
@DrDaveD thanks! Don't know why I didn't think of that.
