### ISSUE TITLE
Deal with moving /etc/singularity to /etc/apptainer

### ISSUE THREAD

**Issue by DrDaveD** [apptainer/apptainer#87]
Import /etc/singularity/singularity.conf if it has been changed and copy into /etc/apptainer/apptainer.conf.

**Comment by boegel** [comment]
Auto-copying `singularity.conf` to `apptainer.conf` on installing `apptainer` may surprise sysadmins.
They would expect to get the `apptainer.conf` that's included in the RPM (after checking the contents with `mc`).

**Comment by DrDaveD** [comment]
But what about all those admins that don't pay a lot of attention?  Wouldn't they rather expect that their configuration options will be preserved on a package upgrade?  How about instead of copying the whole file we only update changed configuration options?

**Comment by boegel** [comment]
From the point of view of a sysadmin, I think failing to run after installation in case an existing `singularity.conf` is present is better than silently copying over `singularity.conf` to `apptainer.conf`.

Most likely `singularity.conf` is managed with some configuration management tool, so a one-time copy is unlikely to be a good approach long term. Exiting with an error that instructs whoever installed `apptainer` to rename `singularity.conf` to `apptainer.conf`, and perhaps mention a command like `sudo apptainer --inherit-singularity-conf`, is easy enough, and won't lead to unexpected surprises?

**Comment by DrDaveD** [comment]
Good points.  On the other hand, it wouldn't do to fail the install, and the only other place to fail is in the running of the command itself and that might hit users before a system admin notices.  Maybe just a warning rather than a fatal error will do.

**Comment by DrDaveD** [comment]
Maybe all that's needed here is a warning whenever apptainer starts:
```
WARNING: /etc/apptainer/../singularity exists, migration to apptainer by system administrator may not be complete
```
Unfortunately the singularity rpm did not explicitly include the /etc/singularity subdirectories (cgroups, network, seccomp-profiles) because those do not get removed even if the system administrator didn't modify anything.  I could try to rmdir those in a post install, and /etc/singularity if it is then empty.

**Comment by PaulCharlton** [comment]
per community meeting discussion, this is purely a documentation issue for admins
most of the /etc/... are maintained by configuration tools and distributed configuration tools such as puppet.
