### ISSUE TITLE
Strange variable name APPTAINERENV_SING_USER_DEFINED_PREPEND_PATH in deprecation warning

### ISSUE THREAD

**Issue by kpedro88** [apptainer/apptainer#870]
### Version of Apptainer

```
apptainer version 1.1.2-1.el7
```

### Expected behavior

When running apptainer with singularity environment variables defined, I get a number of warnings:
```
WARNING: DEPRECATED USAGE: Environment variable SINGULARITY_BIND will not be supported in the future, use APPTAINER_BIND instead
WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_PREPEND_PATH as environment variable will not be supported in the future, use APPTAINERENV_SING_USER_DEFINED_PREPEND_PATH instead
WARNING: DEPRECATED USAGE: Forwarding SINGULARITYENV_PS1 as environment variable will not be supported in the future, use APPTAINERENV_PS1 instead
```

Most of the suggested apptainer environment variables just look like the singularity ones with `'s/SINGULARITY/APPTAINER/'`, as one would expect.

### Actual behavior

For `SINGULARITYENV_PREPEND_PATH`, it suggests `APPTAINERENV_SING_USER_DEFINED_PREPEND_PATH`, rather than the simpler `APPTAINERENV_PREPEND_PATH`.

Interestingly, both options actually work (substituting them into the below command gives the expected `$PATH` inside the container).

### Steps to reproduce this behavior

```
env -i SINGULARITYENV_PREPEND_PATH=. apptainer run [container]
```

### What OS/distro are you running

```sh
$ cat /etc/os-release

NAME="Scientific Linux"
VERSION="7.9 (Nitrogen)"
ID="scientific"
ID_LIKE="rhel centos fedora"
VERSION_ID="7.9"
PRETTY_NAME="Scientific Linux 7.9 (Nitrogen)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:scientificlinux:scientificlinux:7.9:GA"
HOME_URL="http://www.scientificlinux.org//"
BUG_REPORT_URL="mailto:scientific-linux-devel@listserv.fnal.gov"

REDHAT_BUGZILLA_PRODUCT="Scientific Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.9
REDHAT_SUPPORT_PRODUCT="Scientific Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.9"
```

### How did you install Apptainer

RPM apptainer-1.1.2-1.el7.x86_64

**Comment by kpedro88** [comment]
Also: if I have an environment with `SINGULARITYENV_PREPEND_PATH` and `APPTAINERENV_PREPEND_PATH`, I still get the deprecation message. So while `APPTAINERENV_PREPEND_PATH` seems to work, whatever checks for the presence of non-deprecated environment variables does not know about it.

**Comment by DrDaveD** [comment]
Interestingly, there is [code](https://github.com/apptainer/apptainer/blob/main/internal/pkg/util/env/create.go#L79) explicitly making that substitution.  I think that's because the startup scripts look for that longer form.  The warning however should come before that substitution.
