### ISSUE TITLE
apptainer cache is not architecture aware

### ISSUE THREAD

**Issue by traylenator** [apptainer/apptainer#886]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

```
$ apptainer --version
apptainer version 1.1.3-1.el9
```

### Expected behavior

```
/usr/bin/apptainer run docker://alpine:latest hostname
```

ran on both aarch64 and on x86_64 should be posible with the same cache directory.

### Actual behavior

A cached on `x86_64`  image fails on `aarch64` on.

### Steps to reproduce this behavior

1. Login into an aarch64 node.

```
 /usr/bin/apptainer run docker://alpine:latest hostname
INFO:    Using cached SIF image
lxplus9s05.example.org
```

2. Login into an x86_64 node.

```
/usr/bin/apptainer run docker://alpine:latest hostname
INFO:    Using cached SIF image
FATAL:   could not open image /afs/example.ch/user/s/someone/.apptainer/cache/oci-tmp/8914eb54f968791faf6a8638949e480fef81e697984fba772b3976835194c6d4: the image's architecture (arm64) could not run on the host's (amd64)
```

If I purge the cache  all is good and a `x86_64` item is cached.

How can others reproduce this issue/problem?
Need `aarch64` and `x86_64` sharing a `/home` filesystem.

### What OS/distro are you running

```
CentOS 9
```

### How did you install Apptainer

EPEL.

### Summary:
So while the `docker://alpine:latest` is multiarch once it is cache it is not.

### Workarond

Use the `--disablecache` option.

**Comment by DrDaveD** [comment]
That's true.  I assigned it milestone 1.2.0.

**Comment by DrDaveD** [comment]
Include having the cache --clean command clean up all architectures including no architecture for backward compatibility.
