### ISSUE TITLE
Ubuntu Focal Image: `/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [apptainer/apptainer#945]
### Version of Apptainer

`apptainer version 1.1.4`

### Expected behavior

EDIT: Updated to avoid `pydrake` (large dep), and  instead use `glxgears`

For example, in Apptainer with `--nv` and `glxgears` installed:
```
$ glxgears
# No error
```

### Actual behavior

```sh
$ glxgears
glxgears: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLdispatch.so.0)
glxgears: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /.singularity.d/libs/libGLX.so.0)
```

### Steps to reproduce this behavior

See https://github.com/EricCousineau-TRI/repro/tree/f1ff2000abdc631a94a750cdb0c2d66d33ff4857/bug/apptainer_issue945

Look at `repro.sh`; more notably:
```sh
${apptainer_bin} build --fakeroot --sandbox ./repro.sandbox ./repro.Apptainer

# Succeeds.
${apptainer_bin} exec ./repro.sandbox ${test_script}

# Fails.
${apptainer_bin} exec --nv ./repro.sandbox ${test_script}
```

### What OS/distro are you running

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

### How did you install Apptainer

From source, using this script:
https://github.com/EricCousineau-TRI/repro/blob/f1ff2000abdc631a94a750cdb0c2d66d33ff4857/shell/apptainer_stuff/build_and_install_apptainer.sh

**Comment by EricCousineau-TRI** [comment]
Hm... current repro steps actual worked. I am additionally doing stuff related to #847, so maybe something within that workflow is breaking things.

I need to pause at the moment, but will try to pick this back up later.

**Comment by DrDaveD** [comment]
The `--fakeroot` option without `/etc/subuid` and `/etc/subgid` mappings set up also binds in a library from the host that could cause a GLIBC error, if the glibc in the container is incompatible with the glibc on the host.  However, the fact that the error was on libGLX does indeed look like a case of gpu bindings.

**Comment by EricCousineau-TRI** [comment]
Thanks! I've just edited my overview post and example to

(a) Use `glxgears` (more direct test) rather than heavier `pydrake`
(b) Avoid using `exec --fakeroot --writable`. Instead, just use `exec` and/or `exec --nv`
(c) Confirm that not using `--nv` allows it to pass.

> However, the fact that the error was on libGLX does indeed look like a case of gpu bindings.

Yeah, I think that's the case with changes (b) and (c).

> If you don't need to visualize anything within the container I would comment out `libGLX.so*` from your `nvliblist.conf` file and see if that helps.

Will try that out!

**Comment by EricCousineau-TRI** [comment]
Yup, commenting out `libGLdispatch.so` and `libGLX.so` allowed this binary to run.
Will take that for a longer test run to see if it breaks down at any point - thanks!

**Comment by EricCousineau-TRI** [comment]
As a minor side note, I am using [Bazel](https://bazel.build/) inside some of my dev containers.

Sometimes, `bazel run` or `bazel test` for a target would work, but running the produced binary directly would not work. I am not sure if that is related to something like `LD_PRELOAD`, but I briefly tried that out with `libc` and it didn't work (see [wip commit](https://github.com/EricCousineau-TRI/repro/commit/e1bedb4e963a777d60604f13d809578cf1ba8a1f)).

**Comment by EricCousineau-TRI** [comment]
Sorry for delay - I've been running this for some time with the workaround, and haven't noticed anything going awry.

Should I close this given there's a workaround?

**Comment by GodloveD** [comment]
Seems sensible since I'm not sure if there is anything that can be done for a more permanent solution.

**Comment by peci1** [comment]
> not sure if there is anything that can be done for a more permanent solution.

Hmm, what about not mounting the vendor-neutral host libs (i.e. removing them from nvliblist)? :) I think that should be done. In case there are images that do not carry their own GL installation, there could be another switch like `--gl` that would mount just the vendor-neutral host GL libraries. But I can't imagine too easily a container which does not have GL installed but has some apps that can use it.

As a workaround we provide to students using many different versions of singularity/apptainer, we do this in our setup bash script for an Ubuntu 20.04 container with glibc 2.31:

```bash
nv=""
if [ "$USE_SINGULARITY_NV" = "1" ]; then
	# When running on Ubuntu newer than 20.04 host system, the host glibc is newer than 2.31 and this causes problems
	# together with the --nv switch because Singularity mounts too much files from the host inside the container.
	# So, if running on a newer host, we need to build a subset of the list of mounted libraries and exclude those that
	# are not directly related to the nvidia driver.
	glibc_version="$(ldd --version | grep -i glibc | head -n1 | grep -o '2\.[0-9]\{2,\}' | head -n1 | cut -d. -f2)"
	if [[ "$glibc_version" -le 31 ]]; then
		nv="--nv"
	else
		echo "Your system uses glibc newer than 2.31 which is used inside the container. Implementing --nv switch via a workaround. Let's hope it works!"
		libs="$(singularity --debug exec --nv "$IMAGE" echo test 2>&1 | grep 'addLibsMount.*/lib/' | sed 's#^.*\(/lib/[^ ]*\) .*$#\1#')"
		libs="$(echo "$libs" | grep -v -e libEGL.so -e libGL.so -e libGLdispatch.so -e libGLX.so -e libOpenCL.so -e libOpenGL.so)"
		nv="$(echo "$libs" | sed 's/^/-B /g' | tr "\n" " ")"
		nv="$nv -B /usr/share/glvnd/egl_vendor.d/10_nvidia.json"
	fi
fi

# ...

singularity exec -e $nv "$IMAGE" "$SCRIPT_DIR/start" "$@"
```

**Comment by tianyilim** [comment]
@peci1 I would just like to say that your solution worked. thanks a lot!

**Comment by songlin** [comment]
@peci1 I have tried your solution but failed. The host is Ubuntu 24.04 and the container is 22.04. I can not find the GPU via `nvidia-smi` using the command `singularity exec -e $nv "$IMAGE" "$SCRIPT_DIR/start" "$@"`. However, I `nvidia-smi` does show GPU when mounted with the normal `--nv` option.

**Comment by antragoudaras** [comment]
> > not sure if there is anything that can be done for a more permanent solution.
> 
> Hmm, what about not mounting the vendor-neutral host libs (i.e. removing them from nvliblist)? :) I think that should be done. In case there are images that do not carry their own GL installation, there could be another switch like `--gl` that would mount just the vendor-neutral host GL libraries. But I can't imagine too easily a container which does not have GL installed but has some apps that can use it.
> 
> As a workaround we provide to students using many different versions of singularity/apptainer, we do this in our setup bash script for an Ubuntu 20.04 container with glibc 2.31:
> 
> nv=""
> if [ "$USE_SINGULARITY_NV" = "1" ]; then
> 	# When running on Ubuntu newer than 20.04 host system, the host glibc is newer than 2.31 and this causes problems
> 	# together with the --nv switch because Singularity mounts too much files from the host inside the container.
> 	# So, if running on a newer host, we need to build a subset of the list of mounted libraries and exclude those that
> 	# are not directly related to the nvidia driver.
> 	glibc_version="$(ldd --version | grep -i glibc | head -n1 | grep -o '2\.[0-9]\{2,\}' | head -n1 | cut -d. -f2)"
> 	if [[ "$glibc_version" -le 31 ]]; then
> 		nv="--nv"
> 	else
> 		echo "Your system uses glibc newer than 2.31 which is used inside the container. Implementing --nv switch via a workaround. Let's hope it works!"
> 		libs="$(singularity --debug exec --nv "$IMAGE" echo test 2>&1 | grep 'addLibsMount.*/lib/' | sed 's#^.*\(/lib/[^ ]*\) .*$#\1#')"
> 		libs="$(echo "$libs" | grep -v -e libEGL.so -e libGL.so -e libGLdispatch.so -e libGLX.so -e libOpenCL.so -e libOpenGL.so)"
> 		nv="$(echo "$libs" | sed 's/^/-B /g' | tr "\n" " ")"
> 		nv="$nv -B /usr/share/glvnd/egl_vendor.d/10_nvidia.json"
> 	fi
> fi
> 
> # ...
> 
> singularity exec -e $nv "$IMAGE" "$SCRIPT_DIR/start" "$@"

Thanks a lot that worked for me
