### ISSUE TITLE
mount source /.singularity.d/libs/faked doesn't exist

### ISSUE THREAD

**Issue by preney** [apptainer/apptainer#951]
### Version of Apptainer

1.1.3 

(I also built version 1.1.4 manually from source and it is also affected.)

### Expected behavior

Running:
```sh
  apptainer build --sandbox ubuntu.dir docker://ubuntu
  apptainer shell --fakeroot --writable ubuntu.dir
```
should work allowing one to deal with ubuntu.dir/ .

### Actual behavior

Running "apptainer shell --fakeroot --writable ubuntu.dir" generates the following:
```sh
  INFO:    User not listed in /etc/subuid, trying root-mapped namespace
  INFO:    Using fakeroot command combined with root-mapped namespace
  WARNING: Skipping mount /etc/localtime [binds]: /etc/localtime doesn't exist in container
  FATAL:   container creation failed: mount hook function failure: mount /.singularity.d/libs/faked->/var/apptainer/mnt/session/libs/faked error: while mounting /.singularity.d/libs/faked: mount source /.singularity.d/libs/faked doesn't exist
```
and one is not entered in to a shell due to the FATAL error.

### Steps to reproduce this behavior

Install Apptainer 1.1.3 under Gentoo, Gentoo Prefix and probably a number of distributions and run:
```sh
  apptainer build --sandbox ubuntu.dir docker://ubuntu
  apptainer shell --fakeroot --writable ubuntu.dir
```

ASIDE: fakeroot (v1.30.1) is installed so there shouldn't be an issue as fakeroot, right? That said, there are no fakeroot-sysv or fakeroot-tcp executables which the Apptainer release notes for 1.1.3 appears to want to search for. Clearly such will fail which results in the above FATAL error?

### What OS/distro are you running

Gentoo Linux
```sh
$ cat /etc/os-release
NAME=Gentoo
ID=gentoo
PRETTY_NAME="Gentoo Linux"
ANSI_COLOR="1;32"
HOME_URL="https://www.gentoo.org/"
SUPPORT_URL="https://www.gentoo.org/support/"
BUG_REPORT_URL="https://bugs.gentoo.org/"
VERSION_ID="2.9"
```

### How did you install Apptainer

```sh
emerge -av =app-containers/apptainer-1.1.3
```
with USE flags `examples network systemd`, i.e., `suid` was not set.

**Comment by bartoldeman** [comment]
It seems there's an issue here:

https://github.com/apptainer/apptainer/blob/da8b1ffb71ca6a5818011c4ac1218b89b4741c5d/internal/pkg/fakeroot/fakefake.go#L152-L161

where `binds[1]=/.singularity.d/libs/faked`

now if `LD_PRELOAD=libfakeroot-sysv.so`, it'll split in two and `faker-sysv` is added to the mountpoints as `<directory of fakeroot-sysv>/bin/faker-sysv`

but if there is no `-` in `$LD_PRELOAD`, as in Gentoo, where it's simply `libfakeroot.so` (which is a symlink to `libfakeroot-0.so`, nothing happens.

I don't speak Go very well but something like this could work:

```
        if len(splits) > 1 {
                // add the faked that corresponds to the preload library
                src += "-" + splits[1]
        }
        if _, err = os.Stat(src); err == nil {
                binds[1] = src + ":" + point
        }
```

**Comment by DrDaveD** [comment]
That looks reasonable.  Give it a try and let me know if it works.  I don't have a Gentoo system to try it on.

**Comment by bartoldeman** [comment]
I verified that change does the job, see linked PR.
