### ISSUE TITLE
better support for startscript.sh (feature request)

### ISSUE THREAD

**Issue by GodloveD** [apptainer/apptainer#959]
### Version of Apptainer

```
$ apptainer --version
apptainer version 1.1.3
```

### Expected behavior

I'd like to run `apptainer instance start docker://some/container` or similar and get the entrypoint to run as the startscript.

### Actual behavior

afaik, there is no good way to get the container to recognize the docker entrypoint as the startscript.  Instead, apptainer shoves all of the entrypoint stuff into the runscript by default and if you run the container as an instance it does not execute the entrypoint.  

I've tried a few different workarounds, but so far nothing is ideal.  One idea is to force the container to execute the runscript when the instance is started.  I tried this by creating a wrapper script (on the host system) like so:

```
echo "/bin/sh /.singularity.d/runscript" >startscript

chmod 750 startscript
```
Then bind mounting it into the metadata directory at runtime like so:

```
export APPTAINER_BINDPATH=startscript:/.singularity.d/startscript
```
This seems to work, but it is very brittle and there are potential side effects for running other containers. 

The second thing I tried was to rebuild the container with a def file of the following format.

```
Bootstrap: docker                                                               
From: some/container                                                
                                                                                   
%post                                                                           
    cp /.singularity.d/runscript /.singularity.d/startscript
```

This also works, but it produces an intermediate build artifact that may be unwanted.  

### Solution?

I think some discussion is needed about the correct way to approach this.  Maybe the user could pass a flag to `instance start` command to let it know it should treat the runscript as the startscript.  Or maybe Apptainer should intelligently copy the docker CMD and entrypoint stuff to the startscript instead of the runscript if the user is executing the container as an instance.  This second option would probably be a sensible default, but it would also be a breaking change if folks are currently using instance start on OCI containers.  

What say the developers?

**Comment by DrDaveD** [comment]
How about an `apptainer instance run` command?

**Comment by GodloveD** [comment]
That's an interesting idea.  Would we also implement `shell` and `exec` within the instance command group?

**Comment by DrDaveD** [comment]
I wouldn't think so.  I think that `exec` is mostly for something that is running to completion, and not something you'd want to do with an instance left running after the command exits.  `shell` is for running interactively, and you might as well do that in a separate command.

**Comment by GodloveD** [comment]
@JasonYangShadow would you want to have a look at this?

**Comment by GodloveD** [comment]
I finally took a look at this and I'm seeing that the startscript is actually called by the `start` action in the `/.singularity.d/actions` directory.

```
#!/bin/sh
# Copyright (c) Contributors to the Apptainer project, established as
#   Apptainer a Series of LF Projects LLC.
#   For website terms of use, trademark policy, privacy policy and other
#   project policies see https://lfprojects.org/policies
# Copyright (c) 2018-2021, Sylabs Inc. All rights reserved.
# This software is licensed under a 3-clause BSD license. Please consult the
# LICENSE.md file distributed with the sources of this project regarding your
# rights to use or distribute this software.

# if we are here start notify PID 1 to continue
# DON'T REMOVE
kill -CONT 1

for script in /.singularity.d/env/*.sh; do
    if [ -f "$script" ]; then
        . "$script"
    fi
done

if test -x "/.singularity.d/startscript"; then
    exec "/.singularity.d/startscript"
fi
```
So, I'm looking for suggestions on how to implement this.  Should I create a new action in the actions directory of the container?  If so, this feature will only work with newly created containers right?  Is there a better idea that I'm not thinking of?

**Comment by DrDaveD** [comment]
Why can't the `apptainer instance run` command invoke `/.singularity.d/actions/run`?  Are you worried about a missing `kill -CONT 1`?

**Comment by DrDaveD** [comment]
The `apptainer instance run` command could do `/bin/sh -c 'kill -CONT 1; /.singularity.d/actions/run'`.
