### ISSUE TITLE
RFE: Templating Support for Definition File

### ISSUE THREAD

**Issue by panda1100** [apptainer/apptainer#963]
Description
-----------
If we can pass values at build time to replace variables' value inside definition file, before actually process definition file to build image, that brings flexibility to how we interact with definition file. I called this feature, "Templateing".

Usually OSS projects distribute not only source code but its binaries and also container images when they release these days. In the CI/CD era, creating binaries is written in the form of scripts that covers wide range of OS and variety of dependencies. That "recipe" can switch OS versions, library versions etc. Widely known examples in HPC are Spack recipes.

If Apptainer definition file support "Templating" feature:

+ Less integration effort for OSS maintainers: They can reuse existing "recipe" scripts when they try to add Apptainer definition file to their release artifact. 
+ It allows users to alter base image and/or version (This is not supported in Apptainer yet.)
+ It allows users to alter script "switch" (This is kind of supported through APPTAINERENV_VARS but this is not support every section in definition file.)
+ It allows users to alter variables at every section in consistent way (This is not supported in Apptainer yet.)

This is inspired by Dockerfile `ARG` and `--build-arg` (`--build-arg-file`) option for build command.

UI Changes
------------------------
Add `--build-arg` and `--build-arg-file` options to `build` command

`--build-arg`

```
apptainer build --build-arg OS_VER=8.7 --build-arg APP_VERSION=2206 app.sif app.def
```

`--build-arg-file`

```
apptainer build --build-arg-file build-args app.sif app.def
```

`build-args` file

```
OS_VER=8.7
APP_VERSION=2206
```

Internal Behavioural Changes
------------------------

When `build-arg` or `build-arg-file` option comes in:
1. process build-args first
2. fill template to create actual definition file
3. process definition file

How definition file looks like:
-------------------------------

```
Bootstrap: docker
From: rockylinux:${OS_VER}

%setup
    touch /${OS_VER}
    touch ${APPTAINER_ROOTFS}/file2

%files
    /script-${OS_VER}.sh
    /dir-${OS_VER} /opt

%environment
    export OS_VER=${OS_VER}

%post
    /script-${OS_VER}.sh ${APP_VER}

%runscript
    echo "Container was created $NOW"
    echo "Arguments received: $*"
    exec echo "$@"

%startscript
    nc -lp ${LISTEN_PORT:-'8080'}

%test
    grep -q NAME=\"Rocky\" /etc/os-release
    if [ $? -eq 0 ]; then
        echo "Container base is Rocky Linux as expected."
    else
        echo "Container base is not Rocky Linux."
        exit 1
    fi

%labels
    Author ${AUTHER:-}
    Version ${VERSION:-}

%help
    This is a ${DEMO:-} for templating definition file
```

I am please to hear any comments and ideas from community here.

**Comment by GodloveD** [comment]
This is a good idea and has been raised several times in the past.  I think that the major drawback is that it might make it hard to see how a container has been built and how to reproduce the build.  I've run into this issue with Docker where there is a Dockerfile and you have to guess what values were passed at build time to figure out how to rebuild the container.  

Of course, this would not be an issue if you have access to a pre-built version of the container where you can use the `inspect` command to view the def file.  But if you just find the def files up on GitHub for instance, you might not understand how you are supposed to build the container.  

There is also a problem with the implementation above.  The `${SOME_VAR}` syntax already has meaning within the context of the shell scriptlets used during the build.  There is no way for Apptainer to determine if you want to switch the `${KEYWORD}` with a value during pre-processing, or if it should leave the `${KEYWORD}` in place because there will be an environment variable called `KEYWORD` available during the appropriate build stage.  So the templating syntax would have to be made unique.

**Comment by panda1100** [comment]
Thank you @GodloveD!

>  I think that the major drawback is that it might make it hard to see how a container has been built and how to reproduce the build.

[APPTAINERENV_](https://apptainer.org/docs/user/main/environment_and_metadata.html#environment-overview) gives same functionality (but limited sections in definition file) and same drawback. And if we use setup scripts coming from host via `%files` section, that also gives same drawback. But both needs for real world use-case and helps good user experience. What I really try to say here is that `reproducibility` is not completely guaranteed by design but by user's effort. (I'm a big fun of ["mobility of compute" paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0177459) and that's why I'm here.) To sum up, I do understand drawback you described above but I believe this feature is worth to implement.

> ${SOME_VAR} syntax already has meaning within the context of the shell scriptlets used during the build.

I understand the point you made, and actually this is the point I was wondering. [Go template](https://pkg.go.dev/text/template) and [Jinja2](https://jinja.palletsprojects.com/en/3.1.x/templates/) uses `{{ SOME_VAR }}`. This style is more intuitive for users who already knows "template".

How definition file looks like:

```
Bootstrap: docker
From: rockylinux:{{OS_VER}}

%setup
    touch /{{OS_VER}}
    touch ${APPTAINER_ROOTFS}/file2

%files
    /script-{{OS_VER}}.sh
    /dir-{{OS_VER}} /opt

%environment
    export OS_VER={{OS_VER}}

%post
    /script-{{OS_VER}}.sh {{APP_VER}}

%runscript
    echo "Container was created $NOW"
    echo "Arguments received: $*"
    exec echo "$@"

%startscript
    nc -lp ${LISTEN_PORT:-'8080'}

%test
    grep -q NAME=\"Rocky\" /etc/os-release
    if [ $? -eq 0 ]; then
        echo "Container base is Rocky Linux as expected."
    else
        echo "Container base is not Rocky Linux."
        exit 1
    fi

%labels
    Author {{AUTHER}}
    Version {{VERSION}}

%help
    This is a {{DEMO}} for templating definition file
```

**Comment by olesenm** [comment]
once the templating has been expanded, there must be a plaintext definition (or equivalent) that apptainer build uses. would it be possible to then install a copy of that definition (expanded) form directly into the container image? would make self-documented.

**Comment by panda1100** [comment]
Thank you @olesenm for the input!

`apptainer inspect --deffile openfoam.sif` gives you definition file that actually used for building container. At least I can say there is a feature that support your idea. 

@GodloveD If we can set default value for the template, that may help understanding how we can build the templated definition file at least for default settings. Something looks like `{{ OS_DIST:-'rockylinux' }}`.

**Comment by GodloveD** [comment]
@olesenm that's a good idea and I assumed we would do that.  That is currently the way operations like `pull` happen.  Under the hood Apptainer creates a def file to satisfy the operation and then uses that file to carry out the procedure.  
```
$ apptainer pull docker://alpine
INFO:    Using cached SIF image

$ apptainer inspect --deffile alpine_latest.sif 
bootstrap: docker
from: alpine
```
But this only helps you if you have the container.  It doesn't help you if you happen across the def file in the wild and need to figure out what values you are supposed to supply to build the container.  

@panda1100 supplying a default to the template is a good idea.  That would help at least point a user in the right direction.

I'm interested to hear what other apptainer users think of this.  Maybe it would be good to link this issue in the Apptainer Slack and request comments?

**Comment by gmkurtzer** [comment]
As @GodloveD has said on occasion, and I have shamelessly and loosely quoted him... Containers may be reproducible, but container recipes are not because the internet changes.

I love this idea and think it has merit, but I'm also curious about some additional use-cases and wondering if these can be defined, overwritten, and utilized like RPM macros.

**Comment by dcat52** [comment]
For what it is worth, this is a container flow I use regularly and configure differently depending on what system I am building for.  https://github.com/dcat52/apptainer-definitions/blob/master/definitions/argos/full.def

In the first `%post` section, I set up all the variables to use in other `post` components. Then in the final `post` I set a bunch of labels that contain information from the configuration. I agree some sort of default option is needed. I would like the ability to make the params visible from a built container such as via labels.  Beyond defaults, we can encourage populate the `%help` section with something akin to a `help()` bash script function.

**Comment by panda1100** [comment]
@gmkurtzer My straight understanding of PRM macro is for package-wide default settings. In the context of Apptainer, It will be like a distribution-wide x application-wide default settings. Maybe I need an out-of-box thinking here how we can utilize PRM macros-ish template for Apptainer.

**Comment by panda1100** [comment]
@dcat52 Thank you for sharing your work. Encouraging `%help` is absolutely agree. And using `%labels` is a really good idea. That outputs metadata in json format. Template + metadata that will definitely helps reproducibility. Thank you again for the  input!

**Comment by gmkurtzer** [comment]
@panda1100 I'm not sure on the use-case yet, but perhaps being able to define certain values either in a system wide config, or build command line, or in the recipe itself, and trigger various bits of templatable logic based on those values.

It would be nice for the persisted recipe to have those values expanded so the actual build recipe can be evaluated, but aside from that, there might be value here.

Do you have a particular use-case in mind for this or just thinking through how to optimize and make the build process more flexible?

**Comment by panda1100** [comment]
@gmkurtzer The use-case initially on my mind is that when you maintain setup script that is capable to switch OS versions and App versions, we can switch that setup scripts by user supplied arguments at the build time. For example, `apptainer build --build-arg OS_VER=9 --build-arg APP_VER=2212 app.sif app-template.def`.

This `--build-args` idea is coming from Docker's `--build-args`. The value supplied from `--build-arg` is only available at build time and doesn't persist as "environment variables" inside image. That's the original behaviour. So, in the context of Apptainer,  `--build-args` will populate args in definition file, but not persisted as "environment variables" inside image. This is the difference between  "environment variables" and "build time arguments".

The other use-case that I found in Docker documentation is here. The example sets `HTTP_PROXY` variables at build time that shouldn't be persisted inside image.
https://docs.docker.com/engine/reference/commandline/build/#-set-build-time-variables---build-arg

**Comment by panda1100** [comment]
@gmkurtzer The other related topic is here https://github.com/apptainer/apptainer/issues/792 . That is about build time secrets.

**Comment by panda1100** [comment]
Use-case from the community. I'll update this RFE according to discussion on Community Slack channel.

> The thing is that I use git, gitlab, CI/CD, gitlab-runner, gitflow...and pipelines can be triggered in the alpha or beta branches and from a tagged commit....when building my (non-container) project, I can readily tell which branch/tag I am in as Gitlab CI/CD itself provides environemt variables to that effect; but, as soon as I want to containerize such project with apptainer, all those variables are nowhere to be found...so, I am having to "hack" my way around by first writing the env vars of interest to a file in the current directory, just to source it right back during apptainer build...%post

**Comment by panda1100** [comment]
Description
-----------
If we can pass values at build time to replace variables' value inside definition file, before actually process definition file to build image, that brings flexibility to how we interact with definition file. I called this feature, "Templateing".

Usually OSS projects distribute not only source code but its binaries and also container images when they release these days. In the CI/CD era, creating binaries is written in the form of scripts that covers wide range of OS and variety of dependencies. That "recipe" can switch OS versions, library versions etc. Widely known examples in HPC are Spack recipes.

If Apptainer definition file support "Templating" feature:

+ Less integration effort for OSS maintainers: They can reuse existing "recipe" scripts when they try to add Apptainer definition file to their release artifact. 
+ It allows users to alter base image and/or version (This is not supported in Apptainer yet.)
+ It allows users to alter script "switch" (This is kind of supported through APPTAINERENV_VARS but this is not support every section in definition file.)
+ It allows users to alter variables at every section in consistent way (This is not supported in Apptainer yet.)

This is inspired by Dockerfile `ARG` and `--build-arg` (`--build-arg-file`) option for build command. Since we have `--env` and `--env-file` option for `run`, `exec` and `shell`, add such options for `build` is intuitive for users instead of add `--build-arg` and `--build-arg-file`.

Template variable `{{ VAR }}` and environment variable `${VAR}` explicitly use different signs. Template variable supports default value `{{ VAR:-default }}`.

UI Changes
------------------------
Expose build command options`--env` and `--env-file`

`--env`

```
apptainer build --env OS_VER=8.7 --env APP_VERSION=2206 app.sif app.def
```

`--env-file`

```
apptainer build --env-file env.list app.sif app.def
```

ex) contents of `env.list` file (file extension is arbitrary)

```
OS_VER=8.7
APP_VERSION=2206
```

Internal Behavioural Changes
------------------------

When `env` or `env-file` option comes in:
1. process `env` and `env-file` first
2. fill template to create actual definition file
3. process definition file


How definition file looks like:
-------------------------------

```
Bootstrap: docker
From: rockylinux:{{ OS_VER }}

%setup
    touch /{{ OS_VER }}
    touch ${APPTAINER_ROOTFS}/file2

%files
    /script-{{ OS_VER }}.sh
    /dir-{{ OS_VER }} /opt

%environment
    export OS_VER={{ OS_VER }}

%post
    /script-{{ OS_VER }}.sh {{ APP_VER }}

%runscript
    echo "Container was created $NOW"
    echo "Arguments received: $*"
    exec echo "$@"

%startscript
    nc -lp ${LISTEN_PORT:-'8080'}

%test
    grep -q NAME=\"Rocky\" /etc/os-release
    if [ $? -eq 0 ]; then
        echo "Container base is Rocky Linux as expected."
    else
        echo "Container base is not Rocky Linux."
        exit 1
    fi

%labels
    Author {{ AUTHER:- }}
    Version {{ VERSION:- }}

%help
    This is a {{ DEMO:-demo }} for templating definition file
```

I am please to hear any comments and ideas from community here.

**Comment by olesenm** [comment]
It was not mentioned, but I hope there is provision to provide default parameters as well. Eg,
```
%defaults
    AUTHOR="Mark"
    OS_VERSION=jammy

bootstrap: docker
From: ubuntu:{{ OS_VERSION }}

```
This would be much cleaner than having `{{OS_VERSION:-jammy}}` littered in N different places.

One thing that is quite annoying with the docker build args is that you have to re-declare them for each build stage. It looks like the templating will thankfully not have that.

**Comment by dtrudg** [comment]
> This is inspired by Dockerfile `ARG` and `--build-arg` (`--build-arg-file`) option for build command. Since we have `--env` and `--env-file` option for `run`, `exec` and `shell`, add such options for `build` is intuitive for users instead of add `--build-arg` and `--build-arg-file`.

To me, re-using `--env` and `--env-file` is confusing. The naming of those strongly suggests that they are setting environment variables... but that wouldn't be true in a build unless you write the correct template.

Docker has `--env` and `--env-file` for its run command. There doesn't really seem to be a good reason not to use `--build-arg` and `--build-arg-file` here?

**Comment by panda1100** [comment]
Thank you @olesenm that is great idea!

Thank you @dtrudg that makes perfect sense!

**Comment by panda1100** [comment]
@JasonYangShadow I just realized this RFE https://github.com/apptainer/apptainer/issues/792 is kind of similar feature.
build-arg persists on SIF file but secrets shouldn't be persist. That's the difference.

**Comment by JasonYangShadow** [comment]
> @JasonYangShadow I just realized this RFE https://github.com/apptainer/apptainer/issues/792 is kind of similar feature.
> 
> build-arg persists on SIF file but secrets shouldn't be persist. That's the difference.

Didn't notice that. Maybe we can create another RFE for secrets.

**Comment by panda1100** [comment]
Yes, definitely. I'll write that one.

**Comment by DrDaveD** [comment]
> build-arg persists on SIF file but secrets shouldn't be persist. That's the difference.

Doesn't it depend on how the build-arg is used in the definition file?  If it's just used to log in to a service, it won't necessarily be stored in the container, I wouldn't think.

**Comment by panda1100** [comment]
@DrDaveD https://github.com/apptainer/apptainer/issues/792#issuecomment-1569681453 here is the details of "secret" feature, I just started discussion there.
