### ISSUE TITLE
--no-mount tmp --writable-tmpfs broke on 1.1.x (coming from 1.0.x)

### ISSUE THREAD

**Issue by yghorbal** [apptainer/apptainer#994]
### Version of Apptainer

```
$ apptainer version
1.1.4
```
### Expected behavior

successufull run for: `apptainer exec --no-mount tmp --writable-tmpfs docker://rockylinux:8 touch /tmp/foo`

### Actual behavior

`apptainer exec --no-mount tmp --writable-tmpfs docker://rockylinux:8 touch /tmp/foo` fails with this ouput:
`touch: cannot touch '/tmp/foo': Permission denied`

### Steps to reproduce this behavior

just run `apptainer exec --no-mount tmp --writable-tmpfs docker://rockylinux:8 touch /tmp/foo`

### What OS/distro are you running

```
$  cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.4 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.4:GA"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/red_hat_enterprise_linux/8/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.4
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.4"
```
### How did you install Apptainer

Installed from source

**Comment by yghorbal** [comment]
After a discussion on the project Slack channel the issue was due to the fact that Apptainer was using the system's `squashfuse_ll` while it's supposed to used embedded `squashfuse_ll` as instructed in [INSTALL.md](https://github.com/apptainer/apptainer/blob/main/INSTALL.md#installing-improved-performance-squashfuse_ll)
After recompiling Apptainer correctly and using the correct `squashfuse_ll` it's working as expected

Steps to identify the root cause:
run `apptainer exec --debug --no-mount tmp --writable-tmpfs docker://rockylinux:8 touch /tmp/foo` and look for line like:
```
DEBUG   [U=1000,P=14152]   findOnPath()                  Found "squashfuse_ll" at "/usr/libexec/apptainer/bin/squashfuse_ll"
```

On my systeme it was using the system one and the line was like this:
```
DEBUG   [U=1000,P=14152]   findOnPath()                  Found "squashfuse_ll" at "/usr/bin/squashfuse_ll"
```

**Comment by DrDaveD** [comment]
Thanks for submitting the issue and what the fix is, for the record.  The reason why it works is because the squashfuse build instructions include a patch enabled in #759 which makes the files in the container appear to be owned by the user.  Without that, overlayfs refuses to allow overwriting because the underlying files appear to be owned by a different user ("nobody").
