### ISSUE TITLE
while extracting Demuxafy.sif: root filesystem extraction failed: extract command failed: FATAL:   container creation failed: open /etc/resolv.conf: no such file or directory

### ISSUE THREAD

**Issue by wjzwjz5** [apptainer/apptainer#999]
### Version of Apptainer

What version of Apptainer (or Singularity) are you using? Run

singularity-ce version 3.9.2

the problem is :
$ singularity exec Demuxafy.sif bcftools view cellSNP.base.vcf -R cellSNP.base.vcf.gz -S cellSNP.samples.tsv -Ov -o donor_subset.vcf
INFO:    Converting SIF file to temporary sandbox...
FATAL:   while extracting Demuxafy.sif: root filesystem extraction failed: extract command failed: FATAL:   container creation failed: open /etc/resolv.conf: no such file or directory
: exit status 255

### What OS/distro are you running

```sh
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"

```
I guess it's because I restart the HPC?

**Comment by DrDaveD** [comment]
I'm sorry to give you the "runaround", but since you are using singularity-ce, please instead submit to https://github.com/sylabs/singularity.
